.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0019A078, 0x1C

glabel func_0019A078
    /* 19A0EC 0019A078 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 19A0F0 0019A07C 1000BFAF */  sw         $ra, 0x10($sp)
    /* 19A0F4 0019A080 026C060C */  jal        func_0019B008
    /* 19A0F8 0019A084 2520A000 */   or        $a0, $a1, $zero
    /* 19A0FC 0019A088 1000BF8F */  lw         $ra, 0x10($sp)
    /* 19A100 0019A08C 0800E003 */  jr         $ra
    /* 19A104 0019A090 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0019A078
