.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00100610, 0x60

glabel func_00100610
    /* 100684 00100610 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 100688 00100614 3000868C */  lw         $a2, 0x30($a0)
    /* 10068C 00100618 1C00B0AF */  sw         $s0, 0x1C($sp)
    /* 100690 0010061C 25808000 */  or         $s0, $a0, $zero
    /* 100694 00100620 02000734 */  ori        $a3, $zero, 0x2
    /* 100698 00100624 2000BFAF */  sw         $ra, 0x20($sp)
    /* 10069C 00100628 0D00C714 */  bne        $a2, $a3, .Leboot_00100660
    /* 1006A0 0010062C 2520A000 */   or        $a0, $a1, $zero
    /* 1006A4 00100630 C2AA040C */  jal        func_0012AB08
    /* 1006A8 00100634 1000A527 */   addiu     $a1, $sp, 0x10
    /* 1006AC 00100638 1000A48F */  lw         $a0, 0x10($sp)
    /* 1006B0 0010063C 1400A68F */  lw         $a2, 0x14($sp)
    /* 1006B4 00100640 10000526 */  addiu      $a1, $s0, 0x10
    /* 1006B8 00100644 1800A78F */  lw         $a3, 0x18($sp)
    /* 1006BC 00100648 0000A4AC */  sw         $a0, 0x0($a1)
    /* 1006C0 0010064C 0400A6AC */  sw         $a2, 0x4($a1)
    /* 1006C4 00100650 0800A7AC */  sw         $a3, 0x8($a1)
    /* 1006C8 00100654 38000482 */  lb         $a0, 0x38($s0)
    /* 1006CC 00100658 20008434 */  ori        $a0, $a0, 0x20
    /* 1006D0 0010065C 380004A2 */  sb         $a0, 0x38($s0)
  .Leboot_00100660:
    /* 1006D4 00100660 1C00B08F */  lw         $s0, 0x1C($sp)
    /* 1006D8 00100664 2000BF8F */  lw         $ra, 0x20($sp)
    /* 1006DC 00100668 0800E003 */  jr         $ra
    /* 1006E0 0010066C 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_00100610
