.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000A4874, 0x108

glabel func_000A4874
    /* A48E8 000A4874 80FFBD27 */  addiu      $sp, $sp, -0x80
    /* A48EC 000A4878 003F053C */  lui        $a1, (0x3F000000 >> 16)
    /* A48F0 000A487C 5400B6E7 */  swc1       $f22, 0x54($sp)
    /* A48F4 000A4880 00B08544 */  mtc1       $a1, $f22
    /* A48F8 000A4884 5800B8E7 */  swc1       $f24, 0x58($sp)
    /* A48FC 000A4888 02661646 */  mul.s      $f24, $f12, $f22
    /* A4900 000A488C 5000B4E7 */  swc1       $f20, 0x50($sp)
    /* A4904 000A4890 5C00BAE7 */  swc1       $f26, 0x5C($sp)
    /* A4908 000A4894 6800B0AF */  sw         $s0, 0x68($sp)
    /* A490C 000A4898 06750046 */  mov.s      $f20, $f14
    /* A4910 000A489C 25808000 */  or         $s0, $a0, $zero
    /* A4914 000A48A0 866E0046 */  mov.s      $f26, $f13
    /* A4918 000A48A4 6000BCE7 */  swc1       $f28, 0x60($sp)
    /* A491C 000A48A8 6400BEE7 */  swc1       $f30, 0x64($sp)
    /* A4920 000A48AC 6C00B1AF */  sw         $s1, 0x6C($sp)
    /* A4924 000A48B0 7000BFAF */  sw         $ra, 0x70($sp)
    /* A4928 000A48B4 09EF040C */  jal        func_0013BC24
    /* A492C 000A48B8 06C30046 */   mov.s     $f12, $f24
    /* A4930 000A48BC 06C30046 */  mov.s      $f12, $f24
    /* A4934 000A48C0 2CEE040C */  jal        func_0013B8B0
    /* A4938 000A48C4 06070046 */   mov.s     $f28, $f0
    /* A493C 000A48C8 00F08044 */  mtc1       $zero, $f30
    /* A4940 000A48CC 2000BEE7 */  swc1       $f30, 0x20($sp)
    /* A4944 000A48D0 2400BEE7 */  swc1       $f30, 0x24($sp)
    /* A4948 000A48D4 82D61646 */  mul.s      $f26, $f26, $f22
    /* A494C 000A48D8 2800BCE7 */  swc1       $f28, 0x28($sp)
    /* A4950 000A48DC 2C00A0E7 */  swc1       $f0, 0x2C($sp)
    /* A4954 000A48E0 09EF040C */  jal        func_0013BC24
    /* A4958 000A48E4 06D30046 */   mov.s     $f12, $f26
    /* A495C 000A48E8 06D30046 */  mov.s      $f12, $f26
    /* A4960 000A48EC 2CEE040C */  jal        func_0013B8B0
    /* A4964 000A48F0 06070046 */   mov.s     $f28, $f0
    /* A4968 000A48F4 3000BCE7 */  swc1       $f28, 0x30($sp)
    /* A496C 000A48F8 3400BEE7 */  swc1       $f30, 0x34($sp)
    /* A4970 000A48FC 02A51646 */  mul.s      $f20, $f20, $f22
    /* A4974 000A4900 3800BEE7 */  swc1       $f30, 0x38($sp)
    /* A4978 000A4904 3C00A0E7 */  swc1       $f0, 0x3C($sp)
    /* A497C 000A4908 09EF040C */  jal        func_0013BC24
    /* A4980 000A490C 06A30046 */   mov.s     $f12, $f20
    /* A4984 000A4910 06A30046 */  mov.s      $f12, $f20
    /* A4988 000A4914 2CEE040C */  jal        func_0013B8B0
    /* A498C 000A4918 06060046 */   mov.s     $f24, $f0
    /* A4990 000A491C 4000BEE7 */  swc1       $f30, 0x40($sp)
    /* A4994 000A4920 4400B8E7 */  swc1       $f24, 0x44($sp)
    /* A4998 000A4924 4800BEE7 */  swc1       $f30, 0x48($sp)
    /* A499C 000A4928 1000B127 */  addiu      $s1, $sp, 0x10
    /* A49A0 000A492C 4C00A0E7 */  swc1       $f0, 0x4C($sp)
    /* A49A4 000A4930 25202002 */  or         $a0, $s1, $zero
    /* A49A8 000A4934 2000A527 */  addiu      $a1, $sp, 0x20
    /* A49AC 000A4938 35EB060C */  jal        syncSkeleton_22B8
    /* A49B0 000A493C 3000A627 */   addiu     $a2, $sp, 0x30
    /* A49B4 000A4940 25200002 */  or         $a0, $s0, $zero
    /* A49B8 000A4944 25282002 */  or         $a1, $s1, $zero
    /* A49BC 000A4948 35EB060C */  jal        syncSkeleton_22B8
    /* A49C0 000A494C 4000A627 */   addiu     $a2, $sp, 0x40
    /* A49C4 000A4950 5000B4C7 */  lwc1       $f20, 0x50($sp)
    /* A49C8 000A4954 5400B6C7 */  lwc1       $f22, 0x54($sp)
    /* A49CC 000A4958 5800B8C7 */  lwc1       $f24, 0x58($sp)
    /* A49D0 000A495C 5C00BAC7 */  lwc1       $f26, 0x5C($sp)
    /* A49D4 000A4960 6000BCC7 */  lwc1       $f28, 0x60($sp)
    /* A49D8 000A4964 6400BEC7 */  lwc1       $f30, 0x64($sp)
    /* A49DC 000A4968 6800B08F */  lw         $s0, 0x68($sp)
    /* A49E0 000A496C 6C00B18F */  lw         $s1, 0x6C($sp)
    /* A49E4 000A4970 7000BF8F */  lw         $ra, 0x70($sp)
    /* A49E8 000A4974 0800E003 */  jr         $ra
    /* A49EC 000A4978 8000BD27 */   addiu     $sp, $sp, 0x80
endlabel func_000A4874
