.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00143984, 0x34

glabel func_00143984
    /* 1439F8 00143984 00008680 */  lb         $a2, 0x0($a0)
  .Leboot_00143988:
    /* 1439FC 00143988 0800C050 */  beql       $a2, $zero, .Leboot_001439AC
    /* 143A00 0014398C 00008290 */   lbu       $v0, 0x0($a0)
    /* 143A04 00143990 0000A780 */  lb         $a3, 0x0($a1)
    /* 143A08 00143994 0500C754 */  bnel       $a2, $a3, .Leboot_001439AC
    /* 143A0C 00143998 00008290 */   lbu       $v0, 0x0($a0)
    /* 143A10 0014399C 01008424 */  addiu      $a0, $a0, 0x1
    /* 143A14 001439A0 0100A524 */  addiu      $a1, $a1, 0x1
    /* 143A18 001439A4 F8FF0010 */  b          .Leboot_00143988
    /* 143A1C 001439A8 00008680 */   lb        $a2, 0x0($a0)
  .Leboot_001439AC:
    /* 143A20 001439AC 0000A490 */  lbu        $a0, 0x0($a1)
    /* 143A24 001439B0 0800E003 */  jr         $ra
    /* 143A28 001439B4 23104400 */   subu      $v0, $v0, $a0
endlabel func_00143984
