.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

/* Handwritten function */
nonmatching func_000F84D8, 0x18C

glabel func_000F84D8
    /* F854C 000F84D8 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* F8550 000F84DC 2C00B0AF */  sw         $s0, 0x2C($sp)
    /* F8554 000F84E0 3000B1AF */  sw         $s1, 0x30($sp)
    /* F8558 000F84E4 25888000 */  or         $s1, $a0, $zero
    /* F855C 000F84E8 2580A000 */  or         $s0, $a1, $zero
    /* F8560 000F84EC 3400B2AF */  sw         $s2, 0x34($sp)
    /* F8564 000F84F0 0400248E */  lw         $a0, 0x4($s1)
    /* F8568 000F84F4 00001234 */  ori        $s2, $zero, 0x0
    /* F856C 000F84F8 2000A727 */  addiu      $a3, $sp, 0x20
    /* F8570 000F84FC 02000534 */  ori        $a1, $zero, 0x2
    /* F8574 000F8500 21000634 */  ori        $a2, $zero, 0x21
    /* F8578 000F8504 2800B4E7 */  swc1       $f20, 0x28($sp)
    /* F857C 000F8508 3800BFAF */  sw         $ra, 0x38($sp)
    /* F8580 000F850C B2C1060C */  jal        stub_001B06C8
    /* F8584 000F8510 25400000 */   or        $t0, $zero, $zero
    /* F8588 000F8514 5507040C */  jal        func_00101D54
    /* F858C 000F8518 00000000 */   nop
    /* F8590 000F851C 46004010 */  beqz       $v0, .Leboot_000F8638
    /* F8594 000F8520 00000000 */   nop
    /* F8598 000F8524 25200000 */  or         $a0, $zero, $zero
    /* F859C 000F8528 25280000 */  or         $a1, $zero, $zero
    /* F85A0 000F852C E0010634 */  ori        $a2, $zero, 0x1E0
    /* F85A4 000F8530 3607040C */  jal        func_00101CD8
    /* F85A8 000F8534 10010734 */   ori       $a3, $zero, 0x110
    /* F85AC 000F8538 F043043C */  lui        $a0, (0x43F00000 >> 16)
    /* F85B0 000F853C 00A08044 */  mtc1       $zero, $f20
    /* F85B4 000F8540 00688444 */  mtc1       $a0, $f13
    /* F85B8 000F8544 8843043C */  lui        $a0, (0x43880000 >> 16)
    /* F85BC 000F8548 06A30046 */  mov.s      $f12, $f20
    /* F85C0 000F854C 00788444 */  mtc1       $a0, $f15
    /* F85C4 000F8550 803F043C */  lui        $a0, (0x3F800000 >> 16)
    /* F85C8 000F8554 86A30046 */  mov.s      $f14, $f20
    /* F85CC 000F8558 00808444 */  mtc1       $a0, $f16
    /* F85D0 000F855C 80BF043C */  lui        $a0, (0xBF800000 >> 16)
    /* F85D4 000F8560 660C040C */  jal        func_00103198
    /* F85D8 000F8564 00888444 */   mtc1      $a0, $f17
    /* F85DC 000F8568 0F00043C */  lui        $a0, %hi(sym_000EB830)
    /* F85E0 000F856C 0F00053C */  lui        $a1, %hi(func_000EB840)
    /* F85E4 000F8570 30B88424 */  addiu      $a0, $a0, %lo(sym_000EB830)
    /* F85E8 000F8574 450D040C */  jal        func_00103514
    /* F85EC 000F8578 40B8A524 */   addiu     $a1, $a1, %lo(func_000EB840)
    /* F85F0 000F857C 0700043C */  lui        $a0, %hi(sym_00074208)
    /* F85F4 000F8580 FE0A040C */  jal        func_00102BF8
    /* F85F8 000F8584 08428424 */   addiu     $a0, $a0, %lo(sym_00074208)
    /* F85FC 000F8588 3800248E */  lw         $a0, 0x38($s1)
    /* F8600 000F858C 19008010 */  beqz       $a0, .Leboot_000F85F4
    /* F8604 000F8590 00000000 */   nop
    /* F8608 000F8594 0C008490 */  lbu        $a0, 0xC($a0)
    /* F860C 000F8598 16008010 */  beqz       $a0, .Leboot_000F85F4
    /* F8610 000F859C 00000000 */   nop
    /* F8614 000F85A0 0E00043C */  lui        $a0, %hi(sym_000E6D2C)
    /* F8618 000F85A4 2C6D848C */  lw         $a0, %lo(sym_000E6D2C)($a0)
    /* F861C 000F85A8 C392030C */  jal        func_000E4B0C
    /* F8620 000F85AC 2400A527 */   addiu     $a1, $sp, 0x24
    /* F8624 000F85B0 2400A48F */  lw         $a0, 0x24($sp)
    /* F8628 000F85B4 0100053C */  lui        $a1, %hi(D_eboot_00015F90)
    /* F862C 000F85B8 905FA524 */  addiu      $a1, $a1, %lo(D_eboot_00015F90)
    /* F8630 000F85BC 23208500 */  subu       $a0, $a0, $a1
    /* F8634 000F85C0 00608444 */  mtc1       $a0, $f12
    /* F8638 000F85C4 AF47043C */  lui        $a0, (0x47AFC800 >> 16)
    /* F863C 000F85C8 20638046 */  cvt.s.w    $f12, $f12
    /* F8640 000F85CC 00C88434 */  ori        $a0, $a0, (0x47AFC800 & 0xFFFF)
    /* F8644 000F85D0 00688444 */  mtc1       $a0, $f13
    /* F8648 000F85D4 03630D46 */  div.s      $f12, $f12, $f13
    /* F864C 000F85D8 3800248E */  lw         $a0, 0x38($s1)
    /* F8650 000F85DC 3C601446 */  c.lt.s     $f12, $f20
    /* F8654 000F85E0 00000000 */  nop
    /* F8658 000F85E4 01000345 */  bc1tl      .Leboot_000F85EC /* handwritten instruction */
    /* F865C 000F85E8 06A30046 */   mov.s     $f12, $f20
  .Leboot_000F85EC:
    /* F8660 000F85EC A3DC030C */  jal        func_000F728C
    /* F8664 000F85F0 00000000 */   nop
  .Leboot_000F85F4:
    /* F8668 000F85F4 0600043C */  lui        $a0, %hi(sym_00059A04)
    /* F866C 000F85F8 049A91AC */  sw         $s1, %lo(sym_00059A04)($a0)
    /* F8670 000F85FC 0600043C */  lui        $a0, %hi(sym_00059A08)
    /* F8674 000F8600 089A90AC */  sw         $s0, %lo(sym_00059A08)($a0)
    /* F8678 000F8604 1000043C */  lui        $a0, %hi(func_000F8438)
    /* F867C 000F8608 B603040C */  jal        func_00100ED8
    /* F8680 000F860C 38848424 */   addiu     $a0, $a0, %lo(func_000F8438)
    /* F8684 000F8610 E407040C */  jal        func_00101F90
    /* F8688 000F8614 01000434 */   ori       $a0, $zero, 0x1
    /* F868C 000F8618 0600043C */  lui        $a0, %hi(sym_00059A0C)
    /* F8690 000F861C 0C9A928C */  lw         $s2, %lo(sym_00059A0C)($a0)
    /* F8694 000F8620 03004012 */  beqz       $s2, .Leboot_000F8630
    /* F8698 000F8624 00000000 */   nop
    /* F869C 000F8628 06000010 */  b          .Leboot_000F8644
    /* F86A0 000F862C FFFF1224 */   addiu     $s2, $zero, -0x1
  .Leboot_000F8630:
    /* F86A4 000F8630 76C1060C */  jal        stub_001B05D8
    /* F86A8 000F8634 25200000 */   or        $a0, $zero, $zero
  .Leboot_000F8638:
    /* F86AC 000F8638 0400248E */  lw         $a0, 0x4($s1)
    /* F86B0 000F863C AEC1060C */  jal        stub_001B06B8
    /* F86B4 000F8640 04000534 */   ori       $a1, $zero, 0x4
  .Leboot_000F8644:
    /* F86B8 000F8644 25104002 */  or         $v0, $s2, $zero
    /* F86BC 000F8648 2800B4C7 */  lwc1       $f20, 0x28($sp)
    /* F86C0 000F864C 2C00B08F */  lw         $s0, 0x2C($sp)
    /* F86C4 000F8650 3000B18F */  lw         $s1, 0x30($sp)
    /* F86C8 000F8654 3400B28F */  lw         $s2, 0x34($sp)
    /* F86CC 000F8658 3800BF8F */  lw         $ra, 0x38($sp)
    /* F86D0 000F865C 0800E003 */  jr         $ra
    /* F86D4 000F8660 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel func_000F84D8
