.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000AC1C0, 0x134

glabel func_000AC1C0
    /* AC234 000AC1C0 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* AC238 000AC1C4 1001858C */  lw         $a1, 0x110($a0)
    /* AC23C 000AC1C8 3C00A88C */  lw         $t0, 0x3C($a1)
    /* AC240 000AC1CC 2C00A724 */  addiu      $a3, $a1, 0x2C
    /* AC244 000AC1D0 0800A624 */  addiu      $a2, $a1, 0x8
    /* AC248 000AC1D4 00010831 */  andi       $t0, $t0, 0x100
    /* AC24C 000AC1D8 02000015 */  bnez       $t0, .Leboot_000AC1E4
    /* AC250 000AC1DC 1400A524 */   addiu     $a1, $a1, 0x14
    /* AC254 000AC1E0 2528C000 */  or         $a1, $a2, $zero
  .Leboot_000AC1E4:
    /* AC258 000AC1E4 0000ACC4 */  lwc1       $f12, 0x0($a1)
    /* AC25C 000AC1E8 0000ACE7 */  swc1       $f12, 0x0($sp)
    /* AC260 000AC1EC 0400ACC4 */  lwc1       $f12, 0x4($a1)
    /* AC264 000AC1F0 0400ACE7 */  swc1       $f12, 0x4($sp)
    /* AC268 000AC1F4 0800ACC4 */  lwc1       $f12, 0x8($a1)
    /* AC26C 000AC1F8 0800ACE7 */  swc1       $f12, 0x8($sp)
    /* AC270 000AC1FC 0000CCC4 */  lwc1       $f12, 0x0($a2)
    /* AC274 000AC200 0C00ACE7 */  swc1       $f12, 0xC($sp)
    /* AC278 000AC204 0400CCC4 */  lwc1       $f12, 0x4($a2)
    /* AC27C 000AC208 1000ACE7 */  swc1       $f12, 0x10($sp)
    /* AC280 000AC20C 0800CCC4 */  lwc1       $f12, 0x8($a2)
    /* AC284 000AC210 1400ACE7 */  swc1       $f12, 0x14($sp)
    /* AC288 000AC214 0000ECC4 */  lwc1       $f12, 0x0($a3)
    /* AC28C 000AC218 1800ACE7 */  swc1       $f12, 0x18($sp)
    /* AC290 000AC21C 0400ECC4 */  lwc1       $f12, 0x4($a3)
    /* AC294 000AC220 0000ADC7 */  lwc1       $f13, 0x0($sp)
    /* AC298 000AC224 1C00ACE7 */  swc1       $f12, 0x1C($sp)
    /* AC29C 000AC228 0800ECC4 */  lwc1       $f12, 0x8($a3)
    /* AC2A0 000AC22C 0400AEC7 */  lwc1       $f14, 0x4($sp)
    /* AC2A4 000AC230 2400ADE7 */  swc1       $f13, 0x24($sp)
    /* AC2A8 000AC234 0800ADC7 */  lwc1       $f13, 0x8($sp)
    /* AC2AC 000AC238 2000ACE7 */  swc1       $f12, 0x20($sp)
    /* AC2B0 000AC23C 2800AEE7 */  swc1       $f14, 0x28($sp)
    /* AC2B4 000AC240 803F053C */  lui        $a1, (0x3F800000 >> 16)
    /* AC2B8 000AC244 2C00ADE7 */  swc1       $f13, 0x2C($sp)
    /* AC2BC 000AC248 00608544 */  mtc1       $a1, $f12
    /* AC2C0 000AC24C 3000ACE7 */  swc1       $f12, 0x30($sp)
    /* AC2C4 000AC250 2400A527 */  addiu      $a1, $sp, 0x24
    /* AC2C8 000AC254 0000ACC4 */  lwc1       $f12, 0x0($a1)
    /* AC2CC 000AC258 0C00A627 */  addiu      $a2, $sp, 0xC
    /* AC2D0 000AC25C 80038CE4 */  swc1       $f12, 0x380($a0)
    /* AC2D4 000AC260 0400ACC4 */  lwc1       $f12, 0x4($a1)
    /* AC2D8 000AC264 84038CE4 */  swc1       $f12, 0x384($a0)
    /* AC2DC 000AC268 0800ACC4 */  lwc1       $f12, 0x8($a1)
    /* AC2E0 000AC26C 0000CDC4 */  lwc1       $f13, 0x0($a2)
    /* AC2E4 000AC270 88038CE4 */  swc1       $f12, 0x388($a0)
    /* AC2E8 000AC274 0C00ACC4 */  lwc1       $f12, 0xC($a1)
    /* AC2EC 000AC278 2400ADE7 */  swc1       $f13, 0x24($sp)
    /* AC2F0 000AC27C 8C038CE4 */  swc1       $f12, 0x38C($a0)
    /* AC2F4 000AC280 0400CCC4 */  lwc1       $f12, 0x4($a2)
    /* AC2F8 000AC284 2800ACE7 */  swc1       $f12, 0x28($sp)
    /* AC2FC 000AC288 0800CCC4 */  lwc1       $f12, 0x8($a2)
    /* AC300 000AC28C 2C00ACE7 */  swc1       $f12, 0x2C($sp)
    /* AC304 000AC290 0000ACC4 */  lwc1       $f12, 0x0($a1)
    /* AC308 000AC294 1800A727 */  addiu      $a3, $sp, 0x18
    /* AC30C 000AC298 90038CE4 */  swc1       $f12, 0x390($a0)
    /* AC310 000AC29C 0400ACC4 */  lwc1       $f12, 0x4($a1)
    /* AC314 000AC2A0 94038CE4 */  swc1       $f12, 0x394($a0)
    /* AC318 000AC2A4 0800ACC4 */  lwc1       $f12, 0x8($a1)
    /* AC31C 000AC2A8 0000EDC4 */  lwc1       $f13, 0x0($a3)
    /* AC320 000AC2AC 98038CE4 */  swc1       $f12, 0x398($a0)
    /* AC324 000AC2B0 0C00ACC4 */  lwc1       $f12, 0xC($a1)
    /* AC328 000AC2B4 2400ADE7 */  swc1       $f13, 0x24($sp)
    /* AC32C 000AC2B8 9C038CE4 */  swc1       $f12, 0x39C($a0)
    /* AC330 000AC2BC 0400ECC4 */  lwc1       $f12, 0x4($a3)
    /* AC334 000AC2C0 2800ACE7 */  swc1       $f12, 0x28($sp)
    /* AC338 000AC2C4 0800ECC4 */  lwc1       $f12, 0x8($a3)
    /* AC33C 000AC2C8 2C00ACE7 */  swc1       $f12, 0x2C($sp)
    /* AC340 000AC2CC 0000ACC4 */  lwc1       $f12, 0x0($a1)
    /* AC344 000AC2D0 A0038CE4 */  swc1       $f12, 0x3A0($a0)
    /* AC348 000AC2D4 0400ACC4 */  lwc1       $f12, 0x4($a1)
    /* AC34C 000AC2D8 A4038CE4 */  swc1       $f12, 0x3A4($a0)
    /* AC350 000AC2DC 0800ACC4 */  lwc1       $f12, 0x8($a1)
    /* AC354 000AC2E0 A8038CE4 */  swc1       $f12, 0x3A8($a0)
    /* AC358 000AC2E4 0C00ACC4 */  lwc1       $f12, 0xC($a1)
    /* AC35C 000AC2E8 AC038CE4 */  swc1       $f12, 0x3AC($a0)
    /* AC360 000AC2EC 0800E003 */  jr         $ra
    /* AC364 000AC2F0 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel func_000AC1C0
