.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0000F404, 0x100

glabel func_0000F404
    /* F478 0000F404 C0FCBD27 */  addiu      $sp, $sp, -0x340
    /* F47C 0000F408 1000A0A3 */  sb         $zero, 0x10($sp)
    /* F480 0000F40C 1C03B0AF */  sw         $s0, 0x31C($sp)
    /* F484 0000F410 2003B1AF */  sw         $s1, 0x320($sp)
    /* F488 0000F414 2588A000 */  or         $s1, $a1, $zero
    /* F48C 0000F418 2580C000 */  or         $s0, $a2, $zero
    /* F490 0000F41C 1401A0A3 */  sb         $zero, 0x114($sp)
    /* F494 0000F420 2403B2AF */  sw         $s2, 0x324($sp)
    /* F498 0000F424 2803B3AF */  sw         $s3, 0x328($sp)
    /* F49C 0000F428 2C03B4AF */  sw         $s4, 0x32C($sp)
    /* F4A0 0000F42C 1C00053C */  lui        $a1, %hi(sym_001C0530)
    /* F4A4 0000F430 1000B427 */  addiu      $s4, $sp, 0x10
    /* F4A8 0000F434 1401B327 */  addiu      $s3, $sp, 0x114
    /* F4AC 0000F438 1802A0A3 */  sb         $zero, 0x218($sp)
    /* F4B0 0000F43C 1802B227 */  addiu      $s2, $sp, 0x218
    /* F4B4 0000F440 25200002 */  or         $a0, $s0, $zero
    /* F4B8 0000F444 3003BFAF */  sw         $ra, 0x330($sp)
    /* F4BC 0000F448 0E0E050C */  jal        func_00143838
    /* F4C0 0000F44C 3005A524 */   addiu     $a1, $a1, %lo(sym_001C0530)
    /* F4C4 0000F450 1F004010 */  beqz       $v0, .Leboot_0000F4D0
    /* F4C8 0000F454 00000000 */   nop
    /* F4CC 0000F458 1C00053C */  lui        $a1, %hi(str_characters_s_s)
    /* F4D0 0000F45C 25208002 */  or         $a0, $s4, $zero
    /* F4D4 0000F460 25302002 */  or         $a2, $s1, $zero
    /* F4D8 0000F464 25380002 */  or         $a3, $s0, $zero
    /* F4DC 0000F468 6ABD050C */  jal        func_0016F5A8
    /* F4E0 0000F46C 3405A524 */   addiu     $a1, $a1, %lo(str_characters_s_s)
    /* F4E4 0000F470 1C00053C */  lui        $a1, %hi(str_s_tif)
    /* F4E8 0000F474 25206002 */  or         $a0, $s3, $zero
    /* F4EC 0000F478 25308002 */  or         $a2, $s4, $zero
    /* F4F0 0000F47C 6ABD050C */  jal        func_0016F5A8
    /* F4F4 0000F480 4805A524 */   addiu     $a1, $a1, %lo(str_s_tif)
    /* F4F8 0000F484 1C00053C */  lui        $a1, %hi(str_s_res)
    /* F4FC 0000F488 25204002 */  or         $a0, $s2, $zero
    /* F500 0000F48C 25308002 */  or         $a2, $s4, $zero
    /* F504 0000F490 6ABD050C */  jal        func_0016F5A8
    /* F508 0000F494 5005A524 */   addiu     $a1, $a1, %lo(str_s_res)
    /* F50C 0000F498 A562030C */  jal        func_000D8A94
    /* F510 0000F49C 25204002 */   or        $a0, $s2, $zero
    /* F514 0000F4A0 25804000 */  or         $s0, $v0, $zero
    /* F518 0000F4A4 D162030C */  jal        func_000D8B44
    /* F51C 0000F4A8 25200002 */   or        $a0, $s0, $zero
    /* F520 0000F4AC 25200002 */  or         $a0, $s0, $zero
    /* F524 0000F4B0 25286002 */  or         $a1, $s3, $zero
    /* F528 0000F4B4 9DBD050C */  jal        func_0016F674
    /* F52C 0000F4B8 01000634 */   ori       $a2, $zero, 0x1
    /* F530 0000F4BC 25884000 */  or         $s1, $v0, $zero
    /* F534 0000F4C0 05002012 */  beqz       $s1, .Leboot_0000F4D8
    /* F538 0000F4C4 00000000 */   nop
    /* F53C 0000F4C8 05000010 */  b          .Leboot_0000F4E0
    /* F540 0000F4CC 00000000 */   nop
  .Leboot_0000F4D0:
    /* F544 0000F4D0 04000010 */  b          .Leboot_0000F4E4
    /* F548 0000F4D4 25100000 */   or        $v0, $zero, $zero
  .Leboot_0000F4D8:
    /* F54C 0000F4D8 FF62030C */  jal        func_000D8BFC
    /* F550 0000F4DC 25200002 */   or        $a0, $s0, $zero
  .Leboot_0000F4E0:
    /* F554 0000F4E0 25102002 */  or         $v0, $s1, $zero
  .Leboot_0000F4E4:
    /* F558 0000F4E4 1C03B08F */  lw         $s0, 0x31C($sp)
    /* F55C 0000F4E8 2003B18F */  lw         $s1, 0x320($sp)
    /* F560 0000F4EC 2403B28F */  lw         $s2, 0x324($sp)
    /* F564 0000F4F0 2803B38F */  lw         $s3, 0x328($sp)
    /* F568 0000F4F4 2C03B48F */  lw         $s4, 0x32C($sp)
    /* F56C 0000F4F8 3003BF8F */  lw         $ra, 0x330($sp)
    /* F570 0000F4FC 0800E003 */  jr         $ra
    /* F574 0000F500 4003BD27 */   addiu     $sp, $sp, 0x340
endlabel func_0000F404
