.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0002E2A4, 0xB4

glabel func_0002E2A4
    /* 2E318 0002E2A4 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 2E31C 0002E2A8 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2E320 0002E2AC 01000734 */  ori        $a3, $zero, 0x1
    /* 2E324 0002E2B0 25888000 */  or         $s1, $a0, $zero
    /* 2E328 0002E2B4 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2E32C 0002E2B8 1800BFAF */  sw         $ra, 0x18($sp)
    /* 2E330 0002E2BC 0400A710 */  beq        $a1, $a3, .Leboot_0002E2D0
    /* 2E334 0002E2C0 2580C000 */   or        $s0, $a2, $zero
    /* 2E338 0002E2C4 FFFF0424 */  addiu      $a0, $zero, -0x1
    /* 2E33C 0002E2C8 1D00A414 */  bne        $a1, $a0, .Leboot_0002E340
    /* 2E340 0002E2CC 00000000 */   nop
  .Leboot_0002E2D0:
    /* 2E344 0002E2D0 19000012 */  beqz       $s0, .Leboot_0002E338
    /* 2E348 0002E2D4 00000000 */   nop
    /* 2E34C 0002E2D8 7644000C */  jal        func_000111D8
    /* 2E350 0002E2DC 25202002 */   or        $a0, $s1, $zero
    /* 2E354 0002E2E0 0400448C */  lw         $a0, 0x4($v0)
    /* 2E358 0002E2E4 0000458C */  lw         $a1, 0x0($v0)
    /* 2E35C 0002E2E8 23208500 */  subu       $a0, $a0, $a1
    /* 2E360 0002E2EC 83280400 */  sra        $a1, $a0, 2
    /* 2E364 0002E2F0 822F0500 */  srl        $a1, $a1, 30
    /* 2E368 0002E2F4 21208500 */  addu       $a0, $a0, $a1
    /* 2E36C 0002E2F8 83200400 */  sra        $a0, $a0, 2
    /* 2E370 0002E2FC FFFF8424 */  addiu      $a0, $a0, -0x1
    /* 2E374 0002E300 0F000416 */  bne        $s0, $a0, .Leboot_0002E340
    /* 2E378 0002E304 00000000 */   nop
    /* 2E37C 0002E308 7644000C */  jal        func_000111D8
    /* 2E380 0002E30C 25202002 */   or        $a0, $s1, $zero
    /* 2E384 0002E310 0400448C */  lw         $a0, 0x4($v0)
    /* 2E388 0002E314 0000458C */  lw         $a1, 0x0($v0)
    /* 2E38C 0002E318 6800228E */  lw         $v0, 0x68($s1)
    /* 2E390 0002E31C 23208500 */  subu       $a0, $a0, $a1
    /* 2E394 0002E320 83280400 */  sra        $a1, $a0, 2
    /* 2E398 0002E324 822F0500 */  srl        $a1, $a1, 30
    /* 2E39C 0002E328 21208500 */  addu       $a0, $a0, $a1
    /* 2E3A0 0002E32C 83200400 */  sra        $a0, $a0, 2
    /* 2E3A4 0002E330 04000010 */  b          .Leboot_0002E344
    /* 2E3A8 0002E334 23108200 */   subu      $v0, $a0, $v0
  .Leboot_0002E338:
    /* 2E3AC 0002E338 02000010 */  b          .Leboot_0002E344
    /* 2E3B0 0002E33C 6800228E */   lw        $v0, 0x68($s1)
  .Leboot_0002E340:
    /* 2E3B4 0002E340 25100002 */  or         $v0, $s0, $zero
  .Leboot_0002E344:
    /* 2E3B8 0002E344 1000B08F */  lw         $s0, 0x10($sp)
    /* 2E3BC 0002E348 1400B18F */  lw         $s1, 0x14($sp)
    /* 2E3C0 0002E34C 1800BF8F */  lw         $ra, 0x18($sp)
    /* 2E3C4 0002E350 0800E003 */  jr         $ra
    /* 2E3C8 0002E354 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0002E2A4
