.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00182978, 0x1C

glabel func_00182978
    /* 1829EC 00182978 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 1829F0 0018297C 1000BFAF */  sw         $ra, 0x10($sp)
    /* 1829F4 00182980 4B6A050C */  jal        func_0015A92C
    /* 1829F8 00182984 0400858C */   lw        $a1, 0x4($a0)
    /* 1829FC 00182988 1000BF8F */  lw         $ra, 0x10($sp)
    /* 182A00 0018298C 0800E003 */  jr         $ra
    /* 182A04 00182990 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_00182978
