.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

/* Handwritten function */
nonmatching func_0005FAC4, 0x70C

glabel func_0005FAC4
    /* 5FB38 0005FAC4 E0FEBD27 */  addiu      $sp, $sp, -0x120
    /* 5FB3C 0005FAC8 0E00053C */  lui        $a1, %hi(sym_000E2134)
    /* 5FB40 0005FACC 3421A58C */  lw         $a1, %lo(sym_000E2134)($a1)
    /* 5FB44 0005FAD0 0001B0AF */  sw         $s0, 0x100($sp)
    /* 5FB48 0005FAD4 25808000 */  or         $s0, $a0, $zero
    /* 5FB4C 0005FAD8 0400A48C */  lw         $a0, 0x4($a1)
    /* 5FB50 0005FADC FC00B4E7 */  swc1       $f20, 0xFC($sp)
    /* 5FB54 0005FAE0 0401B1AF */  sw         $s1, 0x104($sp)
    /* 5FB58 0005FAE4 0801B2AF */  sw         $s2, 0x108($sp)
    /* 5FB5C 0005FAE8 0C01B3AF */  sw         $s3, 0x10C($sp)
    /* 5FB60 0005FAEC 1001B4AF */  sw         $s4, 0x110($sp)
    /* 5FB64 0005FAF0 1401B5AF */  sw         $s5, 0x114($sp)
    /* 5FB68 0005FAF4 1801BFAF */  sw         $ra, 0x118($sp)
    /* 5FB6C 0005FAF8 08008010 */  beqz       $a0, .Leboot_0005FB1C
    /* 5FB70 0005FAFC 00000000 */   nop
    /* 5FB74 0005FB00 0E00043C */  lui        $a0, %hi(sym_000E2138)
    /* 5FB78 0005FB04 3821848C */  lw         $a0, %lo(sym_000E2138)($a0)
    /* 5FB7C 0005FB08 0400848C */  lw         $a0, 0x4($a0)
    /* 5FB80 0005FB0C 05008010 */  beqz       $a0, .Leboot_0005FB24
    /* 5FB84 0005FB10 00000000 */   nop
    /* 5FB88 0005FB14 18000010 */  b          .Leboot_0005FB78
    /* 5FB8C 0005FB18 00000000 */   nop
  .Leboot_0005FB1C:
    /* 5FB90 0005FB1C A2010010 */  b          .Leboot_000601A8
    /* 5FB94 0005FB20 00000000 */   nop
  .Leboot_0005FB24:
    /* 5FB98 0005FB24 5000A427 */  addiu      $a0, $sp, 0x50
    /* 5FB9C 0005FB28 5400A527 */  addiu      $a1, $sp, 0x54
    /* 5FBA0 0005FB2C 5800A627 */  addiu      $a2, $sp, 0x58
    /* 5FBA4 0005FB30 C206040C */  jal        func_00101B08
    /* 5FBA8 0005FB34 5C00A727 */   addiu     $a3, $sp, 0x5C
    /* 5FBAC 0005FB38 5000A48F */  lw         $a0, 0x50($sp)
    /* 5FBB0 0005FB3C 00608044 */  mtc1       $zero, $f12
    /* 5FBB4 0005FB40 5400A58F */  lw         $a1, 0x54($sp)
    /* 5FBB8 0005FB44 5800A68F */  lw         $a2, 0x58($sp)
    /* 5FBBC 0005FB48 5C00A78F */  lw         $a3, 0x5C($sp)
    /* 5FBC0 0005FB4C 4000ACE7 */  swc1       $f12, 0x40($sp)
    /* 5FBC4 0005FB50 4400ACE7 */  swc1       $f12, 0x44($sp)
    /* 5FBC8 0005FB54 4800ACE7 */  swc1       $f12, 0x48($sp)
    /* 5FBCC 0005FB58 803F083C */  lui        $t0, (0x3F800000 >> 16)
    /* 5FBD0 0005FB5C 00608844 */  mtc1       $t0, $f12
    /* 5FBD4 0005FB60 02000934 */  ori        $t1, $zero, 0x2
    /* 5FBD8 0005FB64 4000A827 */  addiu      $t0, $sp, 0x40
    /* 5FBDC 0005FB68 9804040C */  jal        func_00101260
    /* 5FBE0 0005FB6C 4C00ACE7 */   swc1      $f12, 0x4C($sp)
    /* 5FBE4 0005FB70 8D010010 */  b          .Leboot_000601A8
    /* 5FBE8 0005FB74 00000000 */   nop
  .Leboot_0005FB78:
    /* 5FBEC 0005FB78 5239010C */  jal        func_0004E548
    /* 5FBF0 0005FB7C 1401048E */   lw        $a0, 0x114($s0)
    /* 5FBF4 0005FB80 25804000 */  or         $s0, $v0, $zero
    /* 5FBF8 0005FB84 0D000012 */  beqz       $s0, .Leboot_0005FBBC
    /* 5FBFC 0005FB88 00000000 */   nop
    /* 5FC00 0005FB8C A600020C */  jal        func_00080298
    /* 5FC04 0005FB90 25200002 */   or        $a0, $s0, $zero
    /* 5FC08 0005FB94 09004010 */  beqz       $v0, .Leboot_0005FBBC
    /* 5FC0C 0005FB98 00000000 */   nop
    /* 5FC10 0005FB9C 2400A0AF */  sw         $zero, 0x24($sp)
    /* 5FC14 0005FBA0 2800A0AF */  sw         $zero, 0x28($sp)
    /* 5FC18 0005FBA4 2C00A0AF */  sw         $zero, 0x2C($sp)
    /* 5FC1C 0005FBA8 FFFF1224 */  addiu      $s2, $zero, -0x1
    /* 5FC20 0005FBAC 7644000C */  jal        func_000111D8
    /* 5FC24 0005FBB0 25200002 */   or        $a0, $s0, $zero
    /* 5FC28 0005FBB4 03000010 */  b          .Leboot_0005FBC4
    /* 5FC2C 0005FBB8 0000518C */   lw        $s1, 0x0($v0)
  .Leboot_0005FBBC:
    /* 5FC30 0005FBBC 7A010010 */  b          .Leboot_000601A8
    /* 5FC34 0005FBC0 00000000 */   nop
  .Leboot_0005FBC4:
    /* 5FC38 0005FBC4 7644000C */  jal        func_000111D8
    /* 5FC3C 0005FBC8 25200002 */   or        $a0, $s0, $zero
    /* 5FC40 0005FBCC 0400448C */  lw         $a0, 0x4($v0)
    /* 5FC44 0005FBD0 77002412 */  beq        $s1, $a0, .Leboot_0005FDB0
    /* 5FC48 0005FBD4 00000000 */   nop
    /* 5FC4C 0005FBD8 0000338E */  lw         $s3, 0x0($s1)
    /* 5FC50 0005FBDC 2C00048E */  lw         $a0, 0x2C($s0)
    /* 5FC54 0005FBE0 01005226 */  addiu      $s2, $s2, 0x1
    /* 5FC58 0005FBE4 D8008524 */  addiu      $a1, $a0, 0xD8
    /* 5FC5C 0005FBE8 0000A484 */  lh         $a0, 0x0($a1)
    /* 5FC60 0005FBEC 0400A78C */  lw         $a3, 0x4($a1)
    /* 5FC64 0005FBF0 21200402 */  addu       $a0, $s0, $a0
    /* 5FC68 0005FBF4 25286002 */  or         $a1, $s3, $zero
    /* 5FC6C 0005FBF8 09F8E000 */  jalr       $a3
    /* 5FC70 0005FBFC 25304002 */   or        $a2, $s2, $zero
    /* 5FC74 0005FC00 03004014 */  bnez       $v0, .Leboot_0005FC10
    /* 5FC78 0005FC04 00000000 */   nop
    /* 5FC7C 0005FC08 67000010 */  b          .Leboot_0005FDA8
    /* 5FC80 0005FC0C 00000000 */   nop
  .Leboot_0005FC10:
    /* 5FC84 0005FC10 A600020C */  jal        func_00080298
    /* 5FC88 0005FC14 25206002 */   or        $a0, $s3, $zero
    /* 5FC8C 0005FC18 03004014 */  bnez       $v0, .Leboot_0005FC28
    /* 5FC90 0005FC1C 00000000 */   nop
    /* 5FC94 0005FC20 61000010 */  b          .Leboot_0005FDA8
    /* 5FC98 0005FC24 00000000 */   nop
  .Leboot_0005FC28:
    /* 5FC9C 0005FC28 00A08044 */  mtc1       $zero, $f20
    /* 5FCA0 0005FC2C 7800B427 */  addiu      $s4, $sp, 0x78
    /* 5FCA4 0005FC30 7800B4E7 */  swc1       $f20, 0x78($sp)
    /* 5FCA8 0005FC34 7C00B4E7 */  swc1       $f20, 0x7C($sp)
    /* 5FCAC 0005FC38 25200002 */  or         $a0, $s0, $zero
    /* 5FCB0 0005FC3C 25286002 */  or         $a1, $s3, $zero
    /* 5FCB4 0005FC40 6446000C */  jal        func_00011990
    /* 5FCB8 0005FC44 25308002 */   or        $a2, $s4, $zero
    /* 5FCBC 0005FC48 2C00648E */  lw         $a0, 0x2C($s3)
    /* 5FCC0 0005FC4C 6000B527 */  addiu      $s5, $sp, 0x60
    /* 5FCC4 0005FC50 78008424 */  addiu      $a0, $a0, 0x78
    /* 5FCC8 0005FC54 00008584 */  lh         $a1, 0x0($a0)
    /* 5FCCC 0005FC58 0400868C */  lw         $a2, 0x4($a0)
    /* 5FCD0 0005FC5C 21206502 */  addu       $a0, $s3, $a1
    /* 5FCD4 0005FC60 09F8C000 */  jalr       $a2
    /* 5FCD8 0005FC64 2528A002 */   or        $a1, $s5, $zero
    /* 5FCDC 0005FC68 0000ACC6 */  lwc1       $f12, 0x0($s5)
    /* 5FCE0 0005FC6C 003F043C */  lui        $a0, (0x3F000000 >> 16)
    /* 5FCE4 0005FC70 00688444 */  mtc1       $a0, $f13
    /* 5FCE8 0005FC74 0400AEC6 */  lwc1       $f14, 0x4($s5)
    /* 5FCEC 0005FC78 02630D46 */  mul.s      $f12, $f12, $f13
    /* 5FCF0 0005FC7C 00008FC6 */  lwc1       $f15, 0x0($s4)
    /* 5FCF4 0005FC80 8000A427 */  addiu      $a0, $sp, 0x80
    /* 5FCF8 0005FC84 6800A527 */  addiu      $a1, $sp, 0x68
    /* 5FCFC 0005FC88 42730D46 */  mul.s      $f13, $f14, $f13
    /* 5FD00 0005FC8C 8000ACE7 */  swc1       $f12, 0x80($sp)
    /* 5FD04 0005FC90 8400ADE7 */  swc1       $f13, 0x84($sp)
    /* 5FD08 0005FC94 00008CC4 */  lwc1       $f12, 0x0($a0)
    /* 5FD0C 0005FC98 04008DC6 */  lwc1       $f13, 0x4($s4)
    /* 5FD10 0005FC9C 040090C4 */  lwc1       $f16, 0x4($a0)
    /* 5FD14 0005FCA0 417C0C46 */  sub.s      $f17, $f15, $f12
    /* 5FD18 0005FCA4 416B1046 */  sub.s      $f13, $f13, $f16
    /* 5FD1C 0005FCA8 6800B1E7 */  swc1       $f17, 0x68($sp)
    /* 5FD20 0005FCAC 007B0C46 */  add.s      $f12, $f15, $f12
    /* 5FD24 0005FCB0 6C00ADE7 */  swc1       $f13, 0x6C($sp)
    /* 5FD28 0005FCB4 0000ADC4 */  lwc1       $f13, 0x0($a1)
    /* 5FD2C 0005FCB8 8800ADE7 */  swc1       $f13, 0x88($sp)
    /* 5FD30 0005FCBC 0400ADC4 */  lwc1       $f13, 0x4($a1)
    /* 5FD34 0005FCC0 9000B4E7 */  swc1       $f20, 0x90($sp)
    /* 5FD38 0005FCC4 8C00ADE7 */  swc1       $f13, 0x8C($sp)
    /* 5FD3C 0005FCC8 04008DC6 */  lwc1       $f13, 0x4($s4)
    /* 5FD40 0005FCCC 04008EC4 */  lwc1       $f14, 0x4($a0)
    /* 5FD44 0005FCD0 8800A427 */  addiu      $a0, $sp, 0x88
    /* 5FD48 0005FCD4 406B0E46 */  add.s      $f13, $f13, $f14
    /* 5FD4C 0005FCD8 7000ACE7 */  swc1       $f12, 0x70($sp)
    /* 5FD50 0005FCDC 00008CC4 */  lwc1       $f12, 0x0($a0)
    /* 5FD54 0005FCE0 7000A527 */  addiu      $a1, $sp, 0x70
    /* 5FD58 0005FCE4 7400ADE7 */  swc1       $f13, 0x74($sp)
    /* 5FD5C 0005FCE8 0000ADC4 */  lwc1       $f13, 0x0($a1)
    /* 5FD60 0005FCEC 9400ADE7 */  swc1       $f13, 0x94($sp)
    /* 5FD64 0005FCF0 0400ADC4 */  lwc1       $f13, 0x4($a1)
    /* 5FD68 0005FCF4 9C00B4E7 */  swc1       $f20, 0x9C($sp)
    /* 5FD6C 0005FCF8 9800ADE7 */  swc1       $f13, 0x98($sp)
    /* 5FD70 0005FCFC A000ACE7 */  swc1       $f12, 0xA0($sp)
    /* 5FD74 0005FD00 9400A527 */  addiu      $a1, $sp, 0x94
    /* 5FD78 0005FD04 04008CC4 */  lwc1       $f12, 0x4($a0)
    /* 5FD7C 0005FD08 0000ADC4 */  lwc1       $f13, 0x0($a1)
    /* 5FD80 0005FD0C A400ACE7 */  swc1       $f12, 0xA4($sp)
    /* 5FD84 0005FD10 08008CC4 */  lwc1       $f12, 0x8($a0)
    /* 5FD88 0005FD14 AC00ADE7 */  swc1       $f13, 0xAC($sp)
    /* 5FD8C 0005FD18 A800ACE7 */  swc1       $f12, 0xA8($sp)
    /* 5FD90 0005FD1C 0400ACC4 */  lwc1       $f12, 0x4($a1)
    /* 5FD94 0005FD20 2800A48F */  lw         $a0, 0x28($sp)
    /* 5FD98 0005FD24 B000ACE7 */  swc1       $f12, 0xB0($sp)
    /* 5FD9C 0005FD28 0800ACC4 */  lwc1       $f12, 0x8($a1)
    /* 5FDA0 0005FD2C 2C00A58F */  lw         $a1, 0x2C($sp)
    /* 5FDA4 0005FD30 15008510 */  beq        $a0, $a1, .Leboot_0005FD88
    /* 5FDA8 0005FD34 B400ACE7 */   swc1      $f12, 0xB4($sp)
    /* 5FDAC 0005FD38 2800A48F */  lw         $a0, 0x28($sp)
    /* 5FDB0 0005FD3C 0E008010 */  beqz       $a0, .Leboot_0005FD78
    /* 5FDB4 0005FD40 A000A527 */   addiu     $a1, $sp, 0xA0
    /* 5FDB8 0005FD44 0000ACC4 */  lwc1       $f12, 0x0($a1)
    /* 5FDBC 0005FD48 AC00A627 */  addiu      $a2, $sp, 0xAC
    /* 5FDC0 0005FD4C 00008CE4 */  swc1       $f12, 0x0($a0)
    /* 5FDC4 0005FD50 0400ACC4 */  lwc1       $f12, 0x4($a1)
    /* 5FDC8 0005FD54 04008CE4 */  swc1       $f12, 0x4($a0)
    /* 5FDCC 0005FD58 0800ACC4 */  lwc1       $f12, 0x8($a1)
    /* 5FDD0 0005FD5C 08008CE4 */  swc1       $f12, 0x8($a0)
    /* 5FDD4 0005FD60 0000CCC4 */  lwc1       $f12, 0x0($a2)
    /* 5FDD8 0005FD64 0C008CE4 */  swc1       $f12, 0xC($a0)
    /* 5FDDC 0005FD68 0400CCC4 */  lwc1       $f12, 0x4($a2)
    /* 5FDE0 0005FD6C 10008CE4 */  swc1       $f12, 0x10($a0)
    /* 5FDE4 0005FD70 0800CCC4 */  lwc1       $f12, 0x8($a2)
    /* 5FDE8 0005FD74 14008CE4 */  swc1       $f12, 0x14($a0)
  .Leboot_0005FD78:
    /* 5FDEC 0005FD78 2800A48F */  lw         $a0, 0x28($sp)
    /* 5FDF0 0005FD7C 18008424 */  addiu      $a0, $a0, 0x18
    /* 5FDF4 0005FD80 09000010 */  b          .Leboot_0005FDA8
    /* 5FDF8 0005FD84 2800A4AF */   sw        $a0, 0x28($sp)
  .Leboot_0005FD88:
    /* 5FDFC 0005FD88 2800A58F */  lw         $a1, 0x28($sp)
    /* 5FE00 0005FD8C 2400A427 */  addiu      $a0, $sp, 0x24
    /* 5FE04 0005FD90 A000A627 */  addiu      $a2, $sp, 0xA0
    /* 5FE08 0005FD94 FB00A0A3 */  sb         $zero, 0xFB($sp)
    /* 5FE0C 0005FD98 FB00A727 */  addiu      $a3, $sp, 0xFB
    /* 5FE10 0005FD9C 01000834 */  ori        $t0, $zero, 0x1
    /* 5FE14 0005FDA0 3FFE050C */  jal        func_0017F8FC
    /* 5FE18 0005FDA4 01000934 */   ori       $t1, $zero, 0x1
  .Leboot_0005FDA8:
    /* 5FE1C 0005FDA8 86FF0010 */  b          .Leboot_0005FBC4
    /* 5FE20 0005FDAC 04003126 */   addiu     $s1, $s1, 0x4
  .Leboot_0005FDB0:
    /* 5FE24 0005FDB0 2400B08F */  lw         $s0, 0x24($sp)
    /* 5FE28 0005FDB4 2800A48F */  lw         $a0, 0x28($sp)
    /* 5FE2C 0005FDB8 3D000412 */  beq        $s0, $a0, .Leboot_0005FEB0
    /* 5FE30 0005FDBC 01001434 */   ori       $s4, $zero, 0x1
  .Leboot_0005FDC0:
    /* 5FE34 0005FDC0 2400B28F */  lw         $s2, 0x24($sp)
    /* 5FE38 0005FDC4 25980002 */  or         $s3, $s0, $zero
    /* 5FE3C 0005FDC8 31005312 */  beq        $s2, $s3, .Leboot_0005FE90
    /* 5FE40 0005FDCC 00000000 */   nop
  .Leboot_0005FDD0:
    /* 5FE44 0005FDD0 25884002 */  or         $s1, $s2, $zero
    /* 5FE48 0005FDD4 25202002 */  or         $a0, $s1, $zero
    /* 5FE4C 0005FDD8 14C7060C */  jal        collision_1430
    /* 5FE50 0005FDDC 25286002 */   or        $a1, $s3, $zero
    /* 5FE54 0005FDE0 28004010 */  beqz       $v0, .Leboot_0005FE84
    /* 5FE58 0005FDE4 00000000 */   nop
    /* 5FE5C 0005FDE8 25202002 */  or         $a0, $s1, $zero
    /* 5FE60 0005FDEC 25282002 */  or         $a1, $s1, $zero
    /* 5FE64 0005FDF0 BCC6060C */  jal        collision_12D0
    /* 5FE68 0005FDF4 25306002 */   or        $a2, $s3, $zero
    /* 5FE6C 0005FDF8 2800A48F */  lw         $a0, 0x28($sp)
    /* 5FE70 0005FDFC 18000526 */  addiu      $a1, $s0, 0x18
    /* 5FE74 0005FE00 1B00A410 */  beq        $a1, $a0, .Leboot_0005FE70
    /* 5FE78 0005FE04 00000000 */   nop
    /* 5FE7C 0005FE08 2800A48F */  lw         $a0, 0x28($sp)
    /* 5FE80 0005FE0C 18000626 */  addiu      $a2, $s0, 0x18
    /* 5FE84 0005FE10 23208600 */  subu       $a0, $a0, $a2
    /* 5FE88 0005FE14 18000534 */  ori        $a1, $zero, 0x18
    /* 5FE8C 0005FE18 1A008500 */  div        $zero, $a0, $a1
    /* 5FE90 0005FE1C F800A0A3 */  sb         $zero, 0xF8($sp)
    /* 5FE94 0005FE20 25280002 */  or         $a1, $s0, $zero
    /* 5FE98 0005FE24 12200000 */  mflo       $a0
    /* 5FE9C 0005FE28 11008018 */  blez       $a0, .Leboot_0005FE70
    /* 5FEA0 0005FE2C F900A0A3 */   sb        $zero, 0xF9($sp)
  .Leboot_0005FE30:
    /* 5FEA4 0005FE30 0000C78C */  lw         $a3, 0x0($a2)
    /* 5FEA8 0005FE34 0400C88C */  lw         $t0, 0x4($a2)
    /* 5FEAC 0005FE38 0800C98C */  lw         $t1, 0x8($a2)
    /* 5FEB0 0005FE3C 0000A7AC */  sw         $a3, 0x0($a1)
    /* 5FEB4 0005FE40 0C00C78C */  lw         $a3, 0xC($a2)
    /* 5FEB8 0005FE44 0400A8AC */  sw         $t0, 0x4($a1)
    /* 5FEBC 0005FE48 1000C88C */  lw         $t0, 0x10($a2)
    /* 5FEC0 0005FE4C 0800A9AC */  sw         $t1, 0x8($a1)
    /* 5FEC4 0005FE50 1400C98C */  lw         $t1, 0x14($a2)
    /* 5FEC8 0005FE54 0C00A7AC */  sw         $a3, 0xC($a1)
    /* 5FECC 0005FE58 1000A8AC */  sw         $t0, 0x10($a1)
    /* 5FED0 0005FE5C 1400A9AC */  sw         $t1, 0x14($a1)
    /* 5FED4 0005FE60 1800C624 */  addiu      $a2, $a2, 0x18
    /* 5FED8 0005FE64 FFFF8424 */  addiu      $a0, $a0, -0x1
    /* 5FEDC 0005FE68 F1FF801C */  bgtz       $a0, .Leboot_0005FE30
    /* 5FEE0 0005FE6C 1800A524 */   addiu     $a1, $a1, 0x18
  .Leboot_0005FE70:
    /* 5FEE4 0005FE70 2800A48F */  lw         $a0, 0x28($sp)
    /* 5FEE8 0005FE74 00001434 */  ori        $s4, $zero, 0x0
    /* 5FEEC 0005FE78 E8FF8424 */  addiu      $a0, $a0, -0x18
    /* 5FEF0 0005FE7C 04000010 */  b          .Leboot_0005FE90
    /* 5FEF4 0005FE80 2800A4AF */   sw        $a0, 0x28($sp)
  .Leboot_0005FE84:
    /* 5FEF8 0005FE84 18005226 */  addiu      $s2, $s2, 0x18
    /* 5FEFC 0005FE88 D1FF5016 */  bne        $s2, $s0, .Leboot_0005FDD0
    /* 5FF00 0005FE8C 00000000 */   nop
  .Leboot_0005FE90:
    /* 5FF04 0005FE90 03008016 */  bnez       $s4, .Leboot_0005FEA0
    /* 5FF08 0005FE94 00000000 */   nop
    /* 5FF0C 0005FE98 05000010 */  b          .Leboot_0005FEB0
    /* 5FF10 0005FE9C 00000000 */   nop
  .Leboot_0005FEA0:
    /* 5FF14 0005FEA0 2800A48F */  lw         $a0, 0x28($sp)
    /* 5FF18 0005FEA4 18001026 */  addiu      $s0, $s0, 0x18
    /* 5FF1C 0005FEA8 C5FF0416 */  bne        $s0, $a0, .Leboot_0005FDC0
    /* 5FF20 0005FEAC 00000000 */   nop
  .Leboot_0005FEB0:
    /* 5FF24 0005FEB0 BFFF8012 */  beqz       $s4, .Leboot_0005FDB0
    /* 5FF28 0005FEB4 00000000 */   nop
    /* 5FF2C 0005FEB8 3000A427 */  addiu      $a0, $sp, 0x30
    /* 5FF30 0005FEBC 3400A527 */  addiu      $a1, $sp, 0x34
    /* 5FF34 0005FEC0 3800A627 */  addiu      $a2, $sp, 0x38
    /* 5FF38 0005FEC4 C206040C */  jal        func_00101B08
    /* 5FF3C 0005FEC8 3C00A727 */   addiu     $a3, $sp, 0x3C
    /* 5FF40 0005FECC 2400B08F */  lw         $s0, 0x24($sp)
    /* 5FF44 0005FED0 2800A48F */  lw         $a0, 0x28($sp)
    /* 5FF48 0005FED4 A5000412 */  beq        $s0, $a0, .Leboot_0006016C
    /* 5FF4C 0005FED8 00000000 */   nop
    /* 5FF50 0005FEDC 25200002 */  or         $a0, $s0, $zero
  .Leboot_0005FEE0:
    /* 5FF54 0005FEE0 00008CC4 */  lwc1       $f12, 0x0($a0)
    /* 5FF58 0005FEE4 803F053C */  lui        $a1, (0x3F800000 >> 16)
    /* 5FF5C 0005FEE8 00688544 */  mtc1       $a1, $f13
    /* 5FF60 0005FEEC 003F063C */  lui        $a2, (0x3F000000 >> 16)
    /* 5FF64 0005FEF0 00630D46 */  add.s      $f12, $f12, $f13
    /* 5FF68 0005FEF4 3800A58F */  lw         $a1, 0x38($sp)
    /* 5FF6C 0005FEF8 00708644 */  mtc1       $a2, $f14
    /* 5FF70 0005FEFC 00788544 */  mtc1       $a1, $f15
    /* 5FF74 0005FF00 3000A68F */  lw         $a2, 0x30($sp)
    /* 5FF78 0005FF04 E07B8046 */  cvt.s.w    $f15, $f15
    /* 5FF7C 0005FF08 82630E46 */  mul.s      $f14, $f12, $f14
    /* 5FF80 0005FF0C 2128C500 */  addu       $a1, $a2, $a1
    /* 5FF84 0005FF10 00688544 */  mtc1       $a1, $f13
    /* 5FF88 0005FF14 00608644 */  mtc1       $a2, $f12
    /* 5FF8C 0005FF18 20638046 */  cvt.s.w    $f12, $f12
    /* 5FF90 0005FF1C 82730F46 */  mul.s      $f14, $f14, $f15
    /* 5FF94 0005FF20 80730C46 */  add.s      $f14, $f14, $f12
    /* 5FF98 0005FF24 3E700C46 */  c.le.s     $f14, $f12
    /* 5FF9C 0005FF28 00000000 */  nop
    /* 5FFA0 0005FF2C 06000145 */  bc1t       .Leboot_0005FF48 /* handwritten instruction */
    /* 5FFA4 0005FF30 606B8046 */   cvt.s.w   $f13, $f13
    /* 5FFA8 0005FF34 066B0046 */  mov.s      $f12, $f13
    /* 5FFAC 0005FF38 3C700C46 */  c.lt.s     $f14, $f12
    /* 5FFB0 0005FF3C 00000000 */  nop
    /* 5FFB4 0005FF40 01000345 */  bc1tl      .Leboot_0005FF48 /* handwritten instruction */
    /* 5FFB8 0005FF44 06730046 */   mov.s     $f12, $f14
  .Leboot_0005FF48:
    /* 5FFBC 0005FF48 113F053C */  lui        $a1, (0x3F111111 >> 16)
    /* 5FFC0 0005FF4C 04008DC4 */  lwc1       $f13, 0x4($a0)
    /* 5FFC4 0005FF50 1111A534 */  ori        $a1, $a1, (0x3F111111 & 0xFFFF)
    /* 5FFC8 0005FF54 00708544 */  mtc1       $a1, $f14
    /* 5FFCC 0005FF58 003F063C */  lui        $a2, (0x3F000000 >> 16)
    /* 5FFD0 0005FF5C 406B0E46 */  add.s      $f13, $f13, $f14
    /* 5FFD4 0005FF60 3C00A58F */  lw         $a1, 0x3C($sp)
    /* 5FFD8 0005FF64 00788644 */  mtc1       $a2, $f15
    /* 5FFDC 0005FF68 00808544 */  mtc1       $a1, $f16
    /* 5FFE0 0005FF6C 3400A68F */  lw         $a2, 0x34($sp)
    /* 5FFE4 0005FF70 20848046 */  cvt.s.w    $f16, $f16
    /* 5FFE8 0005FF74 C26B0F46 */  mul.s      $f15, $f13, $f15
    /* 5FFEC 0005FF78 2128A600 */  addu       $a1, $a1, $a2
    /* 5FFF0 0005FF7C 00708544 */  mtc1       $a1, $f14
    /* 5FFF4 0005FF80 00688644 */  mtc1       $a2, $f13
    /* 5FFF8 0005FF84 606B8046 */  cvt.s.w    $f13, $f13
    /* 5FFFC 0005FF88 C27B1046 */  mul.s      $f15, $f15, $f16
    /* 60000 0005FF8C C07B0D46 */  add.s      $f15, $f15, $f13
    /* 60004 0005FF90 3E780D46 */  c.le.s     $f15, $f13
    /* 60008 0005FF94 00000000 */  nop
    /* 6000C 0005FF98 06000145 */  bc1t       .Leboot_0005FFB4 /* handwritten instruction */
    /* 60010 0005FF9C A0738046 */   cvt.s.w   $f14, $f14
    /* 60014 0005FFA0 46730046 */  mov.s      $f13, $f14
    /* 60018 0005FFA4 3C780D46 */  c.lt.s     $f15, $f13
    /* 6001C 0005FFA8 00000000 */  nop
    /* 60020 0005FFAC 01000345 */  bc1tl      .Leboot_0005FFB4 /* handwritten instruction */
    /* 60024 0005FFB0 467B0046 */   mov.s     $f13, $f15
  .Leboot_0005FFB4:
    /* 60028 0005FFB4 0C008524 */  addiu      $a1, $a0, 0xC
    /* 6002C 0005FFB8 0000AEC4 */  lwc1       $f14, 0x0($a1)
    /* 60030 0005FFBC 803F053C */  lui        $a1, (0x3F800000 >> 16)
    /* 60034 0005FFC0 00788544 */  mtc1       $a1, $f15
    /* 60038 0005FFC4 003F063C */  lui        $a2, (0x3F000000 >> 16)
    /* 6003C 0005FFC8 80730F46 */  add.s      $f14, $f14, $f15
    /* 60040 0005FFCC 3800A58F */  lw         $a1, 0x38($sp)
    /* 60044 0005FFD0 00808644 */  mtc1       $a2, $f16
    /* 60048 0005FFD4 00888544 */  mtc1       $a1, $f17
    /* 6004C 0005FFD8 3000A68F */  lw         $a2, 0x30($sp)
    /* 60050 0005FFDC 608C8046 */  cvt.s.w    $f17, $f17
    /* 60054 0005FFE0 02741046 */  mul.s      $f16, $f14, $f16
    /* 60058 0005FFE4 2128C500 */  addu       $a1, $a2, $a1
    /* 6005C 0005FFE8 00788544 */  mtc1       $a1, $f15
    /* 60060 0005FFEC 00708644 */  mtc1       $a2, $f14
    /* 60064 0005FFF0 A0738046 */  cvt.s.w    $f14, $f14
    /* 60068 0005FFF4 02841146 */  mul.s      $f16, $f16, $f17
    /* 6006C 0005FFF8 00840E46 */  add.s      $f16, $f16, $f14
    /* 60070 0005FFFC 3E800E46 */  c.le.s     $f16, $f14
    /* 60074 00060000 00000000 */  nop
    /* 60078 00060004 06000145 */  bc1t       .Leboot_00060020 /* handwritten instruction */
    /* 6007C 00060008 E07B8046 */   cvt.s.w   $f15, $f15
    /* 60080 0006000C 867B0046 */  mov.s      $f14, $f15
    /* 60084 00060010 3C800E46 */  c.lt.s     $f16, $f14
    /* 60088 00060014 00000000 */  nop
    /* 6008C 00060018 01000345 */  bc1tl      .Leboot_00060020 /* handwritten instruction */
    /* 60090 0006001C 86830046 */   mov.s     $f14, $f16
  .Leboot_00060020:
    /* 60094 00060020 0C008424 */  addiu      $a0, $a0, 0xC
    /* 60098 00060024 04008FC4 */  lwc1       $f15, 0x4($a0)
    /* 6009C 00060028 113F043C */  lui        $a0, (0x3F111111 >> 16)
    /* 600A0 0006002C 11118434 */  ori        $a0, $a0, (0x3F111111 & 0xFFFF)
    /* 600A4 00060030 00808444 */  mtc1       $a0, $f16
    /* 600A8 00060034 003F053C */  lui        $a1, (0x3F000000 >> 16)
    /* 600AC 00060038 C07B1046 */  add.s      $f15, $f15, $f16
    /* 600B0 0006003C 3C00A48F */  lw         $a0, 0x3C($sp)
    /* 600B4 00060040 00888544 */  mtc1       $a1, $f17
    /* 600B8 00060044 00908444 */  mtc1       $a0, $f18
    /* 600BC 00060048 3400A58F */  lw         $a1, 0x34($sp)
    /* 600C0 0006004C A0948046 */  cvt.s.w    $f18, $f18
    /* 600C4 00060050 427C1146 */  mul.s      $f17, $f15, $f17
    /* 600C8 00060054 21208500 */  addu       $a0, $a0, $a1
    /* 600CC 00060058 00808444 */  mtc1       $a0, $f16
    /* 600D0 0006005C 00788544 */  mtc1       $a1, $f15
    /* 600D4 00060060 E07B8046 */  cvt.s.w    $f15, $f15
    /* 600D8 00060064 428C1246 */  mul.s      $f17, $f17, $f18
    /* 600DC 00060068 408C0F46 */  add.s      $f17, $f17, $f15
    /* 600E0 0006006C 3E880F46 */  c.le.s     $f17, $f15
    /* 600E4 00060070 00000000 */  nop
    /* 600E8 00060074 06000145 */  bc1t       .Leboot_00060090 /* handwritten instruction */
    /* 600EC 00060078 20848046 */   cvt.s.w   $f16, $f16
    /* 600F0 0006007C C6830046 */  mov.s      $f15, $f16
    /* 600F4 00060080 3C880F46 */  c.lt.s     $f17, $f15
    /* 600F8 00060084 00000000 */  nop
    /* 600FC 00060088 01000345 */  bc1tl      .Leboot_00060090 /* handwritten instruction */
    /* 60100 0006008C C68B0046 */   mov.s     $f15, $f17
  .Leboot_00060090:
    /* 60104 00060090 E000ACE7 */  swc1       $f12, 0xE0($sp)
    /* 60108 00060094 00608044 */  mtc1       $zero, $f12
    /* 6010C 00060098 E400ADE7 */  swc1       $f13, 0xE4($sp)
    /* 60110 0006009C E800ACE7 */  swc1       $f12, 0xE8($sp)
    /* 60114 000600A0 EC00AEE7 */  swc1       $f14, 0xEC($sp)
    /* 60118 000600A4 F000AFE7 */  swc1       $f15, 0xF0($sp)
    /* 6011C 000600A8 E000A627 */  addiu      $a2, $sp, 0xE0
    /* 60120 000600AC F400ACE7 */  swc1       $f12, 0xF4($sp)
    /* 60124 000600B0 0000CDC4 */  lwc1       $f13, 0x0($a2)
    /* 60128 000600B4 EC00A727 */  addiu      $a3, $sp, 0xEC
    /* 6012C 000600B8 0400CEC4 */  lwc1       $f14, 0x4($a2)
    /* 60130 000600BC 0000EFC4 */  lwc1       $f15, 0x0($a3)
    /* 60134 000600C0 0400F0C4 */  lwc1       $f16, 0x4($a3)
    /* 60138 000600C4 0800F1C4 */  lwc1       $f17, 0x8($a3)
    /* 6013C 000600C8 C17B0D46 */  sub.s      $f15, $f15, $f13
    /* 60140 000600CC 0800D2C4 */  lwc1       $f18, 0x8($a2)
    /* 60144 000600D0 01840E46 */  sub.s      $f16, $f16, $f14
    /* 60148 000600D4 418C1246 */  sub.s      $f17, $f17, $f18
    /* 6014C 000600D8 B800AFE7 */  swc1       $f15, 0xB8($sp)
    /* 60150 000600DC 4D6B0046 */  trunc.w.s  $f13, $f13
    /* 60154 000600E0 BC00B0E7 */  swc1       $f16, 0xBC($sp)
    /* 60158 000600E4 8D730046 */  trunc.w.s  $f14, $f14
    /* 6015C 000600E8 B800A827 */  addiu      $t0, $sp, 0xB8
    /* 60160 000600EC C000B1E7 */  swc1       $f17, 0xC0($sp)
    /* 60164 000600F0 0400F0C4 */  lwc1       $f16, 0x4($a3)
    /* 60168 000600F4 00680444 */  mfc1       $a0, $f13
    /* 6016C 000600F8 0400D1C4 */  lwc1       $f17, 0x4($a2)
    /* 60170 000600FC 00700544 */  mfc1       $a1, $f14
    /* 60174 00060100 0800F2C4 */  lwc1       $f18, 0x8($a3)
    /* 60178 00060104 0800D3C4 */  lwc1       $f19, 0x8($a2)
    /* 6017C 00060108 41831146 */  sub.s      $f13, $f16, $f17
    /* 60180 0006010C 000000C5 */  lwc1       $f0, 0x0($t0)
    /* 60184 00060110 81931346 */  sub.s      $f14, $f18, $f19
    /* 60188 00060114 C400AFE7 */  swc1       $f15, 0xC4($sp)
    /* 6018C 00060118 C400A727 */  addiu      $a3, $sp, 0xC4
    /* 60190 0006011C CD030046 */  trunc.w.s  $f15, $f0
    /* 60194 00060120 C800ADE7 */  swc1       $f13, 0xC8($sp)
    /* 60198 00060124 CC00AEE7 */  swc1       $f14, 0xCC($sp)
    /* 6019C 00060128 0400EDC4 */  lwc1       $f13, 0x4($a3)
    /* 601A0 0006012C 00780644 */  mfc1       $a2, $f15
    /* 601A4 00060130 D000ACE7 */  swc1       $f12, 0xD0($sp)
    /* 601A8 00060134 4D6B0046 */  trunc.w.s  $f13, $f13
    /* 601AC 00060138 D400ACE7 */  swc1       $f12, 0xD4($sp)
    /* 601B0 0006013C D800ACE7 */  swc1       $f12, 0xD8($sp)
    /* 601B4 00060140 803F073C */  lui        $a3, (0x3F800000 >> 16)
    /* 601B8 00060144 00608744 */  mtc1       $a3, $f12
    /* 601BC 00060148 D000A827 */  addiu      $t0, $sp, 0xD0
    /* 601C0 0006014C 00680744 */  mfc1       $a3, $f13
    /* 601C4 00060150 DC00ACE7 */  swc1       $f12, 0xDC($sp)
    /* 601C8 00060154 9804040C */  jal        func_00101260
    /* 601CC 00060158 02000934 */   ori       $t1, $zero, 0x2
    /* 601D0 0006015C 2800A48F */  lw         $a0, 0x28($sp)
    /* 601D4 00060160 18001026 */  addiu      $s0, $s0, 0x18
    /* 601D8 00060164 5EFF0416 */  bne        $s0, $a0, .Leboot_0005FEE0
    /* 601DC 00060168 25200002 */   or        $a0, $s0, $zero
  .Leboot_0006016C:
    /* 601E0 0006016C 2400A48F */  lw         $a0, 0x24($sp)
    /* 601E4 00060170 2800A58F */  lw         $a1, 0x28($sp)
    /* 601E8 00060174 04008510 */  beq        $a0, $a1, .Leboot_00060188
    /* 601EC 00060178 FA00A0A3 */   sb        $zero, 0xFA($sp)
    /* 601F0 0006017C 18008424 */  addiu      $a0, $a0, 0x18
  .Leboot_00060180:
    /* 601F4 00060180 FFFF8514 */  bne        $a0, $a1, .Leboot_00060180
    /* 601F8 00060184 18008424 */   addiu     $a0, $a0, 0x18
  .Leboot_00060188:
    /* 601FC 00060188 2400A48F */  lw         $a0, 0x24($sp)
    /* 60200 0006018C 06008010 */  beqz       $a0, .Leboot_000601A8
    /* 60204 00060190 00000000 */   nop
    /* 60208 00060194 2400A48F */  lw         $a0, 0x24($sp)
    /* 6020C 00060198 03008010 */  beqz       $a0, .Leboot_000601A8
    /* 60210 0006019C 00000000 */   nop
    /* 60214 000601A0 DDC6040C */  jal        func_00131B74
    /* 60218 000601A4 00000000 */   nop
  .Leboot_000601A8:
    /* 6021C 000601A8 FC00B4C7 */  lwc1       $f20, 0xFC($sp)
    /* 60220 000601AC 0001B08F */  lw         $s0, 0x100($sp)
    /* 60224 000601B0 0401B18F */  lw         $s1, 0x104($sp)
    /* 60228 000601B4 0801B28F */  lw         $s2, 0x108($sp)
    /* 6022C 000601B8 0C01B38F */  lw         $s3, 0x10C($sp)
    /* 60230 000601BC 1001B48F */  lw         $s4, 0x110($sp)
    /* 60234 000601C0 1401B58F */  lw         $s5, 0x114($sp)
    /* 60238 000601C4 1801BF8F */  lw         $ra, 0x118($sp)
    /* 6023C 000601C8 0800E003 */  jr         $ra
    /* 60240 000601CC 2001BD27 */   addiu     $sp, $sp, 0x120
endlabel func_0005FAC4
