.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00091AD4, 0x2C

glabel func_00091AD4
    /* 91B48 00091AD4 1D00043C */  lui        $a0, %hi(sym_001D4CD8)
    /* 91B4C 00091AD8 D84C8CC4 */  lwc1       $f12, %lo(sym_001D4CD8)($a0)
    /* 91B50 00091ADC 3443043C */  lui        $a0, (0x43340000 >> 16)
    /* 91B54 00091AE0 00688444 */  mtc1       $a0, $f13
    /* 91B58 00091AE4 83630D46 */  div.s      $f14, $f12, $f13
    /* 91B5C 00091AE8 1D00043C */  lui        $a0, %hi(sym_001D4CDC)
    /* 91B60 00091AEC 1D00053C */  lui        $a1, %hi(sym_001D4CE0)
    /* 91B64 00091AF0 036B0C46 */  div.s      $f12, $f13, $f12
    /* 91B68 00091AF4 DC4C8EE4 */  swc1       $f14, %lo(sym_001D4CDC)($a0)
    /* 91B6C 00091AF8 0800E003 */  jr         $ra
    /* 91B70 00091AFC E04CACE4 */   swc1      $f12, %lo(sym_001D4CE0)($a1)
endlabel func_00091AD4
