.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0002C8A0, 0x704

glabel func_0002C8A0
    /* 2C914 0002C8A0 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 2C918 0002C8A4 1C00053C */  lui        $a1, %hi(str_complex)
    /* 2C91C 0002C8A8 02000434 */  ori        $a0, $zero, 0x2
    /* 2C920 0002C8AC 1000BFAF */  sw         $ra, 0x10($sp)
    /* 2C924 0002C8B0 202A020C */  jal        func_0008A880
    /* 2C928 0002C8B4 781DA524 */   addiu     $a1, $a1, %lo(str_complex)
    /* 2C92C 0002C8B8 1C00053C */  lui        $a1, %hi(str_character)
    /* 2C930 0002C8BC 03000434 */  ori        $a0, $zero, 0x3
    /* 2C934 0002C8C0 202A020C */  jal        func_0008A880
    /* 2C938 0002C8C4 801DA524 */   addiu     $a1, $a1, %lo(str_character)
    /* 2C93C 0002C8C8 1C00053C */  lui        $a1, %hi(str_player_1D8C)
    /* 2C940 0002C8CC 04000434 */  ori        $a0, $zero, 0x4
    /* 2C944 0002C8D0 202A020C */  jal        func_0008A880
    /* 2C948 0002C8D4 8C1DA524 */   addiu     $a1, $a1, %lo(str_player_1D8C)
    /* 2C94C 0002C8D8 1C00053C */  lui        $a1, %hi(str_mplayer)
    /* 2C950 0002C8DC 05000434 */  ori        $a0, $zero, 0x5
    /* 2C954 0002C8E0 202A020C */  jal        func_0008A880
    /* 2C958 0002C8E4 941DA524 */   addiu     $a1, $a1, %lo(str_mplayer)
    /* 2C95C 0002C8E8 1C00053C */  lui        $a1, %hi(str_fplayer)
    /* 2C960 0002C8EC 06000434 */  ori        $a0, $zero, 0x6
    /* 2C964 0002C8F0 202A020C */  jal        func_0008A880
    /* 2C968 0002C8F4 9C1DA524 */   addiu     $a1, $a1, %lo(str_fplayer)
    /* 2C96C 0002C8F8 1C00053C */  lui        $a1, %hi(str_oscardelfuego)
    /* 2C970 0002C8FC 07000434 */  ori        $a0, $zero, 0x7
    /* 2C974 0002C900 202A020C */  jal        func_0008A880
    /* 2C978 0002C904 A41DA524 */   addiu     $a1, $a1, %lo(str_oscardelfuego)
    /* 2C97C 0002C908 1C00053C */  lui        $a1, %hi(str_anniehowell)
    /* 2C980 0002C90C 08000434 */  ori        $a0, $zero, 0x8
    /* 2C984 0002C910 202A020C */  jal        func_0008A880
    /* 2C988 0002C914 B41DA524 */   addiu     $a1, $a1, %lo(str_anniehowell)
    /* 2C98C 0002C918 1C00053C */  lui        $a1, %hi(str_hoothowell)
    /* 2C990 0002C91C 09000434 */  ori        $a0, $zero, 0x9
    /* 2C994 0002C920 202A020C */  jal        func_0008A880
    /* 2C998 0002C924 C01DA524 */   addiu     $a1, $a1, %lo(str_hoothowell)
    /* 2C99C 0002C928 1C00053C */  lui        $a1, %hi(str_virginyafeng)
    /* 2C9A0 0002C92C 0A000434 */  ori        $a0, $zero, 0xA
    /* 2C9A4 0002C930 202A020C */  jal        func_0008A880
    /* 2C9A8 0002C934 CC1DA524 */   addiu     $a1, $a1, %lo(str_virginyafeng)
    /* 2C9AC 0002C938 1C00053C */  lui        $a1, %hi(str_virginyafeng_vamp)
    /* 2C9B0 0002C93C 0B000434 */  ori        $a0, $zero, 0xB
    /* 2C9B4 0002C940 202A020C */  jal        func_0008A880
    /* 2C9B8 0002C944 DC1DA524 */   addiu     $a1, $a1, %lo(str_virginyafeng_vamp)
    /* 2C9BC 0002C948 1C00053C */  lui        $a1, %hi(str_betsyshelton)
    /* 2C9C0 0002C94C 0C000434 */  ori        $a0, $zero, 0xC
    /* 2C9C4 0002C950 202A020C */  jal        func_0008A880
    /* 2C9C8 0002C954 F01DA524 */   addiu     $a1, $a1, %lo(str_betsyshelton)
    /* 2C9CC 0002C958 1C00053C */  lui        $a1, %hi(str_chetcrawley)
    /* 2C9D0 0002C95C 0D000434 */  ori        $a0, $zero, 0xD
    /* 2C9D4 0002C960 202A020C */  jal        func_0008A880
    /* 2C9D8 0002C964 001EA524 */   addiu     $a1, $a1, %lo(str_chetcrawley)
    /* 2C9DC 0002C968 1C00053C */  lui        $a1, %hi(str_dantehudd)
    /* 2C9E0 0002C96C 0E000434 */  ori        $a0, $zero, 0xE
    /* 2C9E4 0002C970 202A020C */  jal        func_0008A880
    /* 2C9E8 0002C974 0C1EA524 */   addiu     $a1, $a1, %lo(str_dantehudd)
    /* 2C9EC 0002C978 1C00053C */  lui        $a1, %hi(str_dixiestills)
    /* 2C9F0 0002C97C 0F000434 */  ori        $a0, $zero, 0xF
    /* 2C9F4 0002C980 202A020C */  jal        func_0008A880
    /* 2C9F8 0002C984 181EA524 */   addiu     $a1, $a1, %lo(str_dixiestills)
    /* 2C9FC 0002C988 1C00053C */  lui        $a1, %hi(str_jesseleevarmint)
    /* 2CA00 0002C98C 10000434 */  ori        $a0, $zero, 0x10
    /* 2CA04 0002C990 202A020C */  jal        func_0008A880
    /* 2CA08 0002C994 241EA524 */   addiu     $a1, $a1, %lo(str_jesseleevarmint)
    /* 2CA0C 0002C998 1C00053C */  lui        $a1, %hi(str_penelopekline)
    /* 2CA10 0002C99C 11000434 */  ori        $a0, $zero, 0x11
    /* 2CA14 0002C9A0 202A020C */  jal        func_0008A880
    /* 2CA18 0002C9A4 341EA524 */   addiu     $a1, $a1, %lo(str_penelopekline)
    /* 2CA1C 0002C9A8 1C00053C */  lui        $a1, %hi(str_texfolsom)
    /* 2CA20 0002C9AC 12000434 */  ori        $a0, $zero, 0x12
    /* 2CA24 0002C9B0 202A020C */  jal        func_0008A880
    /* 2CA28 0002C9B4 441EA524 */   addiu     $a1, $a1, %lo(str_texfolsom)
    /* 2CA2C 0002C9B8 1C00053C */  lui        $a1, %hi(str_pitaflorica)
    /* 2CA30 0002C9BC 13000434 */  ori        $a0, $zero, 0x13
    /* 2CA34 0002C9C0 202A020C */  jal        func_0008A880
    /* 2CA38 0002C9C4 501EA524 */   addiu     $a1, $a1, %lo(str_pitaflorica)
    /* 2CA3C 0002C9C8 1C00053C */  lui        $a1, %hi(str_rolandcalonzo)
    /* 2CA40 0002C9CC 14000434 */  ori        $a0, $zero, 0x14
    /* 2CA44 0002C9D0 202A020C */  jal        func_0008A880
    /* 2CA48 0002C9D4 5C1EA524 */   addiu     $a1, $a1, %lo(str_rolandcalonzo)
    /* 2CA4C 0002C9D8 1C00053C */  lui        $a1, %hi(str_rolandcalonzo_kine)
    /* 2CA50 0002C9DC 15000434 */  ori        $a0, $zero, 0x15
    /* 2CA54 0002C9E0 202A020C */  jal        func_0008A880
    /* 2CA58 0002C9E4 6C1EA524 */   addiu     $a1, $a1, %lo(str_rolandcalonzo_kine)
    /* 2CA5C 0002C9E8 1C00053C */  lui        $a1, %hi(str_nightbeast)
    /* 2CA60 0002C9EC 16000434 */  ori        $a0, $zero, 0x16
    /* 2CA64 0002C9F0 202A020C */  jal        func_0008A880
    /* 2CA68 0002C9F4 801EA524 */   addiu     $a1, $a1, %lo(str_nightbeast)
    /* 2CA6C 0002C9F8 1C00053C */  lui        $a1, %hi(str_circebeaker)
    /* 2CA70 0002C9FC 17000434 */  ori        $a0, $zero, 0x17
    /* 2CA74 0002CA00 202A020C */  jal        func_0008A880
    /* 2CA78 0002CA04 8C1EA524 */   addiu     $a1, $a1, %lo(str_circebeaker)
    /* 2CA7C 0002CA08 1C00053C */  lui        $a1, %hi(str_opheliaspecter)
    /* 2CA80 0002CA0C 18000434 */  ori        $a0, $zero, 0x18
    /* 2CA84 0002CA10 202A020C */  jal        func_0008A880
    /* 2CA88 0002CA14 981EA524 */   addiu     $a1, $a1, %lo(str_opheliaspecter)
    /* 2CA8C 0002CA18 1C00053C */  lui        $a1, %hi(str_lokibeaker)
    /* 2CA90 0002CA1C 19000434 */  ori        $a0, $zero, 0x19
    /* 2CA94 0002CA20 202A020C */  jal        func_0008A880
    /* 2CA98 0002CA24 A81EA524 */   addiu     $a1, $a1, %lo(str_lokibeaker)
    /* 2CA9C 0002CA28 1C00053C */  lui        $a1, %hi(str_kristinalove)
    /* 2CAA0 0002CA2C 1A000434 */  ori        $a0, $zero, 0x1A
    /* 2CAA4 0002CA30 202A020C */  jal        func_0008A880
    /* 2CAA8 0002CA34 B41EA524 */   addiu     $a1, $a1, %lo(str_kristinalove)
    /* 2CAAC 0002CA38 1C00053C */  lui        $a1, %hi(str_gimibranko)
    /* 2CAB0 0002CA3C 1B000434 */  ori        $a0, $zero, 0x1B
    /* 2CAB4 0002CA40 202A020C */  jal        func_0008A880
    /* 2CAB8 0002CA44 C41EA524 */   addiu     $a1, $a1, %lo(str_gimibranko)
    /* 2CABC 0002CA48 1C00053C */  lui        $a1, %hi(str_bellagoth)
    /* 2CAC0 0002CA4C 1C000434 */  ori        $a0, $zero, 0x1C
    /* 2CAC4 0002CA50 202A020C */  jal        func_0008A880
    /* 2CAC8 0002CA54 D01EA524 */   addiu     $a1, $a1, %lo(str_bellagoth)
    /* 2CACC 0002CA58 1C00053C */  lui        $a1, %hi(str_johnnysmith)
    /* 2CAD0 0002CA5C 1D000434 */  ori        $a0, $zero, 0x1D
    /* 2CAD4 0002CA60 202A020C */  jal        func_0008A880
    /* 2CAD8 0002CA64 DC1EA524 */   addiu     $a1, $a1, %lo(str_johnnysmith)
    /* 2CADC 0002CA68 1C00053C */  lui        $a1, %hi(str_buzzgrunt)
    /* 2CAE0 0002CA6C 1E000434 */  ori        $a0, $zero, 0x1E
    /* 2CAE4 0002CA70 202A020C */  jal        func_0008A880
    /* 2CAE8 0002CA74 E81EA524 */   addiu     $a1, $a1, %lo(str_buzzgrunt)
    /* 2CAEC 0002CA78 1C00053C */  lui        $a1, %hi(str_tankgrunt)
    /* 2CAF0 0002CA7C 1F000434 */  ori        $a0, $zero, 0x1F
    /* 2CAF4 0002CA80 202A020C */  jal        func_0008A880
    /* 2CAF8 0002CA84 F41EA524 */   addiu     $a1, $a1, %lo(str_tankgrunt)
    /* 2CAFC 0002CA88 1C00053C */  lui        $a1, %hi(str_pascalcurious)
    /* 2CB00 0002CA8C 20000434 */  ori        $a0, $zero, 0x20
    /* 2CB04 0002CA90 202A020C */  jal        func_0008A880
    /* 2CB08 0002CA94 001FA524 */   addiu     $a1, $a1, %lo(str_pascalcurious)
    /* 2CB0C 0002CA98 1C00053C */  lui        $a1, %hi(str_nervoussubject)
    /* 2CB10 0002CA9C 21000434 */  ori        $a0, $zero, 0x21
    /* 2CB14 0002CAA0 202A020C */  jal        func_0008A880
    /* 2CB18 0002CAA4 101FA524 */   addiu     $a1, $a1, %lo(str_nervoussubject)
    /* 2CB1C 0002CAA8 1C00053C */  lui        $a1, %hi(str_vidcundcurious)
    /* 2CB20 0002CAAC 22000434 */  ori        $a0, $zero, 0x22
    /* 2CB24 0002CAB0 202A020C */  jal        func_0008A880
    /* 2CB28 0002CAB4 201FA524 */   addiu     $a1, $a1, %lo(str_vidcundcurious)
    /* 2CB2C 0002CAB8 1C00053C */  lui        $a1, %hi(sym_001C1F30)
    /* 2CB30 0002CABC 23000434 */  ori        $a0, $zero, 0x23
    /* 2CB34 0002CAC0 202A020C */  jal        func_0008A880
    /* 2CB38 0002CAC4 301FA524 */   addiu     $a1, $a1, %lo(sym_001C1F30)
    /* 2CB3C 0002CAC8 1C00053C */  lui        $a1, %hi(str_lazlocurious)
    /* 2CB40 0002CACC 24000434 */  ori        $a0, $zero, 0x24
    /* 2CB44 0002CAD0 202A020C */  jal        func_0008A880
    /* 2CB48 0002CAD4 341FA524 */   addiu     $a1, $a1, %lo(str_lazlocurious)
    /* 2CB4C 0002CAD8 1C00053C */  lui        $a1, %hi(str_dennisphilips)
    /* 2CB50 0002CADC 25000434 */  ori        $a0, $zero, 0x25
    /* 2CB54 0002CAE0 202A020C */  jal        func_0008A880
    /* 2CB58 0002CAE4 441FA524 */   addiu     $a1, $a1, %lo(str_dennisphilips)
    /* 2CB5C 0002CAE8 1C00053C */  lui        $a1, %hi(sym_001C1F54)
    /* 2CB60 0002CAEC 26000434 */  ori        $a0, $zero, 0x26
    /* 2CB64 0002CAF0 202A020C */  jal        func_0008A880
    /* 2CB68 0002CAF4 541FA524 */   addiu     $a1, $a1, %lo(sym_001C1F54)
    /* 2CB6C 0002CAF8 1C00053C */  lui        $a1, %hi(str_clancyhardwick)
    /* 2CB70 0002CAFC 27000434 */  ori        $a0, $zero, 0x27
    /* 2CB74 0002CB00 202A020C */  jal        func_0008A880
    /* 2CB78 0002CB04 581FA524 */   addiu     $a1, $a1, %lo(str_clancyhardwick)
    /* 2CB7C 0002CB08 1C00053C */  lui        $a1, %hi(str_eadiebutler)
    /* 2CB80 0002CB0C 28000434 */  ori        $a0, $zero, 0x28
    /* 2CB84 0002CB10 202A020C */  jal        func_0008A880
    /* 2CB88 0002CB14 681FA524 */   addiu     $a1, $a1, %lo(str_eadiebutler)
    /* 2CB8C 0002CB18 1C00053C */  lui        $a1, %hi(str_emmadarcy)
    /* 2CB90 0002CB1C 29000434 */  ori        $a0, $zero, 0x29
    /* 2CB94 0002CB20 202A020C */  jal        func_0008A880
    /* 2CB98 0002CB24 741FA524 */   addiu     $a1, $a1, %lo(str_emmadarcy)
    /* 2CB9C 0002CB28 1C00053C */  lui        $a1, %hi(str_georgemarlow)
    /* 2CBA0 0002CB2C 2A000434 */  ori        $a0, $zero, 0x2A
    /* 2CBA4 0002CB30 202A020C */  jal        func_0008A880
    /* 2CBA8 0002CB34 801FA524 */   addiu     $a1, $a1, %lo(str_georgemarlow)
    /* 2CBAC 0002CB38 1C00053C */  lui        $a1, %hi(str_heberdarcy)
    /* 2CBB0 0002CB3C 2B000434 */  ori        $a0, $zero, 0x2B
    /* 2CBB4 0002CB40 202A020C */  jal        func_0008A880
    /* 2CBB8 0002CB44 901FA524 */   addiu     $a1, $a1, %lo(str_heberdarcy)
    /* 2CBBC 0002CB48 1C00053C */  lui        $a1, %hi(str_zinamarlowe)
    /* 2CBC0 0002CB4C 2C000434 */  ori        $a0, $zero, 0x2C
    /* 2CBC4 0002CB50 202A020C */  jal        func_0008A880
    /* 2CBC8 0002CB54 9C1FA524 */   addiu     $a1, $a1, %lo(str_zinamarlowe)
    /* 2CBCC 0002CB58 1C00053C */  lui        $a1, %hi(str_territortuga)
    /* 2CBD0 0002CB5C 2D000434 */  ori        $a0, $zero, 0x2D
    /* 2CBD4 0002CB60 202A020C */  jal        func_0008A880
    /* 2CBD8 0002CB64 A81FA524 */   addiu     $a1, $a1, %lo(str_territortuga)
    /* 2CBDC 0002CB68 1C00053C */  lui        $a1, %hi(str_redsands)
    /* 2CBE0 0002CB6C 2E000434 */  ori        $a0, $zero, 0x2E
    /* 2CBE4 0002CB70 202A020C */  jal        func_0008A880
    /* 2CBE8 0002CB74 B81FA524 */   addiu     $a1, $a1, %lo(str_redsands)
    /* 2CBEC 0002CB78 1C00053C */  lui        $a1, %hi(str_cristianallard)
    /* 2CBF0 0002CB7C 2F000434 */  ori        $a0, $zero, 0x2F
    /* 2CBF4 0002CB80 202A020C */  jal        func_0008A880
    /* 2CBF8 0002CB84 C41FA524 */   addiu     $a1, $a1, %lo(str_cristianallard)
    /* 2CBFC 0002CB88 1C00053C */  lui        $a1, %hi(str_catelynlancaster)
    /* 2CC00 0002CB8C 30000434 */  ori        $a0, $zero, 0x30
    /* 2CC04 0002CB90 202A020C */  jal        func_0008A880
    /* 2CC08 0002CB94 D41FA524 */   addiu     $a1, $a1, %lo(str_catelynlancaster)
    /* 2CC0C 0002CB98 1C00053C */  lui        $a1, %hi(str_mamboloa)
    /* 2CC10 0002CB9C 31000434 */  ori        $a0, $zero, 0x31
    /* 2CC14 0002CBA0 202A020C */  jal        func_0008A880
    /* 2CC18 0002CBA4 E81FA524 */   addiu     $a1, $a1, %lo(str_mamboloa)
    /* 2CC1C 0002CBA8 1C00053C */  lui        $a1, %hi(str_blank_1FF4)
    /* 2CC20 0002CBAC 32000434 */  ori        $a0, $zero, 0x32
    /* 2CC24 0002CBB0 202A020C */  jal        func_0008A880
    /* 2CC28 0002CBB4 F41FA524 */   addiu     $a1, $a1, %lo(str_blank_1FF4)
    /* 2CC2C 0002CBB8 1C00053C */  lui        $a1, %hi(str_emilyemory)
    /* 2CC30 0002CBBC 33000434 */  ori        $a0, $zero, 0x33
    /* 2CC34 0002CBC0 202A020C */  jal        func_0008A880
    /* 2CC38 0002CBC4 FC1FA524 */   addiu     $a1, $a1, %lo(str_emilyemory)
    /* 2CC3C 0002CBC8 1C00053C */  lui        $a1, %hi(str_jillsmith)
    /* 2CC40 0002CBCC 34000434 */  ori        $a0, $zero, 0x34
    /* 2CC44 0002CBD0 202A020C */  jal        func_0008A880
    /* 2CC48 0002CBD4 0820A524 */   addiu     $a1, $a1, %lo(str_jillsmith)
    /* 2CC4C 0002CBD8 1C00053C */  lui        $a1, %hi(str_rippgrunt)
    /* 2CC50 0002CBDC 35000434 */  ori        $a0, $zero, 0x35
    /* 2CC54 0002CBE0 202A020C */  jal        func_0008A880
    /* 2CC58 0002CBE4 1420A524 */   addiu     $a1, $a1, %lo(str_rippgrunt)
    /* 2CC5C 0002CBE8 1C00053C */  lui        $a1, %hi(str_robertarossum)
    /* 2CC60 0002CBEC 36000434 */  ori        $a0, $zero, 0x36
    /* 2CC64 0002CBF0 202A020C */  jal        func_0008A880
    /* 2CC68 0002CBF4 2020A524 */   addiu     $a1, $a1, %lo(str_robertarossum)
    /* 2CC6C 0002CBF8 1C00053C */  lui        $a1, %hi(str_jenniesmith)
    /* 2CC70 0002CBFC 37000434 */  ori        $a0, $zero, 0x37
    /* 2CC74 0002CC00 202A020C */  jal        func_0008A880
    /* 2CC78 0002CC04 3020A524 */   addiu     $a1, $a1, %lo(str_jenniesmith)
    /* 2CC7C 0002CC08 1C00053C */  lui        $a1, %hi(str_deputyduncan)
    /* 2CC80 0002CC0C 38000434 */  ori        $a0, $zero, 0x38
    /* 2CC84 0002CC10 202A020C */  jal        func_0008A880
    /* 2CC88 0002CC14 3C20A524 */   addiu     $a1, $a1, %lo(str_deputyduncan)
    /* 2CC8C 0002CC18 1C00053C */  lui        $a1, %hi(str_isaacrossum)
    /* 2CC90 0002CC1C 39000434 */  ori        $a0, $zero, 0x39
    /* 2CC94 0002CC20 202A020C */  jal        func_0008A880
    /* 2CC98 0002CC24 4C20A524 */   addiu     $a1, $a1, %lo(str_isaacrossum)
    /* 2CC9C 0002CC28 1C00053C */  lui        $a1, %hi(str_orderlyblack)
    /* 2CCA0 0002CC2C 3A000434 */  ori        $a0, $zero, 0x3A
    /* 2CCA4 0002CC30 202A020C */  jal        func_0008A880
    /* 2CCA8 0002CC34 5820A524 */   addiu     $a1, $a1, %lo(str_orderlyblack)
    /* 2CCAC 0002CC38 1C00053C */  lui        $a1, %hi(str_orderlywhite)
    /* 2CCB0 0002CC3C 3B000434 */  ori        $a0, $zero, 0x3B
    /* 2CCB4 0002CC40 202A020C */  jal        func_0008A880
    /* 2CCB8 0002CC44 6820A524 */   addiu     $a1, $a1, %lo(str_orderlywhite)
    /* 2CCBC 0002CC48 1C00053C */  lui        $a1, %hi(str_hazeldoss)
    /* 2CCC0 0002CC4C 3C000434 */  ori        $a0, $zero, 0x3C
    /* 2CCC4 0002CC50 202A020C */  jal        func_0008A880
    /* 2CCC8 0002CC54 7820A524 */   addiu     $a1, $a1, %lo(str_hazeldoss)
    /* 2CCCC 0002CC58 1C00053C */  lui        $a1, %hi(str_mib1)
    /* 2CCD0 0002CC5C 3D000434 */  ori        $a0, $zero, 0x3D
    /* 2CCD4 0002CC60 202A020C */  jal        func_0008A880
    /* 2CCD8 0002CC64 8420A524 */   addiu     $a1, $a1, %lo(str_mib1)
    /* 2CCDC 0002CC68 1C00053C */  lui        $a1, %hi(str_mib2)
    /* 2CCE0 0002CC6C 3E000434 */  ori        $a0, $zero, 0x3E
    /* 2CCE4 0002CC70 202A020C */  jal        func_0008A880
    /* 2CCE8 0002CC74 8C20A524 */   addiu     $a1, $a1, %lo(str_mib2)
    /* 2CCEC 0002CC78 1C00053C */  lui        $a1, %hi(str_mib3)
    /* 2CCF0 0002CC7C 3F000434 */  ori        $a0, $zero, 0x3F
    /* 2CCF4 0002CC80 202A020C */  jal        func_0008A880
    /* 2CCF8 0002CC84 9420A524 */   addiu     $a1, $a1, %lo(str_mib3)
    /* 2CCFC 0002CC88 1C00053C */  lui        $a1, %hi(str_mib4)
    /* 2CD00 0002CC8C 40000434 */  ori        $a0, $zero, 0x40
    /* 2CD04 0002CC90 202A020C */  jal        func_0008A880
    /* 2CD08 0002CC94 9C20A524 */   addiu     $a1, $a1, %lo(str_mib4)
    /* 2CD0C 0002CC98 1C00053C */  lui        $a1, %hi(str_sinjinbalani)
    /* 2CD10 0002CC9C 41000434 */  ori        $a0, $zero, 0x41
    /* 2CD14 0002CCA0 202A020C */  jal        func_0008A880
    /* 2CD18 0002CCA4 A420A524 */   addiu     $a1, $a1, %lo(str_sinjinbalani)
    /* 2CD1C 0002CCA8 1C00053C */  lui        $a1, %hi(str_sinjinbalani_kine)
    /* 2CD20 0002CCAC 42000434 */  ori        $a0, $zero, 0x42
    /* 2CD24 0002CCB0 202A020C */  jal        func_0008A880
    /* 2CD28 0002CCB4 B420A524 */   addiu     $a1, $a1, %lo(str_sinjinbalani_kine)
    /* 2CD2C 0002CCB8 1C00053C */  lui        $a1, %hi(str_lincolnbroadsheet)
    /* 2CD30 0002CCBC 43000434 */  ori        $a0, $zero, 0x43
    /* 2CD34 0002CCC0 202A020C */  jal        func_0008A880
    /* 2CD38 0002CCC4 C820A524 */   addiu     $a1, $a1, %lo(str_lincolnbroadsheet)
    /* 2CD3C 0002CCC8 1C00053C */  lui        $a1, %hi(str_berettawinchester)
    /* 2CD40 0002CCCC 44000434 */  ori        $a0, $zero, 0x44
    /* 2CD44 0002CCD0 202A020C */  jal        func_0008A880
    /* 2CD48 0002CCD4 DC20A524 */   addiu     $a1, $a1, %lo(str_berettawinchester)
    /* 2CD4C 0002CCD8 1C00053C */  lui        $a1, %hi(str_bulldratch)
    /* 2CD50 0002CCDC 45000434 */  ori        $a0, $zero, 0x45
    /* 2CD54 0002CCE0 202A020C */  jal        func_0008A880
    /* 2CD58 0002CCE4 F020A524 */   addiu     $a1, $a1, %lo(str_bulldratch)
    /* 2CD5C 0002CCE8 1C00053C */  lui        $a1, %hi(str_clintheckler)
    /* 2CD60 0002CCEC 46000434 */  ori        $a0, $zero, 0x46
    /* 2CD64 0002CCF0 202A020C */  jal        func_0008A880
    /* 2CD68 0002CCF4 FC20A524 */   addiu     $a1, $a1, %lo(str_clintheckler)
    /* 2CD6C 0002CCF8 1C00053C */  lui        $a1, %hi(str_dominicnewlow)
    /* 2CD70 0002CCFC 47000434 */  ori        $a0, $zero, 0x47
    /* 2CD74 0002CD00 202A020C */  jal        func_0008A880
    /* 2CD78 0002CD04 0C21A524 */   addiu     $a1, $a1, %lo(str_dominicnewlow)
    /* 2CD7C 0002CD08 1C00053C */  lui        $a1, %hi(str_erinphilips)
    /* 2CD80 0002CD0C 48000434 */  ori        $a0, $zero, 0x48
    /* 2CD84 0002CD10 202A020C */  jal        func_0008A880
    /* 2CD88 0002CD14 1C21A524 */   addiu     $a1, $a1, %lo(str_erinphilips)
    /* 2CD8C 0002CD18 1C00053C */  lui        $a1, %hi(str_janekoch)
    /* 2CD90 0002CD1C 49000434 */  ori        $a0, $zero, 0x49
    /* 2CD94 0002CD20 202A020C */  jal        func_0008A880
    /* 2CD98 0002CD24 2821A524 */   addiu     $a1, $a1, %lo(str_janekoch)
    /* 2CD9C 0002CD28 1C00053C */  lui        $a1, %hi(str_marieaulait)
    /* 2CDA0 0002CD2C 4A000434 */  ori        $a0, $zero, 0x4A
    /* 2CDA4 0002CD30 202A020C */  jal        func_0008A880
    /* 2CDA8 0002CD34 3421A524 */   addiu     $a1, $a1, %lo(str_marieaulait)
    /* 2CDAC 0002CD38 1C00053C */  lui        $a1, %hi(str_rickwong)
    /* 2CDB0 0002CD3C 4B000434 */  ori        $a0, $zero, 0x4B
    /* 2CDB4 0002CD40 202A020C */  jal        func_0008A880
    /* 2CDB8 0002CD44 4021A524 */   addiu     $a1, $a1, %lo(str_rickwong)
    /* 2CDBC 0002CD48 1C00053C */  lui        $a1, %hi(str_sarastarr)
    /* 2CDC0 0002CD4C 4C000434 */  ori        $a0, $zero, 0x4C
    /* 2CDC4 0002CD50 202A020C */  jal        func_0008A880
    /* 2CDC8 0002CD54 4C21A524 */   addiu     $a1, $a1, %lo(str_sarastarr)
    /* 2CDCC 0002CD58 1C00053C */  lui        $a1, %hi(str_scootsturnberry)
    /* 2CDD0 0002CD5C 4D000434 */  ori        $a0, $zero, 0x4D
    /* 2CDD4 0002CD60 202A020C */  jal        func_0008A880
    /* 2CDD8 0002CD64 5821A524 */   addiu     $a1, $a1, %lo(str_scootsturnberry)
    /* 2CDDC 0002CD68 1C00053C */  lui        $a1, %hi(str_stenluger)
    /* 2CDE0 0002CD6C 4E000434 */  ori        $a0, $zero, 0x4E
    /* 2CDE4 0002CD70 202A020C */  jal        func_0008A880
    /* 2CDE8 0002CD74 6821A524 */   addiu     $a1, $a1, %lo(str_stenluger)
    /* 2CDEC 0002CD78 1C00053C */  lui        $a1, %hi(str_tunaktun)
    /* 2CDF0 0002CD7C 4F000434 */  ori        $a0, $zero, 0x4F
    /* 2CDF4 0002CD80 202A020C */  jal        func_0008A880
    /* 2CDF8 0002CD84 7421A524 */   addiu     $a1, $a1, %lo(str_tunaktun)
    /* 2CDFC 0002CD88 1C00053C */  lui        $a1, %hi(str_tureenallard)
    /* 2CE00 0002CD8C 50000434 */  ori        $a0, $zero, 0x50
    /* 2CE04 0002CD90 202A020C */  jal        func_0008A880
    /* 2CE08 0002CD94 8021A524 */   addiu     $a1, $a1, %lo(str_tureenallard)
    /* 2CE0C 0002CD98 1C00053C */  lui        $a1, %hi(str_vaughanferretino)
    /* 2CE10 0002CD9C 51000434 */  ori        $a0, $zero, 0x51
    /* 2CE14 0002CDA0 202A020C */  jal        func_0008A880
    /* 2CE18 0002CDA4 9021A524 */   addiu     $a1, $a1, %lo(str_vaughanferretino)
    /* 2CE1C 0002CDA8 1C00053C */  lui        $a1, %hi(str_yevacomonova)
    /* 2CE20 0002CDAC 52000434 */  ori        $a0, $zero, 0x52
    /* 2CE24 0002CDB0 202A020C */  jal        func_0008A880
    /* 2CE28 0002CDB4 A421A524 */   addiu     $a1, $a1, %lo(str_yevacomonova)
    /* 2CE2C 0002CDB8 1C00053C */  lui        $a1, %hi(str_zenmu)
    /* 2CE30 0002CDBC 53000434 */  ori        $a0, $zero, 0x53
    /* 2CE34 0002CDC0 202A020C */  jal        func_0008A880
    /* 2CE38 0002CDC4 B421A524 */   addiu     $a1, $a1, %lo(str_zenmu)
    /* 2CE3C 0002CDC8 1C00053C */  lui        $a1, %hi(str_organghost)
    /* 2CE40 0002CDCC 54000434 */  ori        $a0, $zero, 0x54
    /* 2CE44 0002CDD0 202A020C */  jal        func_0008A880
    /* 2CE48 0002CDD4 BC21A524 */   addiu     $a1, $a1, %lo(str_organghost)
    /* 2CE4C 0002CDD8 1C00053C */  lui        $a1, %hi(str_eltoro)
    /* 2CE50 0002CDDC 55000434 */  ori        $a0, $zero, 0x55
    /* 2CE54 0002CDE0 202A020C */  jal        func_0008A880
    /* 2CE58 0002CDE4 C821A524 */   addiu     $a1, $a1, %lo(str_eltoro)
    /* 2CE5C 0002CDE8 1C00053C */  lui        $a1, %hi(str_tinamansfield)
    /* 2CE60 0002CDEC 56000434 */  ori        $a0, $zero, 0x56
    /* 2CE64 0002CDF0 202A020C */  jal        func_0008A880
    /* 2CE68 0002CDF4 D021A524 */   addiu     $a1, $a1, %lo(str_tinamansfield)
    /* 2CE6C 0002CDF8 1C00053C */  lui        $a1, %hi(str_ashtonfelt)
    /* 2CE70 0002CDFC 57000434 */  ori        $a0, $zero, 0x57
    /* 2CE74 0002CE00 202A020C */  jal        func_0008A880
    /* 2CE78 0002CE04 E021A524 */   addiu     $a1, $a1, %lo(str_ashtonfelt)
    /* 2CE7C 0002CE08 1C00053C */  lui        $a1, %hi(str_kerstenspooks)
    /* 2CE80 0002CE0C 58000434 */  ori        $a0, $zero, 0x58
    /* 2CE84 0002CE10 202A020C */  jal        func_0008A880
    /* 2CE88 0002CE14 EC21A524 */   addiu     $a1, $a1, %lo(str_kerstenspooks)
    /* 2CE8C 0002CE18 1C00053C */  lui        $a1, %hi(str_cowthulu)
    /* 2CE90 0002CE1C 59000434 */  ori        $a0, $zero, 0x59
    /* 2CE94 0002CE20 202A020C */  jal        func_0008A880
    /* 2CE98 0002CE24 FC21A524 */   addiu     $a1, $a1, %lo(str_cowthulu)
    /* 2CE9C 0002CE28 1C00053C */  lui        $a1, %hi(str_doctordominion)
    /* 2CEA0 0002CE2C 5A000434 */  ori        $a0, $zero, 0x5A
    /* 2CEA4 0002CE30 202A020C */  jal        func_0008A880
    /* 2CEA8 0002CE34 0822A524 */   addiu     $a1, $a1, %lo(str_doctordominion)
    /* 2CEAC 0002CE38 1C00053C */  lui        $a1, %hi(str_player0)
    /* 2CEB0 0002CE3C 5B000434 */  ori        $a0, $zero, 0x5B
    /* 2CEB4 0002CE40 202A020C */  jal        func_0008A880
    /* 2CEB8 0002CE44 1822A524 */   addiu     $a1, $a1, %lo(str_player0)
    /* 2CEBC 0002CE48 1C00053C */  lui        $a1, %hi(str_player1)
    /* 2CEC0 0002CE4C 5C000434 */  ori        $a0, $zero, 0x5C
    /* 2CEC4 0002CE50 202A020C */  jal        func_0008A880
    /* 2CEC8 0002CE54 2022A524 */   addiu     $a1, $a1, %lo(str_player1)
    /* 2CECC 0002CE58 1C00053C */  lui        $a1, %hi(str_player2)
    /* 2CED0 0002CE5C 5D000434 */  ori        $a0, $zero, 0x5D
    /* 2CED4 0002CE60 202A020C */  jal        func_0008A880
    /* 2CED8 0002CE64 2822A524 */   addiu     $a1, $a1, %lo(str_player2)
    /* 2CEDC 0002CE68 1C00053C */  lui        $a1, %hi(str_player3)
    /* 2CEE0 0002CE6C 5E000434 */  ori        $a0, $zero, 0x5E
    /* 2CEE4 0002CE70 202A020C */  jal        func_0008A880
    /* 2CEE8 0002CE74 3022A524 */   addiu     $a1, $a1, %lo(str_player3)
    /* 2CEEC 0002CE78 1C00053C */  lui        $a1, %hi(str_player4)
    /* 2CEF0 0002CE7C 5F000434 */  ori        $a0, $zero, 0x5F
    /* 2CEF4 0002CE80 202A020C */  jal        func_0008A880
    /* 2CEF8 0002CE84 3822A524 */   addiu     $a1, $a1, %lo(str_player4)
    /* 2CEFC 0002CE88 1C00053C */  lui        $a1, %hi(str_tychocurious)
    /* 2CF00 0002CE8C 60000434 */  ori        $a0, $zero, 0x60
    /* 2CF04 0002CE90 202A020C */  jal        func_0008A880
    /* 2CF08 0002CE94 4022A524 */   addiu     $a1, $a1, %lo(str_tychocurious)
    /* 2CF0C 0002CE98 1C00053C */  lui        $a1, %hi(str_bodyreaper)
    /* 2CF10 0002CE9C 61000434 */  ori        $a0, $zero, 0x61
    /* 2CF14 0002CEA0 202A020C */  jal        func_0008A880
    /* 2CF18 0002CEA4 5022A524 */   addiu     $a1, $a1, %lo(str_bodyreaper)
    /* 2CF1C 0002CEA8 1C00053C */  lui        $a1, %hi(str_beddoubleartnouveu)
    /* 2CF20 0002CEAC 62000434 */  ori        $a0, $zero, 0x62
    /* 2CF24 0002CEB0 202A020C */  jal        func_0008A880
    /* 2CF28 0002CEB4 5C22A524 */   addiu     $a1, $a1, %lo(str_beddoubleartnouveu)
    /* 2CF2C 0002CEB8 1C00053C */  lui        $a1, %hi(str_beddoublebasic)
    /* 2CF30 0002CEBC 63000434 */  ori        $a0, $zero, 0x63
    /* 2CF34 0002CEC0 202A020C */  jal        func_0008A880
    /* 2CF38 0002CEC4 7022A524 */   addiu     $a1, $a1, %lo(str_beddoublebasic)
    /* 2CF3C 0002CEC8 1C00053C */  lui        $a1, %hi(str_beddoubledesigner)
    /* 2CF40 0002CECC 64000434 */  ori        $a0, $zero, 0x64
    /* 2CF44 0002CED0 202A020C */  jal        func_0008A880
    /* 2CF48 0002CED4 8022A524 */   addiu     $a1, $a1, %lo(str_beddoubledesigner)
    /* 2CF4C 0002CED8 1C00053C */  lui        $a1, %hi(str_beddoublemedieval)
    /* 2CF50 0002CEDC 65000434 */  ori        $a0, $zero, 0x65
    /* 2CF54 0002CEE0 202A020C */  jal        func_0008A880
    /* 2CF58 0002CEE4 9422A524 */   addiu     $a1, $a1, %lo(str_beddoublemedieval)
    /* 2CF5C 0002CEE8 1C00053C */  lui        $a1, %hi(str_bedsinglebarracks)
    /* 2CF60 0002CEEC 66000434 */  ori        $a0, $zero, 0x66
    /* 2CF64 0002CEF0 202A020C */  jal        func_0008A880
    /* 2CF68 0002CEF4 A822A524 */   addiu     $a1, $a1, %lo(str_bedsinglebarracks)
    /* 2CF6C 0002CEF8 1C00053C */  lui        $a1, %hi(str_bedsinglecheap)
    /* 2CF70 0002CEFC 67000434 */  ori        $a0, $zero, 0x67
    /* 2CF74 0002CF00 202A020C */  jal        func_0008A880
    /* 2CF78 0002CF04 BC22A524 */   addiu     $a1, $a1, %lo(str_bedsinglecheap)
    /* 2CF7C 0002CF08 1C00053C */  lui        $a1, %hi(str_bedsinglemedieval)
    /* 2CF80 0002CF0C 68000434 */  ori        $a0, $zero, 0x68
    /* 2CF84 0002CF10 202A020C */  jal        func_0008A880
    /* 2CF88 0002CF14 CC22A524 */   addiu     $a1, $a1, %lo(str_bedsinglemedieval)
    /* 2CF8C 0002CF18 1C00053C */  lui        $a1, %hi(str_bedsinglemoderate)
    /* 2CF90 0002CF1C 69000434 */  ori        $a0, $zero, 0x69
    /* 2CF94 0002CF20 202A020C */  jal        func_0008A880
    /* 2CF98 0002CF24 E022A524 */   addiu     $a1, $a1, %lo(str_bedsinglemoderate)
    /* 2CF9C 0002CF28 1C00053C */  lui        $a1, %hi(str_magicmirror)
    /* 2CFA0 0002CF2C 6A000434 */  ori        $a0, $zero, 0x6A
    /* 2CFA4 0002CF30 202A020C */  jal        func_0008A880
    /* 2CFA8 0002CF34 F422A524 */   addiu     $a1, $a1, %lo(str_magicmirror)
    /* 2CFAC 0002CF38 1C00053C */  lui        $a1, %hi(str_carmagazine)
    /* 2CFB0 0002CF3C 6B000434 */  ori        $a0, $zero, 0x6B
    /* 2CFB4 0002CF40 202A020C */  jal        func_0008A880
    /* 2CFB8 0002CF44 0023A524 */   addiu     $a1, $a1, %lo(str_carmagazine)
    /* 2CFBC 0002CF48 1C00053C */  lui        $a1, %hi(str_book)
    /* 2CFC0 0002CF4C 6C000434 */  ori        $a0, $zero, 0x6C
    /* 2CFC4 0002CF50 202A020C */  jal        func_0008A880
    /* 2CFC8 0002CF54 0C23A524 */   addiu     $a1, $a1, %lo(str_book)
    /* 2CFCC 0002CF58 1C00053C */  lui        $a1, %hi(str_plumbobcar)
    /* 2CFD0 0002CF5C 6D000434 */  ori        $a0, $zero, 0x6D
    /* 2CFD4 0002CF60 202A020C */  jal        func_0008A880
    /* 2CFD8 0002CF64 1423A524 */   addiu     $a1, $a1, %lo(str_plumbobcar)
    /* 2CFDC 0002CF68 1C00053C */  lui        $a1, %hi(str_moneytree)
    /* 2CFE0 0002CF6C 6E000434 */  ori        $a0, $zero, 0x6E
    /* 2CFE4 0002CF70 202A020C */  jal        func_0008A880
    /* 2CFE8 0002CF74 2023A524 */   addiu     $a1, $a1, %lo(str_moneytree)
    /* 2CFEC 0002CF78 1C00053C */  lui        $a1, %hi(str_cowthulustage)
    /* 2CFF0 0002CF7C 6F000434 */  ori        $a0, $zero, 0x6F
    /* 2CFF4 0002CF80 202A020C */  jal        func_0008A880
    /* 2CFF8 0002CF84 2C23A524 */   addiu     $a1, $a1, %lo(str_cowthulustage)
    /* 2CFFC 0002CF88 1C00053C */  lui        $a1, %hi(sym_001C233C)
    /* 2D000 0002CF8C 70000434 */  ori        $a0, $zero, 0x70
    /* 2D004 0002CF90 202A020C */  jal        func_0008A880
    /* 2D008 0002CF94 3C23A524 */   addiu     $a1, $a1, %lo(sym_001C233C)
    /* 2D00C 0002CF98 1000BF8F */  lw         $ra, 0x10($sp)
    /* 2D010 0002CF9C 0800E003 */  jr         $ra
    /* 2D014 0002CFA0 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0002C8A0
