.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0003ABA4, 0xFC

glabel func_0003ABA4
    /* 3AC18 0003ABA4 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 3AC1C 0003ABA8 1000B0AF */  sw         $s0, 0x10($sp)
    /* 3AC20 0003ABAC 25808000 */  or         $s0, $a0, $zero
    /* 3AC24 0003ABB0 1C00053C */  lui        $a1, %hi(str_SaveSnapshot)
    /* 3AC28 0003ABB4 18000434 */  ori        $a0, $zero, 0x18
    /* 3AC2C 0003ABB8 1400BFAF */  sw         $ra, 0x14($sp)
    /* 3AC30 0003ABBC E75A010C */  jal        func_00056B9C
    /* 3AC34 0003ABC0 C435A524 */   addiu     $a1, $a1, %lo(str_SaveSnapshot)
    /* 3AC38 0003ABC4 25200002 */  or         $a0, $s0, $zero
    /* 3AC3C 0003ABC8 01000534 */  ori        $a1, $zero, 0x1
    /* 3AC40 0003ABCC 061F040C */  jal        func_00107C18
    /* 3AC44 0003ABD0 03000634 */   ori       $a2, $zero, 0x3
    /* 3AC48 0003ABD4 25200002 */  or         $a0, $s0, $zero
    /* 3AC4C 0003ABD8 2F3F040C */  jal        func_0010FCBC
    /* 3AC50 0003ABDC 01000534 */   ori       $a1, $zero, 0x1
    /* 3AC54 0003ABE0 0D030046 */  trunc.w.s  $f12, $f0
    /* 3AC58 0003ABE4 9738020C */  jal        func_0008E25C
    /* 3AC5C 0003ABE8 00601044 */   mfc1      $s0, $f12
    /* 3AC60 0003ABEC 25204000 */  or         $a0, $v0, $zero
    /* 3AC64 0003ABF0 3934020C */  jal        func_0008D0E4
    /* 3AC68 0003ABF4 25280002 */   or        $a1, $s0, $zero
    /* 3AC6C 0003ABF8 25204000 */  or         $a0, $v0, $zero
    /* 3AC70 0003ABFC 12008010 */  beqz       $a0, .Leboot_0003AC48
    /* 3AC74 0003AC00 00000000 */   nop
    /* 3AC78 0003AC04 5800858C */  lw         $a1, 0x58($a0)
    /* 3AC7C 0003AC08 5800A524 */  addiu      $a1, $a1, 0x58
    /* 3AC80 0003AC0C 0000A684 */  lh         $a2, 0x0($a1)
    /* 3AC84 0003AC10 0400A58C */  lw         $a1, 0x4($a1)
    /* 3AC88 0003AC14 09F8A000 */  jalr       $a1
    /* 3AC8C 0003AC18 21208600 */   addu      $a0, $a0, $a2
    /* 3AC90 0003AC1C 25204000 */  or         $a0, $v0, $zero
    /* 3AC94 0003AC20 11008014 */  bnez       $a0, .Leboot_0003AC68
    /* 3AC98 0003AC24 00000000 */   nop
    /* 3AC9C 0003AC28 1C00043C */  lui        $a0, %hi(sym_001C3604)
    /* 3ACA0 0003AC2C 25280002 */  or         $a1, $s0, $zero
    /* 3ACA4 0003AC30 53DA020C */  jal        func_000B694C
    /* 3ACA8 0003AC34 04368424 */   addiu     $a0, $a0, %lo(sym_001C3604)
    /* 3ACAC 0003AC38 E95A010C */  jal        func_00056BA4
    /* 3ACB0 0003AC3C 18000434 */   ori       $a0, $zero, 0x18
    /* 3ACB4 0003AC40 13000010 */  b          .Leboot_0003AC90
    /* 3ACB8 0003AC44 25100000 */   or        $v0, $zero, $zero
  .Leboot_0003AC48:
    /* 3ACBC 0003AC48 1C00043C */  lui        $a0, %hi(sym_001C35D4)
    /* 3ACC0 0003AC4C 25280002 */  or         $a1, $s0, $zero
    /* 3ACC4 0003AC50 53DA020C */  jal        func_000B694C
    /* 3ACC8 0003AC54 D4358424 */   addiu     $a0, $a0, %lo(sym_001C35D4)
    /* 3ACCC 0003AC58 E95A010C */  jal        func_00056BA4
    /* 3ACD0 0003AC5C 18000434 */   ori       $a0, $zero, 0x18
    /* 3ACD4 0003AC60 0B000010 */  b          .Leboot_0003AC90
    /* 3ACD8 0003AC64 25100000 */   or        $v0, $zero, $zero
  .Leboot_0003AC68:
    /* 3ACDC 0003AC68 1401858C */  lw         $a1, 0x114($a0)
    /* 3ACE0 0003AC6C 10018424 */  addiu      $a0, $a0, 0x110
    /* 3ACE4 0003AC70 6000A524 */  addiu      $a1, $a1, 0x60
    /* 3ACE8 0003AC74 0000A684 */  lh         $a2, 0x0($a1)
    /* 3ACEC 0003AC78 0400A58C */  lw         $a1, 0x4($a1)
    /* 3ACF0 0003AC7C 09F8A000 */  jalr       $a1
    /* 3ACF4 0003AC80 21208600 */   addu      $a0, $a0, $a2
    /* 3ACF8 0003AC84 A22E010C */  jal        func_0004BA88
    /* 3ACFC 0003AC88 25204000 */   or        $a0, $v0, $zero
    /* 3AD00 0003AC8C 25100000 */  or         $v0, $zero, $zero
  .Leboot_0003AC90:
    /* 3AD04 0003AC90 1000B08F */  lw         $s0, 0x10($sp)
    /* 3AD08 0003AC94 1400BF8F */  lw         $ra, 0x14($sp)
    /* 3AD0C 0003AC98 0800E003 */  jr         $ra
    /* 3AD10 0003AC9C 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0003ABA4
