.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00030A38, 0x14C

glabel func_00030A38
    /* 30AAC 00030A38 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 30AB0 00030A3C 1D00043C */  lui        $a0, %hi(sym_001D3678)
    /* 30AB4 00030A40 78368CC4 */  lwc1       $f12, %lo(sym_001D3678)($a0)
    /* 30AB8 00030A44 3443043C */  lui        $a0, (0x43340000 >> 16)
    /* 30ABC 00030A48 00688444 */  mtc1       $a0, $f13
    /* 30AC0 00030A4C 83630D46 */  div.s      $f14, $f12, $f13
    /* 30AC4 00030A50 1D00073C */  lui        $a3, %hi(sym_001D367C)
    /* 30AC8 00030A54 7266043C */  lui        $a0, %hi(D_66727573)
    /* 30ACC 00030A58 1D00083C */  lui        $t0, %hi(sym_001D3680)
    /* 30AD0 00030A5C 3A000534 */  ori        $a1, $zero, 0x3A
    /* 30AD4 00030A60 80000634 */  ori        $a2, $zero, 0x80
    /* 30AD8 00030A64 73758424 */  addiu      $a0, $a0, %lo(D_66727573)
    /* 30ADC 00030A68 1000B4E7 */  swc1       $f20, 0x10($sp)
    /* 30AE0 00030A6C 1400BFAF */  sw         $ra, 0x14($sp)
    /* 30AE4 00030A70 036B0C46 */  div.s      $f12, $f13, $f12
    /* 30AE8 00030A74 7C36EEE4 */  swc1       $f14, %lo(sym_001D367C)($a3)
    /* 30AEC 00030A78 611B040C */  jal        elem_register_chunk_tag
    /* 30AF0 00030A7C 80360CE5 */   swc1      $f12, %lo(sym_001D3680)($t0)
    /* 30AF4 00030A80 1D00043C */  lui        $a0, %hi(sym_001D3684)
    /* 30AF8 00030A84 1C00053C */  lui        $a1, %hi(str_JoystickX_2728)
    /* 30AFC 00030A88 84368424 */  addiu      $a0, $a0, %lo(sym_001D3684)
    /* 30B00 00030A8C 00A08044 */  mtc1       $zero, $f20
    /* 30B04 00030A90 06A30046 */  mov.s      $f12, $f20
    /* 30B08 00030A94 31BA020C */  jal        func_000AE8C4
    /* 30B0C 00030A98 2827A524 */   addiu     $a1, $a1, %lo(str_JoystickX_2728)
    /* 30B10 00030A9C 1D00043C */  lui        $a0, %hi(sym_001D3688)
    /* 30B14 00030AA0 06A30046 */  mov.s      $f12, $f20
    /* 30B18 00030AA4 1C00053C */  lui        $a1, %hi(str_JoystickY_2734)
    /* 30B1C 00030AA8 88368424 */  addiu      $a0, $a0, %lo(sym_001D3688)
    /* 30B20 00030AAC 31BA020C */  jal        func_000AE8C4
    /* 30B24 00030AB0 3427A524 */   addiu     $a1, $a1, %lo(str_JoystickY_2734)
    /* 30B28 00030AB4 1D00043C */  lui        $a0, %hi(sym_001D368C)
    /* 30B2C 00030AB8 06A30046 */  mov.s      $f12, $f20
    /* 30B30 00030ABC 1C00053C */  lui        $a1, %hi(str_Button_Circle_2740)
    /* 30B34 00030AC0 8C368424 */  addiu      $a0, $a0, %lo(sym_001D368C)
    /* 30B38 00030AC4 31BA020C */  jal        func_000AE8C4
    /* 30B3C 00030AC8 4027A524 */   addiu     $a1, $a1, %lo(str_Button_Circle_2740)
    /* 30B40 00030ACC 1D00043C */  lui        $a0, %hi(sym_001D3690)
    /* 30B44 00030AD0 06A30046 */  mov.s      $f12, $f20
    /* 30B48 00030AD4 1C00053C */  lui        $a1, %hi(str_Button_Square_2750)
    /* 30B4C 00030AD8 90368424 */  addiu      $a0, $a0, %lo(sym_001D3690)
    /* 30B50 00030ADC 31BA020C */  jal        func_000AE8C4
    /* 30B54 00030AE0 5027A524 */   addiu     $a1, $a1, %lo(str_Button_Square_2750)
    /* 30B58 00030AE4 1D00043C */  lui        $a0, %hi(sym_001D3694)
    /* 30B5C 00030AE8 06A30046 */  mov.s      $f12, $f20
    /* 30B60 00030AEC 1C00053C */  lui        $a1, %hi(str_Button_Triangle_2760)
    /* 30B64 00030AF0 94368424 */  addiu      $a0, $a0, %lo(sym_001D3694)
    /* 30B68 00030AF4 31BA020C */  jal        func_000AE8C4
    /* 30B6C 00030AF8 6027A524 */   addiu     $a1, $a1, %lo(str_Button_Triangle_2760)
    /* 30B70 00030AFC 1D00043C */  lui        $a0, %hi(sym_001D3698)
    /* 30B74 00030B00 06A30046 */  mov.s      $f12, $f20
    /* 30B78 00030B04 1C00053C */  lui        $a1, %hi(str_Button_X_2770)
    /* 30B7C 00030B08 98368424 */  addiu      $a0, $a0, %lo(sym_001D3698)
    /* 30B80 00030B0C 31BA020C */  jal        func_000AE8C4
    /* 30B84 00030B10 7027A524 */   addiu     $a1, $a1, %lo(str_Button_X_2770)
    /* 30B88 00030B14 1D00043C */  lui        $a0, %hi(sym_001D369C)
    /* 30B8C 00030B18 06A30046 */  mov.s      $f12, $f20
    /* 30B90 00030B1C 1C00053C */  lui        $a1, %hi(str_Confirm_277C)
    /* 30B94 00030B20 9C368424 */  addiu      $a0, $a0, %lo(sym_001D369C)
    /* 30B98 00030B24 31BA020C */  jal        func_000AE8C4
    /* 30B9C 00030B28 7C27A524 */   addiu     $a1, $a1, %lo(str_Confirm_277C)
    /* 30BA0 00030B2C 1D00043C */  lui        $a0, %hi(sym_001D36A0)
    /* 30BA4 00030B30 06A30046 */  mov.s      $f12, $f20
    /* 30BA8 00030B34 1C00053C */  lui        $a1, %hi(str_Cancel_2784)
    /* 30BAC 00030B38 A0368424 */  addiu      $a0, $a0, %lo(sym_001D36A0)
    /* 30BB0 00030B3C 31BA020C */  jal        func_000AE8C4
    /* 30BB4 00030B40 8427A524 */   addiu     $a1, $a1, %lo(str_Cancel_2784)
    /* 30BB8 00030B44 1D00043C */  lui        $a0, %hi(sym_001D36A4)
    /* 30BBC 00030B48 06A30046 */  mov.s      $f12, $f20
    /* 30BC0 00030B4C 1C00053C */  lui        $a1, %hi(str_Start_278C)
    /* 30BC4 00030B50 A4368424 */  addiu      $a0, $a0, %lo(sym_001D36A4)
    /* 30BC8 00030B54 31BA020C */  jal        func_000AE8C4
    /* 30BCC 00030B58 8C27A524 */   addiu     $a1, $a1, %lo(str_Start_278C)
    /* 30BD0 00030B5C 1D00043C */  lui        $a0, %hi(sym_001D36A8)
    /* 30BD4 00030B60 06A30046 */  mov.s      $f12, $f20
    /* 30BD8 00030B64 1C00053C */  lui        $a1, %hi(str_ActiveController_2794)
    /* 30BDC 00030B68 A8368424 */  addiu      $a0, $a0, %lo(sym_001D36A8)
    /* 30BE0 00030B6C 31BA020C */  jal        func_000AE8C4
    /* 30BE4 00030B70 9427A524 */   addiu     $a1, $a1, %lo(str_ActiveController_2794)
    /* 30BE8 00030B74 1000B4C7 */  lwc1       $f20, 0x10($sp)
    /* 30BEC 00030B78 1400BF8F */  lw         $ra, 0x14($sp)
    /* 30BF0 00030B7C 0800E003 */  jr         $ra
    /* 30BF4 00030B80 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_00030A38
