.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0002A5E4, 0x124

glabel func_0002A5E4
    /* 2A658 0002A5E4 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 2A65C 0002A5E8 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2A660 0002A5EC 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2A664 0002A5F0 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 2A668 0002A5F4 24001334 */  ori        $s3, $zero, 0x24
    /* 2A66C 0002A5F8 25808000 */  or         $s0, $a0, $zero
    /* 2A670 0002A5FC 2588A000 */  or         $s1, $a1, $zero
    /* 2A674 0002A600 1800B2AF */  sw         $s2, 0x18($sp)
    /* 2A678 0002A604 2000B4AF */  sw         $s4, 0x20($sp)
    /* 2A67C 0002A608 2400B5AF */  sw         $s5, 0x24($sp)
    /* 2A680 0002A60C 2800B6AF */  sw         $s6, 0x28($sp)
    /* 2A684 0002A610 2C00BFAF */  sw         $ra, 0x2C($sp)
    /* 2A688 0002A614 25200002 */  or         $a0, $s0, $zero
    /* 2A68C 0002A618 6C4D010C */  jal        func_000535B0
    /* 2A690 0002A61C 25282002 */   or        $a1, $s1, $zero
    /* 2A694 0002A620 10001126 */  addiu      $s1, $s0, 0x10
    /* 2A698 0002A624 0400258E */  lw         $a1, 0x4($s1)
    /* 2A69C 0002A628 0000248E */  lw         $a0, 0x0($s1)
    /* 2A6A0 0002A62C 2328A400 */  subu       $a1, $a1, $a0
    /* 2A6A4 0002A630 1A00B300 */  div        $zero, $a1, $s3
    /* 2A6A8 0002A634 12280000 */  mflo       $a1
    /* 2A6AC 0002A638 2900A010 */  beqz       $a1, .Leboot_0002A6E0
    /* 2A6B0 0002A63C 00001234 */   ori       $s2, $zero, 0x0
    /* 2A6B4 0002A640 04001634 */  ori        $s6, $zero, 0x4
    /* 2A6B8 0002A644 00001534 */  ori        $s5, $zero, 0x0
    /* 2A6BC 0002A648 1D00143C */  lui        $s4, %hi(sym_001D3244)
  .Leboot_0002A64C:
    /* 2A6C0 0002A64C 21209500 */  addu       $a0, $a0, $s5
    /* 2A6C4 0002A650 0000858C */  lw         $a1, 0x0($a0)
    /* 2A6C8 0002A654 4432848E */  lw         $a0, %lo(sym_001D3244)($s4)
    /* 2A6CC 0002A658 25300000 */  or         $a2, $zero, $zero
    /* 2A6D0 0002A65C 2BA5000C */  jal        func_000294AC
    /* 2A6D4 0002A660 25380002 */   or        $a3, $s0, $zero
    /* 2A6D8 0002A664 0000258E */  lw         $a1, 0x0($s1)
    /* 2A6DC 0002A668 4432848E */  lw         $a0, %lo(sym_001D3244)($s4)
    /* 2A6E0 0002A66C 2138B500 */  addu       $a3, $a1, $s5
    /* 2A6E4 0002A670 0000E58C */  lw         $a1, 0x0($a3)
    /* 2A6E8 0002A674 01000634 */  ori        $a2, $zero, 0x1
    /* 2A6EC 0002A678 0800E724 */  addiu      $a3, $a3, 0x8
  .Leboot_0002A67C:
    /* 2A6F0 0002A67C 0000E88C */  lw         $t0, 0x0($a3)
    /* 2A6F4 0002A680 04000511 */  beq        $t0, $a1, .Leboot_0002A694
    /* 2A6F8 0002A684 0100C624 */   addiu     $a2, $a2, 0x1
    /* 2A6FC 0002A688 06000010 */  b          .Leboot_0002A6A4
    /* 2A700 0002A68C 25280001 */   or        $a1, $t0, $zero
    /* 2A704 0002A690 0100C624 */  addiu      $a2, $a2, 0x1
  .Leboot_0002A694:
    /* 2A708 0002A694 F9FFD614 */  bne        $a2, $s6, .Leboot_0002A67C
    /* 2A70C 0002A698 0800E724 */   addiu     $a3, $a3, 0x8
    /* 2A710 0002A69C 00000834 */  ori        $t0, $zero, 0x0
    /* 2A714 0002A6A0 25280001 */  or         $a1, $t0, $zero
  .Leboot_0002A6A4:
    /* 2A718 0002A6A4 25300000 */  or         $a2, $zero, $zero
    /* 2A71C 0002A6A8 2BA5000C */  jal        func_000294AC
    /* 2A720 0002A6AC 25380002 */   or        $a3, $s0, $zero
    /* 2A724 0002A6B0 0000248E */  lw         $a0, 0x0($s1)
    /* 2A728 0002A6B4 08000534 */  ori        $a1, $zero, 0x8
    /* 2A72C 0002A6B8 EE45010C */  jal        func_000517B8
    /* 2A730 0002A6BC 21209500 */   addu      $a0, $a0, $s5
    /* 2A734 0002A6C0 0400258E */  lw         $a1, 0x4($s1)
    /* 2A738 0002A6C4 0000248E */  lw         $a0, 0x0($s1)
    /* 2A73C 0002A6C8 2328A400 */  subu       $a1, $a1, $a0
    /* 2A740 0002A6CC 1A00B300 */  div        $zero, $a1, $s3
    /* 2A744 0002A6D0 01005226 */  addiu      $s2, $s2, 0x1
    /* 2A748 0002A6D4 12280000 */  mflo       $a1
    /* 2A74C 0002A6D8 DCFF4516 */  bne        $s2, $a1, .Leboot_0002A64C
    /* 2A750 0002A6DC 2400B526 */   addiu     $s5, $s5, 0x24
  .Leboot_0002A6E0:
    /* 2A754 0002A6E0 1000B08F */  lw         $s0, 0x10($sp)
    /* 2A758 0002A6E4 1400B18F */  lw         $s1, 0x14($sp)
    /* 2A75C 0002A6E8 1800B28F */  lw         $s2, 0x18($sp)
    /* 2A760 0002A6EC 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 2A764 0002A6F0 2000B48F */  lw         $s4, 0x20($sp)
    /* 2A768 0002A6F4 2400B58F */  lw         $s5, 0x24($sp)
    /* 2A76C 0002A6F8 2800B68F */  lw         $s6, 0x28($sp)
    /* 2A770 0002A6FC 2C00BF8F */  lw         $ra, 0x2C($sp)
    /* 2A774 0002A700 0800E003 */  jr         $ra
    /* 2A778 0002A704 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_0002A5E4
