.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00100E54, 0x84

glabel func_00100E54
    /* 100EC8 00100E54 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 100ECC 00100E58 0600043C */  lui        $a0, %hi(sym_00064001)
    /* 100ED0 00100E5C 01408490 */  lbu        $a0, %lo(sym_00064001)($a0)
    /* 100ED4 00100E60 1000B0AF */  sw         $s0, 0x10($sp)
    /* 100ED8 00100E64 1400BFAF */  sw         $ra, 0x14($sp)
    /* 100EDC 00100E68 03008010 */  beqz       $a0, .Leboot_00100E78
    /* 100EE0 00100E6C 1E00103C */   lui       $s0, %hi(sym_001DB178)
    /* 100EE4 00100E70 0603040C */  jal        func_00100C18
    /* 100EE8 00100E74 00000000 */   nop
  .Leboot_00100E78:
    /* 100EEC 00100E78 4EC1060C */  jal        stub_001B0538
    /* 100EF0 00100E7C 00000000 */   nop
    /* 100EF4 00100E80 78B102AE */  sw         $v0, %lo(sym_001DB178)($s0)
    /* 100EF8 00100E84 0F00043C */  lui        $a0, %hi(sym_000EC528)
    /* 100EFC 00100E88 28C5858C */  lw         $a1, %lo(sym_000EC528)($a0)
    /* 100F00 00100E8C 0800A014 */  bnez       $a1, .Leboot_00100EB0
    /* 100F04 00100E90 25204000 */   or        $a0, $v0, $zero
    /* 100F08 00100E94 1E00053C */  lui        $a1, %hi(sym_001DB0AC)
    /* 100F0C 00100E98 ACB0A524 */  addiu      $a1, $a1, %lo(sym_001DB0AC)
    /* 100F10 00100E9C 1800A58C */  lw         $a1, 0x18($a1)
    /* 100F14 00100EA0 C02A0500 */  sll        $a1, $a1, 11
    /* 100F18 00100EA4 21280500 */  addu       $a1, $zero, $a1
    /* 100F1C 00100EA8 21208500 */  addu       $a0, $a0, $a1
    /* 100F20 00100EAC 78B104AE */  sw         $a0, %lo(sym_001DB178)($s0)
  .Leboot_00100EB0:
    /* 100F24 00100EB0 00020534 */  ori        $a1, $zero, 0x200
    /* 100F28 00100EB4 03000634 */  ori        $a2, $zero, 0x3
    /* 100F2C 00100EB8 66C1060C */  jal        stub_001B0598
    /* 100F30 00100EBC 01000734 */   ori       $a3, $zero, 0x1
    /* 100F34 00100EC0 6AC1060C */  jal        stub_001B05A8
    /* 100F38 00100EC4 00000000 */   nop
    /* 100F3C 00100EC8 1000B08F */  lw         $s0, 0x10($sp)
    /* 100F40 00100ECC 1400BF8F */  lw         $ra, 0x14($sp)
    /* 100F44 00100ED0 0800E003 */  jr         $ra
    /* 100F48 00100ED4 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_00100E54
