.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0019A05C, 0x1C

glabel func_0019A05C
    /* 19A0D0 0019A05C E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 19A0D4 0019A060 1000BFAF */  sw         $ra, 0x10($sp)
    /* 19A0D8 0019A064 E96B060C */  jal        func_0019AFA4
    /* 19A0DC 0019A068 2520A000 */   or        $a0, $a1, $zero
    /* 19A0E0 0019A06C 1000BF8F */  lw         $ra, 0x10($sp)
    /* 19A0E4 0019A070 0800E003 */  jr         $ra
    /* 19A0E8 0019A074 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0019A05C
