.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000E5698, 0xE8

glabel func_000E5698
    /* E570C 000E5698 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* E5710 000E569C 1000B0AF */  sw         $s0, 0x10($sp)
    /* E5714 000E56A0 2000B4AF */  sw         $s4, 0x20($sp)
    /* E5718 000E56A4 2580A000 */  or         $s0, $a1, $zero
    /* E571C 000E56A8 0500143C */  lui        $s4, %hi(sym_00051974)
    /* E5720 000E56AC 7419848E */  lw         $a0, %lo(sym_00051974)($s4)
    /* E5724 000E56B0 01000534 */  ori        $a1, $zero, 0x1
    /* E5728 000E56B4 1400B1AF */  sw         $s1, 0x14($sp)
    /* E572C 000E56B8 1800B2AF */  sw         $s2, 0x18($sp)
    /* E5730 000E56BC 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* E5734 000E56C0 2400BFAF */  sw         $ra, 0x24($sp)
    /* E5738 000E56C4 A8C1060C */  jal        stub_001B06A0
    /* E573C 000E56C8 25300000 */   or        $a2, $zero, $zero
    /* E5740 000E56CC 0500133C */  lui        $s3, %hi(func_00051968)
    /* E5744 000E56D0 6819658E */  lw         $a1, %lo(func_00051968)($s3)
    /* E5748 000E56D4 0200123C */  lui        $s2, %hi(D_eboot_00020080)
    /* E574C 000E56D8 80005226 */  addiu      $s2, $s2, %lo(D_eboot_00020080)
    /* E5750 000E56DC 1800B200 */  mult       $a1, $s2
    /* E5754 000E56E0 0100113C */  lui        $s1, %hi(sym_00011868)
    /* E5758 000E56E4 68183126 */  addiu      $s1, $s1, %lo(sym_00011868)
    /* E575C 000E56E8 12200000 */  mflo       $a0
    /* E5760 000E56EC 21209100 */  addu       $a0, $a0, $s1
    /* E5764 000E56F0 0400878C */  lw         $a3, 0x4($a0)
    /* E5768 000E56F4 FFFF0624 */  addiu      $a2, $zero, -0x1
    /* E576C 000E56F8 0800E614 */  bne        $a3, $a2, .Leboot_000E571C
    /* E5770 000E56FC 00000000 */   nop
    /* E5774 000E5700 7419858E */  lw         $a1, %lo(sym_00051974)($s4)
    /* E5778 000E5704 010080A0 */  sb         $zero, 0x1($a0)
    /* E577C 000E5708 2520A000 */  or         $a0, $a1, $zero
    /* E5780 000E570C A6C1060C */  jal        stub_001B0698
    /* E5784 000E5710 01000534 */   ori       $a1, $zero, 0x1
    /* E5788 000E5714 12000010 */  b          .Leboot_000E5760
    /* E578C 000E5718 00000000 */   nop
  .Leboot_000E571C:
    /* E5790 000E571C 3795030C */  jal        func_000E54DC
    /* E5794 000E5720 25200002 */   or        $a0, $s0, $zero
    /* E5798 000E5724 6819648E */  lw         $a0, %lo(func_00051968)($s3)
    /* E579C 000E5728 18009200 */  mult       $a0, $s2
    /* E57A0 000E572C 25280002 */  or         $a1, $s0, $zero
    /* E57A4 000E5730 12200000 */  mflo       $a0
    /* E57A8 000E5734 21209100 */  addu       $a0, $a0, $s1
    /* E57AC 000E5738 6EC0060C */  jal        stub_001B01B8
    /* E57B0 000E573C 0400848C */   lw        $a0, 0x4($a0)
    /* E57B4 000E5740 6819648E */  lw         $a0, %lo(func_00051968)($s3)
    /* E57B8 000E5744 18009200 */  mult       $a0, $s2
    /* E57BC 000E5748 7419848E */  lw         $a0, %lo(sym_00051974)($s4)
    /* E57C0 000E574C 01000534 */  ori        $a1, $zero, 0x1
    /* E57C4 000E5750 12300000 */  mflo       $a2
    /* E57C8 000E5754 2130D100 */  addu       $a2, $a2, $s1
    /* E57CC 000E5758 A6C1060C */  jal        stub_001B0698
    /* E57D0 000E575C 0100C0A0 */   sb        $zero, 0x1($a2)
  .Leboot_000E5760:
    /* E57D4 000E5760 1000B08F */  lw         $s0, 0x10($sp)
    /* E57D8 000E5764 1400B18F */  lw         $s1, 0x14($sp)
    /* E57DC 000E5768 1800B28F */  lw         $s2, 0x18($sp)
    /* E57E0 000E576C 1C00B38F */  lw         $s3, 0x1C($sp)
    /* E57E4 000E5770 2000B48F */  lw         $s4, 0x20($sp)
    /* E57E8 000E5774 2400BF8F */  lw         $ra, 0x24($sp)
    /* E57EC 000E5778 0800E003 */  jr         $ra
    /* E57F0 000E577C 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_000E5698
