.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00005AF0, 0x8

glabel func_00005AF0
    /* 5B64 00005AF0 0800E003 */  jr         $ra
    /* 5B68 00005AF4 04000234 */   ori       $v0, $zero, 0x4
endlabel func_00005AF0
