.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00045D78, 0x34

glabel func_00045D78
    /* 45DEC 00045D78 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 45DF0 00045D7C 25200000 */  or         $a0, $zero, $zero
    /* 45DF4 00045D80 1000BFAF */  sw         $ra, 0x10($sp)
    /* 45DF8 00045D84 0C27010C */  jal        func_00049C30
    /* 45DFC 00045D88 25280000 */   or        $a1, $zero, $zero
    /* 45E00 00045D8C 1D00043C */  lui        $a0, %hi(sym_001D38B8)
    /* 45E04 00045D90 B83882AC */  sw         $v0, %lo(sym_001D38B8)($a0)
    /* 45E08 00045D94 1D00043C */  lui        $a0, %hi(sym_001D38BC)
    /* 45E0C 00045D98 BC3880AC */  sw         $zero, %lo(sym_001D38BC)($a0)
    /* 45E10 00045D9C 25100000 */  or         $v0, $zero, $zero
    /* 45E14 00045DA0 1000BF8F */  lw         $ra, 0x10($sp)
    /* 45E18 00045DA4 0800E003 */  jr         $ra
    /* 45E1C 00045DA8 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_00045D78
