.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00118824, 0x3C

glabel func_00118824
    /* 118898 00118824 2E008528 */  slti       $a1, $a0, 0x2E
    /* 11889C 00118828 0600A010 */  beqz       $a1, .Leboot_00118844
    /* 1188A0 0011882C 0E010534 */   ori       $a1, $zero, 0x10E
    /* 1188A4 00118830 2D008428 */  slti       $a0, $a0, 0x2D
    /* 1188A8 00118834 07008010 */  beqz       $a0, .Leboot_00118854
    /* 1188AC 00118838 00000000 */   nop
  .Leboot_0011883C:
    /* 1188B0 0011883C 06000010 */  b          .Leboot_00118858
    /* 1188B4 00118840 02000234 */   ori       $v0, $zero, 0x2
  .Leboot_00118844:
    /* 1188B8 00118844 FDFF8514 */  bne        $a0, $a1, .Leboot_0011883C
    /* 1188BC 00118848 00000000 */   nop
    /* 1188C0 0011884C 02000010 */  b          .Leboot_00118858
    /* 1188C4 00118850 01000234 */   ori       $v0, $zero, 0x1
  .Leboot_00118854:
    /* 1188C8 00118854 25100000 */  or         $v0, $zero, $zero
  .Leboot_00118858:
    /* 1188CC 00118858 0800E003 */  jr         $ra
    /* 1188D0 0011885C 00000000 */   nop
endlabel func_00118824
