.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0018B1E8, 0xC

glabel func_0018B1E8
    /* 18B25C 0018B1E8 1C00023C */  lui        $v0, %hi(str_test_7D98)
    /* 18B260 0018B1EC 0800E003 */  jr         $ra
    /* 18B264 0018B1F0 987D4224 */   addiu     $v0, $v0, %lo(str_test_7D98)
endlabel func_0018B1E8
