.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000A7A8C, 0x3C

glabel func_000A7A8C
    /* A7B00 000A7A8C E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* A7B04 000A7A90 1000B0AF */  sw         $s0, 0x10($sp)
    /* A7B08 000A7A94 1400BFAF */  sw         $ra, 0x14($sp)
    /* A7B0C 000A7A98 17E7020C */  jal        func_000B9C5C
    /* A7B10 000A7A9C 25808000 */   or        $s0, $a0, $zero
    /* A7B14 000A7AA0 1F00043C */  lui        $a0, %hi(sym_001E9300)
    /* A7B18 000A7AA4 00938424 */  addiu      $a0, $a0, %lo(sym_001E9300)
    /* A7B1C 000A7AA8 180004AE */  sw         $a0, 0x18($s0)
    /* A7B20 000A7AAC 1C0000AE */  sw         $zero, 0x1C($s0)
    /* A7B24 000A7AB0 200000AE */  sw         $zero, 0x20($s0)
    /* A7B28 000A7AB4 25100002 */  or         $v0, $s0, $zero
    /* A7B2C 000A7AB8 1000B08F */  lw         $s0, 0x10($sp)
    /* A7B30 000A7ABC 1400BF8F */  lw         $ra, 0x14($sp)
    /* A7B34 000A7AC0 0800E003 */  jr         $ra
    /* A7B38 000A7AC4 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_000A7A8C
