.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000912A8, 0x2C

glabel func_000912A8
    /* 9131C 000912A8 1D00043C */  lui        $a0, %hi(sym_001D4C80)
    /* 91320 000912AC 804C8CC4 */  lwc1       $f12, %lo(sym_001D4C80)($a0)
    /* 91324 000912B0 3443043C */  lui        $a0, (0x43340000 >> 16)
    /* 91328 000912B4 00688444 */  mtc1       $a0, $f13
    /* 9132C 000912B8 83630D46 */  div.s      $f14, $f12, $f13
    /* 91330 000912BC 1D00043C */  lui        $a0, %hi(sym_001D4C84)
    /* 91334 000912C0 1D00053C */  lui        $a1, %hi(sym_001D4C88)
    /* 91338 000912C4 036B0C46 */  div.s      $f12, $f13, $f12
    /* 9133C 000912C8 844C8EE4 */  swc1       $f14, %lo(sym_001D4C84)($a0)
    /* 91340 000912CC 0800E003 */  jr         $ra
    /* 91344 000912D0 884CACE4 */   swc1      $f12, %lo(sym_001D4C88)($a1)
endlabel func_000912A8
