.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000273C4, 0x8C

glabel func_000273C4
    /* 27438 000273C4 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 2743C 000273C8 2C00B0AF */  sw         $s0, 0x2C($sp)
    /* 27440 000273CC 25808000 */  or         $s0, $a0, $zero
    /* 27444 000273D0 3000BFAF */  sw         $ra, 0x30($sp)
    /* 27448 000273D4 0500A010 */  beqz       $a1, .Leboot_000273EC
    /* 2744C 000273D8 5C000426 */   addiu     $a0, $s0, 0x5C
    /* 27450 000273DC 97B2040C */  jal        func_0012CA5C
    /* 27454 000273E0 50000634 */   ori       $a2, $zero, 0x50
    /* 27458 000273E4 03000010 */  b          .Leboot_000273F4
    /* 2745C 000273E8 00608044 */   mtc1      $zero, $f12
  .Leboot_000273EC:
    /* 27460 000273EC 5C0000A2 */  sb         $zero, 0x5C($s0)
    /* 27464 000273F0 00608044 */  mtc1       $zero, $f12
  .Leboot_000273F4:
    /* 27468 000273F4 1400ACE7 */  swc1       $f12, 0x14($sp)
    /* 2746C 000273F8 1800ACE7 */  swc1       $f12, 0x18($sp)
    /* 27470 000273FC 1C00ACE7 */  swc1       $f12, 0x1C($sp)
    /* 27474 00027400 2000ACE7 */  swc1       $f12, 0x20($sp)
    /* 27478 00027404 2400ACE7 */  swc1       $f12, 0x24($sp)
    /* 2747C 00027408 2800ACE7 */  swc1       $f12, 0x28($sp)
    /* 27480 0002740C 1400A58F */  lw         $a1, 0x14($sp)
    /* 27484 00027410 1800A68F */  lw         $a2, 0x18($sp)
    /* 27488 00027414 AC000426 */  addiu      $a0, $s0, 0xAC
    /* 2748C 00027418 1C00A78F */  lw         $a3, 0x1C($sp)
    /* 27490 0002741C 000085AC */  sw         $a1, 0x0($a0)
    /* 27494 00027420 2000A58F */  lw         $a1, 0x20($sp)
    /* 27498 00027424 040086AC */  sw         $a2, 0x4($a0)
    /* 2749C 00027428 2400A68F */  lw         $a2, 0x24($sp)
    /* 274A0 0002742C 080087AC */  sw         $a3, 0x8($a0)
    /* 274A4 00027430 2800A78F */  lw         $a3, 0x28($sp)
    /* 274A8 00027434 0C0085AC */  sw         $a1, 0xC($a0)
    /* 274AC 00027438 100086AC */  sw         $a2, 0x10($a0)
    /* 274B0 0002743C 140087AC */  sw         $a3, 0x14($a0)
    /* 274B4 00027440 2C00B08F */  lw         $s0, 0x2C($sp)
    /* 274B8 00027444 3000BF8F */  lw         $ra, 0x30($sp)
    /* 274BC 00027448 0800E003 */  jr         $ra
    /* 274C0 0002744C 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel func_000273C4
