.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0011B278, 0x84

glabel func_0011B278
    /* 11B2EC 0011B278 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 11B2F0 0011B27C 0700A690 */  lbu        $a2, 0x7($a1)
    /* 11B2F4 0011B280 1800BFAF */  sw         $ra, 0x18($sp)
    /* 11B2F8 0011B284 0D00C010 */  beqz       $a2, .Leboot_0011B2BC
    /* 11B2FC 0011B288 00000000 */   nop
    /* 11B300 0011B28C 01000734 */  ori        $a3, $zero, 0x1
    /* 11B304 0011B290 0430C700 */  sllv       $a2, $a3, $a2
    /* 11B308 0011B294 00390600 */  sll        $a3, $a2, 4
    /* 11B30C 0011B298 1400A5AF */  sw         $a1, 0x14($sp)
    /* 11B310 0011B29C 80300600 */  sll        $a2, $a2, 2
    /* 11B314 0011B2A0 1000A4AF */  sw         $a0, 0x10($sp)
    /* 11B318 0011B2A4 2130E600 */  addu       $a2, $a3, $a2
    /* 11B31C 0011B2A8 1000A58C */  lw         $a1, 0x10($a1)
    /* 11B320 0011B2AC 9958040C */  jal        func_00116264
    /* 11B324 0011B2B0 25380000 */   or        $a3, $zero, $zero
    /* 11B328 0011B2B4 1000A48F */  lw         $a0, 0x10($sp)
    /* 11B32C 0011B2B8 1400A58F */  lw         $a1, 0x14($sp)
  .Leboot_0011B2BC:
    /* 11B330 0011B2BC 1400A5AF */  sw         $a1, 0x14($sp)
    /* 11B334 0011B2C0 2530A000 */  or         $a2, $a1, $zero
    /* 11B338 0011B2C4 1000A4AF */  sw         $a0, 0x10($sp)
    /* 11B33C 0011B2C8 0C00C58C */  lw         $a1, 0xC($a2)
    /* 11B340 0011B2CC 1C00C68C */  lw         $a2, 0x1C($a2)
    /* 11B344 0011B2D0 25380000 */  or         $a3, $zero, $zero
    /* 11B348 0011B2D4 9958040C */  jal        func_00116264
    /* 11B34C 0011B2D8 C0300600 */   sll       $a2, $a2, 3
    /* 11B350 0011B2DC 1000A48F */  lw         $a0, 0x10($sp)
    /* 11B354 0011B2E0 1400A58F */  lw         $a1, 0x14($sp)
    /* 11B358 0011B2E4 20000634 */  ori        $a2, $zero, 0x20
    /* 11B35C 0011B2E8 9958040C */  jal        func_00116264
    /* 11B360 0011B2EC 25380000 */   or        $a3, $zero, $zero
    /* 11B364 0011B2F0 1800BF8F */  lw         $ra, 0x18($sp)
    /* 11B368 0011B2F4 0800E003 */  jr         $ra
    /* 11B36C 0011B2F8 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0011B278
