.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000E1EC0, 0x128

glabel func_000E1EC0
    /* E1F34 000E1EC0 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* E1F38 000E1EC4 1000B0AF */  sw         $s0, 0x10($sp)
    /* E1F3C 000E1EC8 1400BFAF */  sw         $ra, 0x14($sp)
    /* E1F40 000E1ECC C8C0060C */  jal        stub_001B0320
    /* E1F44 000E1ED0 25808000 */   or        $s0, $a0, $zero
    /* E1F48 000E1ED4 25204000 */  or         $a0, $v0, $zero
    /* E1F4C 000E1ED8 0500852C */  sltiu      $a1, $a0, 0x5
    /* E1F50 000E1EDC 0A00A050 */  beql       $a1, $zero, .Leboot_000E1F08
    /* E1F54 000E1EE0 0800048E */   lw        $a0, 0x8($s0)
    /* E1F58 000E1EE4 2A008010 */  beqz       $a0, .Leboot_000E1F90
    /* E1F5C 000E1EE8 02000124 */   addiu     $at, $zero, 0x2
    /* E1F60 000E1EEC 16008110 */  beq        $a0, $at, .Leboot_000E1F48
    /* E1F64 000E1EF0 03000124 */   addiu     $at, $zero, 0x3
    /* E1F68 000E1EF4 19008110 */  beq        $a0, $at, .Leboot_000E1F5C
    /* E1F6C 000E1EF8 04000124 */   addiu     $at, $zero, 0x4
    /* E1F70 000E1EFC 22008110 */  beq        $a0, $at, .Leboot_000E1F88
    /* E1F74 000E1F00 00000000 */   nop
  .Leboot_000E1F04:
    /* E1F78 000E1F04 0800048E */  lw         $a0, 0x8($s0)
  .Leboot_000E1F08:
    /* E1F7C 000E1F08 0000858C */  lw         $a1, 0x0($a0)
    /* E1F80 000E1F0C 0100A524 */  addiu      $a1, $a1, 0x1
    /* E1F84 000E1F10 3F00A630 */  andi       $a2, $a1, 0x3F
    /* E1F88 000E1F14 C0300600 */  sll        $a2, $a2, 3
    /* E1F8C 000E1F18 2138C600 */  addu       $a3, $a2, $a2
    /* E1F90 000E1F1C 2130C700 */  addu       $a2, $a2, $a3
    /* E1F94 000E1F20 21208600 */  addu       $a0, $a0, $a2
    /* E1F98 000E1F24 0C0005AE */  sw         $a1, 0xC($s0)
    /* E1F9C 000E1F28 24038424 */  addiu      $a0, $a0, 0x324
    /* E1FA0 000E1F2C 000004AE */  sw         $a0, 0x0($s0)
    /* E1FA4 000E1F30 0400848C */  lw         $a0, 0x4($a0)
    /* E1FA8 000E1F34 040004AE */  sw         $a0, 0x4($s0)
    /* E1FAC 000E1F38 000090AC */  sw         $s0, 0x0($a0)
    /* E1FB0 000E1F3C 0000048E */  lw         $a0, 0x0($s0)
    /* E1FB4 000E1F40 25000010 */  b          .Leboot_000E1FD8
    /* E1FB8 000E1F44 040090AC */   sw        $s0, 0x4($a0)
  .Leboot_000E1F48:
    /* E1FBC 000E1F48 0E00043C */  lui        $a0, %hi(func_000E1D20)
    /* E1FC0 000E1F4C E107040C */  jal        func_00101F84
    /* E1FC4 000E1F50 201D8424 */   addiu     $a0, $a0, %lo(func_000E1D20)
    /* E1FC8 000E1F54 ECFF0010 */  b          .Leboot_000E1F08
    /* E1FCC 000E1F58 0800048E */   lw        $a0, 0x8($s0)
  .Leboot_000E1F5C:
    /* E1FD0 000E1F5C C4C0060C */  jal        stub_001B0310
    /* E1FD4 000E1F60 00000000 */   nop
    /* E1FD8 000E1F64 0100043C */  lui        $a0, %hi(sym_000115D0)
    /* E1FDC 000E1F68 01004010 */  beqz       $v0, .Leboot_000E1F70
    /* E1FE0 000E1F6C D0158424 */   addiu     $a0, $a0, %lo(sym_000115D0)
  .Leboot_000E1F70:
    /* E1FE4 000E1F70 1C00848C */  lw         $a0, 0x1C($a0)
    /* E1FE8 000E1F74 1E00053C */  lui        $a1, %hi(sym_001DA258)
    /* E1FEC 000E1F78 02008438 */  xori       $a0, $a0, 0x2
    /* E1FF0 000E1F7C 0100842C */  sltiu      $a0, $a0, 0x1
    /* E1FF4 000E1F80 E0FF0010 */  b          .Leboot_000E1F04
    /* E1FF8 000E1F84 58A2A4A0 */   sb        $a0, %lo(sym_001DA258)($a1)
  .Leboot_000E1F88:
    /* E1FFC 000E1F88 DFFF0010 */  b          .Leboot_000E1F08
    /* E2000 000E1F8C 0800048E */   lw        $a0, 0x8($s0)
  .Leboot_000E1F90:
    /* E2004 000E1F90 1E00043C */  lui        $a0, %hi(sym_001DA258)
    /* E2008 000E1F94 58A28490 */  lbu        $a0, %lo(sym_001DA258)($a0)
    /* E200C 000E1F98 04008010 */  beqz       $a0, .Leboot_000E1FAC
    /* E2010 000E1F9C 00000000 */   nop
    /* E2014 000E1FA0 FFFF0424 */  addiu      $a0, $zero, -0x1
    /* E2018 000E1FA4 0C000010 */  b          .Leboot_000E1FD8
    /* E201C 000E1FA8 180104AE */   sw        $a0, 0x118($s0)
  .Leboot_000E1FAC:
    /* E2020 000E1FAC 0100043C */  lui        $a0, %hi(sym_000115D0)
    /* E2024 000E1FB0 D0158424 */  addiu      $a0, $a0, %lo(sym_000115D0)
    /* E2028 000E1FB4 3C02858C */  lw         $a1, 0x23C($a0)
    /* E202C 000E1FB8 1000A530 */  andi       $a1, $a1, 0x10
    /* E2030 000E1FBC 0400A010 */  beqz       $a1, .Leboot_000E1FD0
    /* E2034 000E1FC0 00000000 */   nop
    /* E2038 000E1FC4 4002848C */  lw         $a0, 0x240($a0)
    /* E203C 000E1FC8 03000010 */  b          .Leboot_000E1FD8
    /* E2040 000E1FCC 180104AE */   sw        $a0, 0x118($s0)
  .Leboot_000E1FD0:
    /* E2044 000E1FD0 3000848C */  lw         $a0, 0x30($a0)
    /* E2048 000E1FD4 180104AE */  sw         $a0, 0x118($s0)
  .Leboot_000E1FD8:
    /* E204C 000E1FD8 1000B08F */  lw         $s0, 0x10($sp)
    /* E2050 000E1FDC 1400BF8F */  lw         $ra, 0x14($sp)
    /* E2054 000E1FE0 0800E003 */  jr         $ra
    /* E2058 000E1FE4 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_000E1EC0
