.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0007A308, 0xC0

glabel func_0007A308
    /* 7A37C 0007A308 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 7A380 0007A30C 1400B1AF */  sw         $s1, 0x14($sp)
    /* 7A384 0007A310 25888000 */  or         $s1, $a0, $zero
    /* 7A388 0007A314 1000B0AF */  sw         $s0, 0x10($sp)
    /* 7A38C 0007A318 1800BFAF */  sw         $ra, 0x18($sp)
    /* 7A390 0007A31C 25008010 */  beqz       $a0, .Leboot_0007A3B4
    /* 7A394 0007A320 2580A000 */   or        $s0, $a1, $zero
    /* 7A398 0007A324 1E00043C */  lui        $a0, %hi(sym_001E6D48)
    /* 7A39C 0007A328 486D8424 */  addiu      $a0, $a0, %lo(sym_001E6D48)
    /* 7A3A0 0007A32C 380024AE */  sw         $a0, 0x38($s1)
    /* 7A3A4 0007A330 1E00043C */  lui        $a0, %hi(sym_001E6DB8)
    /* 7A3A8 0007A334 B86D8424 */  addiu      $a0, $a0, %lo(sym_001E6DB8)
    /* 7A3AC 0007A338 19002012 */  beqz       $s1, .Leboot_0007A3A0
    /* 7A3B0 0007A33C 0C0024AE */   sw        $a0, 0xC($s1)
    /* 7A3B4 0007A340 1F00043C */  lui        $a0, %hi(sym_001E82E0)
    /* 7A3B8 0007A344 E0828424 */  addiu      $a0, $a0, %lo(sym_001E82E0)
    /* 7A3BC 0007A348 380024AE */  sw         $a0, 0x38($s1)
    /* 7A3C0 0007A34C 1F00043C */  lui        $a0, %hi(sym_001E8350)
    /* 7A3C4 0007A350 50838424 */  addiu      $a0, $a0, %lo(sym_001E8350)
    /* 7A3C8 0007A354 3C002726 */  addiu      $a3, $s1, 0x3C
    /* 7A3CC 0007A358 0E00E010 */  beqz       $a3, .Leboot_0007A394
    /* 7A3D0 0007A35C 0C0024AE */   sw        $a0, 0xC($s1)
    /* 7A3D4 0007A360 0D00E010 */  beqz       $a3, .Leboot_0007A398
    /* 7A3D8 0007A364 25202002 */   or        $a0, $s1, $zero
    /* 7A3DC 0007A368 3C00268E */  lw         $a2, 0x3C($s1)
    /* 7A3E0 0007A36C 0A00C010 */  beqz       $a2, .Leboot_0007A398
    /* 7A3E4 0007A370 25202002 */   or        $a0, $s1, $zero
    /* 7A3E8 0007A374 0000C58C */  lw         $a1, 0x0($a2)
    /* 7A3EC 0007A378 0500A710 */  beq        $a1, $a3, .Leboot_0007A390
    /* 7A3F0 0007A37C 4000248E */   lw        $a0, 0x40($s1)
    /* 7A3F4 0007A380 0400A624 */  addiu      $a2, $a1, 0x4
  .Leboot_0007A384:
    /* 7A3F8 0007A384 0000C58C */  lw         $a1, 0x0($a2)
    /* 7A3FC 0007A388 FEFFA754 */  bnel       $a1, $a3, .Leboot_0007A384
    /* 7A400 0007A38C 0400A624 */   addiu     $a2, $a1, 0x4
  .Leboot_0007A390:
    /* 7A404 0007A390 0000C4AC */  sw         $a0, 0x0($a2)
  .Leboot_0007A394:
    /* 7A408 0007A394 25202002 */  or         $a0, $s1, $zero
  .Leboot_0007A398:
    /* 7A40C 0007A398 6316020C */  jal        func_0008598C
    /* 7A410 0007A39C 25280000 */   or        $a1, $zero, $zero
  .Leboot_0007A3A0:
    /* 7A414 0007A3A0 01000432 */  andi       $a0, $s0, 0x1
    /* 7A418 0007A3A4 03008010 */  beqz       $a0, .Leboot_0007A3B4
    /* 7A41C 0007A3A8 00000000 */   nop
    /* 7A420 0007A3AC C79D040C */  jal        func_0012771C
    /* 7A424 0007A3B0 25202002 */   or        $a0, $s1, $zero
  .Leboot_0007A3B4:
    /* 7A428 0007A3B4 1000B08F */  lw         $s0, 0x10($sp)
    /* 7A42C 0007A3B8 1400B18F */  lw         $s1, 0x14($sp)
    /* 7A430 0007A3BC 1800BF8F */  lw         $ra, 0x18($sp)
    /* 7A434 0007A3C0 0800E003 */  jr         $ra
    /* 7A438 0007A3C4 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0007A308
