.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0002123C, 0x48

glabel func_0002123C
    /* 212B0 0002123C E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 212B4 00021240 3D588690 */  lbu        $a2, 0x583D($a0)
    /* 212B8 00021244 1400B1AF */  sw         $s1, 0x14($sp)
    /* 212BC 00021248 25888000 */  or         $s1, $a0, $zero
    /* 212C0 0002124C 1000B0AF */  sw         $s0, 0x10($sp)
    /* 212C4 00021250 1800BFAF */  sw         $ra, 0x18($sp)
    /* 212C8 00021254 0300C014 */  bnez       $a2, .Leboot_00021264
    /* 212CC 00021258 2580A000 */   or        $s0, $a1, $zero
    /* 212D0 0002125C 7588000C */  jal        func_000221D4
    /* 212D4 00021260 25202002 */   or        $a0, $s1, $zero
  .Leboot_00021264:
    /* 212D8 00021264 25202002 */  or         $a0, $s1, $zero
    /* 212DC 00021268 9D9A020C */  jal        func_000A6A74
    /* 212E0 0002126C 25280002 */   or        $a1, $s0, $zero
    /* 212E4 00021270 1000B08F */  lw         $s0, 0x10($sp)
    /* 212E8 00021274 1400B18F */  lw         $s1, 0x14($sp)
    /* 212EC 00021278 1800BF8F */  lw         $ra, 0x18($sp)
    /* 212F0 0002127C 0800E003 */  jr         $ra
    /* 212F4 00021280 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0002123C
