.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0014E2B8, 0x164

glabel func_0014E2B8
    /* 14E32C 0014E2B8 0000838C */  lw         $v1, 0x0($a0)
    /* 14E330 0014E2BC 0C00858C */  lw         $a1, 0xC($a0)
    /* 14E334 0014E2C0 0400888C */  lw         $t0, 0x4($a0)
    /* 14E338 0014E2C4 0200622C */  sltiu      $v0, $v1, 0x2
    /* 14E33C 0014E2C8 18004010 */  beqz       $v0, .Leboot_0014E32C
    /* 14E340 0014E2CC 21380000 */   addu      $a3, $zero, $zero
    /* 14E344 0014E2D0 1000023C */  lui        $v0, (0x100000 >> 16)
    /* 14E348 0014E2D4 2528A200 */  or         $a1, $a1, $v0
    /* 14E34C 0014E2D8 FF000724 */  addiu      $a3, $zero, 0xFF
  sym_0014E2DC:
    /* 14E350 0014E2DC 7F00033C */  lui        $v1, (0x7FFFFF >> 16)
  .Leboot_0014E2E0:
    /* 14E354 0014E2E0 80FF023C */  lui        $v0, (0xFF800000 >> 16)
    /* 14E358 0014E2E4 FFFF6334 */  ori        $v1, $v1, (0x7FFFFF & 0xFFFF)
    /* 14E35C 0014E2E8 2418A300 */  and        $v1, $a1, $v1
    /* 14E360 0014E2EC 2430C200 */  and        $a2, $a2, $v0
    /* 14E364 0014E2F0 7F80053C */  lui        $a1, (0x807FFFFF >> 16)
    /* 14E368 0014E2F4 2530C300 */  or         $a2, $a2, $v1
    /* 14E36C 0014E2F8 FF00E430 */  andi       $a0, $a3, 0xFF
    /* 14E370 0014E2FC FFFFA534 */  ori        $a1, $a1, (0x807FFFFF & 0xFFFF)
    /* 14E374 0014E300 C0250400 */  sll        $a0, $a0, 23
    /* 14E378 0014E304 2430C500 */  and        $a2, $a2, $a1
    /* 14E37C 0014E308 FF7F023C */  lui        $v0, (0x7FFFFFFF >> 16)
    /* 14E380 0014E30C 2530C400 */  or         $a2, $a2, $a0
    /* 14E384 0014E310 FFFF4234 */  ori        $v0, $v0, (0x7FFFFFFF & 0xFFFF)
    /* 14E388 0014E314 C01F0800 */  sll        $v1, $t0, 31
    /* 14E38C 0014E318 2430C200 */  and        $a2, $a2, $v0
    /* 14E390 0014E31C 2530C300 */  or         $a2, $a2, $v1
    /* 14E394 0014E320 00008644 */  mtc1       $a2, $f0
    /* 14E398 0014E324 0800E003 */  jr         $ra
    /* 14E39C 0014E328 00000000 */   nop
  .Leboot_0014E32C:
    /* 14E3A0 0014E32C 04006238 */  xori       $v0, $v1, 0x4
    /* 14E3A4 0014E330 2A004050 */  beql       $v0, $zero, .Leboot_0014E3DC
    /* 14E3A8 0014E334 FF000724 */   addiu     $a3, $zero, 0xFF
    /* 14E3AC 0014E338 02006238 */  xori       $v0, $v1, 0x2
    /* 14E3B0 0014E33C E7FF4050 */  beql       $v0, $zero, sym_0014E2DC
    /* 14E3B4 0014E340 21280000 */   addu      $a1, $zero, $zero
    /* 14E3B8 0014E344 E6FFA010 */  beqz       $a1, .Leboot_0014E2E0
    /* 14E3BC 0014E348 7F00033C */   lui       $v1, (0x7FFFFF >> 16)
    /* 14E3C0 0014E34C 0800848C */  lw         $a0, 0x8($a0)
    /* 14E3C4 0014E350 82FF8228 */  slti       $v0, $a0, -0x7E
    /* 14E3C8 0014E354 1E004010 */  beqz       $v0, .Leboot_0014E3D0
    /* 14E3CC 0014E358 80008228 */   slti      $v0, $a0, 0x80
    /* 14E3D0 0014E35C 82FF0224 */  addiu      $v0, $zero, -0x7E
    /* 14E3D4 0014E360 23204400 */  subu       $a0, $v0, $a0
    /* 14E3D8 0014E364 1A008328 */  slti       $v1, $a0, 0x1A
    /* 14E3DC 0014E368 12006014 */  bnez       $v1, .Leboot_0014E3B4
    /* 14E3E0 0014E36C 01000224 */   addiu     $v0, $zero, 0x1
    /* 14E3E4 0014E370 21280000 */  addu       $a1, $zero, $zero
  sym_0014E374:
    /* 14E3E8 0014E374 7F00A330 */  andi       $v1, $a1, 0x7F
    /* 14E3EC 0014E378 40000224 */  addiu      $v0, $zero, 0x40
    /* 14E3F0 0014E37C 09006250 */  beql       $v1, $v0, .Leboot_0014E3A4
    /* 14E3F4 0014E380 8000A230 */   andi      $v0, $a1, 0x80
    /* 14E3F8 0014E384 3F00A524 */  addiu      $a1, $a1, 0x3F
  .Leboot_0014E388:
    /* 14E3FC 0014E388 FF3F023C */  lui        $v0, (0x3FFFFFFF >> 16)
  sym_0014E38C:
    /* 14E400 0014E38C FFFF4234 */  ori        $v0, $v0, (0x3FFFFFFF & 0xFFFF)
    /* 14E404 0014E390 2B104500 */  sltu       $v0, $v0, $a1
    /* 14E408 0014E394 01000324 */  addiu      $v1, $zero, 0x1
    /* 14E40C 0014E398 0B386200 */  movn       $a3, $v1, $v0
  .L0014E39C:
    /* 14E410 0014E39C B7380508 */  j          sym_0014E2DC
    /* 14E414 0014E3A0 C2290500 */   srl       $a1, $a1, 7
  .Leboot_0014E3A4:
    /* 14E418 0014E3A4 F8FF4054 */  bnel       $v0, $zero, .Leboot_0014E388
    /* 14E41C 0014E3A8 4000A524 */   addiu     $a1, $a1, 0x40
    /* 14E420 0014E3AC E3380508 */  j          sym_0014E38C
    /* 14E424 0014E3B0 FF3F023C */   lui       $v0, (0x3FFF0000 >> 16)
  .Leboot_0014E3B4:
    /* 14E428 0014E3B4 04108200 */  sllv       $v0, $v0, $a0
    /* 14E42C 0014E3B8 FFFF4224 */  addiu      $v0, $v0, -0x1
    /* 14E430 0014E3BC 2410A200 */  and        $v0, $a1, $v0
    /* 14E434 0014E3C0 06188500 */  srlv       $v1, $a1, $a0
    /* 14E438 0014E3C4 2B100200 */  sltu       $v0, $zero, $v0
    /* 14E43C 0014E3C8 DD380508 */  j          sym_0014E374
    /* 14E440 0014E3CC 25286200 */   or        $a1, $v1, $v0
  .Leboot_0014E3D0:
    /* 14E444 0014E3D0 04004054 */  bnel       $v0, $zero, .Leboot_0014E3E4
    /* 14E448 0014E3D4 7F00A330 */   andi      $v1, $a1, 0x7F
    /* 14E44C 0014E3D8 FF000724 */  addiu      $a3, $zero, 0xFF
  .Leboot_0014E3DC:
    /* 14E450 0014E3DC B7380508 */  j          sym_0014E2DC
    /* 14E454 0014E3E0 21280000 */   addu      $a1, $zero, $zero
  .Leboot_0014E3E4:
    /* 14E458 0014E3E4 40000224 */  addiu      $v0, $zero, 0x40
    /* 14E45C 0014E3E8 07006210 */  beq        $v1, $v0, .Leboot_0014E408
    /* 14E460 0014E3EC 7F008724 */   addiu     $a3, $a0, 0x7F
    /* 14E464 0014E3F0 3F00A524 */  addiu      $a1, $a1, 0x3F
  sym_0014E3F4:
    /* 14E468 0014E3F4 B9FFA304 */  bgezl      $a1, sym_0014E2DC
    /* 14E46C 0014E3F8 C2290500 */   srl       $a1, $a1, 7
    /* 14E470 0014E3FC 42280500 */  srl        $a1, $a1, 1
    /* 14E474 0014E400 E7380508 */  j          sym_0014E39C
    /* 14E478 0014E404 0100E724 */   addiu     $a3, $a3, 0x1
  .Leboot_0014E408:
    /* 14E47C 0014E408 8000A230 */  andi       $v0, $a1, 0x80
    /* 14E480 0014E40C F9FF4054 */  bnel       $v0, $zero, sym_0014E3F4
    /* 14E484 0014E410 4000A524 */   addiu     $a1, $a1, 0x40
    /* 14E488 0014E414 FD380508 */  j          sym_0014E3F4
    /* 14E48C 0014E418 00000000 */   nop
endlabel func_0014E2B8

nonmatching func_eboot_0014E41C, 0x120

glabel func_eboot_0014E41C
    /* 14E490 0014E41C F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 14E494 0014E420 0000B0AF */  sw         $s0, 0x0($sp)
    /* 14E498 0014E424 0700103C */  lui        $s0, %hi(sym_00068728)
    /* 14E49C 0014E428 28870626 */  addiu      $a2, $s0, %lo(sym_00068728)
    /* 14E4A0 0014E42C 0800BFAF */  sw         $ra, 0x8($sp)
    /* 14E4A4 0014E430 0080033C */  lui        $v1, (0x80000021 >> 16)
    /* 14E4A8 0014E434 FFFF8730 */  andi       $a3, $a0, 0xFFFF
    /* 14E4AC 0014E438 0400B1AF */  sw         $s1, 0x4($sp)
    /* 14E4B0 0014E43C 4400C58C */  lw         $a1, 0x44($a2)
    /* 14E4B4 0014E440 7400A88C */  lw         $t0, 0x74($a1)
    /* 14E4B8 0014E444 35000015 */  bnez       $t0, .Leboot_0014E51C
    /* 14E4BC 0014E448 21006534 */   ori       $a1, $v1, (0x80000021 & 0xFFFF)
    /* 14E4C0 0014E44C 0800C38C */  lw         $v1, 0x8($a2)
    /* 14E4C4 0014E450 0080023C */  lui        $v0, (0x80000107 >> 16)
    /* 14E4C8 0014E454 0500642C */  sltiu      $a0, $v1, 0x5
    /* 14E4CC 0014E458 30008010 */  beqz       $a0, .Leboot_0014E51C
    /* 14E4D0 0014E45C 07014534 */   ori       $a1, $v0, (0x80000107 & 0xFFFF)
    /* 14E4D4 0014E460 1D000B3C */  lui        $t3, %hi(sym_001D16A0)
    /* 14E4D8 0014E464 80480300 */  sll        $t1, $v1, 2
    /* 14E4DC 0014E468 A0166A25 */  addiu      $t2, $t3, %lo(sym_001D16A0)
    /* 14E4E0 0014E46C 21402A01 */  addu       $t0, $t1, $t2
    /* 14E4E4 0014E470 0000068D */  lw         $a2, 0x0($t0)
    /* 14E4E8 0014E474 0800C000 */  jr         $a2
    /* 14E4EC 0014E478 00000000 */   nop
  .L0014E47C:
    /* 14E4F0 0014E47C 28870526 */  addiu      $a1, $s0, %lo(sym_00068728)
    /* 14E4F4 0014E480 4400AE8C */  lw         $t6, 0x44($a1)
    /* 14E4F8 0014E484 000F193C */  lui        $t9, (0xF000000 >> 16)
    /* 14E4FC 0014E488 25C0F900 */  or         $t8, $a3, $t9
    /* 14E500 0014E48C 0800D18D */  lw         $s1, 0x8($t6)
    /* 14E504 0014E490 000C0D3C */  lui        $t5, (0xC000000 >> 16)
    /* 14E508 0014E494 04002C26 */  addiu      $t4, $s1, 0x4
    /* 14E50C 0014E498 04008F25 */  addiu      $t7, $t4, 0x4
    /* 14E510 0014E49C 000038AE */  sw         $t8, 0x0($s1)
    /* 14E514 0014E4A0 0800CFAD */  sw         $t7, 0x8($t6)
    /* 14E518 0014E4A4 2C3B050C */  jal        func_0014ECB0
    /* 14E51C 0014E4A8 00008DAD */   sw        $t5, 0x0($t4)
    /* 14E520 0014E4AC 1B004004 */  bltz       $v0, .Leboot_0014E51C
    /* 14E524 0014E4B0 21284000 */   addu      $a1, $v0, $zero
  .L0014E4B4:
    /* 14E528 0014E4B4 28871026 */  addiu      $s0, $s0, %lo(sym_00068728)
    /* 14E52C 0014E4B8 44000E8E */  lw         $t6, 0x44($s0)
    /* 14E530 0014E4BC 0800C48D */  lw         $a0, 0x8($t6)
    /* 14E534 0014E4C0 0400CD8D */  lw         $t5, 0x4($t6)
    /* 14E538 0014E4C4 EAC1060C */  jal        stub_001B07A8
    /* 14E53C 0014E4C8 23888D00 */   subu      $s1, $a0, $t5
    /* 14E540 0014E4CC 08000C8E */  lw         $t4, 0x8($s0)
    /* 14E544 0014E4D0 FFFF0A24 */  addiu      $t2, $zero, -0x1
    /* 14E548 0014E4D4 21204000 */  addu       $a0, $v0, $zero
    /* 14E54C 0014E4D8 80390C00 */  sll        $a3, $t4, 6
    /* 14E550 0014E4DC 2358EC00 */  subu       $t3, $a3, $t4
    /* 14E554 0014E4E0 80180B00 */  sll        $v1, $t3, 2
    /* 14E558 0014E4E4 21487000 */  addu       $t1, $v1, $s0
    /* 14E55C 0014E4E8 4001258D */  lw         $a1, 0x140($t1)
    /* 14E560 0014E4EC 40012AAD */  sw         $t2, 0x140($t1)
    /* 14E564 0014E4F0 1000A004 */  bltz       $a1, .Leboot_0014E534
    /* 14E568 0014E4F4 080005AE */   sw        $a1, 0x8($s0)
    /* 14E56C 0014E4F8 80410500 */  sll        $t0, $a1, 6
    /* 14E570 0014E4FC 23300501 */  subu       $a2, $t0, $a1
    /* 14E574 0014E500 80C00600 */  sll        $t8, $a2, 2
    /* 14E578 0014E504 48001926 */  addiu      $t9, $s0, 0x48
    /* 14E57C 0014E508 21781903 */  addu       $t7, $t8, $t9
    /* 14E580 0014E50C 44000FAE */  sw         $t7, 0x44($s0)
  .L0014E510:
    /* 14E584 0014E510 ECC1060C */  jal        stub_001B07B0
    /* 14E588 0014E514 00000000 */   nop
    /* 14E58C 0014E518 21282002 */  addu       $a1, $s1, $zero
  .Leboot_0014E51C:
    /* 14E590 0014E51C 0800BF8F */  lw         $ra, 0x8($sp)
    /* 14E594 0014E520 0400B18F */  lw         $s1, 0x4($sp)
    /* 14E598 0014E524 0000B08F */  lw         $s0, 0x0($sp)
    /* 14E59C 0014E528 2110A000 */  addu       $v0, $a1, $zero
    /* 14E5A0 0014E52C 0800E003 */  jr         $ra
    /* 14E5A4 0014E530 1000BD27 */   addiu     $sp, $sp, 0x10
  .Leboot_0014E534:
    /* 14E5A8 0014E534 44390508 */  j          sym_0014E510
    /* 14E5AC 0014E538 440000AE */   sw        $zero, 0x44($s0)
endlabel func_eboot_0014E41C

nonmatching .Leboot_0014E53C, 0x54

glabel .Leboot_0014E53C
    /* 14E5B0 0014E53C 28870426 */  addiu      $a0, $s0, %lo(sym_00068728)
    /* 14E5B4 0014E540 0C008C8C */  lw         $t4, 0xC($a0)
    /* 14E5B8 0014E544 01000724 */  addiu      $a3, $zero, 0x1
    /* 14E5BC 0014E548 07008711 */  beq        $t4, $a3, .Leboot_0014E568
    /* 14E5C0 0014E54C 000B083C */   lui       $t0, (0xB000000 >> 16)
    /* 14E5C4 0014E550 4400858C */  lw         $a1, 0x44($a0)
    /* 14E5C8 0014E554 0800A28C */  lw         $v0, 0x8($a1)
    /* 14E5CC 0014E558 04004624 */  addiu      $a2, $v0, 0x4
    /* 14E5D0 0014E55C 000048AC */  sw         $t0, 0x0($v0)
    /* 14E5D4 0014E560 2D390508 */  j          sym_0014E4B4
    /* 14E5D8 0014E564 0800A6AC */   sw        $a2, 0x8($a1)
  .Leboot_0014E568:
    /* 14E5DC 0014E568 44008F8C */  lw         $t7, 0x44($a0)
    /* 14E5E0 0014E56C 120E193C */  lui        $t9, (0xE120000 >> 16)
    /* 14E5E4 0014E570 000C0E3C */  lui        $t6, (0xC000000 >> 16)
    /* 14E5E8 0014E574 0800F88D */  lw         $t8, 0x8($t7)
    /* 14E5EC 0014E578 04000D27 */  addiu      $t5, $t8, 0x4
    /* 14E5F0 0014E57C 0400B125 */  addiu      $s1, $t5, 0x4
    /* 14E5F4 0014E580 000019AF */  sw         $t9, 0x0($t8)
    /* 14E5F8 0014E584 0800F1AD */  sw         $s1, 0x8($t7)
    /* 14E5FC 0014E588 2D390508 */  j          sym_0014E4B4
    /* 14E600 0014E58C 0000AEAD */   sw        $t6, 0x0($t5)
endlabel .Leboot_0014E53C

nonmatching .Leboot_0014E590, 0x30

glabel .Leboot_0014E590
    /* 14E604 0014E590 28870B26 */  addiu      $t3, $s0, %lo(sym_00068728)
    /* 14E608 0014E594 4400648D */  lw         $a0, 0x44($t3)
    /* 14E60C 0014E598 000F0A3C */  lui        $t2, (0xF000000 >> 16)
    /* 14E610 0014E59C 2518EA00 */  or         $v1, $a3, $t2
    /* 14E614 0014E5A0 0800898C */  lw         $t1, 0x8($a0)
    /* 14E618 0014E5A4 000C023C */  lui        $v0, (0xC000000 >> 16)
    /* 14E61C 0014E5A8 04002625 */  addiu      $a2, $t1, 0x4
    /* 14E620 0014E5AC 0400C824 */  addiu      $t0, $a2, 0x4
    /* 14E624 0014E5B0 000023AD */  sw         $v1, 0x0($t1)
    /* 14E628 0014E5B4 080088AC */  sw         $t0, 0x8($a0)
    /* 14E62C 0014E5B8 2D390508 */  j          sym_0014E4B4
    /* 14E630 0014E5BC 0000C2AC */   sw        $v0, 0x0($a2)
endlabel .Leboot_0014E590
