.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0012DF70, 0x88

glabel func_0012DF70
    /* 12DFE4 0012DF70 816C0C46 */  sub.s      $f18, $f13, $f12
    /* 12DFE8 0012DF74 0040053C */  lui        $a1, (0x40000000 >> 16)
    /* 12DFEC 0012DF78 00988544 */  mtc1       $a1, $f19
    /* 12DFF0 0012DF7C 03981246 */  div.s      $f0, $f19, $f18
    /* 12DFF4 0012DF80 040080AC */  sw         $zero, 0x4($a0)
    /* 12DFF8 0012DF84 080080AC */  sw         $zero, 0x8($a0)
    /* 12DFFC 0012DF88 0C0080AC */  sw         $zero, 0xC($a0)
    /* 12E000 0012DF8C 100080AC */  sw         $zero, 0x10($a0)
    /* 12E004 0012DF90 180080AC */  sw         $zero, 0x18($a0)
    /* 12E008 0012DF94 1C0080AC */  sw         $zero, 0x1C($a0)
    /* 12E00C 0012DF98 80BF053C */  lui        $a1, (0xBF800000 >> 16)
    /* 12E010 0012DF9C 2C0085AC */  sw         $a1, 0x2C($a0)
    /* 12E014 0012DFA0 300080AC */  sw         $zero, 0x30($a0)
    /* 12E018 0012DFA4 340080AC */  sw         $zero, 0x34($a0)
    /* 12E01C 0012DFA8 3C0080AC */  sw         $zero, 0x3C($a0)
    /* 12E020 0012DFAC 81780E46 */  sub.s      $f2, $f15, $f14
    /* 12E024 0012DFB0 43980246 */  div.s      $f1, $f19, $f2
    /* 12E028 0012DFB4 000080E4 */  swc1       $f0, 0x0($a0)
    /* 12E02C 0012DFB8 00630D46 */  add.s      $f12, $f12, $f13
    /* 12E030 0012DFBC 03631246 */  div.s      $f12, $f12, $f18
    /* 12E034 0012DFC0 140081E4 */  swc1       $f1, 0x14($a0)
    /* 12E038 0012DFC4 80730F46 */  add.s      $f14, $f14, $f15
    /* 12E03C 0012DFC8 83730246 */  div.s      $f14, $f14, $f2
    /* 12E040 0012DFCC 20008CE4 */  swc1       $f12, 0x20($a0)
    /* 12E044 0012DFD0 C28C1346 */  mul.s      $f19, $f17, $f19
    /* 12E048 0012DFD4 01831146 */  sub.s      $f12, $f16, $f17
    /* 12E04C 0012DFD8 408C1046 */  add.s      $f17, $f17, $f16
    /* 12E050 0012DFDC 438B0C46 */  div.s      $f13, $f17, $f12
    /* 12E054 0012DFE0 24008EE4 */  swc1       $f14, 0x24($a0)
    /* 12E058 0012DFE4 829B1046 */  mul.s      $f14, $f19, $f16
    /* 12E05C 0012DFE8 03730C46 */  div.s      $f12, $f14, $f12
    /* 12E060 0012DFEC 28008DE4 */  swc1       $f13, 0x28($a0)
    /* 12E064 0012DFF0 0800E003 */  jr         $ra
    /* 12E068 0012DFF4 38008CE4 */   swc1      $f12, 0x38($a0)
endlabel func_0012DF70
