.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0018F678, 0x8

glabel func_0018F678
    /* 18F6EC 0018F678 0800E003 */  jr         $ra
    /* 18F6F0 0018F67C 25100000 */   or        $v0, $zero, $zero
endlabel func_0018F678
