.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

/* Handwritten function */
nonmatching func_0013DAF0, 0x3D0

glabel func_0013DAF0
    /* 13DB64 0013DAF0 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 13DB68 0013DAF4 1000ACE7 */  swc1       $f12, 0x10($sp)
    /* 13DB6C 0013DAF8 2800B0AF */  sw         $s0, 0x28($sp)
    /* 13DB70 0013DAFC 1000B08F */  lw         $s0, 0x10($sp)
    /* 13DB74 0013DB00 0080043C */  lui        $a0, %hi(D_7FFFFFFF)
    /* 13DB78 0013DB04 2C00B1AF */  sw         $s1, 0x2C($sp)
    /* 13DB7C 0013DB08 FFFF9124 */  addiu      $s1, $a0, %lo(D_7FFFFFFF)
    /* 13DB80 0013DB0C 24881102 */  and        $s1, $s0, $s1
    /* 13DB84 0013DB10 803F043C */  lui        $a0, (0x3F800000 >> 16)
    /* 13DB88 0013DB14 1C00B4E7 */  swc1       $f20, 0x1C($sp)
    /* 13DB8C 0013DB18 2000B6E7 */  swc1       $f22, 0x20($sp)
    /* 13DB90 0013DB1C 2400B8E7 */  swc1       $f24, 0x24($sp)
    /* 13DB94 0013DB20 3000BFAF */  sw         $ra, 0x30($sp)
    /* 13DB98 0013DB24 14002412 */  beq        $s1, $a0, .Leboot_0013DB78
    /* 13DB9C 0013DB28 06600046 */   mov.s     $f0, $f12
    /* 13DBA0 0013DB2C 2A209100 */  slt        $a0, $a0, $s1
    /* 13DBA4 0013DB30 07008014 */  bnez       $a0, .Leboot_0013DB50
    /* 13DBA8 0013DB34 003F043C */   lui       $a0, (0x3F000000 >> 16)
    /* 13DBAC 0013DB38 803F053C */  lui        $a1, (0x3F800000 >> 16)
    /* 13DBB0 0013DB3C 2A202402 */  slt        $a0, $s1, $a0
    /* 13DBB4 0013DB40 1E008014 */  bnez       $a0, .Leboot_0013DBBC
    /* 13DBB8 0013DB44 00A08544 */   mtc1      $a1, $f20
    /* 13DBBC 0013DB48 6D000010 */  b          .Leboot_0013DD00
    /* 13DBC0 0013DB4C 86A50046 */   mov.s     $f22, $f20
  .Leboot_0013DB50:
    /* 13DBC4 0013DB50 00008044 */  mtc1       $zero, $f0
    /* 13DBC8 0013DB54 03000046 */  div.s      $f0, $f0, $f0
    /* 13DBCC 0013DB58 1C00B4C7 */  lwc1       $f20, 0x1C($sp)
    /* 13DBD0 0013DB5C 2000B6C7 */  lwc1       $f22, 0x20($sp)
    /* 13DBD4 0013DB60 2400B8C7 */  lwc1       $f24, 0x24($sp)
    /* 13DBD8 0013DB64 2800B08F */  lw         $s0, 0x28($sp)
    /* 13DBDC 0013DB68 2C00B18F */  lw         $s1, 0x2C($sp)
    /* 13DBE0 0013DB6C 3000BF8F */  lw         $ra, 0x30($sp)
    /* 13DBE4 0013DB70 0800E003 */  jr         $ra
    /* 13DBE8 0013DB74 4000BD27 */   addiu     $sp, $sp, 0x40
  .Leboot_0013DB78:
    /* 13DBEC 0013DB78 C93F043C */  lui        $a0, (0x3FC90FDA >> 16)
    /* 13DBF0 0013DB7C DA0F8434 */  ori        $a0, $a0, (0x3FC90FDA & 0xFFFF)
    /* 13DBF4 0013DB80 00608444 */  mtc1       $a0, $f12
    /* 13DBF8 0013DB84 02030C46 */  mul.s      $f12, $f0, $f12
    /* 13DBFC 0013DB88 A233043C */  lui        $a0, (0x33A22168 >> 16)
    /* 13DC00 0013DB8C 68218434 */  ori        $a0, $a0, (0x33A22168 & 0xFFFF)
    /* 13DC04 0013DB90 00688444 */  mtc1       $a0, $f13
    /* 13DC08 0013DB94 02000D46 */  mul.s      $f0, $f0, $f13
    /* 13DC0C 0013DB98 00600046 */  add.s      $f0, $f12, $f0
    /* 13DC10 0013DB9C 1C00B4C7 */  lwc1       $f20, 0x1C($sp)
    /* 13DC14 0013DBA0 2000B6C7 */  lwc1       $f22, 0x20($sp)
    /* 13DC18 0013DBA4 2400B8C7 */  lwc1       $f24, 0x24($sp)
    /* 13DC1C 0013DBA8 2800B08F */  lw         $s0, 0x28($sp)
    /* 13DC20 0013DBAC 2C00B18F */  lw         $s1, 0x2C($sp)
    /* 13DC24 0013DBB0 3000BF8F */  lw         $ra, 0x30($sp)
    /* 13DC28 0013DBB4 0800E003 */  jr         $ra
    /* 13DC2C 0013DBB8 4000BD27 */   addiu     $sp, $sp, 0x40
  .Leboot_0013DBBC:
    /* 13DC30 0013DBBC 0032043C */  lui        $a0, (0x32000000 >> 16)
    /* 13DC34 0013DBC0 2A202402 */  slt        $a0, $s1, $a0
    /* 13DC38 0013DBC4 4C008010 */  beqz       $a0, .Leboot_0013DCF8
    /* 13DC3C 0013DBC8 4971043C */   lui       $a0, (0x7149F2CA >> 16)
    /* 13DC40 0013DBCC CAF28434 */  ori        $a0, $a0, (0x7149F2CA & 0xFFFF)
    /* 13DC44 0013DBD0 00608444 */  mtc1       $a0, $f12
    /* 13DC48 0013DBD4 00030C46 */  add.s      $f12, $f0, $f12
    /* 13DC4C 0013DBD8 3E601446 */  c.le.s     $f12, $f20
    /* 13DC50 0013DBDC 00000000 */  nop
    /* 13DC54 0013DBE0 3D000045 */  bc1f       .Leboot_0013DCD8 /* handwritten instruction */
    /* 13DC58 0013DBE4 00000000 */   nop
  .Leboot_0013DBE8:
    /* 13DC5C 0013DBE8 1138043C */  lui        $a0, (0x3811EF08 >> 16)
    /* 13DC60 0013DBEC 08EF8434 */  ori        $a0, $a0, (0x3811EF08 & 0xFFFF)
    /* 13DC64 0013DBF0 00688444 */  mtc1       $a0, $f13
    /* 13DC68 0013DBF4 42630D46 */  mul.s      $f13, $f12, $f13
    /* 13DC6C 0013DBF8 4F3A043C */  lui        $a0, (0x3A4F7F04 >> 16)
    /* 13DC70 0013DBFC 047F8434 */  ori        $a0, $a0, (0x3A4F7F04 & 0xFFFF)
    /* 13DC74 0013DC00 00708444 */  mtc1       $a0, $f14
    /* 13DC78 0013DC04 24BD043C */  lui        $a0, (0xBD241146 >> 16)
    /* 13DC7C 0013DC08 406B0E46 */  add.s      $f13, $f13, $f14
    /* 13DC80 0013DC0C 46118434 */  ori        $a0, $a0, (0xBD241146 & 0xFFFF)
    /* 13DC84 0013DC10 00788444 */  mtc1       $a0, $f15
    /* 13DC88 0013DC14 4E3E043C */  lui        $a0, (0x3E4E0AA8 >> 16)
    /* 13DC8C 0013DC18 A80A8434 */  ori        $a0, $a0, (0x3E4E0AA8 & 0xFFFF)
    /* 13DC90 0013DC1C 42630D46 */  mul.s      $f13, $f12, $f13
    /* 13DC94 0013DC20 30BF053C */  lui        $a1, (0xBF303361 >> 16)
    /* 13DC98 0013DC24 00808444 */  mtc1       $a0, $f16
    /* 13DC9C 0013DC28 9D3D043C */  lui        $a0, (0x3D9DC62E >> 16)
    /* 13DCA0 0013DC2C 2EC68434 */  ori        $a0, $a0, (0x3D9DC62E & 0xFFFF)
    /* 13DCA4 0013DC30 406B0F46 */  add.s      $f13, $f13, $f15
    /* 13DCA8 0013DC34 00708444 */  mtc1       $a0, $f14
    /* 13DCAC 0013DC38 82630E46 */  mul.s      $f14, $f12, $f14
    /* 13DCB0 0013DC3C 6133A434 */  ori        $a0, $a1, (0xBF303361 & 0xFFFF)
    /* 13DCB4 0013DC40 A6BE053C */  lui        $a1, (0xBEA6B090 >> 16)
    /* 13DCB8 0013DC44 00788444 */  mtc1       $a0, $f15
    /* 13DCBC 0013DC48 42630D46 */  mul.s      $f13, $f12, $f13
    /* 13DCC0 0013DC4C 90B0A434 */  ori        $a0, $a1, (0xBEA6B090 & 0xFFFF)
    /* 13DCC4 0013DC50 80730F46 */  add.s      $f14, $f14, $f15
    /* 13DCC8 0013DC54 2A3E053C */  lui        $a1, (0x3E2AAAAB >> 16)
    /* 13DCCC 0013DC58 00888444 */  mtc1       $a0, $f17
    /* 13DCD0 0013DC5C 0140043C */  lui        $a0, (0x4001572D >> 16)
    /* 13DCD4 0013DC60 406B1046 */  add.s      $f13, $f13, $f16
    /* 13DCD8 0013DC64 2D578434 */  ori        $a0, $a0, (0x4001572D & 0xFFFF)
    /* 13DCDC 0013DC68 82630E46 */  mul.s      $f14, $f12, $f14
    /* 13DCE0 0013DC6C 00788444 */  mtc1       $a0, $f15
    /* 13DCE4 0013DC70 ABAAA434 */  ori        $a0, $a1, (0x3E2AAAAB & 0xFFFF)
    /* 13DCE8 0013DC74 42630D46 */  mul.s      $f13, $f12, $f13
    /* 13DCEC 0013DC78 80730F46 */  add.s      $f14, $f14, $f15
    /* 13DCF0 0013DC7C 00808444 */  mtc1       $a0, $f16
    /* 13DCF4 0013DC80 19C0043C */  lui        $a0, (0xC019D139 >> 16)
    /* 13DCF8 0013DC84 406B1146 */  add.s      $f13, $f13, $f17
    /* 13DCFC 0013DC88 39D18434 */  ori        $a0, $a0, (0xC019D139 & 0xFFFF)
    /* 13DD00 0013DC8C 82630E46 */  mul.s      $f14, $f12, $f14
    /* 13DD04 0013DC90 00788444 */  mtc1       $a0, $f15
    /* 13DD08 0013DC94 42630D46 */  mul.s      $f13, $f12, $f13
    /* 13DD0C 0013DC98 80730F46 */  add.s      $f14, $f14, $f15
    /* 13DD10 0013DC9C 406B1046 */  add.s      $f13, $f13, $f16
    /* 13DD14 0013DCA0 82630E46 */  mul.s      $f14, $f12, $f14
    /* 13DD18 0013DCA4 02630D46 */  mul.s      $f12, $f12, $f13
    /* 13DD1C 0013DCA8 80731446 */  add.s      $f14, $f14, $f20
    /* 13DD20 0013DCAC 03630E46 */  div.s      $f12, $f12, $f14
    /* 13DD24 0013DCB0 02630046 */  mul.s      $f12, $f12, $f0
    /* 13DD28 0013DCB4 00000C46 */  add.s      $f0, $f0, $f12
    /* 13DD2C 0013DCB8 1C00B4C7 */  lwc1       $f20, 0x1C($sp)
    /* 13DD30 0013DCBC 2000B6C7 */  lwc1       $f22, 0x20($sp)
    /* 13DD34 0013DCC0 2400B8C7 */  lwc1       $f24, 0x24($sp)
    /* 13DD38 0013DCC4 2800B08F */  lw         $s0, 0x28($sp)
    /* 13DD3C 0013DCC8 2C00B18F */  lw         $s1, 0x2C($sp)
    /* 13DD40 0013DCCC 3000BF8F */  lw         $ra, 0x30($sp)
    /* 13DD44 0013DCD0 0800E003 */  jr         $ra
    /* 13DD48 0013DCD4 4000BD27 */   addiu     $sp, $sp, 0x40
  .Leboot_0013DCD8:
    /* 13DD4C 0013DCD8 1C00B4C7 */  lwc1       $f20, 0x1C($sp)
    /* 13DD50 0013DCDC 2000B6C7 */  lwc1       $f22, 0x20($sp)
    /* 13DD54 0013DCE0 2400B8C7 */  lwc1       $f24, 0x24($sp)
    /* 13DD58 0013DCE4 2800B08F */  lw         $s0, 0x28($sp)
    /* 13DD5C 0013DCE8 2C00B18F */  lw         $s1, 0x2C($sp)
    /* 13DD60 0013DCEC 3000BF8F */  lw         $ra, 0x30($sp)
    /* 13DD64 0013DCF0 0800E003 */  jr         $ra
    /* 13DD68 0013DCF4 4000BD27 */   addiu     $sp, $sp, 0x40
  .Leboot_0013DCF8:
    /* 13DD6C 0013DCF8 BBFF0010 */  b          .Leboot_0013DBE8
    /* 13DD70 0013DCFC 02030046 */   mul.s     $f12, $f0, $f0
  .Leboot_0013DD00:
    /* 13DD74 0013DD00 70EE040C */  jal        func_0013B9C0
    /* 13DD78 0013DD04 06030046 */   mov.s     $f12, $f0
    /* 13DD7C 0013DD08 01B60046 */  sub.s      $f24, $f22, $f0
    /* 13DD80 0013DD0C 003F043C */  lui        $a0, (0x3F000000 >> 16)
    /* 13DD84 0013DD10 00608444 */  mtc1       $a0, $f12
    /* 13DD88 0013DD14 1138043C */  lui        $a0, (0x3811EF08 >> 16)
    /* 13DD8C 0013DD18 08EF8434 */  ori        $a0, $a0, (0x3811EF08 & 0xFFFF)
    /* 13DD90 0013DD1C 02C60C46 */  mul.s      $f24, $f24, $f12
    /* 13DD94 0013DD20 00688444 */  mtc1       $a0, $f13
    /* 13DD98 0013DD24 4F3A043C */  lui        $a0, (0x3A4F7F04 >> 16)
    /* 13DD9C 0013DD28 047F8434 */  ori        $a0, $a0, (0x3A4F7F04 & 0xFFFF)
    /* 13DDA0 0013DD2C 42C30D46 */  mul.s      $f13, $f24, $f13
    /* 13DDA4 0013DD30 00608444 */  mtc1       $a0, $f12
    /* 13DDA8 0013DD34 24BD043C */  lui        $a0, (0xBD241146 >> 16)
    /* 13DDAC 0013DD38 46118434 */  ori        $a0, $a0, (0xBD241146 & 0xFFFF)
    /* 13DDB0 0013DD3C 006B0C46 */  add.s      $f12, $f13, $f12
    /* 13DDB4 0013DD40 00708444 */  mtc1       $a0, $f14
    /* 13DDB8 0013DD44 4E3E043C */  lui        $a0, (0x3E4E0AA8 >> 16)
    /* 13DDBC 0013DD48 A80A8434 */  ori        $a0, $a0, (0x3E4E0AA8 & 0xFFFF)
    /* 13DDC0 0013DD4C 02C30C46 */  mul.s      $f12, $f24, $f12
    /* 13DDC4 0013DD50 30BF053C */  lui        $a1, (0xBF303361 >> 16)
    /* 13DDC8 0013DD54 00788444 */  mtc1       $a0, $f15
    /* 13DDCC 0013DD58 9D3D043C */  lui        $a0, (0x3D9DC62E >> 16)
    /* 13DDD0 0013DD5C 2EC68434 */  ori        $a0, $a0, (0x3D9DC62E & 0xFFFF)
    /* 13DDD4 0013DD60 00630E46 */  add.s      $f12, $f12, $f14
    /* 13DDD8 0013DD64 00688444 */  mtc1       $a0, $f13
    /* 13DDDC 0013DD68 42C30D46 */  mul.s      $f13, $f24, $f13
    /* 13DDE0 0013DD6C 6133A434 */  ori        $a0, $a1, (0xBF303361 & 0xFFFF)
    /* 13DDE4 0013DD70 A6BE053C */  lui        $a1, (0xBEA6B090 >> 16)
    /* 13DDE8 0013DD74 00708444 */  mtc1       $a0, $f14
    /* 13DDEC 0013DD78 02C30C46 */  mul.s      $f12, $f24, $f12
    /* 13DDF0 0013DD7C 90B0A434 */  ori        $a0, $a1, (0xBEA6B090 & 0xFFFF)
    /* 13DDF4 0013DD80 406B0E46 */  add.s      $f13, $f13, $f14
    /* 13DDF8 0013DD84 2A3E053C */  lui        $a1, (0x3E2AAAAB >> 16)
    /* 13DDFC 0013DD88 00808444 */  mtc1       $a0, $f16
    /* 13DE00 0013DD8C 0140043C */  lui        $a0, (0x4001572D >> 16)
    /* 13DE04 0013DD90 00630F46 */  add.s      $f12, $f12, $f15
    /* 13DE08 0013DD94 2D578434 */  ori        $a0, $a0, (0x4001572D & 0xFFFF)
    /* 13DE0C 0013DD98 42C30D46 */  mul.s      $f13, $f24, $f13
    /* 13DE10 0013DD9C 00708444 */  mtc1       $a0, $f14
    /* 13DE14 0013DDA0 ABAAA434 */  ori        $a0, $a1, (0x3E2AAAAB & 0xFFFF)
    /* 13DE18 0013DDA4 02C30C46 */  mul.s      $f12, $f24, $f12
    /* 13DE1C 0013DDA8 406B0E46 */  add.s      $f13, $f13, $f14
    /* 13DE20 0013DDAC 00788444 */  mtc1       $a0, $f15
    /* 13DE24 0013DDB0 19C0043C */  lui        $a0, (0xC019D139 >> 16)
    /* 13DE28 0013DDB4 00631046 */  add.s      $f12, $f12, $f16
    /* 13DE2C 0013DDB8 39D18434 */  ori        $a0, $a0, (0xC019D139 & 0xFFFF)
    /* 13DE30 0013DDBC 42C30D46 */  mul.s      $f13, $f24, $f13
    /* 13DE34 0013DDC0 00708444 */  mtc1       $a0, $f14
    /* 13DE38 0013DDC4 02C30C46 */  mul.s      $f12, $f24, $f12
    /* 13DE3C 0013DDC8 406B0E46 */  add.s      $f13, $f13, $f14
    /* 13DE40 0013DDCC 00650F46 */  add.s      $f20, $f12, $f15
    /* 13DE44 0013DDD0 42C30D46 */  mul.s      $f13, $f24, $f13
    /* 13DE48 0013DDD4 06C30046 */  mov.s      $f12, $f24
    /* 13DE4C 0013DDD8 02C51446 */  mul.s      $f20, $f24, $f20
    /* 13DE50 0013DDDC 08FF040C */  jal        func_0013FC20
    /* 13DE54 0013DDE0 806D1646 */   add.s     $f22, $f13, $f22
    /* 13DE58 0013DDE4 A233053C */  lui        $a1, (0x33A22168 >> 16)
    /* 13DE5C 0013DDE8 06030046 */  mov.s      $f12, $f0
    /* 13DE60 0013DDEC 6821A534 */  ori        $a1, $a1, (0x33A22168 & 0xFFFF)
    /* 13DE64 0013DDF0 7A3F043C */  lui        $a0, %hi(D_3F79999A)
    /* 13DE68 0013DDF4 00008544 */  mtc1       $a1, $f0
    /* 13DE6C 0013DDF8 9A998424 */  addiu      $a0, $a0, %lo(D_3F79999A)
    /* 13DE70 0013DDFC 0040053C */  lui        $a1, (0x40000000 >> 16)
    /* 13DE74 0013DE00 2A202402 */  slt        $a0, $s1, $a0
    /* 13DE78 0013DE04 0B008014 */  bnez       $a0, .Leboot_0013DE34
    /* 13DE7C 0013DE08 00688544 */   mtc1      $a1, $f13
    /* 13DE80 0013DE0C 83A31646 */  div.s      $f14, $f20, $f22
    /* 13DE84 0013DE10 C93F043C */  lui        $a0, (0x3FC90FDA >> 16)
    /* 13DE88 0013DE14 DA0F8434 */  ori        $a0, $a0, (0x3FC90FDA & 0xFFFF)
    /* 13DE8C 0013DE18 00788444 */  mtc1       $a0, $f15
    /* 13DE90 0013DE1C 82630E46 */  mul.s      $f14, $f12, $f14
    /* 13DE94 0013DE20 00630E46 */  add.s      $f12, $f12, $f14
    /* 13DE98 0013DE24 02630D46 */  mul.s      $f12, $f12, $f13
    /* 13DE9C 0013DE28 01600046 */  sub.s      $f0, $f12, $f0
    /* 13DEA0 0013DE2C 18000010 */  b          .Leboot_0013DE90
    /* 13DEA4 0013DE30 01780046 */   sub.s     $f0, $f15, $f0
  .Leboot_0013DE34:
    /* 13DEA8 0013DE34 1400ACE7 */  swc1       $f12, 0x14($sp)
    /* 13DEAC 0013DE38 1400A48F */  lw         $a0, 0x14($sp)
    /* 13DEB0 0013DE3C 00F00524 */  addiu      $a1, $zero, -0x1000
    /* 13DEB4 0013DE40 24208500 */  and        $a0, $a0, $a1
    /* 13DEB8 0013DE44 1800A4AF */  sw         $a0, 0x18($sp)
    /* 13DEBC 0013DE48 1800AEC7 */  lwc1       $f14, 0x18($sp)
    /* 13DEC0 0013DE4C C3A31646 */  div.s      $f15, $f20, $f22
    /* 13DEC4 0013DE50 493F043C */  lui        $a0, (0x3F490FDB >> 16)
    /* 13DEC8 0013DE54 DB0F8434 */  ori        $a0, $a0, (0x3F490FDB & 0xFFFF)
    /* 13DECC 0013DE58 02740E46 */  mul.s      $f16, $f14, $f14
    /* 13DED0 0013DE5C 40640E46 */  add.s      $f17, $f12, $f14
    /* 13DED4 0013DE60 01C41046 */  sub.s      $f16, $f24, $f16
    /* 13DED8 0013DE64 03841146 */  div.s      $f16, $f16, $f17
    /* 13DEDC 0013DE68 02630D46 */  mul.s      $f12, $f12, $f13
    /* 13DEE0 0013DE6C 82730D46 */  mul.s      $f14, $f14, $f13
    /* 13DEE4 0013DE70 00908444 */  mtc1       $a0, $f18
    /* 13DEE8 0013DE74 02630F46 */  mul.s      $f12, $f12, $f15
    /* 13DEEC 0013DE78 81930E46 */  sub.s      $f14, $f18, $f14
    /* 13DEF0 0013DE7C 42830D46 */  mul.s      $f13, $f16, $f13
    /* 13DEF4 0013DE80 41030D46 */  sub.s      $f13, $f0, $f13
    /* 13DEF8 0013DE84 01630D46 */  sub.s      $f12, $f12, $f13
    /* 13DEFC 0013DE88 01600E46 */  sub.s      $f0, $f12, $f14
    /* 13DF00 0013DE8C 01900046 */  sub.s      $f0, $f18, $f0
  .Leboot_0013DE90:
    /* 13DF04 0013DE90 06030046 */  mov.s      $f12, $f0
    /* 13DF08 0013DE94 0100005A */  blezl      $s0, .Leboot_0013DE9C
    /* 13DF0C 0013DE98 07030046 */   neg.s     $f12, $f0
  .Leboot_0013DE9C:
    /* 13DF10 0013DE9C 06600046 */  mov.s      $f0, $f12
    /* 13DF14 0013DEA0 1C00B4C7 */  lwc1       $f20, 0x1C($sp)
    /* 13DF18 0013DEA4 2000B6C7 */  lwc1       $f22, 0x20($sp)
    /* 13DF1C 0013DEA8 2400B8C7 */  lwc1       $f24, 0x24($sp)
    /* 13DF20 0013DEAC 2800B08F */  lw         $s0, 0x28($sp)
    /* 13DF24 0013DEB0 2C00B18F */  lw         $s1, 0x2C($sp)
    /* 13DF28 0013DEB4 3000BF8F */  lw         $ra, 0x30($sp)
    /* 13DF2C 0013DEB8 0800E003 */  jr         $ra
    /* 13DF30 0013DEBC 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel func_0013DAF0
