.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000E5CDC, 0xB8

glabel func_000E5CDC
    /* E5D50 000E5CDC E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* E5D54 000E5CE0 0700A72C */  sltiu      $a3, $a1, 0x7
    /* E5D58 000E5CE4 1000B0AF */  sw         $s0, 0x10($sp)
    /* E5D5C 000E5CE8 1400BFAF */  sw         $ra, 0x14($sp)
    /* E5D60 000E5CEC 2100E010 */  beqz       $a3, .Leboot_000E5D74
    /* E5D64 000E5CF0 2580C000 */   or        $s0, $a2, $zero
    /* E5D68 000E5CF4 80280500 */  sll        $a1, $a1, 2
    /* E5D6C 000E5CF8 1D00013C */  lui        $at, %hi(sym_001CB8C8)
    /* E5D70 000E5CFC 21082500 */  addu       $at, $at, $a1
    /* E5D74 000E5D00 C8B8218C */  lw         $at, %lo(sym_001CB8C8)($at)
    /* E5D78 000E5D04 08002000 */  jr         $at
    /* E5D7C 000E5D08 00000000 */   nop
  sym_000E5D0C:
    /* E5D80 000E5D0C 1A009000 */  div        $zero, $a0, $s0
    /* E5D84 000E5D10 12100000 */  mflo       $v0
    /* E5D88 000E5D14 1B000010 */  b          .Leboot_000E5D84
    /* E5D8C 000E5D18 00000000 */   nop
  sym_000E5D1C:
    /* E5D90 000E5D1C 21281002 */  addu       $a1, $s0, $s0
    /* E5D94 000E5D20 1A008500 */  div        $zero, $a0, $a1
    /* E5D98 000E5D24 12100000 */  mflo       $v0
    /* E5D9C 000E5D28 16000010 */  b          .Leboot_000E5D84
    /* E5DA0 000E5D2C 00000000 */   nop
  sym_000E5D30:
    /* E5DA4 000E5D30 C0281000 */  sll        $a1, $s0, 3
    /* E5DA8 000E5D34 1A008500 */  div        $zero, $a0, $a1
    /* E5DAC 000E5D38 12100000 */  mflo       $v0
    /* E5DB0 000E5D3C 00210200 */  sll        $a0, $v0, 4
    /* E5DB4 000E5D40 23208200 */  subu       $a0, $a0, $v0
    /* E5DB8 000E5D44 0F000010 */  b          .Leboot_000E5D84
    /* E5DBC 000E5D48 23108200 */   subu      $v0, $a0, $v0
  .L000E5D4C:
    /* E5DC0 000E5D4C 0500053C */  lui        $a1, %hi(func_00051968)
    /* E5DC4 000E5D50 6819A68C */  lw         $a2, %lo(func_00051968)($a1)
    /* E5DC8 000E5D54 25288000 */  or         $a1, $a0, $zero
    /* E5DCC 000E5D58 2994030C */  jal        func_000E50A4
    /* E5DD0 000E5D5C 2520C000 */   or        $a0, $a2, $zero
    /* E5DD4 000E5D60 21201002 */  addu       $a0, $s0, $s0
    /* E5DD8 000E5D64 1A004400 */  div        $zero, $v0, $a0
    /* E5DDC 000E5D68 12100000 */  mflo       $v0
    /* E5DE0 000E5D6C 05000010 */  b          .Leboot_000E5D84
    /* E5DE4 000E5D70 00000000 */   nop
  .Leboot_000E5D74:
    /* E5DE8 000E5D74 1D00043C */  lui        $a0, %hi(str_Unsupported_music_format)
    /* E5DEC 000E5D78 DCBB040C */  jal        elem_throw_bad_alloc
    /* E5DF0 000E5D7C A8B88424 */   addiu     $a0, $a0, %lo(str_Unsupported_music_format)
    /* E5DF4 000E5D80 00000234 */  ori        $v0, $zero, 0x0
  .Leboot_000E5D84:
    /* E5DF8 000E5D84 1000B08F */  lw         $s0, 0x10($sp)
    /* E5DFC 000E5D88 1400BF8F */  lw         $ra, 0x14($sp)
    /* E5E00 000E5D8C 0800E003 */  jr         $ra
    /* E5E04 000E5D90 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_000E5CDC
