.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_001A5FBC, 0xA0

glabel func_001A5FBC
    /* 1A6030 001A5FBC C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 1A6034 001A5FC0 4000A6AF */  sw         $a2, 0x40($sp)
    /* 1A6038 001A5FC4 4000A683 */  lb         $a2, 0x40($sp)
    /* 1A603C 001A5FC8 2000A6A3 */  sb         $a2, 0x20($sp)
    /* 1A6040 001A5FCC 2000A683 */  lb         $a2, 0x20($sp)
    /* 1A6044 001A5FD0 F0FFA524 */  addiu      $a1, $a1, -0x10
    /* 1A6048 001A5FD4 2100A6A3 */  sb         $a2, 0x21($sp)
    /* 1A604C 001A5FD8 0000A68C */  lw         $a2, 0x0($a1)
    /* 1A6050 001A5FDC 0800ACC4 */  lwc1       $f12, 0x8($a1)
    /* 1A6054 001A5FE0 0400A78C */  lw         $a3, 0x4($a1)
    /* 1A6058 001A5FE4 0C00ADC4 */  lwc1       $f13, 0xC($a1)
    /* 1A605C 001A5FE8 2400A6AF */  sw         $a2, 0x24($sp)
    /* 1A6060 001A5FEC 00600844 */  mfc1       $t0, $f12
    /* 1A6064 001A5FF0 2800A7AF */  sw         $a3, 0x28($sp)
    /* 1A6068 001A5FF4 00680644 */  mfc1       $a2, $f13
    /* 1A606C 001A5FF8 2C00A8AF */  sw         $t0, 0x2C($sp)
    /* 1A6070 001A5FFC 3000A6AF */  sw         $a2, 0x30($sp)
    /* 1A6074 001A6000 0000868C */  lw         $a2, 0x0($a0)
    /* 1A6078 001A6004 08008EC4 */  lwc1       $f14, 0x8($a0)
    /* 1A607C 001A6008 0400878C */  lw         $a3, 0x4($a0)
    /* 1A6080 001A600C 0C008CC4 */  lwc1       $f12, 0xC($a0)
    /* 1A6084 001A6010 0000A6AC */  sw         $a2, 0x0($a1)
    /* 1A6088 001A6014 00700844 */  mfc1       $t0, $f14
    /* 1A608C 001A6018 0400A7AC */  sw         $a3, 0x4($a1)
    /* 1A6090 001A601C 00600644 */  mfc1       $a2, $f12
    /* 1A6094 001A6020 0800A8AC */  sw         $t0, 0x8($a1)
    /* 1A6098 001A6024 2338A400 */  subu       $a3, $a1, $a0
    /* 1A609C 001A6028 0C00A6AC */  sw         $a2, 0xC($a1)
    /* 1A60A0 001A602C 03290700 */  sra        $a1, $a3, 4
    /* 1A60A4 001A6030 022F0500 */  srl        $a1, $a1, 28
    /* 1A60A8 001A6034 2130E500 */  addu       $a2, $a3, $a1
    /* 1A60AC 001A6038 2100A883 */  lb         $t0, 0x21($sp)
    /* 1A60B0 001A603C 03310600 */  sra        $a2, $a2, 4
    /* 1A60B4 001A6040 2400A727 */  addiu      $a3, $sp, 0x24
    /* 1A60B8 001A6044 3400BFAF */  sw         $ra, 0x34($sp)
    /* 1A60BC 001A6048 5897060C */  jal        func_001A5D60
    /* 1A60C0 001A604C 25280000 */   or        $a1, $zero, $zero
    /* 1A60C4 001A6050 3400BF8F */  lw         $ra, 0x34($sp)
    /* 1A60C8 001A6054 0800E003 */  jr         $ra
    /* 1A60CC 001A6058 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel func_001A5FBC
