.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00151A10, 0x168

glabel func_00151A10
    /* 151A84 00151A10 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 151A88 00151A14 0800868C */  lw         $a2, 0x8($a0)
    /* 151A8C 00151A18 0000878C */  lw         $a3, 0x0($a0)
    /* 151A90 00151A1C 2330C700 */  subu       $a2, $a2, $a3
    /* 151A94 00151A20 83380600 */  sra        $a3, $a2, 2
    /* 151A98 00151A24 823F0700 */  srl        $a3, $a3, 30
    /* 151A9C 00151A28 2130C700 */  addu       $a2, $a2, $a3
    /* 151AA0 00151A2C 83300600 */  sra        $a2, $a2, 2
    /* 151AA4 00151A30 2400B0AF */  sw         $s0, 0x24($sp)
    /* 151AA8 00151A34 25808000 */  or         $s0, $a0, $zero
    /* 151AAC 00151A38 2B30C500 */  sltu       $a2, $a2, $a1
    /* 151AB0 00151A3C 2800B1AF */  sw         $s1, 0x28($sp)
    /* 151AB4 00151A40 2C00B2AF */  sw         $s2, 0x2C($sp)
    /* 151AB8 00151A44 3000B3AF */  sw         $s3, 0x30($sp)
    /* 151ABC 00151A48 3400B4AF */  sw         $s4, 0x34($sp)
    /* 151AC0 00151A4C 3800B5AF */  sw         $s5, 0x38($sp)
    /* 151AC4 00151A50 3C00BFAF */  sw         $ra, 0x3C($sp)
    /* 151AC8 00151A54 3F00C010 */  beqz       $a2, .Leboot_00151B54
    /* 151ACC 00151A58 2588A000 */   or        $s1, $a1, $zero
    /* 151AD0 00151A5C 0400048E */  lw         $a0, 0x4($s0)
    /* 151AD4 00151A60 0000058E */  lw         $a1, 0x0($s0)
    /* 151AD8 00151A64 23208500 */  subu       $a0, $a0, $a1
    /* 151ADC 00151A68 83300400 */  sra        $a2, $a0, 2
    /* 151AE0 00151A6C 82370600 */  srl        $a2, $a2, 30
    /* 151AE4 00151A70 21908600 */  addu       $s2, $a0, $a2
    /* 151AE8 00151A74 2500A010 */  beqz       $a1, .Leboot_00151B0C
    /* 151AEC 00151A78 83901200 */   sra       $s2, $s2, 2
    /* 151AF0 00151A7C 0000138E */  lw         $s3, 0x0($s0)
    /* 151AF4 00151A80 0400148E */  lw         $s4, 0x4($s0)
    /* 151AF8 00151A84 0A002012 */  beqz       $s1, .Leboot_00151AB0
    /* 151AFC 00151A88 00001534 */   ori       $s5, $zero, 0x0
    /* 151B00 00151A8C 80201100 */  sll        $a0, $s1, 2
    /* 151B04 00151A90 70C5040C */  jal        func_001315C0
    /* 151B08 00151A94 2000A4AF */   sw        $a0, 0x20($sp)
    /* 151B0C 00151A98 25A84000 */  or         $s5, $v0, $zero
    /* 151B10 00151A9C 0400A016 */  bnez       $s5, .Leboot_00151AB0
    /* 151B14 00151AA0 2000A48F */   lw        $a0, 0x20($sp)
    /* 151B18 00151AA4 AB41050C */  jal        func_001506AC
    /* 151B1C 00151AA8 00000000 */   nop
    /* 151B20 00151AAC 25A84000 */  or         $s5, $v0, $zero
  .Leboot_00151AB0:
    /* 151B24 00151AB0 1200A0A3 */  sb         $zero, 0x12($sp)
    /* 151B28 00151AB4 1200A483 */  lb         $a0, 0x12($sp)
    /* 151B2C 00151AB8 1500A0A3 */  sb         $zero, 0x15($sp)
    /* 151B30 00151ABC 1000A0A3 */  sb         $zero, 0x10($sp)
    /* 151B34 00151AC0 1500A583 */  lb         $a1, 0x15($sp)
    /* 151B38 00151AC4 1100A4A3 */  sb         $a0, 0x11($sp)
    /* 151B3C 00151AC8 DE46050C */  jal        func_00151B78
    /* 151B40 00151ACC 1600A5A3 */   sb        $a1, 0x16($sp)
    /* 151B44 00151AD0 1800A2AF */  sw         $v0, 0x18($sp)
    /* 151B48 00151AD4 1800A483 */  lb         $a0, 0x18($sp)
    /* 151B4C 00151AD8 05009312 */  beq        $s4, $s3, .Leboot_00151AF0
    /* 151B50 00151ADC 1400A4A3 */   sb        $a0, 0x14($sp)
    /* 151B54 00151AE0 23309302 */  subu       $a2, $s4, $s3
    /* 151B58 00151AE4 2520A002 */  or         $a0, $s5, $zero
    /* 151B5C 00151AE8 DC0D050C */  jal        func_00143770
    /* 151B60 00151AEC 25286002 */   or        $a1, $s3, $zero
  .Leboot_00151AF0:
    /* 151B64 00151AF0 0000048E */  lw         $a0, 0x0($s0)
    /* 151B68 00151AF4 10008010 */  beqz       $a0, .Leboot_00151B38
    /* 151B6C 00151AF8 1700A0A3 */   sb        $zero, 0x17($sp)
    /* 151B70 00151AFC DDC6040C */  jal        func_00131B74
    /* 151B74 00151B00 00000000 */   nop
    /* 151B78 00151B04 0C000010 */  b          .Leboot_00151B38
    /* 151B7C 00151B08 00000000 */   nop
  .Leboot_00151B0C:
    /* 151B80 00151B0C 0A002012 */  beqz       $s1, .Leboot_00151B38
    /* 151B84 00151B10 00001534 */   ori       $s5, $zero, 0x0
    /* 151B88 00151B14 80201100 */  sll        $a0, $s1, 2
    /* 151B8C 00151B18 70C5040C */  jal        func_001315C0
    /* 151B90 00151B1C 1C00A4AF */   sw        $a0, 0x1C($sp)
    /* 151B94 00151B20 25A84000 */  or         $s5, $v0, $zero
    /* 151B98 00151B24 0400A016 */  bnez       $s5, .Leboot_00151B38
    /* 151B9C 00151B28 1C00A48F */   lw        $a0, 0x1C($sp)
    /* 151BA0 00151B2C AB41050C */  jal        func_001506AC
    /* 151BA4 00151B30 00000000 */   nop
    /* 151BA8 00151B34 25A84000 */  or         $s5, $v0, $zero
  .Leboot_00151B38:
    /* 151BAC 00151B38 80201200 */  sll        $a0, $s2, 2
    /* 151BB0 00151B3C 80281100 */  sll        $a1, $s1, 2
    /* 151BB4 00151B40 2120A402 */  addu       $a0, $s5, $a0
    /* 151BB8 00151B44 000015AE */  sw         $s5, 0x0($s0)
    /* 151BBC 00151B48 2128A502 */  addu       $a1, $s5, $a1
    /* 151BC0 00151B4C 040004AE */  sw         $a0, 0x4($s0)
    /* 151BC4 00151B50 080005AE */  sw         $a1, 0x8($s0)
  .Leboot_00151B54:
    /* 151BC8 00151B54 2400B08F */  lw         $s0, 0x24($sp)
    /* 151BCC 00151B58 2800B18F */  lw         $s1, 0x28($sp)
    /* 151BD0 00151B5C 2C00B28F */  lw         $s2, 0x2C($sp)
    /* 151BD4 00151B60 3000B38F */  lw         $s3, 0x30($sp)
    /* 151BD8 00151B64 3400B48F */  lw         $s4, 0x34($sp)
    /* 151BDC 00151B68 3800B58F */  lw         $s5, 0x38($sp)
    /* 151BE0 00151B6C 3C00BF8F */  lw         $ra, 0x3C($sp)
    /* 151BE4 00151B70 0800E003 */  jr         $ra
    /* 151BE8 00151B74 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel func_00151A10
