.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_001931F8, 0x8

glabel func_001931F8
    /* 19326C 001931F8 0800E003 */  jr         $ra
    /* 193270 001931FC 04008290 */   lbu       $v0, 0x4($a0)
endlabel func_001931F8
