.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000C8E2C, 0x8

glabel func_000C8E2C
    /* C8EA0 000C8E2C 0800E003 */  jr         $ra
    /* C8EA4 000C8E30 01000234 */   ori       $v0, $zero, 0x1
endlabel func_000C8E2C
