.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000A24E8, 0x54

glabel func_000A24E8
    /* A255C 000A24E8 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* A2560 000A24EC 1400B0AF */  sw         $s0, 0x14($sp)
    /* A2564 000A24F0 2580A000 */  or         $s0, $a1, $zero
    /* A2568 000A24F4 2000A6AF */  sw         $a2, 0x20($sp)
    /* A256C 000A24F8 2000A597 */  lhu        $a1, 0x20($sp)
    /* A2570 000A24FC FFFFA638 */  xori       $a2, $a1, 0xFFFF
    /* A2574 000A2500 2B300600 */  sltu       $a2, $zero, $a2
    /* A2578 000A2504 FF00C630 */  andi       $a2, $a2, 0xFF
    /* A257C 000A2508 1800BFAF */  sw         $ra, 0x18($sp)
    /* A2580 000A250C 0700C010 */  beqz       $a2, .Leboot_000A252C
    /* A2584 000A2510 00000000 */   nop
    /* A2588 000A2514 1000A5A7 */  sh         $a1, 0x10($sp)
    /* A258C 000A2518 238A020C */  jal        func_000A288C
    /* A2590 000A251C 1000A597 */   lhu       $a1, 0x10($sp)
    /* A2594 000A2520 25204000 */  or         $a0, $v0, $zero
    /* A2598 000A2524 A580020C */  jal        func_000A0294
    /* A259C 000A2528 25280002 */   or        $a1, $s0, $zero
  .Leboot_000A252C:
    /* A25A0 000A252C 1400B08F */  lw         $s0, 0x14($sp)
    /* A25A4 000A2530 1800BF8F */  lw         $ra, 0x18($sp)
    /* A25A8 000A2534 0800E003 */  jr         $ra
    /* A25AC 000A2538 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_000A24E8
