.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0016F7D8, 0x5C

glabel func_0016F7D8
    /* 16F84C 0016F7D8 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 16F850 0016F7DC 1400B1AF */  sw         $s1, 0x14($sp)
    /* 16F854 0016F7E0 25888000 */  or         $s1, $a0, $zero
    /* 16F858 0016F7E4 1000B0AF */  sw         $s0, 0x10($sp)
    /* 16F85C 0016F7E8 1800BFAF */  sw         $ra, 0x18($sp)
    /* 16F860 0016F7EC 0C008010 */  beqz       $a0, .Leboot_0016F820
    /* 16F864 0016F7F0 2580A000 */   or        $s0, $a1, $zero
    /* 16F868 0016F7F4 0000043C */  lui        $a0, %hi(sym_00000B34)
    /* 16F86C 0016F7F8 340B8424 */  addiu      $a0, $a0, %lo(sym_00000B34)
    /* 16F870 0016F7FC 2C0024AE */  sw         $a0, 0x2C($s1)
    /* 16F874 0016F800 25202002 */  or         $a0, $s1, $zero
    /* 16F878 0016F804 E9EE010C */  jal        func_0007BBA4
    /* 16F87C 0016F808 25280000 */   or        $a1, $zero, $zero
    /* 16F880 0016F80C 01000432 */  andi       $a0, $s0, 0x1
    /* 16F884 0016F810 03008010 */  beqz       $a0, .Leboot_0016F820
    /* 16F888 0016F814 00000000 */   nop
    /* 16F88C 0016F818 C79D040C */  jal        func_0012771C
    /* 16F890 0016F81C 25202002 */   or        $a0, $s1, $zero
  .Leboot_0016F820:
    /* 16F894 0016F820 1000B08F */  lw         $s0, 0x10($sp)
    /* 16F898 0016F824 1400B18F */  lw         $s1, 0x14($sp)
    /* 16F89C 0016F828 1800BF8F */  lw         $ra, 0x18($sp)
    /* 16F8A0 0016F82C 0800E003 */  jr         $ra
    /* 16F8A4 0016F830 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0016F7D8
