.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0018DD34, 0x8

glabel func_0018DD34
    /* 18DDA8 0018DD34 0800E003 */  jr         $ra
    /* 18DDAC 0018DD38 00008044 */   mtc1      $zero, $f0
endlabel func_0018DD34
