.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00168BA0, 0x190

glabel func_00168BA0
    /* 168C14 00168BA0 B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* 168C18 00168BA4 2800B0AF */  sw         $s0, 0x28($sp)
    /* 168C1C 00168BA8 25808000 */  or         $s0, $a0, $zero
    /* 168C20 00168BAC 0000048E */  lw         $a0, 0x0($s0)
    /* 168C24 00168BB0 3000B2AF */  sw         $s2, 0x30($sp)
    /* 168C28 00168BB4 25908000 */  or         $s2, $a0, $zero
    /* 168C2C 00168BB8 04004626 */  addiu      $a2, $s2, 0x4
    /* 168C30 00168BBC 3400B3AF */  sw         $s3, 0x34($sp)
    /* 168C34 00168BC0 0000D38C */  lw         $s3, 0x0($a2)
    /* 168C38 00168BC4 2C00B1AF */  sw         $s1, 0x2C($sp)
    /* 168C3C 00168BC8 3800B4AF */  sw         $s4, 0x38($sp)
    /* 168C40 00168BCC 3C00B5AF */  sw         $s5, 0x3C($sp)
    /* 168C44 00168BD0 4000BFAF */  sw         $ra, 0x40($sp)
    /* 168C48 00168BD4 29006012 */  beqz       $s3, .Leboot_00168C7C
    /* 168C4C 00168BD8 2588A000 */   or        $s1, $a1, $zero
    /* 168C50 00168BDC 1800B427 */  addiu      $s4, $sp, 0x18
    /* 168C54 00168BE0 1400B527 */  addiu      $s5, $sp, 0x14
    /* 168C58 00168BE4 1000A0A3 */  sb         $zero, 0x10($sp)
  .Leboot_00168BE8:
    /* 168C5C 00168BE8 1000648E */  lw         $a0, 0x10($s3)
    /* 168C60 00168BEC 0000258E */  lw         $a1, 0x0($s1)
    /* 168C64 00168BF0 1400668E */  lw         $a2, 0x14($s3)
    /* 168C68 00168BF4 0400278E */  lw         $a3, 0x4($s1)
    /* 168C6C 00168BF8 2330C400 */  subu       $a2, $a2, $a0
    /* 168C70 00168BFC 2338E500 */  subu       $a3, $a3, $a1
    /* 168C74 00168C00 1400A6AF */  sw         $a2, 0x14($sp)
    /* 168C78 00168C04 2A30E600 */  slt        $a2, $a3, $a2
    /* 168C7C 00168C08 0300C010 */  beqz       $a2, .Leboot_00168C18
    /* 168C80 00168C0C 1800A7AF */   sw        $a3, 0x18($sp)
    /* 168C84 00168C10 02000010 */  b          .Leboot_00168C1C
    /* 168C88 00168C14 0000868E */   lw        $a2, 0x0($s4)
  .Leboot_00168C18:
    /* 168C8C 00168C18 0000A68E */  lw         $a2, 0x0($s5)
  .Leboot_00168C1C:
    /* 168C90 00168C1C B90D050C */  jal        func_001436E4
    /* 168C94 00168C20 00000000 */   nop
    /* 168C98 00168C24 25204000 */  or         $a0, $v0, $zero
    /* 168C9C 00168C28 08008014 */  bnez       $a0, .Leboot_00168C4C
    /* 168CA0 00168C2C 00008428 */   slti      $a0, $a0, 0x0
    /* 168CA4 00168C30 1400A58F */  lw         $a1, 0x14($sp)
    /* 168CA8 00168C34 1800A68F */  lw         $a2, 0x18($sp)
    /* 168CAC 00168C38 FFFF0424 */  addiu      $a0, $zero, -0x1
    /* 168CB0 00168C3C 2A38A600 */  slt        $a3, $a1, $a2
    /* 168CB4 00168C40 0100E050 */  beql       $a3, $zero, .Leboot_00168C48
    /* 168CB8 00168C44 2A20C500 */   slt       $a0, $a2, $a1
  .Leboot_00168C48:
    /* 168CBC 00168C48 00008428 */  slti       $a0, $a0, 0x0
  .Leboot_00168C4C:
    /* 168CC0 00168C4C FF008430 */  andi       $a0, $a0, 0xFF
    /* 168CC4 00168C50 05008014 */  bnez       $a0, .Leboot_00168C68
    /* 168CC8 00168C54 00000000 */   nop
    /* 168CCC 00168C58 25906002 */  or         $s2, $s3, $zero
    /* 168CD0 00168C5C 08004426 */  addiu      $a0, $s2, 0x8
    /* 168CD4 00168C60 03000010 */  b          .Leboot_00168C70
    /* 168CD8 00168C64 0000938C */   lw        $s3, 0x0($a0)
  .Leboot_00168C68:
    /* 168CDC 00168C68 0C006426 */  addiu      $a0, $s3, 0xC
    /* 168CE0 00168C6C 0000938C */  lw         $s3, 0x0($a0)
  .Leboot_00168C70:
    /* 168CE4 00168C70 DDFF6056 */  bnel       $s3, $zero, .Leboot_00168BE8
    /* 168CE8 00168C74 1000A0A3 */   sb        $zero, 0x10($sp)
    /* 168CEC 00168C78 0000048E */  lw         $a0, 0x0($s0)
  .Leboot_00168C7C:
    /* 168CF0 00168C7C 21004412 */  beq        $s2, $a0, .Leboot_00168D04
    /* 168CF4 00168C80 00000000 */   nop
    /* 168CF8 00168C84 1C00A0A3 */  sb         $zero, 0x1C($sp)
    /* 168CFC 00168C88 0000248E */  lw         $a0, 0x0($s1)
    /* 168D00 00168C8C 0400268E */  lw         $a2, 0x4($s1)
    /* 168D04 00168C90 1000518E */  lw         $s1, 0x10($s2)
    /* 168D08 00168C94 1400478E */  lw         $a3, 0x14($s2)
    /* 168D0C 00168C98 2330C400 */  subu       $a2, $a2, $a0
    /* 168D10 00168C9C 2328F100 */  subu       $a1, $a3, $s1
    /* 168D14 00168CA0 2000A6AF */  sw         $a2, 0x20($sp)
    /* 168D18 00168CA4 2400A5AF */  sw         $a1, 0x24($sp)
    /* 168D1C 00168CA8 2A28A600 */  slt        $a1, $a1, $a2
    /* 168D20 00168CAC 0400A010 */  beqz       $a1, .Leboot_00168CC0
    /* 168D24 00168CB0 2000A527 */   addiu     $a1, $sp, 0x20
    /* 168D28 00168CB4 2400A527 */  addiu      $a1, $sp, 0x24
    /* 168D2C 00168CB8 02000010 */  b          .Leboot_00168CC4
    /* 168D30 00168CBC 0000A58C */   lw        $a1, 0x0($a1)
  .Leboot_00168CC0:
    /* 168D34 00168CC0 0000A58C */  lw         $a1, 0x0($a1)
  .Leboot_00168CC4:
    /* 168D38 00168CC4 2530A000 */  or         $a2, $a1, $zero
    /* 168D3C 00168CC8 B90D050C */  jal        func_001436E4
    /* 168D40 00168CCC 25282002 */   or        $a1, $s1, $zero
    /* 168D44 00168CD0 25204000 */  or         $a0, $v0, $zero
    /* 168D48 00168CD4 08008014 */  bnez       $a0, .Leboot_00168CF8
    /* 168D4C 00168CD8 00008428 */   slti      $a0, $a0, 0x0
    /* 168D50 00168CDC 2000A58F */  lw         $a1, 0x20($sp)
    /* 168D54 00168CE0 2400A68F */  lw         $a2, 0x24($sp)
    /* 168D58 00168CE4 FFFF0424 */  addiu      $a0, $zero, -0x1
    /* 168D5C 00168CE8 2A38A600 */  slt        $a3, $a1, $a2
    /* 168D60 00168CEC 0100E050 */  beql       $a3, $zero, .Leboot_00168CF4
    /* 168D64 00168CF0 2A20C500 */   slt       $a0, $a2, $a1
  .Leboot_00168CF4:
    /* 168D68 00168CF4 00008428 */  slti       $a0, $a0, 0x0
  .Leboot_00168CF8:
    /* 168D6C 00168CF8 FF008430 */  andi       $a0, $a0, 0xFF
    /* 168D70 00168CFC 02008010 */  beqz       $a0, .Leboot_00168D08
    /* 168D74 00168D00 00000000 */   nop
  .Leboot_00168D04:
    /* 168D78 00168D04 0000128E */  lw         $s2, 0x0($s0)
  .Leboot_00168D08:
    /* 168D7C 00168D08 25104002 */  or         $v0, $s2, $zero
    /* 168D80 00168D0C 2800B08F */  lw         $s0, 0x28($sp)
    /* 168D84 00168D10 2C00B18F */  lw         $s1, 0x2C($sp)
    /* 168D88 00168D14 3000B28F */  lw         $s2, 0x30($sp)
    /* 168D8C 00168D18 3400B38F */  lw         $s3, 0x34($sp)
    /* 168D90 00168D1C 3800B48F */  lw         $s4, 0x38($sp)
    /* 168D94 00168D20 3C00B58F */  lw         $s5, 0x3C($sp)
    /* 168D98 00168D24 4000BF8F */  lw         $ra, 0x40($sp)
    /* 168D9C 00168D28 0800E003 */  jr         $ra
    /* 168DA0 00168D2C 5000BD27 */   addiu     $sp, $sp, 0x50
endlabel func_00168BA0
