.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00116F18, 0x58

glabel func_00116F18
    /* 116F8C 00116F18 1C00848C */  lw         $a0, 0x1C($a0)
    /* 116F90 00116F1C 34008690 */  lbu        $a2, 0x34($a0)
    /* 116F94 00116F20 2130C500 */  addu       $a2, $a2, $a1
    /* 116F98 00116F24 1000A010 */  beqz       $a1, .Leboot_00116F68
    /* 116F9C 00116F28 340086A0 */   sb        $a2, 0x34($a0)
  .Leboot_00116F2C:
    /* 116FA0 00116F2C 34008690 */  lbu        $a2, 0x34($a0)
    /* 116FA4 00116F30 0000878C */  lw         $a3, 0x0($a0)
    /* 116FA8 00116F34 2330C500 */  subu       $a2, $a2, $a1
    /* 116FAC 00116F38 2130C600 */  addu       $a2, $a2, $a2
    /* 116FB0 00116F3C 1800888C */  lw         $t0, 0x18($a0)
    /* 116FB4 00116F40 21308600 */  addu       $a2, $a0, $a2
    /* 116FB8 00116F44 1800E78C */  lw         $a3, 0x18($a3)
    /* 116FBC 00116F48 7600C694 */  lhu        $a2, 0x76($a2)
    /* 116FC0 00116F4C FFFFA524 */  addiu      $a1, $a1, -0x1
    /* 116FC4 00116F50 2148C600 */  addu       $t1, $a2, $a2
    /* 116FC8 00116F54 2130C900 */  addu       $a2, $a2, $t1
    /* 116FCC 00116F58 80300600 */  sll        $a2, $a2, 2
    /* 116FD0 00116F5C 2130E600 */  addu       $a2, $a3, $a2
    /* 116FD4 00116F60 F2FFA014 */  bnez       $a1, .Leboot_00116F2C
    /* 116FD8 00116F64 0400C8AC */   sw        $t0, 0x4($a2)
  .Leboot_00116F68:
    /* 116FDC 00116F68 0800E003 */  jr         $ra
    /* 116FE0 00116F6C 00000000 */   nop
endlabel func_00116F18
