.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00124090, 0x44

glabel func_00124090
    /* 124104 00124090 0E00A010 */  beqz       $a1, .Leboot_001240CC
    /* 124108 00124094 00000000 */   nop
    /* 12410C 00124098 2530A000 */  or         $a2, $a1, $zero
    /* 124110 0012409C 0000C78C */  lw         $a3, 0x0($a2)
    /* 124114 001240A0 0600E010 */  beqz       $a3, .Leboot_001240BC
    /* 124118 001240A4 00000000 */   nop
  .Leboot_001240A8:
    /* 12411C 001240A8 0400C4AC */  sw         $a0, 0x4($a2)
    /* 124120 001240AC 0000C68C */  lw         $a2, 0x0($a2)
    /* 124124 001240B0 0000C78C */  lw         $a3, 0x0($a2)
    /* 124128 001240B4 FCFFE014 */  bnez       $a3, .Leboot_001240A8
    /* 12412C 001240B8 00000000 */   nop
  .Leboot_001240BC:
    /* 124130 001240BC 0C00878C */  lw         $a3, 0xC($a0)
    /* 124134 001240C0 0400C4AC */  sw         $a0, 0x4($a2)
    /* 124138 001240C4 0000C7AC */  sw         $a3, 0x0($a2)
    /* 12413C 001240C8 0C0085AC */  sw         $a1, 0xC($a0)
  .Leboot_001240CC:
    /* 124140 001240CC 0800E003 */  jr         $ra
    /* 124144 001240D0 00000000 */   nop
endlabel func_00124090
