.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0009DB2C, 0xB4

glabel func_0009DB2C
    /* 9DBA0 0009DB2C D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 9DBA4 0009DB30 1000B0AF */  sw         $s0, 0x10($sp)
    /* 9DBA8 0009DB34 1400B1AF */  sw         $s1, 0x14($sp)
    /* 9DBAC 0009DB38 25888000 */  or         $s1, $a0, $zero
    /* 9DBB0 0009DB3C 2580A000 */  or         $s0, $a1, $zero
    /* 9DBB4 0009DB40 1800B2AF */  sw         $s2, 0x18($sp)
    /* 9DBB8 0009DB44 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 9DBBC 0009DB48 2000B4AF */  sw         $s4, 0x20($sp)
    /* 9DBC0 0009DB4C 2400BFAF */  sw         $ra, 0x24($sp)
    /* 9DBC4 0009DB50 4000248E */  lw         $a0, 0x40($s1)
    /* 9DBC8 0009DB54 00001334 */  ori        $s3, $zero, 0x0
    /* 9DBCC 0009DB58 0000948C */  lw         $s4, 0x0($a0)
    /* 9DBD0 0009DB5C 2A207402 */  slt        $a0, $s3, $s4
    /* 9DBD4 0009DB60 16008010 */  beqz       $a0, .Leboot_0009DBBC
    /* 9DBD8 0009DB64 00001234 */   ori       $s2, $zero, 0x0
  .Leboot_0009DB68:
    /* 9DBDC 0009DB68 4000248E */  lw         $a0, 0x40($s1)
    /* 9DBE0 0009DB6C 0400858C */  lw         $a1, 0x4($a0)
    /* 9DBE4 0009DB70 04008424 */  addiu      $a0, $a0, 0x4
    /* 9DBE8 0009DB74 21208500 */  addu       $a0, $a0, $a1
    /* 9DBEC 0009DB78 21209200 */  addu       $a0, $a0, $s2
    /* 9DBF0 0009DB7C 0000868C */  lw         $a2, 0x0($a0)
    /* 9DBF4 0009DB80 25280002 */  or         $a1, $s0, $zero
    /* 9DBF8 0009DB84 610E050C */  jal        func_00143984
    /* 9DBFC 0009DB88 21208600 */   addu      $a0, $a0, $a2
    /* 9DC00 0009DB8C 07004014 */  bnez       $v0, .Leboot_0009DBAC
    /* 9DC04 0009DB90 00000000 */   nop
    /* 9DC08 0009DB94 80211300 */  sll        $a0, $s3, 6
    /* 9DC0C 0009DB98 4800228E */  lw         $v0, 0x48($s1)
    /* 9DC10 0009DB9C 21288400 */  addu       $a1, $a0, $a0
    /* 9DC14 0009DBA0 21208500 */  addu       $a0, $a0, $a1
    /* 9DC18 0009DBA4 06000010 */  b          .Leboot_0009DBC0
    /* 9DC1C 0009DBA8 21104400 */   addu      $v0, $v0, $a0
  .Leboot_0009DBAC:
    /* 9DC20 0009DBAC 01007326 */  addiu      $s3, $s3, 0x1
    /* 9DC24 0009DBB0 2A207402 */  slt        $a0, $s3, $s4
    /* 9DC28 0009DBB4 ECFF8014 */  bnez       $a0, .Leboot_0009DB68
    /* 9DC2C 0009DBB8 A0005226 */   addiu     $s2, $s2, 0xA0
  .Leboot_0009DBBC:
    /* 9DC30 0009DBBC 25100000 */  or         $v0, $zero, $zero
  .Leboot_0009DBC0:
    /* 9DC34 0009DBC0 1000B08F */  lw         $s0, 0x10($sp)
    /* 9DC38 0009DBC4 1400B18F */  lw         $s1, 0x14($sp)
    /* 9DC3C 0009DBC8 1800B28F */  lw         $s2, 0x18($sp)
    /* 9DC40 0009DBCC 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 9DC44 0009DBD0 2000B48F */  lw         $s4, 0x20($sp)
    /* 9DC48 0009DBD4 2400BF8F */  lw         $ra, 0x24($sp)
    /* 9DC4C 0009DBD8 0800E003 */  jr         $ra
    /* 9DC50 0009DBDC 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_0009DB2C
