.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_001669B0, 0x1C

glabel func_001669B0
    /* 166A24 001669B0 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 166A28 001669B4 1000BFAF */  sw         $ra, 0x10($sp)
    /* 166A2C 001669B8 739A050C */  jal        func_001669CC
    /* 166A30 001669BC 0400858C */   lw        $a1, 0x4($a0)
    /* 166A34 001669C0 1000BF8F */  lw         $ra, 0x10($sp)
    /* 166A38 001669C4 0800E003 */  jr         $ra
    /* 166A3C 001669C8 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_001669B0
