.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000A85D0, 0xD0

glabel func_000A85D0
    /* A8644 000A85D0 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* A8648 000A85D4 4800868C */  lw         $a2, 0x48($a0)
    /* A864C 000A85D8 1400B1AF */  sw         $s1, 0x14($sp)
    /* A8650 000A85DC 25888000 */  or         $s1, $a0, $zero
    /* A8654 000A85E0 1000B0AF */  sw         $s0, 0x10($sp)
    /* A8658 000A85E4 1800B2AF */  sw         $s2, 0x18($sp)
    /* A865C 000A85E8 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* A8660 000A85EC 2000B4AF */  sw         $s4, 0x20($sp)
    /* A8664 000A85F0 2400B5AF */  sw         $s5, 0x24($sp)
    /* A8668 000A85F4 2800B6AF */  sw         $s6, 0x28($sp)
    /* A866C 000A85F8 2C00BFAF */  sw         $ra, 0x2C($sp)
    /* A8670 000A85FC 1E00C010 */  beqz       $a2, .Leboot_000A8678
    /* A8674 000A8600 2580A000 */   or        $s0, $a1, $zero
    /* A8678 000A8604 0700043C */  lui        $a0, %hi(sym_00073FBC)
    /* A867C 000A8608 BC3F968C */  lw         $s6, %lo(sym_00073FBC)($a0)
    /* A8680 000A860C 0800048E */  lw         $a0, 0x8($s0)
    /* A8684 000A8610 25A80002 */  or         $s5, $s0, $zero
    /* A8688 000A8614 1800A412 */  beq        $s5, $a0, .Leboot_000A8678
    /* A868C 000A8618 00000000 */   nop
  .Leboot_000A861C:
    /* A8690 000A861C 0000A596 */  lhu        $a1, 0x0($s5)
    /* A8694 000A8620 D874030C */  jal        func_000DD360
    /* A8698 000A8624 2520C002 */   or        $a0, $s6, $zero
    /* A869C 000A8628 4800248E */  lw         $a0, 0x48($s1)
    /* A86A0 000A862C 01001334 */  ori        $s3, $zero, 0x1
    /* A86A4 000A8630 2A206402 */  slt        $a0, $s3, $a0
    /* A86A8 000A8634 0C008010 */  beqz       $a0, .Leboot_000A8668
    /* A86AC 000A8638 25A04000 */   or        $s4, $v0, $zero
    /* A86B0 000A863C 04001234 */  ori        $s2, $zero, 0x4
  .Leboot_000A8640:
    /* A86B4 000A8640 4400258E */  lw         $a1, 0x44($s1)
    /* A86B8 000A8644 25208002 */  or         $a0, $s4, $zero
    /* A86BC 000A8648 2128B200 */  addu       $a1, $a1, $s2
    /* A86C0 000A864C F37F020C */  jal        func_0009FFCC
    /* A86C4 000A8650 0000A58C */   lw        $a1, 0x0($a1)
    /* A86C8 000A8654 4800248E */  lw         $a0, 0x48($s1)
    /* A86CC 000A8658 01007326 */  addiu      $s3, $s3, 0x1
    /* A86D0 000A865C 2A206402 */  slt        $a0, $s3, $a0
    /* A86D4 000A8660 F7FF8014 */  bnez       $a0, .Leboot_000A8640
    /* A86D8 000A8664 04005226 */   addiu     $s2, $s2, 0x4
  .Leboot_000A8668:
    /* A86DC 000A8668 0800048E */  lw         $a0, 0x8($s0)
    /* A86E0 000A866C 0200B526 */  addiu      $s5, $s5, 0x2
    /* A86E4 000A8670 EAFFA416 */  bne        $s5, $a0, .Leboot_000A861C
    /* A86E8 000A8674 00000000 */   nop
  .Leboot_000A8678:
    /* A86EC 000A8678 1000B08F */  lw         $s0, 0x10($sp)
    /* A86F0 000A867C 1400B18F */  lw         $s1, 0x14($sp)
    /* A86F4 000A8680 1800B28F */  lw         $s2, 0x18($sp)
    /* A86F8 000A8684 1C00B38F */  lw         $s3, 0x1C($sp)
    /* A86FC 000A8688 2000B48F */  lw         $s4, 0x20($sp)
    /* A8700 000A868C 2400B58F */  lw         $s5, 0x24($sp)
    /* A8704 000A8690 2800B68F */  lw         $s6, 0x28($sp)
    /* A8708 000A8694 2C00BF8F */  lw         $ra, 0x2C($sp)
    /* A870C 000A8698 0800E003 */  jr         $ra
    /* A8710 000A869C 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_000A85D0
