.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000BAA24, 0x48

glabel func_000BAA24
    /* BAA98 000BAA24 2400868C */  lw         $a2, 0x24($a0)
    /* BAA9C 000BAA28 0200A730 */  andi       $a3, $a1, 0x2
    /* BAAA0 000BAA2C 2528C500 */  or         $a1, $a2, $a1
    /* BAAA4 000BAA30 0C00E010 */  beqz       $a3, .Leboot_000BAA64
    /* BAAA8 000BAA34 240085AC */   sw        $a1, 0x24($a0)
    /* BAAAC 000BAA38 0000858C */  lw         $a1, 0x0($a0)
    /* BAAB0 000BAA3C 2B300500 */  sltu       $a2, $zero, $a1
    /* BAAB4 000BAA40 FF00C630 */  andi       $a2, $a2, 0xFF
    /* BAAB8 000BAA44 0700C010 */  beqz       $a2, .Leboot_000BAA64
    /* BAABC 000BAA48 00000000 */   nop
    /* BAAC0 000BAA4C 0400868C */  lw         $a2, 0x4($a0)
    /* BAAC4 000BAA50 0000C5AC */  sw         $a1, 0x0($a2)
    /* BAAC8 000BAA54 0400868C */  lw         $a2, 0x4($a0)
    /* BAACC 000BAA58 0400A6AC */  sw         $a2, 0x4($a1)
    /* BAAD0 000BAA5C 000080AC */  sw         $zero, 0x0($a0)
    /* BAAD4 000BAA60 040080AC */  sw         $zero, 0x4($a0)
  .Leboot_000BAA64:
    /* BAAD8 000BAA64 0800E003 */  jr         $ra
    /* BAADC 000BAA68 00000000 */   nop
endlabel func_000BAA24
