.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000DF56C, 0x4C

glabel func_000DF56C
    /* DF5E0 000DF56C 0C008624 */  addiu      $a2, $a0, 0xC
    /* DF5E4 000DF570 00008CC4 */  lwc1       $f12, 0x0($a0)
    /* DF5E8 000DF574 0000CDC4 */  lwc1       $f13, 0x0($a2)
    /* DF5EC 000DF578 04008EC4 */  lwc1       $f14, 0x4($a0)
    /* DF5F0 000DF57C 0400CFC4 */  lwc1       $f15, 0x4($a2)
    /* DF5F4 000DF580 00630D46 */  add.s      $f12, $f12, $f13
    /* DF5F8 000DF584 080090C4 */  lwc1       $f16, 0x8($a0)
    /* DF5FC 000DF588 0800D1C4 */  lwc1       $f17, 0x8($a2)
    /* DF600 000DF58C 80730F46 */  add.s      $f14, $f14, $f15
    /* DF604 000DF590 003F043C */  lui        $a0, (0x3F000000 >> 16)
    /* DF608 000DF594 00841146 */  add.s      $f16, $f16, $f17
    /* DF60C 000DF598 00908444 */  mtc1       $a0, $f18
    /* DF610 000DF59C 02631246 */  mul.s      $f12, $f12, $f18
    /* DF614 000DF5A0 42731246 */  mul.s      $f13, $f14, $f18
    /* DF618 000DF5A4 02841246 */  mul.s      $f16, $f16, $f18
    /* DF61C 000DF5A8 0000ACE4 */  swc1       $f12, 0x0($a1)
    /* DF620 000DF5AC 0400ADE4 */  swc1       $f13, 0x4($a1)
    /* DF624 000DF5B0 0800E003 */  jr         $ra
    /* DF628 000DF5B4 0800B0E4 */   swc1      $f16, 0x8($a1)
endlabel func_000DF56C
