.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0002A708, 0x114

glabel func_0002A708
    /* 2A77C 0002A708 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 2A780 0002A70C 1D00053C */  lui        $a1, %hi(sym_001D3244)
    /* 2A784 0002A710 1400B1AF */  sw         $s1, 0x14($sp)
    /* 2A788 0002A714 4432B18C */  lw         $s1, %lo(sym_001D3244)($a1)
    /* 2A78C 0002A718 1000B0AF */  sw         $s0, 0x10($sp)
    /* 2A790 0002A71C 1800B2AF */  sw         $s2, 0x18($sp)
    /* 2A794 0002A720 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 2A798 0002A724 2000B4AF */  sw         $s4, 0x20($sp)
    /* 2A79C 0002A728 2400B5AF */  sw         $s5, 0x24($sp)
    /* 2A7A0 0002A72C 2800B6AF */  sw         $s6, 0x28($sp)
    /* 2A7A4 0002A730 2C00BFAF */  sw         $ra, 0x2C($sp)
    /* 2A7A8 0002A734 03002016 */  bnez       $s1, .Leboot_0002A744
    /* 2A7AC 0002A738 25808000 */   or        $s0, $a0, $zero
    /* 2A7B0 0002A73C 2D000010 */  b          .Leboot_0002A7F4
    /* 2A7B4 0002A740 00000000 */   nop
  .Leboot_0002A744:
    /* 2A7B8 0002A744 10001226 */  addiu      $s2, $s0, 0x10
    /* 2A7BC 0002A748 0400458E */  lw         $a1, 0x4($s2)
    /* 2A7C0 0002A74C 0000448E */  lw         $a0, 0x0($s2)
    /* 2A7C4 0002A750 24001434 */  ori        $s4, $zero, 0x24
    /* 2A7C8 0002A754 2328A400 */  subu       $a1, $a1, $a0
    /* 2A7CC 0002A758 1A00B400 */  div        $zero, $a1, $s4
    /* 2A7D0 0002A75C 12280000 */  mflo       $a1
    /* 2A7D4 0002A760 2400A010 */  beqz       $a1, .Leboot_0002A7F4
    /* 2A7D8 0002A764 00001334 */   ori       $s3, $zero, 0x0
    /* 2A7DC 0002A768 04001634 */  ori        $s6, $zero, 0x4
    /* 2A7E0 0002A76C 00001534 */  ori        $s5, $zero, 0x0
  .Leboot_0002A770:
    /* 2A7E4 0002A770 21209500 */  addu       $a0, $a0, $s5
    /* 2A7E8 0002A774 0000858C */  lw         $a1, 0x0($a0)
    /* 2A7EC 0002A778 25202002 */  or         $a0, $s1, $zero
    /* 2A7F0 0002A77C 25300002 */  or         $a2, $s0, $zero
    /* 2A7F4 0002A780 2BA5000C */  jal        func_000294AC
    /* 2A7F8 0002A784 25380000 */   or        $a3, $zero, $zero
    /* 2A7FC 0002A788 0000448E */  lw         $a0, 0x0($s2)
    /* 2A800 0002A78C 01000534 */  ori        $a1, $zero, 0x1
    /* 2A804 0002A790 21309500 */  addu       $a2, $a0, $s5
    /* 2A808 0002A794 0000C48C */  lw         $a0, 0x0($a2)
    /* 2A80C 0002A798 0800C624 */  addiu      $a2, $a2, 0x8
  .Leboot_0002A79C:
    /* 2A810 0002A79C 0000C78C */  lw         $a3, 0x0($a2)
    /* 2A814 0002A7A0 0400E410 */  beq        $a3, $a0, .Leboot_0002A7B4
    /* 2A818 0002A7A4 0100A524 */   addiu     $a1, $a1, 0x1
    /* 2A81C 0002A7A8 06000010 */  b          .Leboot_0002A7C4
    /* 2A820 0002A7AC 2528E000 */   or        $a1, $a3, $zero
    /* 2A824 0002A7B0 0100A524 */  addiu      $a1, $a1, 0x1
  .Leboot_0002A7B4:
    /* 2A828 0002A7B4 F9FFB614 */  bne        $a1, $s6, .Leboot_0002A79C
    /* 2A82C 0002A7B8 0800C624 */   addiu     $a2, $a2, 0x8
    /* 2A830 0002A7BC 00000734 */  ori        $a3, $zero, 0x0
    /* 2A834 0002A7C0 2528E000 */  or         $a1, $a3, $zero
  .Leboot_0002A7C4:
    /* 2A838 0002A7C4 25202002 */  or         $a0, $s1, $zero
    /* 2A83C 0002A7C8 25300002 */  or         $a2, $s0, $zero
    /* 2A840 0002A7CC 2BA5000C */  jal        func_000294AC
    /* 2A844 0002A7D0 25380000 */   or        $a3, $zero, $zero
    /* 2A848 0002A7D4 0400458E */  lw         $a1, 0x4($s2)
    /* 2A84C 0002A7D8 0000448E */  lw         $a0, 0x0($s2)
    /* 2A850 0002A7DC 2328A400 */  subu       $a1, $a1, $a0
    /* 2A854 0002A7E0 1A00B400 */  div        $zero, $a1, $s4
    /* 2A858 0002A7E4 01007326 */  addiu      $s3, $s3, 0x1
    /* 2A85C 0002A7E8 12280000 */  mflo       $a1
    /* 2A860 0002A7EC E0FF6516 */  bne        $s3, $a1, .Leboot_0002A770
    /* 2A864 0002A7F0 2400B526 */   addiu     $s5, $s5, 0x24
  .Leboot_0002A7F4:
    /* 2A868 0002A7F4 1000B08F */  lw         $s0, 0x10($sp)
    /* 2A86C 0002A7F8 1400B18F */  lw         $s1, 0x14($sp)
    /* 2A870 0002A7FC 1800B28F */  lw         $s2, 0x18($sp)
    /* 2A874 0002A800 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 2A878 0002A804 2000B48F */  lw         $s4, 0x20($sp)
    /* 2A87C 0002A808 2400B58F */  lw         $s5, 0x24($sp)
    /* 2A880 0002A80C 2800B68F */  lw         $s6, 0x28($sp)
    /* 2A884 0002A810 2C00BF8F */  lw         $ra, 0x2C($sp)
    /* 2A888 0002A814 0800E003 */  jr         $ra
    /* 2A88C 0002A818 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_0002A708
