.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0009D6B4, 0x48

glabel func_0009D6B4
    /* 9D728 0009D6B4 0900A104 */  bgez       $a1, .Leboot_0009D6DC
    /* 9D72C 0009D6B8 88008624 */   addiu     $a2, $a0, 0x88
    /* 9D730 0009D6BC 5800848C */  lw         $a0, 0x58($a0)
    /* 9D734 0009D6C0 40290400 */  sll        $a1, $a0, 5
    /* 9D738 0009D6C4 2320A400 */  subu       $a0, $a1, $a0
    /* 9D73C 0009D6C8 80200400 */  sll        $a0, $a0, 2
    /* 9D740 0009D6CC 23208500 */  subu       $a0, $a0, $a1
    /* 9D744 0009D6D0 2120C400 */  addu       $a0, $a2, $a0
    /* 9D748 0009D6D4 07000010 */  b          .Leboot_0009D6F4
    /* 9D74C 0009D6D8 0400828C */   lw        $v0, 0x4($a0)
  .Leboot_0009D6DC:
    /* 9D750 0009D6DC 40210500 */  sll        $a0, $a1, 5
    /* 9D754 0009D6E0 23288500 */  subu       $a1, $a0, $a1
    /* 9D758 0009D6E4 80280500 */  sll        $a1, $a1, 2
    /* 9D75C 0009D6E8 2320A400 */  subu       $a0, $a1, $a0
    /* 9D760 0009D6EC 2120C400 */  addu       $a0, $a2, $a0
    /* 9D764 0009D6F0 0400828C */  lw         $v0, 0x4($a0)
  .Leboot_0009D6F4:
    /* 9D768 0009D6F4 0800E003 */  jr         $ra
    /* 9D76C 0009D6F8 00000000 */   nop
endlabel func_0009D6B4
