.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0019B008, 0x64

glabel func_0019B008
    /* 19B07C 0019B008 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 19B080 0019B00C 0000868C */  lw         $a2, 0x0($a0)
    /* 19B084 0019B010 0800C624 */  addiu      $a2, $a2, 0x8
    /* 19B088 0019B014 0000C784 */  lh         $a3, 0x0($a2)
    /* 19B08C 0019B018 0400C68C */  lw         $a2, 0x4($a2)
    /* 19B090 0019B01C 28000534 */  ori        $a1, $zero, 0x28
    /* 19B094 0019B020 1000B0AF */  sw         $s0, 0x10($sp)
    /* 19B098 0019B024 1400BFAF */  sw         $ra, 0x14($sp)
    /* 19B09C 0019B028 09F8C000 */  jalr       $a2
    /* 19B0A0 0019B02C 21208700 */   addu      $a0, $a0, $a3
    /* 19B0A4 0019B030 25804000 */  or         $s0, $v0, $zero
    /* 19B0A8 0019B034 08000012 */  beqz       $s0, .Leboot_0019B058
    /* 19B0AC 0019B038 00000000 */   nop
    /* 19B0B0 0019B03C 04000012 */  beqz       $s0, .Leboot_0019B050
    /* 19B0B4 0019B040 00000434 */   ori       $a0, $zero, 0x0
    /* 19B0B8 0019B044 57F3020C */  jal        func_000BCD5C
    /* 19B0BC 0019B048 25200002 */   or        $a0, $s0, $zero
    /* 19B0C0 0019B04C 25200002 */  or         $a0, $s0, $zero
  .Leboot_0019B050:
    /* 19B0C4 0019B050 02000010 */  b          .Leboot_0019B05C
    /* 19B0C8 0019B054 25108000 */   or        $v0, $a0, $zero
  .Leboot_0019B058:
    /* 19B0CC 0019B058 25100000 */  or         $v0, $zero, $zero
  .Leboot_0019B05C:
    /* 19B0D0 0019B05C 1000B08F */  lw         $s0, 0x10($sp)
    /* 19B0D4 0019B060 1400BF8F */  lw         $ra, 0x14($sp)
    /* 19B0D8 0019B064 0800E003 */  jr         $ra
    /* 19B0DC 0019B068 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0019B008
