.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000C9CB4, 0x160

glabel func_000C9CB4
    /* C9D28 000C9CB4 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* C9D2C 000C9CB8 1000B0AF */  sw         $s0, 0x10($sp)
    /* C9D30 000C9CBC 1400BFAF */  sw         $ra, 0x14($sp)
    /* C9D34 000C9CC0 4DE7020C */  jal        func_000B9D34
    /* C9D38 000C9CC4 25808000 */   or        $s0, $a0, $zero
    /* C9D3C 000C9CC8 06004010 */  beqz       $v0, .Leboot_000C9CE4
    /* C9D40 000C9CCC 00000000 */   nop
    /* C9D44 000C9CD0 4000048E */  lw         $a0, 0x40($s0)
    /* C9D48 000C9CD4 05008014 */  bnez       $a0, .Leboot_000C9CEC
    /* C9D4C 000C9CD8 00000534 */   ori       $a1, $zero, 0x0
    /* C9D50 000C9CDC 04000010 */  b          .Leboot_000C9CF0
    /* C9D54 000C9CE0 00000000 */   nop
  .Leboot_000C9CE4:
    /* C9D58 000C9CE4 47000010 */  b          .Leboot_000C9E04
    /* C9D5C 000C9CE8 25100000 */   or        $v0, $zero, $zero
  .Leboot_000C9CEC:
    /* C9D60 000C9CEC 90FF8524 */  addiu      $a1, $a0, -0x70
  .Leboot_000C9CF0:
    /* C9D64 000C9CF0 4300A010 */  beqz       $a1, .Leboot_000C9E00
    /* C9D68 000C9CF4 00000000 */   nop
    /* C9D6C 000C9CF8 00000534 */  ori        $a1, $zero, 0x0
    /* C9D70 000C9CFC 01008054 */  bnel       $a0, $zero, .Leboot_000C9D04
    /* C9D74 000C9D00 90FF8524 */   addiu     $a1, $a0, -0x70
  .Leboot_000C9D04:
    /* C9D78 000C9D04 0000068E */  lw         $a2, 0x0($s0)
    /* C9D7C 000C9D08 2520A000 */  or         $a0, $a1, $zero
    /* C9D80 000C9D0C 4C00C524 */  addiu      $a1, $a2, 0x4C
    /* C9D84 000C9D10 F61F030C */  jal        func_000C7FD8
    /* C9D88 000C9D14 25300000 */   or        $a2, $zero, $zero
    /* C9D8C 000C9D18 25200002 */  or         $a0, $s0, $zero
    /* C9D90 000C9D1C 9BE8020C */  jal        func_000BA26C
    /* C9D94 000C9D20 03000534 */   ori       $a1, $zero, 0x3
    /* C9D98 000C9D24 05004014 */  bnez       $v0, .Leboot_000C9D3C
    /* C9D9C 000C9D28 25200002 */   or        $a0, $s0, $zero
    /* C9DA0 000C9D2C 9BE8020C */  jal        func_000BA26C
    /* C9DA4 000C9D30 04000534 */   ori       $a1, $zero, 0x4
    /* C9DA8 000C9D34 04004010 */  beqz       $v0, .Leboot_000C9D48
    /* C9DAC 000C9D38 00000000 */   nop
  .Leboot_000C9D3C:
    /* C9DB0 000C9D3C 5000048E */  lw         $a0, 0x50($s0)
    /* C9DB4 000C9D40 01008434 */  ori        $a0, $a0, 0x1
    /* C9DB8 000C9D44 500004AE */  sw         $a0, 0x50($s0)
  .Leboot_000C9D48:
    /* C9DBC 000C9D48 25200002 */  or         $a0, $s0, $zero
    /* C9DC0 000C9D4C 9BE8020C */  jal        func_000BA26C
    /* C9DC4 000C9D50 06000534 */   ori       $a1, $zero, 0x6
    /* C9DC8 000C9D54 09004014 */  bnez       $v0, .Leboot_000C9D7C
    /* C9DCC 000C9D58 25200002 */   or        $a0, $s0, $zero
    /* C9DD0 000C9D5C 9BE8020C */  jal        func_000BA26C
    /* C9DD4 000C9D60 07000534 */   ori       $a1, $zero, 0x7
    /* C9DD8 000C9D64 05004014 */  bnez       $v0, .Leboot_000C9D7C
    /* C9DDC 000C9D68 25200002 */   or        $a0, $s0, $zero
    /* C9DE0 000C9D6C 9BE8020C */  jal        func_000BA26C
    /* C9DE4 000C9D70 08000534 */   ori       $a1, $zero, 0x8
    /* C9DE8 000C9D74 04004010 */  beqz       $v0, .Leboot_000C9D88
    /* C9DEC 000C9D78 00000000 */   nop
  .Leboot_000C9D7C:
    /* C9DF0 000C9D7C 5000048E */  lw         $a0, 0x50($s0)
    /* C9DF4 000C9D80 02008434 */  ori        $a0, $a0, 0x2
    /* C9DF8 000C9D84 500004AE */  sw         $a0, 0x50($s0)
  .Leboot_000C9D88:
    /* C9DFC 000C9D88 25200002 */  or         $a0, $s0, $zero
    /* C9E00 000C9D8C 9BE8020C */  jal        func_000BA26C
    /* C9E04 000C9D90 01000534 */   ori       $a1, $zero, 0x1
    /* C9E08 000C9D94 4000048E */  lw         $a0, 0x40($s0)
    /* C9E0C 000C9D98 03004010 */  beqz       $v0, .Leboot_000C9DA8
    /* C9E10 000C9D9C 5000068E */   lw        $a2, 0x50($s0)
    /* C9E14 000C9DA0 0400C634 */  ori        $a2, $a2, 0x4
    /* C9E18 000C9DA4 500006AE */  sw         $a2, 0x50($s0)
  .Leboot_000C9DA8:
    /* C9E1C 000C9DA8 00000534 */  ori        $a1, $zero, 0x0
    /* C9E20 000C9DAC 01008054 */  bnel       $a0, $zero, .Leboot_000C9DB4
    /* C9E24 000C9DB0 90FF8524 */   addiu     $a1, $a0, -0x70
  .Leboot_000C9DB4:
    /* C9E28 000C9DB4 8800A794 */  lhu        $a3, 0x88($a1)
    /* C9E2C 000C9DB8 25200002 */  or         $a0, $s0, $zero
    /* C9E30 000C9DBC 2530E600 */  or         $a2, $a3, $a2
    /* C9E34 000C9DC0 8800A6A4 */  sh         $a2, 0x88($a1)
    /* C9E38 000C9DC4 9BE8020C */  jal        func_000BA26C
    /* C9E3C 000C9DC8 02000534 */   ori       $a1, $zero, 0x2
    /* C9E40 000C9DCC 0C004010 */  beqz       $v0, .Leboot_000C9E00
    /* C9E44 000C9DD0 00000000 */   nop
    /* C9E48 000C9DD4 4000048E */  lw         $a0, 0x40($s0)
    /* C9E4C 000C9DD8 00001034 */  ori        $s0, $zero, 0x0
    /* C9E50 000C9DDC 01008054 */  bnel       $a0, $zero, .Leboot_000C9DE4
    /* C9E54 000C9DE0 90FF9024 */   addiu     $s0, $a0, -0x70
  .Leboot_000C9DE4:
    /* C9E58 000C9DE4 8400058E */  lw         $a1, 0x84($s0)
    /* C9E5C 000C9DE8 0010043C */  lui        $a0, (0x10000000 >> 16)
    /* C9E60 000C9DEC 2730A000 */  not        $a2, $a1
    /* C9E64 000C9DF0 24208600 */  and        $a0, $a0, $a2
    /* C9E68 000C9DF4 2528A400 */  or         $a1, $a1, $a0
    /* C9E6C 000C9DF8 B37D030C */  jal        func_000DF6CC
    /* C9E70 000C9DFC 25200002 */   or        $a0, $s0, $zero
  .Leboot_000C9E00:
    /* C9E74 000C9E00 01000234 */  ori        $v0, $zero, 0x1
  .Leboot_000C9E04:
    /* C9E78 000C9E04 1000B08F */  lw         $s0, 0x10($sp)
    /* C9E7C 000C9E08 1400BF8F */  lw         $ra, 0x14($sp)
    /* C9E80 000C9E0C 0800E003 */  jr         $ra
    /* C9E84 000C9E10 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_000C9CB4
