.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000F680C, 0x88

glabel func_000F680C
    /* F6880 000F680C E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* F6884 000F6810 1400B0AF */  sw         $s0, 0x14($sp)
    /* F6888 000F6814 25808000 */  or         $s0, $a0, $zero
    /* F688C 000F6818 1000B4E7 */  swc1       $f20, 0x10($sp)
    /* F6890 000F681C 1800B1AF */  sw         $s1, 0x18($sp)
    /* F6894 000F6820 1C00BFAF */  sw         $ra, 0x1C($sp)
    /* F6898 000F6824 6B3F040C */  jal        func_0010FDAC
    /* F689C 000F6828 02000534 */   ori       $a1, $zero, 0x2
    /* F68A0 000F682C 25884000 */  or         $s1, $v0, $zero
    /* F68A4 000F6830 25200002 */  or         $a0, $s0, $zero
    /* F68A8 000F6834 2F3F040C */  jal        func_0010FCBC
    /* F68AC 000F6838 03000534 */   ori       $a1, $zero, 0x3
    /* F68B0 000F683C 06050046 */  mov.s      $f20, $f0
    /* F68B4 000F6840 998F040C */  jal        func_00123E64
    /* F68B8 000F6844 25202002 */   or        $a0, $s1, $zero
    /* F68BC 000F6848 25204000 */  or         $a0, $v0, $zero
    /* F68C0 000F684C 06008010 */  beqz       $a0, .Leboot_000F6868
    /* F68C4 000F6850 00000000 */   nop
    /* F68C8 000F6854 0DA30046 */  trunc.w.s  $f12, $f20
    /* F68CC 000F6858 818E040C */  jal        func_00123A04
    /* F68D0 000F685C 00600544 */   mfc1      $a1, $f12
    /* F68D4 000F6860 06000010 */  b          .Leboot_000F687C
    /* F68D8 000F6864 25100000 */   or        $v0, $zero, $zero
  .Leboot_000F6868:
    /* F68DC 000F6868 1D00053C */  lui        $a1, %hi(str_attempt_to_set_unknown_debug_option_s)
    /* F68E0 000F686C 25200002 */  or         $a0, $s0, $zero
    /* F68E4 000F6870 25302002 */  or         $a2, $s1, $zero
    /* F68E8 000F6874 801E040C */  jal        func_00107A00
    /* F68EC 000F6878 70BCA524 */   addiu     $a1, $a1, %lo(str_attempt_to_set_unknown_debug_option_s)
  .Leboot_000F687C:
    /* F68F0 000F687C 1000B4C7 */  lwc1       $f20, 0x10($sp)
    /* F68F4 000F6880 1400B08F */  lw         $s0, 0x14($sp)
    /* F68F8 000F6884 1800B18F */  lw         $s1, 0x18($sp)
    /* F68FC 000F6888 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* F6900 000F688C 0800E003 */  jr         $ra
    /* F6904 000F6890 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_000F680C
