.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0010D4DC, 0xB0

glabel func_0010D4DC
    /* 10D550 0010D4DC D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 10D554 0010D4E0 2540E000 */  or         $t0, $a3, $zero
    /* 10D558 0010D4E4 0C00878C */  lw         $a3, 0xC($a0)
    /* 10D55C 0010D4E8 2548C000 */  or         $t1, $a2, $zero
    /* 10D560 0010D4EC 2530A000 */  or         $a2, $a1, $zero
    /* 10D564 0010D4F0 2000B0AF */  sw         $s0, 0x20($sp)
    /* 10D568 0010D4F4 25808000 */  or         $s0, $a0, $zero
    /* 10D56C 0010D4F8 2000EA28 */  slti       $t2, $a3, 0x20
    /* 10D570 0010D4FC 25282001 */  or         $a1, $t1, $zero
    /* 10D574 0010D500 2400BFAF */  sw         $ra, 0x24($sp)
    /* 10D578 0010D504 0D004015 */  bnez       $t2, .Leboot_0010D53C
    /* 10D57C 0010D508 25200001 */   or        $a0, $t0, $zero
    /* 10D580 0010D50C 1C00A6AF */  sw         $a2, 0x1C($sp)
    /* 10D584 0010D510 1800A5AF */  sw         $a1, 0x18($sp)
    /* 10D588 0010D514 1400A4AF */  sw         $a0, 0x14($sp)
    /* 10D58C 0010D518 0800048E */  lw         $a0, 0x8($s0)
    /* 10D590 0010D51C 1D00053C */  lui        $a1, %hi(str_too_many_captures)
    /* 10D594 0010D520 1000A7AF */  sw         $a3, 0x10($sp)
    /* 10D598 0010D524 801E040C */  jal        func_00107A00
    /* 10D59C 0010D528 E0E1A524 */   addiu     $a1, $a1, %lo(str_too_many_captures)
    /* 10D5A0 0010D52C 1000A78F */  lw         $a3, 0x10($sp)
    /* 10D5A4 0010D530 1400A48F */  lw         $a0, 0x14($sp)
    /* 10D5A8 0010D534 1800A58F */  lw         $a1, 0x18($sp)
    /* 10D5AC 0010D538 1C00A68F */  lw         $a2, 0x1C($sp)
  .Leboot_0010D53C:
    /* 10D5B0 0010D53C 2540A000 */  or         $t0, $a1, $zero
    /* 10D5B4 0010D540 C0280700 */  sll        $a1, $a3, 3
    /* 10D5B8 0010D544 21280502 */  addu       $a1, $s0, $a1
    /* 10D5BC 0010D548 1000A6AC */  sw         $a2, 0x10($a1)
    /* 10D5C0 0010D54C 1400A4AC */  sw         $a0, 0x14($a1)
    /* 10D5C4 0010D550 0100E424 */  addiu      $a0, $a3, 0x1
    /* 10D5C8 0010D554 0C0004AE */  sw         $a0, 0xC($s0)
    /* 10D5CC 0010D558 2528C000 */  or         $a1, $a2, $zero
    /* 10D5D0 0010D55C 25200002 */  or         $a0, $s0, $zero
    /* 10D5D4 0010D560 E838040C */  jal        func_0010E3A0
    /* 10D5D8 0010D564 25300001 */   or        $a2, $t0, $zero
    /* 10D5DC 0010D568 04004014 */  bnez       $v0, .Leboot_0010D57C
    /* 10D5E0 0010D56C 00000000 */   nop
    /* 10D5E4 0010D570 0C00048E */  lw         $a0, 0xC($s0)
    /* 10D5E8 0010D574 FFFF8424 */  addiu      $a0, $a0, -0x1
    /* 10D5EC 0010D578 0C0004AE */  sw         $a0, 0xC($s0)
  .Leboot_0010D57C:
    /* 10D5F0 0010D57C 2000B08F */  lw         $s0, 0x20($sp)
    /* 10D5F4 0010D580 2400BF8F */  lw         $ra, 0x24($sp)
    /* 10D5F8 0010D584 0800E003 */  jr         $ra
    /* 10D5FC 0010D588 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_0010D4DC
