.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000475FC, 0x30

glabel func_000475FC
    /* 47670 000475FC E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 47674 00047600 1000BFAF */  sw         $ra, 0x10($sp)
    /* 47678 00047604 8143040C */  jal        func_00110E04
    /* 4767C 00047608 01000534 */   ori       $a1, $zero, 0x1
    /* 47680 0004760C 03004010 */  beqz       $v0, .Leboot_0004761C
    /* 47684 00047610 00000000 */   nop
    /* 47688 00047614 02000010 */  b          .Leboot_00047620
    /* 4768C 00047618 02000234 */   ori       $v0, $zero, 0x2
  .Leboot_0004761C:
    /* 47690 0004761C 25100000 */  or         $v0, $zero, $zero
  .Leboot_00047620:
    /* 47694 00047620 1000BF8F */  lw         $ra, 0x10($sp)
    /* 47698 00047624 0800E003 */  jr         $ra
    /* 4769C 00047628 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_000475FC
