.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000C82CC, 0x3C

glabel func_000C82CC
    /* C8340 000C82CC C401858C */  lw         $a1, 0x1C4($a0)
    /* C8344 000C82D0 00000634 */  ori        $a2, $zero, 0x0
    /* C8348 000C82D4 2A28C500 */  slt        $a1, $a2, $a1
    /* C834C 000C82D8 0900A010 */  beqz       $a1, .Leboot_000C8300
    /* C8350 000C82DC 00000534 */   ori       $a1, $zero, 0x0
  .Leboot_000C82E0:
    /* C8354 000C82E0 C801878C */  lw         $a3, 0x1C8($a0)
    /* C8358 000C82E4 0100C624 */  addiu      $a2, $a2, 0x1
    /* C835C 000C82E8 2138E500 */  addu       $a3, $a3, $a1
    /* C8360 000C82EC E000ECE4 */  swc1       $f12, 0xE0($a3)
    /* C8364 000C82F0 C401878C */  lw         $a3, 0x1C4($a0)
    /* C8368 000C82F4 2A38C700 */  slt        $a3, $a2, $a3
    /* C836C 000C82F8 F9FFE014 */  bnez       $a3, .Leboot_000C82E0
    /* C8370 000C82FC 6001A524 */   addiu     $a1, $a1, 0x160
  .Leboot_000C8300:
    /* C8374 000C8300 0800E003 */  jr         $ra
    /* C8378 000C8304 00000000 */   nop
endlabel func_000C82CC
