.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000BC4D4, 0x120

glabel func_000BC4D4
    /* BC548 000BC4D4 B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* BC54C 000BC4D8 4000B1AF */  sw         $s1, 0x40($sp)
    /* BC550 000BC4DC 25888000 */  or         $s1, $a0, $zero
    /* BC554 000BC4E0 2400248E */  lw         $a0, 0x24($s1)
    /* BC558 000BC4E4 3C00B0AF */  sw         $s0, 0x3C($sp)
    /* BC55C 000BC4E8 4400B2AF */  sw         $s2, 0x44($sp)
    /* BC560 000BC4EC 4800B3AF */  sw         $s3, 0x48($sp)
    /* BC564 000BC4F0 4C00BFAF */  sw         $ra, 0x4C($sp)
    /* BC568 000BC4F4 07008010 */  beqz       $a0, .Leboot_000BC514
    /* BC56C 000BC4F8 2580A000 */   or        $s0, $a1, $zero
    /* BC570 000BC4FC 0040053C */  lui        $a1, (0x40000000 >> 16)
    /* BC574 000BC500 24280502 */  and        $a1, $s0, $a1
    /* BC578 000BC504 0500A014 */  bnez       $a1, .Leboot_000BC51C
    /* BC57C 000BC508 00000000 */   nop
    /* BC580 000BC50C 1B000010 */  b          .Leboot_000BC57C
    /* BC584 000BC510 00000000 */   nop
  .Leboot_000BC514:
    /* BC588 000BC514 30000010 */  b          .Leboot_000BC5D8
    /* BC58C 000BC518 00000000 */   nop
  .Leboot_000BC51C:
    /* BC590 000BC51C 1FD7060C */  jal        updateNodeGraph_03FC
    /* BC594 000BC520 25202002 */   or        $a0, $s1, $zero
    /* BC598 000BC524 25904000 */  or         $s2, $v0, $zero
    /* BC59C 000BC528 2C00B327 */  addiu      $s3, $sp, 0x2C
    /* BC5A0 000BC52C 25206002 */  or         $a0, $s3, $zero
    /* BC5A4 000BC530 EBAB040C */  jal        func_0012AFAC
    /* BC5A8 000BC534 25284002 */   or        $a1, $s2, $zero
    /* BC5AC 000BC538 2400248E */  lw         $a0, 0x24($s1)
    /* BC5B0 000BC53C 8401040C */  jal        func_00100610
    /* BC5B4 000BC540 25286002 */   or        $a1, $s3, $zero
    /* BC5B8 000BC544 30004426 */  addiu      $a0, $s2, 0x30
    /* BC5BC 000BC548 00008CC4 */  lwc1       $f12, 0x0($a0)
    /* BC5C0 000BC54C 2400268E */  lw         $a2, 0x24($s1)
    /* BC5C4 000BC550 1C00ACE7 */  swc1       $f12, 0x1C($sp)
    /* BC5C8 000BC554 04008CC4 */  lwc1       $f12, 0x4($a0)
    /* BC5CC 000BC558 1C00A527 */  addiu      $a1, $sp, 0x1C
    /* BC5D0 000BC55C 2000ACE7 */  swc1       $f12, 0x20($sp)
    /* BC5D4 000BC560 08008CC4 */  lwc1       $f12, 0x8($a0)
    /* BC5D8 000BC564 2400ACE7 */  swc1       $f12, 0x24($sp)
    /* BC5DC 000BC568 0C008CC4 */  lwc1       $f12, 0xC($a0)
    /* BC5E0 000BC56C 2520C000 */  or         $a0, $a2, $zero
    /* BC5E4 000BC570 9C01040C */  jal        func_00100670
    /* BC5E8 000BC574 2800ACE7 */   swc1      $f12, 0x28($sp)
    /* BC5EC 000BC578 2400248E */  lw         $a0, 0x24($s1)
  .Leboot_000BC57C:
    /* BC5F0 000BC57C 80000532 */  andi       $a1, $s0, 0x80
    /* BC5F4 000BC580 0D00A010 */  beqz       $a1, .Leboot_000BC5B8
    /* BC5F8 000BC584 0800308E */   lw        $s0, 0x8($s1)
    /* BC5FC 000BC588 3000858C */  lw         $a1, 0x30($a0)
    /* BC600 000BC58C 01000634 */  ori        $a2, $zero, 0x1
    /* BC604 000BC590 0500A614 */  bne        $a1, $a2, .Leboot_000BC5A8
    /* BC608 000BC594 1C000CC6 */   lwc1      $f12, 0x1C($s0)
    /* BC60C 000BC598 B33F053C */  lui        $a1, (0x3FB3851F >> 16)
    /* BC610 000BC59C 1F85A534 */  ori        $a1, $a1, (0x3FB3851F & 0xFFFF)
    /* BC614 000BC5A0 00688544 */  mtc1       $a1, $f13
    /* BC618 000BC5A4 02630D46 */  mul.s      $f12, $f12, $f13
  .Leboot_000BC5A8:
    /* BC61C 000BC5A8 F001040C */  jal        func_001007C0
    /* BC620 000BC5AC 00000000 */   nop
    /* BC624 000BC5B0 2400248E */  lw         $a0, 0x24($s1)
    /* BC628 000BC5B4 0800308E */  lw         $s0, 0x8($s1)
  .Leboot_000BC5B8:
    /* BC62C 000BC5B8 10000CC6 */  lwc1       $f12, 0x10($s0)
    /* BC630 000BC5BC 14000DC6 */  lwc1       $f13, 0x14($s0)
    /* BC634 000BC5C0 18000EC6 */  lwc1       $f14, 0x18($s0)
    /* BC638 000BC5C4 1000ACE7 */  swc1       $f12, 0x10($sp)
    /* BC63C 000BC5C8 1400ADE7 */  swc1       $f13, 0x14($sp)
    /* BC640 000BC5CC 1800AEE7 */  swc1       $f14, 0x18($sp)
    /* BC644 000BC5D0 B301040C */  jal        func_001006CC
    /* BC648 000BC5D4 1000A527 */   addiu     $a1, $sp, 0x10
  .Leboot_000BC5D8:
    /* BC64C 000BC5D8 3C00B08F */  lw         $s0, 0x3C($sp)
    /* BC650 000BC5DC 4000B18F */  lw         $s1, 0x40($sp)
    /* BC654 000BC5E0 4400B28F */  lw         $s2, 0x44($sp)
    /* BC658 000BC5E4 4800B38F */  lw         $s3, 0x48($sp)
    /* BC65C 000BC5E8 4C00BF8F */  lw         $ra, 0x4C($sp)
    /* BC660 000BC5EC 0800E003 */  jr         $ra
    /* BC664 000BC5F0 5000BD27 */   addiu     $sp, $sp, 0x50
endlabel func_000BC4D4
