.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0002D224, 0x230

glabel func_0002D224
    /* 2D298 0002D224 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 2D29C 0002D228 1D00043C */  lui        $a0, %hi(sym_001D33F4)
    /* 2D2A0 0002D22C F4338CC4 */  lwc1       $f12, %lo(sym_001D33F4)($a0)
    /* 2D2A4 0002D230 3443043C */  lui        $a0, (0x43340000 >> 16)
    /* 2D2A8 0002D234 00688444 */  mtc1       $a0, $f13
    /* 2D2AC 0002D238 83630D46 */  div.s      $f14, $f12, $f13
    /* 2D2B0 0002D23C 1D00073C */  lui        $a3, %hi(sym_001D33F8)
    /* 2D2B4 0002D240 7266043C */  lui        $a0, %hi(D_66727573)
    /* 2D2B8 0002D244 1D00083C */  lui        $t0, %hi(sym_001D33FC)
    /* 2D2BC 0002D248 3A000534 */  ori        $a1, $zero, 0x3A
    /* 2D2C0 0002D24C 80000634 */  ori        $a2, $zero, 0x80
    /* 2D2C4 0002D250 73758424 */  addiu      $a0, $a0, %lo(D_66727573)
    /* 2D2C8 0002D254 1000B4E7 */  swc1       $f20, 0x10($sp)
    /* 2D2CC 0002D258 1400BFAF */  sw         $ra, 0x14($sp)
    /* 2D2D0 0002D25C 036B0C46 */  div.s      $f12, $f13, $f12
    /* 2D2D4 0002D260 F833EEE4 */  swc1       $f14, %lo(sym_001D33F8)($a3)
    /* 2D2D8 0002D264 611B040C */  jal        elem_register_chunk_tag
    /* 2D2DC 0002D268 FC330CE5 */   swc1      $f12, %lo(sym_001D33FC)($t0)
    /* 2D2E0 0002D26C 1D00043C */  lui        $a0, %hi(sym_001D3400)
    /* 2D2E4 0002D270 1C00053C */  lui        $a1, %hi(str_JoystickX_2368)
    /* 2D2E8 0002D274 00348424 */  addiu      $a0, $a0, %lo(sym_001D3400)
    /* 2D2EC 0002D278 00A08044 */  mtc1       $zero, $f20
    /* 2D2F0 0002D27C 06A30046 */  mov.s      $f12, $f20
    /* 2D2F4 0002D280 31BA020C */  jal        func_000AE8C4
    /* 2D2F8 0002D284 6823A524 */   addiu     $a1, $a1, %lo(str_JoystickX_2368)
    /* 2D2FC 0002D288 1D00043C */  lui        $a0, %hi(sym_001D3404)
    /* 2D300 0002D28C 06A30046 */  mov.s      $f12, $f20
    /* 2D304 0002D290 1C00053C */  lui        $a1, %hi(str_JoystickY_2374)
    /* 2D308 0002D294 04348424 */  addiu      $a0, $a0, %lo(sym_001D3404)
    /* 2D30C 0002D298 31BA020C */  jal        func_000AE8C4
    /* 2D310 0002D29C 7423A524 */   addiu     $a1, $a1, %lo(str_JoystickY_2374)
    /* 2D314 0002D2A0 1D00043C */  lui        $a0, %hi(sym_001D3408)
    /* 2D318 0002D2A4 06A30046 */  mov.s      $f12, $f20
    /* 2D31C 0002D2A8 1C00053C */  lui        $a1, %hi(str_Button_Circle_2380)
    /* 2D320 0002D2AC 08348424 */  addiu      $a0, $a0, %lo(sym_001D3408)
    /* 2D324 0002D2B0 31BA020C */  jal        func_000AE8C4
    /* 2D328 0002D2B4 8023A524 */   addiu     $a1, $a1, %lo(str_Button_Circle_2380)
    /* 2D32C 0002D2B8 1D00043C */  lui        $a0, %hi(sym_001D340C)
    /* 2D330 0002D2BC 06A30046 */  mov.s      $f12, $f20
    /* 2D334 0002D2C0 1C00053C */  lui        $a1, %hi(str_Button_Square_2390)
    /* 2D338 0002D2C4 0C348424 */  addiu      $a0, $a0, %lo(sym_001D340C)
    /* 2D33C 0002D2C8 31BA020C */  jal        func_000AE8C4
    /* 2D340 0002D2CC 9023A524 */   addiu     $a1, $a1, %lo(str_Button_Square_2390)
    /* 2D344 0002D2D0 1D00043C */  lui        $a0, %hi(sym_001D3410)
    /* 2D348 0002D2D4 06A30046 */  mov.s      $f12, $f20
    /* 2D34C 0002D2D8 1C00053C */  lui        $a1, %hi(str_Button_Triangle_23A0)
    /* 2D350 0002D2DC 10348424 */  addiu      $a0, $a0, %lo(sym_001D3410)
    /* 2D354 0002D2E0 31BA020C */  jal        func_000AE8C4
    /* 2D358 0002D2E4 A023A524 */   addiu     $a1, $a1, %lo(str_Button_Triangle_23A0)
    /* 2D35C 0002D2E8 1D00043C */  lui        $a0, %hi(sym_001D3414)
    /* 2D360 0002D2EC 06A30046 */  mov.s      $f12, $f20
    /* 2D364 0002D2F0 1C00053C */  lui        $a1, %hi(str_Button_X_23B0)
    /* 2D368 0002D2F4 14348424 */  addiu      $a0, $a0, %lo(sym_001D3414)
    /* 2D36C 0002D2F8 31BA020C */  jal        func_000AE8C4
    /* 2D370 0002D2FC B023A524 */   addiu     $a1, $a1, %lo(str_Button_X_23B0)
    /* 2D374 0002D300 1D00043C */  lui        $a0, %hi(sym_001D3418)
    /* 2D378 0002D304 06A30046 */  mov.s      $f12, $f20
    /* 2D37C 0002D308 1C00053C */  lui        $a1, %hi(str_Confirm_23BC)
    /* 2D380 0002D30C 18348424 */  addiu      $a0, $a0, %lo(sym_001D3418)
    /* 2D384 0002D310 31BA020C */  jal        func_000AE8C4
    /* 2D388 0002D314 BC23A524 */   addiu     $a1, $a1, %lo(str_Confirm_23BC)
    /* 2D38C 0002D318 1D00043C */  lui        $a0, %hi(sym_001D341C)
    /* 2D390 0002D31C 06A30046 */  mov.s      $f12, $f20
    /* 2D394 0002D320 1C00053C */  lui        $a1, %hi(str_Cancel_23C4)
    /* 2D398 0002D324 1C348424 */  addiu      $a0, $a0, %lo(sym_001D341C)
    /* 2D39C 0002D328 31BA020C */  jal        func_000AE8C4
    /* 2D3A0 0002D32C C423A524 */   addiu     $a1, $a1, %lo(str_Cancel_23C4)
    /* 2D3A4 0002D330 1D00043C */  lui        $a0, %hi(sym_001D3420)
    /* 2D3A8 0002D334 06A30046 */  mov.s      $f12, $f20
    /* 2D3AC 0002D338 1C00053C */  lui        $a1, %hi(str_Start_23CC)
    /* 2D3B0 0002D33C 20348424 */  addiu      $a0, $a0, %lo(sym_001D3420)
    /* 2D3B4 0002D340 31BA020C */  jal        func_000AE8C4
    /* 2D3B8 0002D344 CC23A524 */   addiu     $a1, $a1, %lo(str_Start_23CC)
    /* 2D3BC 0002D348 1D00043C */  lui        $a0, %hi(sym_001D3424)
    /* 2D3C0 0002D34C 06A30046 */  mov.s      $f12, $f20
    /* 2D3C4 0002D350 1C00053C */  lui        $a1, %hi(str_ActiveController_23D4)
    /* 2D3C8 0002D354 24348424 */  addiu      $a0, $a0, %lo(sym_001D3424)
    /* 2D3CC 0002D358 31BA020C */  jal        func_000AE8C4
    /* 2D3D0 0002D35C D423A524 */   addiu     $a1, $a1, %lo(str_ActiveController_23D4)
    /* 2D3D4 0002D360 6864043C */  lui        $a0, %hi(D_64687367)
    /* 2D3D8 0002D364 0D000534 */  ori        $a1, $zero, 0xD
    /* 2D3DC 0002D368 20000634 */  ori        $a2, $zero, 0x20
    /* 2D3E0 0002D36C 611B040C */  jal        elem_register_chunk_tag
    /* 2D3E4 0002D370 67738424 */   addiu     $a0, $a0, %lo(D_64687367)
    /* 2D3E8 0002D374 6D73043C */  lui        $a0, %hi(D_736D6472)
    /* 2D3EC 0002D378 36000534 */  ori        $a1, $zero, 0x36
    /* 2D3F0 0002D37C 40000634 */  ori        $a2, $zero, 0x40
    /* 2D3F4 0002D380 611B040C */  jal        elem_register_chunk_tag
    /* 2D3F8 0002D384 72648424 */   addiu     $a0, $a0, %lo(D_736D6472)
    /* 2D3FC 0002D388 726E043C */  lui        $a0, %hi(D_6E726574)
    /* 2D400 0002D38C 06000534 */  ori        $a1, $zero, 0x6
    /* 2D404 0002D390 20000634 */  ori        $a2, $zero, 0x20
    /* 2D408 0002D394 611B040C */  jal        elem_register_chunk_tag
    /* 2D40C 0002D398 74658424 */   addiu     $a0, $a0, %lo(D_6E726574)
    /* 2D410 0002D39C 7665043C */  lui        $a0, %hi(D_65766177)
    /* 2D414 0002D3A0 09000534 */  ori        $a1, $zero, 0x9
    /* 2D418 0002D3A4 20000634 */  ori        $a2, $zero, 0x20
    /* 2D41C 0002D3A8 611B040C */  jal        elem_register_chunk_tag
    /* 2D420 0002D3AC 77618424 */   addiu     $a0, $a0, %lo(D_65766177)
    /* 2D424 0002D3B0 7461043C */  lui        $a0, %hi(D_61746473)
    /* 2D428 0002D3B4 01000534 */  ori        $a1, $zero, 0x1
    /* 2D42C 0002D3B8 20000634 */  ori        $a2, $zero, 0x20
    /* 2D430 0002D3BC 611B040C */  jal        elem_register_chunk_tag
    /* 2D434 0002D3C0 73648424 */   addiu     $a0, $a0, %lo(D_61746473)
    /* 2D438 0002D3C4 6220043C */  lui        $a0, %hi(D_20626D78)
    /* 2D43C 0002D3C8 25280000 */  or         $a1, $zero, $zero
    /* 2D440 0002D3CC 40000634 */  ori        $a2, $zero, 0x40
    /* 2D444 0002D3D0 611B040C */  jal        elem_register_chunk_tag
    /* 2D448 0002D3D4 786D8424 */   addiu     $a0, $a0, %lo(D_20626D78)
    /* 2D44C 0002D3D8 7320043C */  lui        $a0, %hi(D_20736D78)
    /* 2D450 0002D3DC 25280000 */  or         $a1, $zero, $zero
    /* 2D454 0002D3E0 40000634 */  ori        $a2, $zero, 0x40
    /* 2D458 0002D3E4 611B040C */  jal        elem_register_chunk_tag
    /* 2D45C 0002D3E8 786D8424 */   addiu     $a0, $a0, %lo(D_20736D78)
    /* 2D460 0002D3EC 6820043C */  lui        $a0, %hi(D_20686D78)
    /* 2D464 0002D3F0 25280000 */  or         $a1, $zero, $zero
    /* 2D468 0002D3F4 20000634 */  ori        $a2, $zero, 0x20
    /* 2D46C 0002D3F8 611B040C */  jal        elem_register_chunk_tag
    /* 2D470 0002D3FC 786D8424 */   addiu     $a0, $a0, %lo(D_20686D78)
    /* 2D474 0002D400 6267043C */  lui        $a0, %hi(D_6762646E)
    /* 2D478 0002D404 04000534 */  ori        $a1, $zero, 0x4
    /* 2D47C 0002D408 20000634 */  ori        $a2, $zero, 0x20
    /* 2D480 0002D40C 611B040C */  jal        elem_register_chunk_tag
    /* 2D484 0002D410 6E648424 */   addiu     $a0, $a0, %lo(D_6762646E)
    /* 2D488 0002D414 6465043C */  lui        $a0, %hi(D_65646F6E)
    /* 2D48C 0002D418 D0000534 */  ori        $a1, $zero, 0xD0
    /* 2D490 0002D41C 20000634 */  ori        $a2, $zero, 0x20
    /* 2D494 0002D420 611B040C */  jal        elem_register_chunk_tag
    /* 2D498 0002D424 6E6F8424 */   addiu     $a0, $a0, %lo(D_65646F6E)
    /* 2D49C 0002D428 766C043C */  lui        $a0, %hi(D_6C76656C)
    /* 2D4A0 0002D42C 62000534 */  ori        $a1, $zero, 0x62
    /* 2D4A4 0002D430 20000634 */  ori        $a2, $zero, 0x20
    /* 2D4A8 0002D434 611B040C */  jal        elem_register_chunk_tag
    /* 2D4AC 0002D438 6C658424 */   addiu     $a0, $a0, %lo(D_6C76656C)
    /* 2D4B0 0002D43C 1D00043C */  lui        $a0, %hi(sym_001D32F0)
    /* 2D4B4 0002D440 F03280A0 */  sb         $zero, %lo(sym_001D32F0)($a0)
    /* 2D4B8 0002D444 1000B4C7 */  lwc1       $f20, 0x10($sp)
    /* 2D4BC 0002D448 1400BF8F */  lw         $ra, 0x14($sp)
    /* 2D4C0 0002D44C 0800E003 */  jr         $ra
    /* 2D4C4 0002D450 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0002D224
