.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00193248, 0x8

glabel func_00193248
    /* 1932BC 00193248 0800E003 */  jr         $ra
    /* 1932C0 0019324C 02000234 */   ori       $v0, $zero, 0x2
endlabel func_00193248
