.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0002A3D4, 0x8C

glabel func_0002A3D4
    /* 2A448 0002A3D4 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 2A44C 0002A3D8 1D00043C */  lui        $a0, %hi(sym_001D3248)
    /* 2A450 0002A3DC 48328CC4 */  lwc1       $f12, %lo(sym_001D3248)($a0)
    /* 2A454 0002A3E0 3443043C */  lui        $a0, (0x43340000 >> 16)
    /* 2A458 0002A3E4 00688444 */  mtc1       $a0, $f13
    /* 2A45C 0002A3E8 83630D46 */  div.s      $f14, $f12, $f13
    /* 2A460 0002A3EC 1D000A3C */  lui        $t2, %hi(sym_001D324C)
    /* 2A464 0002A3F0 1D00043C */  lui        $a0, %hi(sym_001D3238)
    /* 2A468 0002A3F4 1C00053C */  lui        $a1, %hi(str_furniture_print_for_lua_file)
    /* 2A46C 0002A3F8 0300093C */  lui        $t1, %hi(func_0002A2FC)
    /* 2A470 0002A3FC 1D000B3C */  lui        $t3, %hi(sym_001D3250)
    /* 2A474 0002A400 00000634 */  ori        $a2, $zero, 0x0
    /* 2A478 0002A404 25380000 */  or         $a3, $zero, $zero
    /* 2A47C 0002A408 02000834 */  ori        $t0, $zero, 0x2
    /* 2A480 0002A40C 38328424 */  addiu      $a0, $a0, %lo(sym_001D3238)
    /* 2A484 0002A410 7817A524 */  addiu      $a1, $a1, %lo(str_furniture_print_for_lua_file)
    /* 2A488 0002A414 FCA22925 */  addiu      $t1, $t1, %lo(func_0002A2FC)
    /* 2A48C 0002A418 2000BFAF */  sw         $ra, 0x20($sp)
    /* 2A490 0002A41C 036B0C46 */  div.s      $f12, $f13, $f12
    /* 2A494 0002A420 4C324EE5 */  swc1       $f14, %lo(sym_001D324C)($t2)
    /* 2A498 0002A424 8C8E040C */  jal        func_00123A30
    /* 2A49C 0002A428 50326CE5 */   swc1      $f12, %lo(sym_001D3250)($t3)
    /* 2A4A0 0002A42C 1D00043C */  lui        $a0, %hi(sym_001D323C)
    /* 2A4A4 0002A430 1C00053C */  lui        $a1, %hi(str_print_graph_do_furniture)
    /* 2A4A8 0002A434 0300093C */  lui        $t1, %hi(func_0002A340)
    /* 2A4AC 0002A438 00000634 */  ori        $a2, $zero, 0x0
    /* 2A4B0 0002A43C 25380000 */  or         $a3, $zero, $zero
    /* 2A4B4 0002A440 02000834 */  ori        $t0, $zero, 0x2
    /* 2A4B8 0002A444 3C328424 */  addiu      $a0, $a0, %lo(sym_001D323C)
    /* 2A4BC 0002A448 9817A524 */  addiu      $a1, $a1, %lo(str_print_graph_do_furniture)
    /* 2A4C0 0002A44C 8C8E040C */  jal        func_00123A30
    /* 2A4C4 0002A450 40A32925 */   addiu     $t1, $t1, %lo(func_0002A340)
    /* 2A4C8 0002A454 2000BF8F */  lw         $ra, 0x20($sp)
    /* 2A4CC 0002A458 0800E003 */  jr         $ra
    /* 2A4D0 0002A45C 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_0002A3D4
