.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000D34DC, 0xF4

glabel func_000D34DC
    /* D3550 000D34DC E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* D3554 000D34E0 2540A000 */  or         $t0, $a1, $zero
    /* D3558 000D34E4 04008524 */  addiu      $a1, $a0, 0x4
    /* D355C 000D34E8 040085AC */  sw         $a1, 0x4($a0)
    /* D3560 000D34EC 080085AC */  sw         $a1, 0x8($a0)
    /* D3564 000D34F0 1F00053C */  lui        $a1, %hi(sym_001EC800)
    /* D3568 000D34F4 00C8A524 */  addiu      $a1, $a1, %lo(sym_001EC800)
    /* D356C 000D34F8 000085AC */  sw         $a1, 0x0($a0)
    /* D3570 000D34FC 1800B2AF */  sw         $s2, 0x18($sp)
    /* D3574 000D3500 0C008524 */  addiu      $a1, $a0, 0xC
    /* D3578 000D3504 25908000 */  or         $s2, $a0, $zero
    /* D357C 000D3508 1400B1AF */  sw         $s1, 0x14($sp)
    /* D3580 000D350C 25200001 */  or         $a0, $t0, $zero
    /* D3584 000D3510 2588C000 */  or         $s1, $a2, $zero
    /* D3588 000D3514 1000B0AF */  sw         $s0, 0x10($sp)
    /* D358C 000D3518 1C00BFAF */  sw         $ra, 0x1C($sp)
    /* D3590 000D351C 08000011 */  beqz       $t0, .Leboot_000D3540
    /* D3594 000D3520 2580E000 */   or        $s0, $a3, $zero
    /* D3598 000D3524 25308000 */  or         $a2, $a0, $zero
    /* D359C 000D3528 2520A000 */  or         $a0, $a1, $zero
    /* D35A0 000D352C 2528C000 */  or         $a1, $a2, $zero
    /* D35A4 000D3530 97B2040C */  jal        func_0012CA5C
    /* D35A8 000D3534 04010634 */   ori       $a2, $zero, 0x104
    /* D35AC 000D3538 03000010 */  b          .Leboot_000D3548
    /* D35B0 000D353C 01002432 */   andi      $a0, $s1, 0x1
  .Leboot_000D3540:
    /* D35B4 000D3540 0C0040A2 */  sb         $zero, 0xC($s2)
    /* D35B8 000D3544 01002432 */  andi       $a0, $s1, 0x1
  .Leboot_000D3548:
    /* D35BC 000D3548 04002532 */  andi       $a1, $s1, 0x4
    /* D35C0 000D354C 100144A2 */  sb         $a0, 0x110($s2)
    /* D35C4 000D3550 2B200500 */  sltu       $a0, $zero, $a1
    /* D35C8 000D3554 02002532 */  andi       $a1, $s1, 0x2
    /* D35CC 000D3558 110144A2 */  sb         $a0, 0x111($s2)
    /* D35D0 000D355C 2B200500 */  sltu       $a0, $zero, $a1
    /* D35D4 000D3560 120144A2 */  sb         $a0, 0x112($s2)
    /* D35D8 000D3564 140140AE */  sw         $zero, 0x114($s2)
    /* D35DC 000D3568 03000016 */  bnez       $s0, .Leboot_000D3578
    /* D35E0 000D356C 25880002 */   or        $s1, $s0, $zero
    /* D35E4 000D3570 1E00043C */  lui        $a0, %hi(sym_001D9E80)
    /* D35E8 000D3574 809E918C */  lw         $s1, %lo(sym_001D9E80)($a0)
  .Leboot_000D3578:
    /* D35EC 000D3578 180151AE */  sw         $s1, 0x118($s2)
    /* D35F0 000D357C 1C0140AE */  sw         $zero, 0x11C($s2)
    /* D35F4 000D3580 200140AE */  sw         $zero, 0x120($s2)
    /* D35F8 000D3584 240140AE */  sw         $zero, 0x124($s2)
    /* D35FC 000D3588 280140AE */  sw         $zero, 0x128($s2)
    /* D3600 000D358C 2C0140AE */  sw         $zero, 0x12C($s2)
    /* D3604 000D3590 300140AE */  sw         $zero, 0x130($s2)
    /* D3608 000D3594 340140AE */  sw         $zero, 0x134($s2)
    /* D360C 000D3598 380140AE */  sw         $zero, 0x138($s2)
    /* D3610 000D359C 3C0140AE */  sw         $zero, 0x13C($s2)
    /* D3614 000D35A0 400140AE */  sw         $zero, 0x140($s2)
    /* D3618 000D35A4 FFFF0424 */  addiu      $a0, $zero, -0x1
    /* D361C 000D35A8 500140AE */  sw         $zero, 0x150($s2)
    /* D3620 000D35AC 540144AE */  sw         $a0, 0x154($s2)
    /* D3624 000D35B0 580140A2 */  sb         $zero, 0x158($s2)
    /* D3628 000D35B4 25104002 */  or         $v0, $s2, $zero
    /* D362C 000D35B8 1000B08F */  lw         $s0, 0x10($sp)
    /* D3630 000D35BC 1400B18F */  lw         $s1, 0x14($sp)
    /* D3634 000D35C0 1800B28F */  lw         $s2, 0x18($sp)
    /* D3638 000D35C4 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* D363C 000D35C8 0800E003 */  jr         $ra
    /* D3640 000D35CC 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_000D34DC
