.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_001AC99C, 0x5C

glabel func_001AC99C
    /* 1ACA10 001AC99C E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 1ACA14 001AC9A0 1400B1AF */  sw         $s1, 0x14($sp)
    /* 1ACA18 001AC9A4 25888000 */  or         $s1, $a0, $zero
    /* 1ACA1C 001AC9A8 1000B0AF */  sw         $s0, 0x10($sp)
    /* 1ACA20 001AC9AC 1800BFAF */  sw         $ra, 0x18($sp)
    /* 1ACA24 001AC9B0 0C008010 */  beqz       $a0, .Leboot_001AC9E4
    /* 1ACA28 001AC9B4 2580A000 */   or        $s0, $a1, $zero
    /* 1ACA2C 001AC9B8 1F00043C */  lui        $a0, %hi(sym_001EDD30)
    /* 1ACA30 001AC9BC 30DD8424 */  addiu      $a0, $a0, %lo(sym_001EDD30)
    /* 1ACA34 001AC9C0 140024AE */  sw         $a0, 0x14($s1)
    /* 1ACA38 001AC9C4 25202002 */  or         $a0, $s1, $zero
    /* 1ACA3C 001AC9C8 8AB0040C */  jal        func_0012C228
    /* 1ACA40 001AC9CC 25280000 */   or        $a1, $zero, $zero
    /* 1ACA44 001AC9D0 01000432 */  andi       $a0, $s0, 0x1
    /* 1ACA48 001AC9D4 03008010 */  beqz       $a0, .Leboot_001AC9E4
    /* 1ACA4C 001AC9D8 00000000 */   nop
    /* 1ACA50 001AC9DC C79D040C */  jal        func_0012771C
    /* 1ACA54 001AC9E0 25202002 */   or        $a0, $s1, $zero
  .Leboot_001AC9E4:
    /* 1ACA58 001AC9E4 1000B08F */  lw         $s0, 0x10($sp)
    /* 1ACA5C 001AC9E8 1400B18F */  lw         $s1, 0x14($sp)
    /* 1ACA60 001AC9EC 1800BF8F */  lw         $ra, 0x18($sp)
    /* 1ACA64 001AC9F0 0800E003 */  jr         $ra
    /* 1ACA68 001AC9F4 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_001AC99C
