.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00058FF8, 0x80

glabel func_00058FF8
    /* 5906C 00058FF8 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 59070 00058FFC 1400B1AF */  sw         $s1, 0x14($sp)
    /* 59074 00059000 1800B2AF */  sw         $s2, 0x18($sp)
    /* 59078 00059004 0000A0AC */  sw         $zero, 0x0($a1)
    /* 5907C 00059008 25908000 */  or         $s2, $a0, $zero
    /* 59080 0005900C 2588C000 */  or         $s1, $a2, $zero
    /* 59084 00059010 1000B0AF */  sw         $s0, 0x10($sp)
    /* 59088 00059014 1C00BFAF */  sw         $ra, 0x1C($sp)
    /* 5908C 00059018 06008010 */  beqz       $a0, .Leboot_00059034
    /* 59090 0005901C 2580E000 */   or        $s0, $a3, $zero
    /* 59094 00059020 1C00448E */  lw         $a0, 0x1C($s2)
    /* 59098 00059024 05008014 */  bnez       $a0, .Leboot_0005903C
    /* 5909C 00059028 0000A4AC */   sw        $a0, 0x0($a1)
    /* 590A0 0005902C 0C000010 */  b          .Leboot_00059060
    /* 590A4 00059030 25100000 */   or        $v0, $zero, $zero
  .Leboot_00059034:
    /* 590A8 00059034 0A000010 */  b          .Leboot_00059060
    /* 590AC 00059038 25100000 */   or        $v0, $zero, $zero
  .Leboot_0005903C:
    /* 590B0 0005903C F563010C */  jal        func_00058FD4
    /* 590B4 00059040 25204002 */   or        $a0, $s2, $zero
    /* 590B8 00059044 000022AE */  sw         $v0, 0x0($s1)
    /* 590BC 00059048 FB63010C */  jal        func_00058FEC
    /* 590C0 0005904C 25204002 */   or        $a0, $s2, $zero
    /* 590C4 00059050 000002AE */  sw         $v0, 0x0($s0)
    /* 590C8 00059054 2000428E */  lw         $v0, 0x20($s2)
    /* 590CC 00059058 20004426 */  addiu      $a0, $s2, 0x20
    /* 590D0 0005905C 21108200 */  addu       $v0, $a0, $v0
  .Leboot_00059060:
    /* 590D4 00059060 1000B08F */  lw         $s0, 0x10($sp)
    /* 590D8 00059064 1400B18F */  lw         $s1, 0x14($sp)
    /* 590DC 00059068 1800B28F */  lw         $s2, 0x18($sp)
    /* 590E0 0005906C 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* 590E4 00059070 0800E003 */  jr         $ra
    /* 590E8 00059074 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_00058FF8
