.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

/* Handwritten function */
nonmatching func_0001EFAC, 0x298

glabel func_0001EFAC
    /* 1F020 0001EFAC 90FDBD27 */  addiu      $sp, $sp, -0x270
    /* 1F024 0001EFB0 4002B4E7 */  swc1       $f20, 0x240($sp)
    /* 1F028 0001EFB4 4402B6E7 */  swc1       $f22, 0x244($sp)
    /* 1F02C 0001EFB8 4802B0AF */  sw         $s0, 0x248($sp)
    /* 1F030 0001EFBC 4C02B1AF */  sw         $s1, 0x24C($sp)
    /* 1F034 0001EFC0 5002B2AF */  sw         $s2, 0x250($sp)
    /* 1F038 0001EFC4 5402B3AF */  sw         $s3, 0x254($sp)
    /* 1F03C 0001EFC8 5802B4AF */  sw         $s4, 0x258($sp)
    /* 1F040 0001EFCC 5C02B5AF */  sw         $s5, 0x25C($sp)
    /* 1F044 0001EFD0 6002B6AF */  sw         $s6, 0x260($sp)
    /* 1F048 0001EFD4 6402B7AF */  sw         $s7, 0x264($sp)
    /* 1F04C 0001EFD8 6802BEAF */  sw         $fp, 0x268($sp)
    /* 1F050 0001EFDC 6C02BFAF */  sw         $ra, 0x26C($sp)
    /* 1F054 0001EFE0 2C78000C */  jal        func_0001E0B0
    /* 1F058 0001EFE4 25A88000 */   or        $s5, $a0, $zero
    /* 1F05C 0001EFE8 03004014 */  bnez       $v0, .Leboot_0001EFF8
    /* 1F060 0001EFEC 00000000 */   nop
    /* 1F064 0001EFF0 86000010 */  b          .Leboot_0001F20C
    /* 1F068 0001EFF4 00000000 */   nop
  .Leboot_0001EFF8:
    /* 1F06C 0001EFF8 00000434 */  ori        $a0, $zero, 0x0
    /* 1F070 0001EFFC 00A08044 */  mtc1       $zero, $f20
    /* 1F074 0001F000 3402A4AF */  sw         $a0, 0x234($sp)
    /* 1F078 0001F004 1801A426 */  addiu      $a0, $s5, 0x118
    /* 1F07C 0001F008 3C02A4AF */  sw         $a0, 0x23C($sp)
    /* 1F080 0001F00C 1C00BE27 */  addiu      $fp, $sp, 0x1C
    /* 1F084 0001F010 2001B727 */  addiu      $s7, $sp, 0x120
    /* 1F088 0001F014 1000B627 */  addiu      $s6, $sp, 0x10
    /* 1F08C 0001F018 25A0A002 */  or         $s4, $s5, $zero
    /* 1F090 0001F01C 3802B5AF */  sw         $s5, 0x238($sp)
  .Leboot_0001F020:
    /* 1F094 0001F020 B801A48E */  lw         $a0, 0x1B8($s5)
    /* 1F098 0001F024 3C02B28F */  lw         $s2, 0x23C($sp)
    /* 1F09C 0001F028 0000858C */  lw         $a1, 0x0($a0)
    /* 1F0A0 0001F02C 26D8060C */  jal        updateNodeGraph_0818
    /* 1F0A4 0001F030 25204002 */   or        $a0, $s2, $zero
    /* 1F0A8 0001F034 3402B18F */  lw         $s1, 0x234($sp)
    /* 1F0AC 0001F038 25204000 */  or         $a0, $v0, $zero
    /* 1F0B0 0001F03C AD75020C */  jal        func_0009D6B4
    /* 1F0B4 0001F040 25282002 */   or        $a1, $s1, $zero
    /* 1F0B8 0001F044 25804000 */  or         $s0, $v0, $zero
    /* 1F0BC 0001F048 00100432 */  andi       $a0, $s0, 0x1000
    /* 1F0C0 0001F04C 16008010 */  beqz       $a0, .Leboot_0001F0A8
    /* 1F0C4 0001F050 10000432 */   andi      $a0, $s0, 0x10
    /* 1F0C8 0001F054 03008010 */  beqz       $a0, .Leboot_0001F064
    /* 1F0CC 0001F058 02000432 */   andi      $a0, $s0, 0x2
    /* 1F0D0 0001F05C 12008010 */  beqz       $a0, .Leboot_0001F0A8
    /* 1F0D4 0001F060 00000000 */   nop
  .Leboot_0001F064:
    /* 1F0D8 0001F064 B801A58E */  lw         $a1, 0x1B8($s5)
    /* 1F0DC 0001F068 25204002 */  or         $a0, $s2, $zero
    /* 1F0E0 0001F06C 0000A58C */  lw         $a1, 0x0($a1)
    /* 1F0E4 0001F070 6DAC020C */  jal        func_000AB1B4
    /* 1F0E8 0001F074 25302002 */   or        $a2, $s1, $zero
    /* 1F0EC 0001F078 3E001446 */  c.le.s     $f0, $f20
    /* 1F0F0 0001F07C 00000000 */  nop
    /* 1F0F4 0001F080 09000145 */  bc1t       .Leboot_0001F0A8 /* handwritten instruction */
    /* 1F0F8 0001F084 00400432 */   andi      $a0, $s0, 0x4000
    /* 1F0FC 0001F088 07008014 */  bnez       $a0, .Leboot_0001F0A8
    /* 1F100 0001F08C 00000000 */   nop
    /* 1F104 0001F090 3802A48F */  lw         $a0, 0x238($sp)
    /* 1F108 0001F094 1C028CC4 */  lwc1       $f12, 0x21C($a0)
    /* 1F10C 0001F098 3C601446 */  c.lt.s     $f12, $f20
    /* 1F110 0001F09C 00000000 */  nop
    /* 1F114 0001F0A0 03000045 */  bc1f       .Leboot_0001F0B0 /* handwritten instruction */
    /* 1F118 0001F0A4 00000000 */   nop
  .Leboot_0001F0A8:
    /* 1F11C 0001F0A8 4F000010 */  b          .Leboot_0001F1E8
    /* 1F120 0001F0AC 00000000 */   nop
  .Leboot_0001F0B0:
    /* 1F124 0001F0B0 B801A58E */  lw         $a1, 0x1B8($s5)
    /* 1F128 0001F0B4 25204002 */  or         $a0, $s2, $zero
    /* 1F12C 0001F0B8 0000A58C */  lw         $a1, 0x0($a1)
    /* 1F130 0001F0BC 3DAC020C */  jal        func_000AB0F4
    /* 1F134 0001F0C0 25302002 */   or        $a2, $s1, $zero
    /* 1F138 0001F0C4 B801A58E */  lw         $a1, 0x1B8($s5)
    /* 1F13C 0001F0C8 86050046 */  mov.s      $f22, $f0
    /* 1F140 0001F0CC 25204002 */  or         $a0, $s2, $zero
    /* 1F144 0001F0D0 0000A58C */  lw         $a1, 0x0($a1)
    /* 1F148 0001F0D4 55AC020C */  jal        func_000AB154
    /* 1F14C 0001F0D8 25302002 */   or        $a2, $s1, $zero
    /* 1F150 0001F0DC 08028CC6 */  lwc1       $f12, 0x208($s4)
    /* 1F154 0001F0E0 3CB00C46 */  c.lt.s     $f22, $f12
    /* 1F158 0001F0E4 00000000 */  nop
    /* 1F15C 0001F0E8 02000045 */  bc1f       .Leboot_0001F0F4 /* handwritten instruction */
    /* 1F160 0001F0EC 00000000 */   nop
    /* 1F164 0001F0F0 080296E6 */  swc1       $f22, 0x208($s4)
  .Leboot_0001F0F4:
    /* 1F168 0001F0F4 3802B28F */  lw         $s2, 0x238($sp)
    /* 1F16C 0001F0F8 00001334 */  ori        $s3, $zero, 0x0
    /* 1F170 0001F0FC 18025226 */  addiu      $s2, $s2, 0x218
  .Leboot_0001F100:
    /* 1F174 0001F100 25804002 */  or         $s0, $s2, $zero
    /* 1F178 0001F104 0000048E */  lw         $a0, 0x0($s0)
    /* 1F17C 0001F108 10011126 */  addiu      $s1, $s0, 0x110
    /* 1F180 0001F10C 1000A4AF */  sw         $a0, 0x10($sp)
    /* 1F184 0001F110 04000CC6 */  lwc1       $f12, 0x4($s0)
    /* 1F188 0001F114 0C000426 */  addiu      $a0, $s0, 0xC
    /* 1F18C 0001F118 1400ACE7 */  swc1       $f12, 0x14($sp)
    /* 1F190 0001F11C 0800058E */  lw         $a1, 0x8($s0)
    /* 1F194 0001F120 07008010 */  beqz       $a0, .Leboot_0001F140
    /* 1F198 0001F124 1800A5AF */   sw        $a1, 0x18($sp)
    /* 1F19C 0001F128 25288000 */  or         $a1, $a0, $zero
    /* 1F1A0 0001F12C 2520C003 */  or         $a0, $fp, $zero
    /* 1F1A4 0001F130 97B2040C */  jal        func_0012CA5C
    /* 1F1A8 0001F134 04010634 */   ori       $a2, $zero, 0x104
    /* 1F1AC 0001F138 02000010 */  b          .Leboot_0001F144
    /* 1F1B0 0001F13C 00000000 */   nop
  .Leboot_0001F140:
    /* 1F1B4 0001F140 1C00A0A3 */  sb         $zero, 0x1C($sp)
  .Leboot_0001F144:
    /* 1F1B8 0001F144 06002012 */  beqz       $s1, .Leboot_0001F160
    /* 1F1BC 0001F148 2520E002 */   or        $a0, $s7, $zero
    /* 1F1C0 0001F14C 25282002 */  or         $a1, $s1, $zero
    /* 1F1C4 0001F150 97B2040C */  jal        func_0012CA5C
    /* 1F1C8 0001F154 04010634 */   ori       $a2, $zero, 0x104
    /* 1F1CC 0001F158 03000010 */  b          .Leboot_0001F168
    /* 1F1D0 0001F15C 1400ACC7 */   lwc1      $f12, 0x14($sp)
  .Leboot_0001F160:
    /* 1F1D4 0001F160 2001A0A3 */  sb         $zero, 0x120($sp)
    /* 1F1D8 0001F164 1400ACC7 */  lwc1       $f12, 0x14($sp)
  .Leboot_0001F168:
    /* 1F1DC 0001F168 14020426 */  addiu      $a0, $s0, 0x214
    /* 1F1E0 0001F16C 0000858C */  lw         $a1, 0x0($a0)
    /* 1F1E4 0001F170 3C601446 */  c.lt.s     $f12, $f20
    /* 1F1E8 0001F174 0400868C */  lw         $a2, 0x4($a0)
    /* 1F1EC 0001F178 0800878C */  lw         $a3, 0x8($a0)
    /* 1F1F0 0001F17C 2402A5AF */  sw         $a1, 0x224($sp)
    /* 1F1F4 0001F180 0C00848C */  lw         $a0, 0xC($a0)
    /* 1F1F8 0001F184 2802A6AF */  sw         $a2, 0x228($sp)
    /* 1F1FC 0001F188 2C02A7AF */  sw         $a3, 0x22C($sp)
    /* 1F200 0001F18C 05000145 */  bc1t       .Leboot_0001F1A4 /* handwritten instruction */
    /* 1F204 0001F190 3002A4AF */   sw        $a0, 0x230($sp)
    /* 1F208 0001F194 3E601646 */  c.le.s     $f12, $f22
    /* 1F20C 0001F198 00000000 */  nop
    /* 1F210 0001F19C 03000145 */  bc1t       .Leboot_0001F1AC /* handwritten instruction */
    /* 1F214 0001F1A0 00000000 */   nop
  .Leboot_0001F1A4:
    /* 1F218 0001F1A4 0F000010 */  b          .Leboot_0001F1E4
    /* 1F21C 0001F1A8 00000000 */   nop
  .Leboot_0001F1AC:
    /* 1F220 0001F1AC 08028DC6 */  lwc1       $f13, 0x208($s4)
    /* 1F224 0001F1B0 3C600D46 */  c.lt.s     $f12, $f13
    /* 1F228 0001F1B4 00000000 */  nop
    /* 1F22C 0001F1B8 03000045 */  bc1f       .Leboot_0001F1C8 /* handwritten instruction */
    /* 1F230 0001F1BC 00000000 */   nop
    /* 1F234 0001F1C0 04000010 */  b          .Leboot_0001F1D4
    /* 1F238 0001F1C4 00000000 */   nop
  .Leboot_0001F1C8:
    /* 1F23C 0001F1C8 2520C002 */  or         $a0, $s6, $zero
    /* 1F240 0001F1CC C785000C */  jal        func_0002171C
    /* 1F244 0001F1D0 2528A002 */   or        $a1, $s5, $zero
  .Leboot_0001F1D4:
    /* 1F248 0001F1D4 01007326 */  addiu      $s3, $s3, 0x1
    /* 1F24C 0001F1D8 0A00642A */  slti       $a0, $s3, 0xA
    /* 1F250 0001F1DC C8FF8014 */  bnez       $a0, .Leboot_0001F100
    /* 1F254 0001F1E0 24025226 */   addiu     $s2, $s2, 0x224
  .Leboot_0001F1E4:
    /* 1F258 0001F1E4 080296E6 */  swc1       $f22, 0x208($s4)
  .Leboot_0001F1E8:
    /* 1F25C 0001F1E8 3402A48F */  lw         $a0, 0x234($sp)
    /* 1F260 0001F1EC 3802A58F */  lw         $a1, 0x238($sp)
    /* 1F264 0001F1F0 01008424 */  addiu      $a0, $a0, 0x1
    /* 1F268 0001F1F4 6815A524 */  addiu      $a1, $a1, 0x1568
    /* 1F26C 0001F1F8 3402A4AF */  sw         $a0, 0x234($sp)
    /* 1F270 0001F1FC 04009426 */  addiu      $s4, $s4, 0x4
    /* 1F274 0001F200 04008428 */  slti       $a0, $a0, 0x4
    /* 1F278 0001F204 86FF8014 */  bnez       $a0, .Leboot_0001F020
    /* 1F27C 0001F208 3802A5AF */   sw        $a1, 0x238($sp)
  .Leboot_0001F20C:
    /* 1F280 0001F20C 4002B4C7 */  lwc1       $f20, 0x240($sp)
    /* 1F284 0001F210 4402B6C7 */  lwc1       $f22, 0x244($sp)
    /* 1F288 0001F214 4802B08F */  lw         $s0, 0x248($sp)
    /* 1F28C 0001F218 4C02B18F */  lw         $s1, 0x24C($sp)
    /* 1F290 0001F21C 5002B28F */  lw         $s2, 0x250($sp)
    /* 1F294 0001F220 5402B38F */  lw         $s3, 0x254($sp)
    /* 1F298 0001F224 5802B48F */  lw         $s4, 0x258($sp)
    /* 1F29C 0001F228 5C02B58F */  lw         $s5, 0x25C($sp)
    /* 1F2A0 0001F22C 6002B68F */  lw         $s6, 0x260($sp)
    /* 1F2A4 0001F230 6402B78F */  lw         $s7, 0x264($sp)
    /* 1F2A8 0001F234 6802BE8F */  lw         $fp, 0x268($sp)
    /* 1F2AC 0001F238 6C02BF8F */  lw         $ra, 0x26C($sp)
    /* 1F2B0 0001F23C 0800E003 */  jr         $ra
    /* 1F2B4 0001F240 7002BD27 */   addiu     $sp, $sp, 0x270
endlabel func_0001EFAC
