.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000E8CB0, 0x1F8

glabel func_000E8CB0
    /* E8D24 000E8CB0 B0FFBD27 */  addiu      $sp, $sp, -0x50
    /* E8D28 000E8CB4 80200600 */  sll        $a0, $a2, 2
    /* E8D2C 000E8CB8 0F00063C */  lui        $a2, %hi(sym_000E9718)
    /* E8D30 000E8CBC 1897C68C */  lw         $a2, %lo(sym_000E9718)($a2)
    /* E8D34 000E8CC0 2400B1AF */  sw         $s1, 0x24($sp)
    /* E8D38 000E8CC4 2120C400 */  addu       $a0, $a2, $a0
    /* E8D3C 000E8CC8 3400B5AF */  sw         $s5, 0x34($sp)
    /* E8D40 000E8CCC 0F00113C */  lui        $s1, %hi(sym_000E9714)
    /* E8D44 000E8CD0 1808958C */  lw         $s5, 0x818($a0)
    /* E8D48 000E8CD4 1497248E */  lw         $a0, %lo(sym_000E9714)($s1)
    /* E8D4C 000E8CD8 2800B2AF */  sw         $s2, 0x28($sp)
    /* E8D50 000E8CDC 2A009294 */  lhu        $s2, 0x2A($a0)
    /* E8D54 000E8CE0 2C00B3AF */  sw         $s3, 0x2C($sp)
    /* E8D58 000E8CE4 2C009394 */  lhu        $s3, 0x2C($a0)
    /* E8D5C 000E8CE8 3000B4AF */  sw         $s4, 0x30($sp)
    /* E8D60 000E8CEC FF005232 */  andi       $s2, $s2, 0xFF
    /* E8D64 000E8CF0 28009484 */  lh         $s4, 0x28($a0)
    /* E8D68 000E8CF4 80201200 */  sll        $a0, $s2, 2
    /* E8D6C 000E8CF8 2000B0AF */  sw         $s0, 0x20($sp)
    /* E8D70 000E8CFC FF00B030 */  andi       $s0, $a1, 0xFF
    /* E8D74 000E8D00 2120A402 */  addu       $a0, $s5, $a0
    /* E8D78 000E8D04 B4008590 */  lbu        $a1, 0xB4($a0)
    /* E8D7C 000E8D08 B3008690 */  lbu        $a2, 0xB3($a0)
    /* E8D80 000E8D0C FF007332 */  andi       $s3, $s3, 0xFF
    /* E8D84 000E8D10 002A0500 */  sll        $a1, $a1, 8
    /* E8D88 000E8D14 80381300 */  sll        $a3, $s3, 2
    /* E8D8C 000E8D18 2128C500 */  addu       $a1, $a2, $a1
    /* E8D90 000E8D1C 2130A702 */  addu       $a2, $s5, $a3
    /* E8D94 000E8D20 002C0500 */  sll        $a1, $a1, 16
    /* E8D98 000E8D24 B400C790 */  lbu        $a3, 0xB4($a2)
    /* E8D9C 000E8D28 032C0500 */  sra        $a1, $a1, 16
    /* E8DA0 000E8D2C B300C890 */  lbu        $t0, 0xB3($a2)
    /* E8DA4 000E8D30 80280500 */  sll        $a1, $a1, 2
    /* E8DA8 000E8D34 003A0700 */  sll        $a3, $a3, 8
    /* E8DAC 000E8D38 002C0500 */  sll        $a1, $a1, 16
    /* E8DB0 000E8D3C 21400701 */  addu       $t0, $t0, $a3
    /* E8DB4 000E8D40 033C0500 */  sra        $a3, $a1, 16
    /* E8DB8 000E8D44 002C0800 */  sll        $a1, $t0, 16
    /* E8DBC 000E8D48 032C0500 */  sra        $a1, $a1, 16
    /* E8DC0 000E8D4C B2008890 */  lbu        $t0, 0xB2($a0)
    /* E8DC4 000E8D50 80280500 */  sll        $a1, $a1, 2
    /* E8DC8 000E8D54 B1008490 */  lbu        $a0, 0xB1($a0)
    /* E8DCC 000E8D58 002C0500 */  sll        $a1, $a1, 16
    /* E8DD0 000E8D5C 004A0800 */  sll        $t1, $t0, 8
    /* E8DD4 000E8D60 03440500 */  sra        $t0, $a1, 16
    /* E8DD8 000E8D64 21208900 */  addu       $a0, $a0, $t1
    /* E8DDC 000E8D68 B200C590 */  lbu        $a1, 0xB2($a2)
    /* E8DE0 000E8D6C 3800B6AF */  sw         $s6, 0x38($sp)
    /* E8DE4 000E8D70 B100C690 */  lbu        $a2, 0xB1($a2)
    /* E8DE8 000E8D74 00B40400 */  sll        $s6, $a0, 16
    /* E8DEC 000E8D78 00220500 */  sll        $a0, $a1, 8
    /* E8DF0 000E8D7C 2120C400 */  addu       $a0, $a2, $a0
    /* E8DF4 000E8D80 3C00B7AF */  sw         $s7, 0x3C($sp)
    /* E8DF8 000E8D84 FFFF9432 */  andi       $s4, $s4, 0xFFFF
    /* E8DFC 000E8D88 00BC0400 */  sll        $s7, $a0, 16
    /* E8E00 000E8D8C 03B41600 */  sra        $s6, $s6, 16
    /* E8E04 000E8D90 00241400 */  sll        $a0, $s4, 16
    /* E8E08 000E8D94 03BC1700 */  sra        $s7, $s7, 16
    /* E8E0C 000E8D98 03240400 */  sra        $a0, $a0, 16
    /* E8E10 000E8D9C 2528C002 */  or         $a1, $s6, $zero
    /* E8E14 000E8DA0 4000BFAF */  sw         $ra, 0x40($sp)
    /* E8E18 000E8DA4 2BA6030C */  jal        func_000E98AC
    /* E8E1C 000E8DA8 2530E002 */   or        $a2, $s7, $zero
    /* E8E20 000E8DAC 1497248E */  lw         $a0, %lo(sym_000E9714)($s1)
    /* E8E24 000E8DB0 22008590 */  lbu        $a1, 0x22($a0)
    /* E8E28 000E8DB4 0200A630 */  andi       $a2, $a1, 0x2
    /* E8E2C 000E8DB8 0800C010 */  beqz       $a2, .Leboot_000E8DDC
    /* E8E30 000E8DBC 00000000 */   nop
    /* E8E34 000E8DC0 06000012 */  beqz       $s0, .Leboot_000E8DDC
    /* E8E38 000E8DC4 00000000 */   nop
    /* E8E3C 000E8DC8 24008690 */  lbu        $a2, 0x24($a0)
    /* E8E40 000E8DCC 03004616 */  bne        $s2, $a2, .Leboot_000E8DDC
    /* E8E44 000E8DD0 00000000 */   nop
    /* E8E48 000E8DD4 23009652 */  beql       $s4, $s6, .Leboot_000E8E64
    /* E8E4C 000E8DD8 FF004532 */   andi      $a1, $s2, 0xFF
  .Leboot_000E8DDC:
    /* E8E50 000E8DDC 01009426 */  addiu      $s4, $s4, 0x1
    /* E8E54 000E8DE0 FFFF9432 */  andi       $s4, $s4, 0xFFFF
    /* E8E58 000E8DE4 2A309702 */  slt        $a2, $s4, $s7
    /* E8E5C 000E8DE8 1E00C054 */  bnel       $a2, $zero, .Leboot_000E8E64
    /* E8E60 000E8DEC FF004532 */   andi      $a1, $s2, 0xFF
    /* E8E64 000E8DF0 25906002 */  or         $s2, $s3, $zero
    /* E8E68 000E8DF4 01005326 */  addiu      $s3, $s2, 0x1
    /* E8E6C 000E8DF8 0400A530 */  andi       $a1, $a1, 0x4
    /* E8E70 000E8DFC 1000A010 */  beqz       $a1, .Leboot_000E8E40
    /* E8E74 000E8E00 FF007332 */   andi      $s3, $s3, 0xFF
    /* E8E78 000E8E04 26008590 */  lbu        $a1, 0x26($a0)
    /* E8E7C 000E8E08 2A28B300 */  slt        $a1, $a1, $s3
    /* E8E80 000E8E0C 1500A010 */  beqz       $a1, .Leboot_000E8E64
    /* E8E84 000E8E10 FF004532 */   andi      $a1, $s2, 0xFF
    /* E8E88 000E8E14 25009290 */  lbu        $s2, 0x25($a0)
    /* E8E8C 000E8E18 80281200 */  sll        $a1, $s2, 2
    /* E8E90 000E8E1C 2128A502 */  addu       $a1, $s5, $a1
    /* E8E94 000E8E20 B200A690 */  lbu        $a2, 0xB2($a1)
    /* E8E98 000E8E24 B100A590 */  lbu        $a1, 0xB1($a1)
    /* E8E9C 000E8E28 00320600 */  sll        $a2, $a2, 8
    /* E8EA0 000E8E2C 01005326 */  addiu      $s3, $s2, 0x1
    /* E8EA4 000E8E30 21A0A600 */  addu       $s4, $a1, $a2
    /* E8EA8 000E8E34 FF007332 */  andi       $s3, $s3, 0xFF
    /* E8EAC 000E8E38 09000010 */  b          .Leboot_000E8E60
    /* E8EB0 000E8E3C FFFF9432 */   andi      $s4, $s4, 0xFFFF
  .Leboot_000E8E40:
    /* E8EB4 000E8E40 23008590 */  lbu        $a1, 0x23($a0)
    /* E8EB8 000E8E44 2A286502 */  slt        $a1, $s3, $a1
    /* E8EBC 000E8E48 0600A014 */  bnez       $a1, .Leboot_000E8E64
    /* E8EC0 000E8E4C FF004532 */   andi      $a1, $s2, 0xFF
    /* E8EC4 000E8E50 FFFF7326 */  addiu      $s3, $s3, -0x1
    /* E8EC8 000E8E54 FFFF9426 */  addiu      $s4, $s4, -0x1
    /* E8ECC 000E8E58 FF007332 */  andi       $s3, $s3, 0xFF
    /* E8ED0 000E8E5C FFFF9432 */  andi       $s4, $s4, 0xFFFF
  .Leboot_000E8E60:
    /* E8ED4 000E8E60 FF004532 */  andi       $a1, $s2, 0xFF
  .Leboot_000E8E64:
    /* E8ED8 000E8E64 2A0085A4 */  sh         $a1, 0x2A($a0)
    /* E8EDC 000E8E68 1497248E */  lw         $a0, %lo(sym_000E9714)($s1)
    /* E8EE0 000E8E6C FF006532 */  andi       $a1, $s3, 0xFF
    /* E8EE4 000E8E70 2C0085A4 */  sh         $a1, 0x2C($a0)
    /* E8EE8 000E8E74 1497248E */  lw         $a0, %lo(sym_000E9714)($s1)
    /* E8EEC 000E8E78 280094A4 */  sh         $s4, 0x28($a0)
    /* E8EF0 000E8E7C 2000B08F */  lw         $s0, 0x20($sp)
    /* E8EF4 000E8E80 2400B18F */  lw         $s1, 0x24($sp)
    /* E8EF8 000E8E84 2800B28F */  lw         $s2, 0x28($sp)
    /* E8EFC 000E8E88 2C00B38F */  lw         $s3, 0x2C($sp)
    /* E8F00 000E8E8C 3000B48F */  lw         $s4, 0x30($sp)
    /* E8F04 000E8E90 3400B58F */  lw         $s5, 0x34($sp)
    /* E8F08 000E8E94 3800B68F */  lw         $s6, 0x38($sp)
    /* E8F0C 000E8E98 3C00B78F */  lw         $s7, 0x3C($sp)
    /* E8F10 000E8E9C 4000BF8F */  lw         $ra, 0x40($sp)
    /* E8F14 000E8EA0 0800E003 */  jr         $ra
    /* E8F18 000E8EA4 5000BD27 */   addiu     $sp, $sp, 0x50
endlabel func_000E8CB0
