.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000E821C, 0x48

glabel func_000E821C
    /* E8290 000E821C 0800A628 */  slti       $a2, $a1, 0x8
    /* E8294 000E8220 0D00C010 */  beqz       $a2, .Leboot_000E8258
    /* E8298 000E8224 00000000 */   nop
    /* E829C 000E8228 0B00A004 */  bltz       $a1, .Leboot_000E8258
    /* E82A0 000E822C 00000000 */   nop
    /* E82A4 000E8230 0F00063C */  lui        $a2, %hi(sym_000E9808)
    /* E82A8 000E8234 80280500 */  sll        $a1, $a1, 2
    /* E82AC 000E8238 0898C624 */  addiu      $a2, $a2, %lo(sym_000E9808)
    /* E82B0 000E823C 2128A600 */  addu       $a1, $a1, $a2
    /* E82B4 000E8240 0000A68C */  lw         $a2, 0x0($a1)
    /* E82B8 000E8244 0100C010 */  beqz       $a2, .Leboot_000E824C
    /* E82BC 000E8248 00000000 */   nop
  .Leboot_000E824C:
    /* E82C0 000E824C 0000A4AC */  sw         $a0, 0x0($a1)
    /* E82C4 000E8250 02000010 */  b          .Leboot_000E825C
    /* E82C8 000E8254 25100000 */   or        $v0, $zero, $zero
  .Leboot_000E8258:
    /* E82CC 000E8258 FFFF0224 */  addiu      $v0, $zero, -0x1
  .Leboot_000E825C:
    /* E82D0 000E825C 0800E003 */  jr         $ra
    /* E82D4 000E8260 00000000 */   nop
endlabel func_000E821C
