.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000F75DC, 0x2C

glabel func_000F75DC
    /* F7650 000F75DC E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* F7654 000F75E0 0400858C */  lw         $a1, 0x4($a0)
    /* F7658 000F75E4 0F00073C */  lui        $a3, %hi(func_000F7198)
    /* F765C 000F75E8 0800848C */  lw         $a0, 0x8($a0)
    /* F7660 000F75EC 18000634 */  ori        $a2, $zero, 0x18
    /* F7664 000F75F0 1000BFAF */  sw         $ra, 0x10($sp)
    /* F7668 000F75F4 A90A050C */  jal        func_00142AA4
    /* F766C 000F75F8 9871E724 */   addiu     $a3, $a3, %lo(func_000F7198)
    /* F7670 000F75FC 1000BF8F */  lw         $ra, 0x10($sp)
    /* F7674 000F7600 0800E003 */  jr         $ra
    /* F7678 000F7604 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_000F75DC
