.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00083C00, 0xAC

glabel func_00083C00
    /* 83C74 00083C00 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 83C78 00083C04 2400A4AF */  sw         $a0, 0x24($sp)
    /* 83C7C 00083C08 2800BFAF */  sw         $ra, 0x28($sp)
    /* 83C80 00083C0C AA3D020C */  jal        func_0008F6A8
    /* 83C84 00083C10 2520A000 */   or        $a0, $a1, $zero
    /* 83C88 00083C14 2400A48F */  lw         $a0, 0x24($sp)
    /* 83C8C 00083C18 1000A2AF */  sw         $v0, 0x10($sp)
    /* 83C90 00083C1C 1800848C */  lw         $a0, 0x18($a0)
    /* 83C94 00083C20 1800A527 */  addiu      $a1, $sp, 0x18
    /* 83C98 00083C24 1800A4AF */  sw         $a0, 0x18($sp)
    /* 83C9C 00083C28 0C000434 */  ori        $a0, $zero, 0xC
    /* 83CA0 00083C2C 2000A5AF */  sw         $a1, 0x20($sp)
    /* 83CA4 00083C30 70C5040C */  jal        func_001315C0
    /* 83CA8 00083C34 1C00A4AF */   sw        $a0, 0x1C($sp)
    /* 83CAC 00083C38 1C00A88F */  lw         $t0, 0x1C($sp)
    /* 83CB0 00083C3C 2000A68F */  lw         $a2, 0x20($sp)
    /* 83CB4 00083C40 1000A78F */  lw         $a3, 0x10($sp)
    /* 83CB8 00083C44 25284000 */  or         $a1, $v0, $zero
    /* 83CBC 00083C48 0A00A014 */  bnez       $a1, .Leboot_00083C74
    /* 83CC0 00083C4C 2400A48F */   lw        $a0, 0x24($sp)
    /* 83CC4 00083C50 2400A4AF */  sw         $a0, 0x24($sp)
    /* 83CC8 00083C54 1000A7AF */  sw         $a3, 0x10($sp)
    /* 83CCC 00083C58 2000A6AF */  sw         $a2, 0x20($sp)
    /* 83CD0 00083C5C AB41050C */  jal        func_001506AC
    /* 83CD4 00083C60 25200001 */   or        $a0, $t0, $zero
    /* 83CD8 00083C64 2000A68F */  lw         $a2, 0x20($sp)
    /* 83CDC 00083C68 1000A78F */  lw         $a3, 0x10($sp)
    /* 83CE0 00083C6C 25284000 */  or         $a1, $v0, $zero
    /* 83CE4 00083C70 2400A48F */  lw         $a0, 0x24($sp)
  .Leboot_00083C74:
    /* 83CE8 00083C74 0800A824 */  addiu      $t0, $a1, 0x8
    /* 83CEC 00083C78 01000055 */  bnel       $t0, $zero, .Leboot_00083C80
    /* 83CF0 00083C7C 000007AD */   sw        $a3, 0x0($t0)
  .Leboot_00083C80:
    /* 83CF4 00083C80 0000C68C */  lw         $a2, 0x0($a2)
    /* 83CF8 00083C84 0400C78C */  lw         $a3, 0x4($a2)
    /* 83CFC 00083C88 0000A6AC */  sw         $a2, 0x0($a1)
    /* 83D00 00083C8C 0400A7AC */  sw         $a3, 0x4($a1)
    /* 83D04 00083C90 0000E5AC */  sw         $a1, 0x0($a3)
    /* 83D08 00083C94 0400C5AC */  sw         $a1, 0x4($a2)
    /* 83D0C 00083C98 6B13020C */  jal        func_00084DAC
    /* 83D10 00083C9C 1400A5AF */   sw        $a1, 0x14($sp)
    /* 83D14 00083CA0 2800BF8F */  lw         $ra, 0x28($sp)
    /* 83D18 00083CA4 0800E003 */  jr         $ra
    /* 83D1C 00083CA8 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_00083C00
