.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000F7EB0, 0x64

glabel func_000F7EB0
    /* F7F24 000F7EB0 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* F7F28 000F7EB4 1E00043C */  lui        $a0, %hi(sym_001DAC10)
    /* F7F2C 000F7EB8 10AC8CC4 */  lwc1       $f12, %lo(sym_001DAC10)($a0)
    /* F7F30 000F7EBC 3443043C */  lui        $a0, (0x43340000 >> 16)
    /* F7F34 000F7EC0 00688444 */  mtc1       $a0, $f13
    /* F7F38 000F7EC4 83630D46 */  div.s      $f14, $f12, $f13
    /* F7F3C 000F7EC8 1E00073C */  lui        $a3, %hi(sym_001DAC14)
    /* F7F40 000F7ECC 7266043C */  lui        $a0, %hi(D_66727573)
    /* F7F44 000F7ED0 1E00083C */  lui        $t0, %hi(sym_001DAC18)
    /* F7F48 000F7ED4 3A000534 */  ori        $a1, $zero, 0x3A
    /* F7F4C 000F7ED8 80000634 */  ori        $a2, $zero, 0x80
    /* F7F50 000F7EDC 73758424 */  addiu      $a0, $a0, %lo(D_66727573)
    /* F7F54 000F7EE0 1000BFAF */  sw         $ra, 0x10($sp)
    /* F7F58 000F7EE4 036B0C46 */  div.s      $f12, $f13, $f12
    /* F7F5C 000F7EE8 14ACEEE4 */  swc1       $f14, %lo(sym_001DAC14)($a3)
    /* F7F60 000F7EEC 611B040C */  jal        elem_register_chunk_tag
    /* F7F64 000F7EF0 18AC0CE5 */   swc1      $f12, %lo(sym_001DAC18)($t0)
    /* F7F68 000F7EF4 6E74043C */  lui        $a0, %hi(D_746E6F66)
    /* F7F6C 000F7EF8 01000534 */  ori        $a1, $zero, 0x1
    /* F7F70 000F7EFC 20000634 */  ori        $a2, $zero, 0x20
    /* F7F74 000F7F00 611B040C */  jal        elem_register_chunk_tag
    /* F7F78 000F7F04 666F8424 */   addiu     $a0, $a0, %lo(D_746E6F66)
    /* F7F7C 000F7F08 1000BF8F */  lw         $ra, 0x10($sp)
    /* F7F80 000F7F0C 0800E003 */  jr         $ra
    /* F7F84 000F7F10 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_000F7EB0
