.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00080378, 0x4C

glabel func_00080378
    /* 803EC 00080378 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 803F0 0008037C FF00A530 */  andi       $a1, $a1, 0xFF
    /* 803F4 00080380 0400868C */  lw         $a2, 0x4($a0)
    /* 803F8 00080384 FDFF0724 */  addiu      $a3, $zero, -0x3
    /* 803FC 00080388 0100A530 */  andi       $a1, $a1, 0x1
    /* 80400 0008038C 2430C700 */  and        $a2, $a2, $a3
    /* 80404 00080390 40280500 */  sll        $a1, $a1, 1
    /* 80408 00080394 2528C500 */  or         $a1, $a2, $a1
    /* 8040C 00080398 2C00868C */  lw         $a2, 0x2C($a0)
    /* 80410 0008039C 040085AC */  sw         $a1, 0x4($a0)
    /* 80414 000803A0 8800C524 */  addiu      $a1, $a2, 0x88
    /* 80418 000803A4 0000A684 */  lh         $a2, 0x0($a1)
    /* 8041C 000803A8 0400A58C */  lw         $a1, 0x4($a1)
    /* 80420 000803AC 1000BFAF */  sw         $ra, 0x10($sp)
    /* 80424 000803B0 09F8A000 */  jalr       $a1
    /* 80428 000803B4 21208600 */   addu      $a0, $a0, $a2
    /* 8042C 000803B8 1000BF8F */  lw         $ra, 0x10($sp)
    /* 80430 000803BC 0800E003 */  jr         $ra
    /* 80434 000803C0 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_00080378
