.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00181344, 0x1C

glabel func_00181344
    /* 1813B8 00181344 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 1813BC 00181348 1000BFAF */  sw         $ra, 0x10($sp)
    /* 1813C0 0018134C FC5E050C */  jal        func_00157BF0
    /* 1813C4 00181350 0400858C */   lw        $a1, 0x4($a0)
    /* 1813C8 00181354 1000BF8F */  lw         $ra, 0x10($sp)
    /* 1813CC 00181358 0800E003 */  jr         $ra
    /* 1813D0 0018135C 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_00181344
