.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0008BF98, 0x28

glabel func_0008BF98
    /* 8C00C 0008BF98 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 8C010 0008BF9C 1D00043C */  lui        $a0, %hi(str_gameObjectGenerator)
    /* 8C014 0008BFA0 1900053C */  lui        $a1, %hi(func_0018F6E8)
    /* 8C018 0008BFA4 508A8424 */  addiu      $a0, $a0, %lo(str_gameObjectGenerator)
    /* 8C01C 0008BFA8 1000BFAF */  sw         $ra, 0x10($sp)
    /* 8C020 0008BFAC F7E8020C */  jal        func_000BA3DC
    /* 8C024 0008BFB0 E8F6A524 */   addiu     $a1, $a1, %lo(func_0018F6E8)
    /* 8C028 0008BFB4 1000BF8F */  lw         $ra, 0x10($sp)
    /* 8C02C 0008BFB8 0800E003 */  jr         $ra
    /* 8C030 0008BFBC 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0008BF98
