.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0004DB98, 0x254

glabel func_0004DB98
    /* 4DC0C 0004DB98 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 4DC10 0004DB9C 1D00043C */  lui        $a0, %hi(sym_001D3E70)
    /* 4DC14 0004DBA0 703E8CC4 */  lwc1       $f12, %lo(sym_001D3E70)($a0)
    /* 4DC18 0004DBA4 3443043C */  lui        $a0, (0x43340000 >> 16)
    /* 4DC1C 0004DBA8 00688444 */  mtc1       $a0, $f13
    /* 4DC20 0004DBAC 83630D46 */  div.s      $f14, $f12, $f13
    /* 4DC24 0004DBB0 1D00073C */  lui        $a3, %hi(sym_001D3E74)
    /* 4DC28 0004DBB4 7665043C */  lui        $a0, %hi(D_65766177)
    /* 4DC2C 0004DBB8 1D00083C */  lui        $t0, %hi(sym_001D3E78)
    /* 4DC30 0004DBBC 09000534 */  ori        $a1, $zero, 0x9
    /* 4DC34 0004DBC0 20000634 */  ori        $a2, $zero, 0x20
    /* 4DC38 0004DBC4 77618424 */  addiu      $a0, $a0, %lo(D_65766177)
    /* 4DC3C 0004DBC8 1000B4E7 */  swc1       $f20, 0x10($sp)
    /* 4DC40 0004DBCC 1400BFAF */  sw         $ra, 0x14($sp)
    /* 4DC44 0004DBD0 036B0C46 */  div.s      $f12, $f13, $f12
    /* 4DC48 0004DBD4 743EEEE4 */  swc1       $f14, %lo(sym_001D3E74)($a3)
    /* 4DC4C 0004DBD8 611B040C */  jal        elem_register_chunk_tag
    /* 4DC50 0004DBDC 783E0CE5 */   swc1      $f12, %lo(sym_001D3E78)($t0)
    /* 4DC54 0004DBE0 7461043C */  lui        $a0, %hi(D_61746473)
    /* 4DC58 0004DBE4 01000534 */  ori        $a1, $zero, 0x1
    /* 4DC5C 0004DBE8 20000634 */  ori        $a2, $zero, 0x20
    /* 4DC60 0004DBEC 611B040C */  jal        elem_register_chunk_tag
    /* 4DC64 0004DBF0 73648424 */   addiu     $a0, $a0, %lo(D_61746473)
    /* 4DC68 0004DBF4 6220043C */  lui        $a0, %hi(D_20626D78)
    /* 4DC6C 0004DBF8 25280000 */  or         $a1, $zero, $zero
    /* 4DC70 0004DBFC 40000634 */  ori        $a2, $zero, 0x40
    /* 4DC74 0004DC00 611B040C */  jal        elem_register_chunk_tag
    /* 4DC78 0004DC04 786D8424 */   addiu     $a0, $a0, %lo(D_20626D78)
    /* 4DC7C 0004DC08 7320043C */  lui        $a0, %hi(D_20736D78)
    /* 4DC80 0004DC0C 25280000 */  or         $a1, $zero, $zero
    /* 4DC84 0004DC10 40000634 */  ori        $a2, $zero, 0x40
    /* 4DC88 0004DC14 611B040C */  jal        elem_register_chunk_tag
    /* 4DC8C 0004DC18 786D8424 */   addiu     $a0, $a0, %lo(D_20736D78)
    /* 4DC90 0004DC1C 6820043C */  lui        $a0, %hi(D_20686D78)
    /* 4DC94 0004DC20 25280000 */  or         $a1, $zero, $zero
    /* 4DC98 0004DC24 20000634 */  ori        $a2, $zero, 0x20
    /* 4DC9C 0004DC28 611B040C */  jal        elem_register_chunk_tag
    /* 4DCA0 0004DC2C 786D8424 */   addiu     $a0, $a0, %lo(D_20686D78)
    /* 4DCA4 0004DC30 626C043C */  lui        $a0, %hi(D_6C626174)
    /* 4DCA8 0004DC34 05000534 */  ori        $a1, $zero, 0x5
    /* 4DCAC 0004DC38 20000634 */  ori        $a2, $zero, 0x20
    /* 4DCB0 0004DC3C 611B040C */  jal        elem_register_chunk_tag
    /* 4DCB4 0004DC40 74618424 */   addiu     $a0, $a0, %lo(D_6C626174)
    /* 4DCB8 0004DC44 7266043C */  lui        $a0, %hi(D_66727573)
    /* 4DCBC 0004DC48 3A000534 */  ori        $a1, $zero, 0x3A
    /* 4DCC0 0004DC4C 80000634 */  ori        $a2, $zero, 0x80
    /* 4DCC4 0004DC50 611B040C */  jal        elem_register_chunk_tag
    /* 4DCC8 0004DC54 73758424 */   addiu     $a0, $a0, %lo(D_66727573)
    /* 4DCCC 0004DC58 00A08044 */  mtc1       $zero, $f20
    /* 4DCD0 0004DC5C 1D00043C */  lui        $a0, %hi(sym_001D3E7C)
    /* 4DCD4 0004DC60 1C00053C */  lui        $a1, %hi(str_JoystickX_51B0)
    /* 4DCD8 0004DC64 06A30046 */  mov.s      $f12, $f20
    /* 4DCDC 0004DC68 7C3E8424 */  addiu      $a0, $a0, %lo(sym_001D3E7C)
    /* 4DCE0 0004DC6C 31BA020C */  jal        func_000AE8C4
    /* 4DCE4 0004DC70 B051A524 */   addiu     $a1, $a1, %lo(str_JoystickX_51B0)
    /* 4DCE8 0004DC74 1D00043C */  lui        $a0, %hi(sym_001D3E80)
    /* 4DCEC 0004DC78 06A30046 */  mov.s      $f12, $f20
    /* 4DCF0 0004DC7C 1C00053C */  lui        $a1, %hi(str_JoystickY_51BC)
    /* 4DCF4 0004DC80 803E8424 */  addiu      $a0, $a0, %lo(sym_001D3E80)
    /* 4DCF8 0004DC84 31BA020C */  jal        func_000AE8C4
    /* 4DCFC 0004DC88 BC51A524 */   addiu     $a1, $a1, %lo(str_JoystickY_51BC)
    /* 4DD00 0004DC8C 1D00043C */  lui        $a0, %hi(sym_001D3E84)
    /* 4DD04 0004DC90 06A30046 */  mov.s      $f12, $f20
    /* 4DD08 0004DC94 1C00053C */  lui        $a1, %hi(str_Button_Circle_51C8)
    /* 4DD0C 0004DC98 843E8424 */  addiu      $a0, $a0, %lo(sym_001D3E84)
    /* 4DD10 0004DC9C 31BA020C */  jal        func_000AE8C4
    /* 4DD14 0004DCA0 C851A524 */   addiu     $a1, $a1, %lo(str_Button_Circle_51C8)
    /* 4DD18 0004DCA4 1D00043C */  lui        $a0, %hi(sym_001D3E88)
    /* 4DD1C 0004DCA8 06A30046 */  mov.s      $f12, $f20
    /* 4DD20 0004DCAC 1C00053C */  lui        $a1, %hi(str_Button_Square_51D8)
    /* 4DD24 0004DCB0 883E8424 */  addiu      $a0, $a0, %lo(sym_001D3E88)
    /* 4DD28 0004DCB4 31BA020C */  jal        func_000AE8C4
    /* 4DD2C 0004DCB8 D851A524 */   addiu     $a1, $a1, %lo(str_Button_Square_51D8)
    /* 4DD30 0004DCBC 1D00043C */  lui        $a0, %hi(sym_001D3E8C)
    /* 4DD34 0004DCC0 06A30046 */  mov.s      $f12, $f20
    /* 4DD38 0004DCC4 1C00053C */  lui        $a1, %hi(str_Button_Triangle_51E8)
    /* 4DD3C 0004DCC8 8C3E8424 */  addiu      $a0, $a0, %lo(sym_001D3E8C)
    /* 4DD40 0004DCCC 31BA020C */  jal        func_000AE8C4
    /* 4DD44 0004DCD0 E851A524 */   addiu     $a1, $a1, %lo(str_Button_Triangle_51E8)
    /* 4DD48 0004DCD4 1D00043C */  lui        $a0, %hi(sym_001D3E90)
    /* 4DD4C 0004DCD8 06A30046 */  mov.s      $f12, $f20
    /* 4DD50 0004DCDC 1C00053C */  lui        $a1, %hi(str_Button_X_51F8)
    /* 4DD54 0004DCE0 903E8424 */  addiu      $a0, $a0, %lo(sym_001D3E90)
    /* 4DD58 0004DCE4 31BA020C */  jal        func_000AE8C4
    /* 4DD5C 0004DCE8 F851A524 */   addiu     $a1, $a1, %lo(str_Button_X_51F8)
    /* 4DD60 0004DCEC 1D00043C */  lui        $a0, %hi(sym_001D3E94)
    /* 4DD64 0004DCF0 06A30046 */  mov.s      $f12, $f20
    /* 4DD68 0004DCF4 1C00053C */  lui        $a1, %hi(str_Confirm_5204)
    /* 4DD6C 0004DCF8 943E8424 */  addiu      $a0, $a0, %lo(sym_001D3E94)
    /* 4DD70 0004DCFC 31BA020C */  jal        func_000AE8C4
    /* 4DD74 0004DD00 0452A524 */   addiu     $a1, $a1, %lo(str_Confirm_5204)
    /* 4DD78 0004DD04 1D00043C */  lui        $a0, %hi(sym_001D3E98)
    /* 4DD7C 0004DD08 06A30046 */  mov.s      $f12, $f20
    /* 4DD80 0004DD0C 1C00053C */  lui        $a1, %hi(str_Cancel_520C)
    /* 4DD84 0004DD10 983E8424 */  addiu      $a0, $a0, %lo(sym_001D3E98)
    /* 4DD88 0004DD14 31BA020C */  jal        func_000AE8C4
    /* 4DD8C 0004DD18 0C52A524 */   addiu     $a1, $a1, %lo(str_Cancel_520C)
    /* 4DD90 0004DD1C 1D00043C */  lui        $a0, %hi(sym_001D3E9C)
    /* 4DD94 0004DD20 06A30046 */  mov.s      $f12, $f20
    /* 4DD98 0004DD24 1C00053C */  lui        $a1, %hi(str_Start_5214)
    /* 4DD9C 0004DD28 9C3E8424 */  addiu      $a0, $a0, %lo(sym_001D3E9C)
    /* 4DDA0 0004DD2C 31BA020C */  jal        func_000AE8C4
    /* 4DDA4 0004DD30 1452A524 */   addiu     $a1, $a1, %lo(str_Start_5214)
    /* 4DDA8 0004DD34 1D00043C */  lui        $a0, %hi(sym_001D3EA0)
    /* 4DDAC 0004DD38 06A30046 */  mov.s      $f12, $f20
    /* 4DDB0 0004DD3C 1C00053C */  lui        $a1, %hi(str_ActiveController_521C)
    /* 4DDB4 0004DD40 A03E8424 */  addiu      $a0, $a0, %lo(sym_001D3EA0)
    /* 4DDB8 0004DD44 31BA020C */  jal        func_000AE8C4
    /* 4DDBC 0004DD48 1C52A524 */   addiu     $a1, $a1, %lo(str_ActiveController_521C)
    /* 4DDC0 0004DD4C 1D00043C */  lui        $a0, %hi(sym_001D3E10)
    /* 4DDC4 0004DD50 9A4F050C */  jal        func_00153E68
    /* 4DDC8 0004DD54 103E8424 */   addiu     $a0, $a0, %lo(sym_001D3E10)
    /* 4DDCC 0004DD58 1D00043C */  lui        $a0, %hi(sym_001D3EB0)
    /* 4DDD0 0004DD5C 7631050C */  jal        func_0014C5D8
    /* 4DDD4 0004DD60 B03E8424 */   addiu     $a0, $a0, %lo(sym_001D3EB0)
    /* 4DDD8 0004DD64 1D00043C */  lui        $a0, %hi(sym_001D3E1C)
    /* 4DDDC 0004DD68 9A4F050C */  jal        func_00153E68
    /* 4DDE0 0004DD6C 1C3E8424 */   addiu     $a0, $a0, %lo(sym_001D3E1C)
    /* 4DDE4 0004DD70 1D00043C */  lui        $a0, %hi(sym_001D3EBC)
    /* 4DDE8 0004DD74 7631050C */  jal        func_0014C5D8
    /* 4DDEC 0004DD78 BC3E8424 */   addiu     $a0, $a0, %lo(sym_001D3EBC)
    /* 4DDF0 0004DD7C 1D00043C */  lui        $a0, %hi(sym_001D3E28)
    /* 4DDF4 0004DD80 9A4F050C */  jal        func_00153E68
    /* 4DDF8 0004DD84 283E8424 */   addiu     $a0, $a0, %lo(sym_001D3E28)
    /* 4DDFC 0004DD88 1D00043C */  lui        $a0, %hi(sym_001D3EC8)
    /* 4DE00 0004DD8C 7631050C */  jal        func_0014C5D8
    /* 4DE04 0004DD90 C83E8424 */   addiu     $a0, $a0, %lo(sym_001D3EC8)
    /* 4DE08 0004DD94 1D00043C */  lui        $a0, %hi(sym_001D3E34)
    /* 4DE0C 0004DD98 9A4F050C */  jal        func_00153E68
    /* 4DE10 0004DD9C 343E8424 */   addiu     $a0, $a0, %lo(sym_001D3E34)
    /* 4DE14 0004DDA0 1D00043C */  lui        $a0, %hi(sym_001D3ED4)
    /* 4DE18 0004DDA4 7631050C */  jal        func_0014C5D8
    /* 4DE1C 0004DDA8 D43E8424 */   addiu     $a0, $a0, %lo(sym_001D3ED4)
    /* 4DE20 0004DDAC 1D00043C */  lui        $a0, %hi(sym_001D3E40)
    /* 4DE24 0004DDB0 9A4F050C */  jal        func_00153E68
    /* 4DE28 0004DDB4 403E8424 */   addiu     $a0, $a0, %lo(sym_001D3E40)
    /* 4DE2C 0004DDB8 1D00043C */  lui        $a0, %hi(sym_001D3EE0)
    /* 4DE30 0004DDBC 7631050C */  jal        func_0014C5D8
    /* 4DE34 0004DDC0 E03E8424 */   addiu     $a0, $a0, %lo(sym_001D3EE0)
    /* 4DE38 0004DDC4 1D00043C */  lui        $a0, %hi(sym_001D3E4C)
    /* 4DE3C 0004DDC8 9A4F050C */  jal        func_00153E68
    /* 4DE40 0004DDCC 4C3E8424 */   addiu     $a0, $a0, %lo(sym_001D3E4C)
    /* 4DE44 0004DDD0 1D00043C */  lui        $a0, %hi(sym_001D3EEC)
    /* 4DE48 0004DDD4 7631050C */  jal        func_0014C5D8
    /* 4DE4C 0004DDD8 EC3E8424 */   addiu     $a0, $a0, %lo(sym_001D3EEC)
    /* 4DE50 0004DDDC 1000B4C7 */  lwc1       $f20, 0x10($sp)
    /* 4DE54 0004DDE0 1400BF8F */  lw         $ra, 0x14($sp)
    /* 4DE58 0004DDE4 0800E003 */  jr         $ra
    /* 4DE5C 0004DDE8 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0004DB98
