.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0004584C, 0x5C

glabel func_0004584C
    /* 458C0 0004584C E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 458C4 00045850 1000B0AF */  sw         $s0, 0x10($sp)
    /* 458C8 00045854 0700103C */  lui        $s0, %hi(sym_000734D4)
    /* 458CC 00045858 1C00063C */  lui        $a2, %hi(str_readAllData)
    /* 458D0 0004585C D434048E */  lw         $a0, %lo(sym_000734D4)($s0)
    /* 458D4 00045860 EFD80524 */  addiu      $a1, $zero, -0x2711
    /* 458D8 00045864 1400BFAF */  sw         $ra, 0x14($sp)
    /* 458DC 00045868 DC40040C */  jal        func_00110370
    /* 458E0 0004586C E049C624 */   addiu     $a2, $a2, %lo(str_readAllData)
    /* 458E4 00045870 D434048E */  lw         $a0, %lo(sym_000734D4)($s0)
    /* 458E8 00045874 25280000 */  or         $a1, $zero, $zero
    /* 458EC 00045878 BFC6020C */  jal        func_000B1AFC
    /* 458F0 0004587C 01000634 */   ori       $a2, $zero, 0x1
    /* 458F4 00045880 1C00063C */  lui        $a2, %hi(str_persistentData)
    /* 458F8 00045884 D434048E */  lw         $a0, %lo(sym_000734D4)($s0)
    /* 458FC 00045888 EFD80524 */  addiu      $a1, $zero, -0x2711
    /* 45900 0004588C B641040C */  jal        func_001106D8
    /* 45904 00045890 D049C624 */   addiu     $a2, $a2, %lo(str_persistentData)
    /* 45908 00045894 01000234 */  ori        $v0, $zero, 0x1
    /* 4590C 00045898 1000B08F */  lw         $s0, 0x10($sp)
    /* 45910 0004589C 1400BF8F */  lw         $ra, 0x14($sp)
    /* 45914 000458A0 0800E003 */  jr         $ra
    /* 45918 000458A4 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0004584C
