.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000C9048, 0x130

glabel func_000C9048
    /* C90BC 000C9048 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* C90C0 000C904C 0000858C */  lw         $a1, 0x0($a0)
    /* C90C4 000C9050 2000B1AF */  sw         $s1, 0x20($sp)
    /* C90C8 000C9054 00001134 */  ori        $s1, $zero, 0x0
    /* C90CC 000C9058 1C00B0AF */  sw         $s0, 0x1C($sp)
    /* C90D0 000C905C 2400BFAF */  sw         $ra, 0x24($sp)
    /* C90D4 000C9060 2E00A010 */  beqz       $a1, .Leboot_000C911C
    /* C90D8 000C9064 25808000 */   or        $s0, $a0, $zero
    /* C90DC 000C9068 C31E030C */  jal        func_000C7B0C
    /* C90E0 000C906C 00000000 */   nop
    /* C90E4 000C9070 25384000 */  or         $a3, $v0, $zero
    /* C90E8 000C9074 0000E68C */  lw         $a2, 0x0($a3)
    /* C90EC 000C9078 2520C000 */  or         $a0, $a2, $zero
    /* C90F0 000C907C 04008524 */  addiu      $a1, $a0, 0x4
    /* C90F4 000C9080 0000A58C */  lw         $a1, 0x0($a1)
    /* C90F8 000C9084 1000A010 */  beqz       $a1, .Leboot_000C90C8
    /* C90FC 000C9088 00000000 */   nop
    /* C9100 000C908C 1800A0A3 */  sb         $zero, 0x18($sp)
    /* C9104 000C9090 0000088E */  lw         $t0, 0x0($s0)
    /* C9108 000C9094 0000E68C */  lw         $a2, 0x0($a3)
    /* C910C 000C9098 1000A98C */  lw         $t1, 0x10($a1)
  .Leboot_000C909C:
    /* C9110 000C909C 2A482801 */  slt        $t1, $t1, $t0
    /* C9114 000C90A0 FF002931 */  andi       $t1, $t1, 0xFF
    /* C9118 000C90A4 05002055 */  bnel       $t1, $zero, .Leboot_000C90BC
    /* C911C 000C90A8 0C00A524 */   addiu     $a1, $a1, 0xC
    /* C9120 000C90AC 2520A000 */  or         $a0, $a1, $zero
    /* C9124 000C90B0 08008524 */  addiu      $a1, $a0, 0x8
    /* C9128 000C90B4 02000010 */  b          .Leboot_000C90C0
    /* C912C 000C90B8 0000A58C */   lw        $a1, 0x0($a1)
  .Leboot_000C90BC:
    /* C9130 000C90BC 0000A58C */  lw         $a1, 0x0($a1)
  .Leboot_000C90C0:
    /* C9134 000C90C0 F6FFA054 */  bnel       $a1, $zero, .Leboot_000C909C
    /* C9138 000C90C4 1000A98C */   lw        $t1, 0x10($a1)
  .Leboot_000C90C8:
    /* C913C 000C90C8 09008650 */  beql       $a0, $a2, .Leboot_000C90F0
    /* C9140 000C90CC 0000E48C */   lw        $a0, 0x0($a3)
    /* C9144 000C90D0 1900A0A3 */  sb         $zero, 0x19($sp)
    /* C9148 000C90D4 0000058E */  lw         $a1, 0x0($s0)
    /* C914C 000C90D8 1000868C */  lw         $a2, 0x10($a0)
    /* C9150 000C90DC 2A28A600 */  slt        $a1, $a1, $a2
    /* C9154 000C90E0 FF00A530 */  andi       $a1, $a1, 0xFF
    /* C9158 000C90E4 0200A010 */  beqz       $a1, .Leboot_000C90F0
    /* C915C 000C90E8 00000000 */   nop
    /* C9160 000C90EC 0000E48C */  lw         $a0, 0x0($a3)
  .Leboot_000C90F0:
    /* C9164 000C90F0 C31E030C */  jal        func_000C7B0C
    /* C9168 000C90F4 1400A4AF */   sw        $a0, 0x14($sp)
    /* C916C 000C90F8 0000458C */  lw         $a1, 0x0($v0)
    /* C9170 000C90FC 1400A48F */  lw         $a0, 0x14($sp)
    /* C9174 000C9100 1000A5AF */  sw         $a1, 0x10($sp)
    /* C9178 000C9104 26288500 */  xor        $a1, $a0, $a1
    /* C917C 000C9108 2B280500 */  sltu       $a1, $zero, $a1
    /* C9180 000C910C FF00A530 */  andi       $a1, $a1, 0xFF
    /* C9184 000C9110 0200A010 */  beqz       $a1, .Leboot_000C911C
    /* C9188 000C9114 00000000 */   nop
    /* C918C 000C9118 1400918C */  lw         $s1, 0x14($a0)
  .Leboot_000C911C:
    /* C9190 000C911C 0A002016 */  bnez       $s1, .Leboot_000C9148
    /* C9194 000C9120 00000000 */   nop
    /* C9198 000C9124 0100043C */  lui        $a0, %hi(sym_0000D328)
    /* C919C 000C9128 28D3848C */  lw         $a0, %lo(sym_0000D328)($a0)
    /* C91A0 000C912C 0A008010 */  beqz       $a0, .Leboot_000C9158
    /* C91A4 000C9130 00000000 */   nop
    /* C91A8 000C9134 25288000 */  or         $a1, $a0, $zero
    /* C91AC 000C9138 09F8A000 */  jalr       $a1
    /* C91B0 000C913C 25200002 */   or        $a0, $s0, $zero
    /* C91B4 000C9140 08000010 */  b          .Leboot_000C9164
    /* C91B8 000C9144 00000000 */   nop
  .Leboot_000C9148:
    /* C91BC 000C9148 09F82002 */  jalr       $s1
    /* C91C0 000C914C 25200002 */   or        $a0, $s0, $zero
    /* C91C4 000C9150 04000010 */  b          .Leboot_000C9164
    /* C91C8 000C9154 00000000 */   nop
  .Leboot_000C9158:
    /* C91CC 000C9158 2400048E */  lw         $a0, 0x24($s0)
    /* C91D0 000C915C 3282060C */  jal        func_001A08C8
    /* C91D4 000C9160 25280002 */   or        $a1, $s0, $zero
  .Leboot_000C9164:
    /* C91D8 000C9164 1C00B08F */  lw         $s0, 0x1C($sp)
    /* C91DC 000C9168 2000B18F */  lw         $s1, 0x20($sp)
    /* C91E0 000C916C 2400BF8F */  lw         $ra, 0x24($sp)
    /* C91E4 000C9170 0800E003 */  jr         $ra
    /* C91E8 000C9174 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_000C9048
