.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000BFB14, 0x60

glabel func_000BFB14
    /* BFB88 000BFB14 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* BFB8C 000BFB18 1000B0AF */  sw         $s0, 0x10($sp)
    /* BFB90 000BFB1C 1400B1AF */  sw         $s1, 0x14($sp)
    /* BFB94 000BFB20 1800B2AF */  sw         $s2, 0x18($sp)
    /* BFB98 000BFB24 1C00BFAF */  sw         $ra, 0x1C($sp)
    /* BFB9C 000BFB28 00001234 */  ori        $s2, $zero, 0x0
    /* BFBA0 000BFB2C 1C009024 */  addiu      $s0, $a0, 0x1C
    /* BFBA4 000BFB30 25888000 */  or         $s1, $a0, $zero
  .Leboot_000BFB34:
    /* BFBA8 000BFB34 2000248E */  lw         $a0, 0x20($s1)
    /* BFBAC 000BFB38 04008010 */  beqz       $a0, .Leboot_000BFB4C
    /* BFBB0 000BFB3C 00000000 */   nop
    /* BFBB4 000BFB40 FC60030C */  jal        func_000D83F0
    /* BFBB8 000BFB44 25280002 */   or        $a1, $s0, $zero
    /* BFBBC 000BFB48 200020AE */  sw         $zero, 0x20($s1)
  .Leboot_000BFB4C:
    /* BFBC0 000BFB4C 01005226 */  addiu      $s2, $s2, 0x1
    /* BFBC4 000BFB50 0A00442A */  slti       $a0, $s2, 0xA
    /* BFBC8 000BFB54 F7FF8014 */  bnez       $a0, .Leboot_000BFB34
    /* BFBCC 000BFB58 04003126 */   addiu     $s1, $s1, 0x4
    /* BFBD0 000BFB5C 1000B08F */  lw         $s0, 0x10($sp)
    /* BFBD4 000BFB60 1400B18F */  lw         $s1, 0x14($sp)
    /* BFBD8 000BFB64 1800B28F */  lw         $s2, 0x18($sp)
    /* BFBDC 000BFB68 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* BFBE0 000BFB6C 0800E003 */  jr         $ra
    /* BFBE4 000BFB70 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_000BFB14
