.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0009F730, 0x78

glabel func_0009F730
    /* 9F7A4 0009F730 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 9F7A8 0009F734 1800B1AF */  sw         $s1, 0x18($sp)
    /* 9F7AC 0009F738 25888000 */  or         $s1, $a0, $zero
    /* 9F7B0 0009F73C 1400B0AF */  sw         $s0, 0x14($sp)
    /* 9F7B4 0009F740 1C00BFAF */  sw         $ra, 0x1C($sp)
    /* 9F7B8 0009F744 13008010 */  beqz       $a0, .Leboot_0009F794
    /* 9F7BC 0009F748 2580A000 */   or        $s0, $a1, $zero
    /* 9F7C0 0009F74C 1F00043C */  lui        $a0, %hi(sym_001E8F70)
    /* 9F7C4 0009F750 708F8424 */  addiu      $a0, $a0, %lo(sym_001E8F70)
    /* 9F7C8 0009F754 0A002012 */  beqz       $s1, .Leboot_0009F780
    /* 9F7CC 0009F758 0C0024AE */   sw        $a0, 0xC($s1)
    /* 9F7D0 0009F75C 0000248E */  lw         $a0, 0x0($s1)
    /* 9F7D4 0009F760 07002012 */  beqz       $s1, .Leboot_0009F780
    /* 9F7D8 0009F764 1000A0A3 */   sb        $zero, 0x10($sp)
    /* 9F7DC 0009F768 06008050 */  beql       $a0, $zero, .Leboot_0009F784
    /* 9F7E0 0009F76C 01000432 */   andi      $a0, $s0, 0x1
    /* 9F7E4 0009F770 04008050 */  beql       $a0, $zero, .Leboot_0009F784
    /* 9F7E8 0009F774 01000432 */   andi      $a0, $s0, 0x1
    /* 9F7EC 0009F778 DDC6040C */  jal        func_00131B74
    /* 9F7F0 0009F77C 00000000 */   nop
  .Leboot_0009F780:
    /* 9F7F4 0009F780 01000432 */  andi       $a0, $s0, 0x1
  .Leboot_0009F784:
    /* 9F7F8 0009F784 03008010 */  beqz       $a0, .Leboot_0009F794
    /* 9F7FC 0009F788 00000000 */   nop
    /* 9F800 0009F78C C79D040C */  jal        func_0012771C
    /* 9F804 0009F790 25202002 */   or        $a0, $s1, $zero
  .Leboot_0009F794:
    /* 9F808 0009F794 1400B08F */  lw         $s0, 0x14($sp)
    /* 9F80C 0009F798 1800B18F */  lw         $s1, 0x18($sp)
    /* 9F810 0009F79C 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* 9F814 0009F7A0 0800E003 */  jr         $ra
    /* 9F818 0009F7A4 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0009F730
