.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000AB4C8, 0x128

glabel func_000AB4C8
    /* AB53C 000AB4C8 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* AB540 000AB4CC 1001858C */  lw         $a1, 0x110($a0)
    /* AB544 000AB4D0 1000B0AF */  sw         $s0, 0x10($sp)
    /* AB548 000AB4D4 25808000 */  or         $s0, $a0, $zero
    /* AB54C 000AB4D8 5C00A48C */  lw         $a0, 0x5C($a1)
    /* AB550 000AB4DC 1400B1AF */  sw         $s1, 0x14($sp)
    /* AB554 000AB4E0 02008428 */  slti       $a0, $a0, 0x2
    /* AB558 000AB4E4 1800B2AF */  sw         $s2, 0x18($sp)
    /* AB55C 000AB4E8 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* AB560 000AB4EC 2000B4AF */  sw         $s4, 0x20($sp)
    /* AB564 000AB4F0 2400BFAF */  sw         $ra, 0x24($sp)
    /* AB568 000AB4F4 03008010 */  beqz       $a0, .Leboot_000AB504
    /* AB56C 000AB4F8 00000000 */   nop
    /* AB570 000AB4FC 34000010 */  b          .Leboot_000AB5D0
    /* AB574 000AB500 1C0100A2 */   sb        $zero, 0x11C($s0)
  .Leboot_000AB504:
    /* AB578 000AB504 00608044 */  mtc1       $zero, $f12
    /* AB57C 000AB508 E80300AE */  sw         $zero, 0x3E8($s0)
    /* AB580 000AB50C E4030CE6 */  swc1       $f12, 0x3E4($s0)
    /* AB584 000AB510 25200002 */  or         $a0, $s0, $zero
    /* AB588 000AB514 8DAF020C */  jal        func_000ABE34
    /* AB58C 000AB518 01000534 */   ori       $a1, $zero, 0x1
    /* AB590 000AB51C 18010CC6 */  lwc1       $f12, 0x118($s0)
    /* AB594 000AB520 14010DC6 */  lwc1       $f13, 0x114($s0)
    /* AB598 000AB524 1001048E */  lw         $a0, 0x110($s0)
    /* AB59C 000AB528 02630D46 */  mul.s      $f12, $f12, $f13
    /* AB5A0 000AB52C 803F053C */  lui        $a1, (0x3F800000 >> 16)
    /* AB5A4 000AB530 40008EC4 */  lwc1       $f14, 0x40($a0)
    /* AB5A8 000AB534 00788544 */  mtc1       $a1, $f15
    /* AB5AC 000AB538 B0030FE6 */  swc1       $f15, 0x3B0($s0)
    /* AB5B0 000AB53C B4030FE6 */  swc1       $f15, 0x3B4($s0)
    /* AB5B4 000AB540 02630E46 */  mul.s      $f12, $f12, $f14
    /* AB5B8 000AB544 B8030FE6 */  swc1       $f15, 0x3B8($s0)
    /* AB5BC 000AB548 BC030CE6 */  swc1       $f12, 0x3BC($s0)
    /* AB5C0 000AB54C 5C00858C */  lw         $a1, 0x5C($a0)
    /* AB5C4 000AB550 25200002 */  or         $a0, $s0, $zero
    /* AB5C8 000AB554 F80305A6 */  sh         $a1, 0x3F8($s0)
    /* AB5CC 000AB558 C8AF020C */  jal        func_000ABF20
    /* AB5D0 000AB55C F4010534 */   ori       $a1, $zero, 0x1F4
    /* AB5D4 000AB560 25884000 */  or         $s1, $v0, $zero
    /* AB5D8 000AB564 25200002 */  or         $a0, $s0, $zero
    /* AB5DC 000AB568 25280000 */  or         $a1, $zero, $zero
    /* AB5E0 000AB56C 64B0020C */  jal        func_000AC190
    /* AB5E4 000AB570 25300000 */   or        $a2, $zero, $zero
    /* AB5E8 000AB574 01C9143C */  lui        $s4, %hi(D_C9010100)
    /* AB5EC 000AB578 980111AE */  sw         $s1, 0x198($s0)
    /* AB5F0 000AB57C 00019426 */  addiu      $s4, $s4, %lo(D_C9010100)
    /* AB5F4 000AB580 9C0114AE */  sw         $s4, 0x19C($s0)
    /* AB5F8 000AB584 1001048E */  lw         $a0, 0x110($s0)
    /* AB5FC 000AB588 01001334 */  ori        $s3, $zero, 0x1
    /* AB600 000AB58C 5C00848C */  lw         $a0, 0x5C($a0)
    /* AB604 000AB590 2A206402 */  slt        $a0, $s3, $a0
    /* AB608 000AB594 0E008010 */  beqz       $a0, .Leboot_000AB5D0
    /* AB60C 000AB598 04001234 */   ori       $s2, $zero, 0x4
    /* AB610 000AB59C 40001126 */  addiu      $s1, $s0, 0x40
  .Leboot_000AB5A0:
    /* AB614 000AB5A0 25200002 */  or         $a0, $s0, $zero
    /* AB618 000AB5A4 25286002 */  or         $a1, $s3, $zero
    /* AB61C 000AB5A8 64B0020C */  jal        func_000AC190
    /* AB620 000AB5AC 25306002 */   or        $a2, $s3, $zero
    /* AB624 000AB5B0 980132AE */  sw         $s2, 0x198($s1)
    /* AB628 000AB5B4 9C0134AE */  sw         $s4, 0x19C($s1)
    /* AB62C 000AB5B8 1001048E */  lw         $a0, 0x110($s0)
    /* AB630 000AB5BC 01007326 */  addiu      $s3, $s3, 0x1
    /* AB634 000AB5C0 5C00848C */  lw         $a0, 0x5C($a0)
    /* AB638 000AB5C4 2A206402 */  slt        $a0, $s3, $a0
    /* AB63C 000AB5C8 F5FF8014 */  bnez       $a0, .Leboot_000AB5A0
    /* AB640 000AB5CC 40003126 */   addiu     $s1, $s1, 0x40
  .Leboot_000AB5D0:
    /* AB644 000AB5D0 1000B08F */  lw         $s0, 0x10($sp)
    /* AB648 000AB5D4 1400B18F */  lw         $s1, 0x14($sp)
    /* AB64C 000AB5D8 1800B28F */  lw         $s2, 0x18($sp)
    /* AB650 000AB5DC 1C00B38F */  lw         $s3, 0x1C($sp)
    /* AB654 000AB5E0 2000B48F */  lw         $s4, 0x20($sp)
    /* AB658 000AB5E4 2400BF8F */  lw         $ra, 0x24($sp)
    /* AB65C 000AB5E8 0800E003 */  jr         $ra
    /* AB660 000AB5EC 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_000AB4C8
