.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000E08BC, 0x1C

glabel func_000E08BC
    /* E0930 000E08BC F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* E0934 000E08C0 0000BFAF */  sw         $ra, 0x0($sp)
    /* E0938 000E08C4 BF84030C */  jal        func_000E12FC
    /* E093C 000E08C8 00000000 */   nop
    /* E0940 000E08CC 0000BF8F */  lw         $ra, 0x0($sp)
    /* E0944 000E08D0 0800E003 */  jr         $ra
    /* E0948 000E08D4 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel func_000E08BC
