.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000BBBF8, 0x34

glabel func_000BBBF8
    /* BBC6C 000BBBF8 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* BBC70 000BBBFC 0800888C */  lw         $t0, 0x8($a0)
    /* BBC74 000BBC00 2548A000 */  or         $t1, $a1, $zero
    /* BBC78 000BBC04 80008524 */  addiu      $a1, $a0, 0x80
    /* BBC7C 000BBC08 04000625 */  addiu      $a2, $t0, 0x4
    /* BBC80 000BBC0C 10000725 */  addiu      $a3, $t0, 0x10
    /* BBC84 000BBC10 1400848C */  lw         $a0, 0x14($a0)
    /* BBC88 000BBC14 2000BFAF */  sw         $ra, 0x20($sp)
    /* BBC8C 000BBC18 A415040C */  jal        func_00105690
    /* BBC90 000BBC1C 1C000825 */   addiu     $t0, $t0, 0x1C
    /* BBC94 000BBC20 2000BF8F */  lw         $ra, 0x20($sp)
    /* BBC98 000BBC24 0800E003 */  jr         $ra
    /* BBC9C 000BBC28 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_000BBBF8
