.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0018BE84, 0x208

glabel func_0018BE84
    /* 18BEF8 0018BE84 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 18BEFC 0018BE88 2C00B0AF */  sw         $s0, 0x2C($sp)
    /* 18BF00 0018BE8C 25808000 */  or         $s0, $a0, $zero
    /* 18BF04 0018BE90 1000A8AF */  sw         $t0, 0x10($sp)
    /* 18BF08 0018BE94 0400078E */  lw         $a3, 0x4($s0)
    /* 18BF0C 0018BE98 00000A8E */  lw         $t2, 0x0($s0)
    /* 18BF10 0018BE9C FF002431 */  andi       $a0, $t1, 0xFF
    /* 18BF14 0018BEA0 2338EA00 */  subu       $a3, $a3, $t2
    /* 18BF18 0018BEA4 C3480700 */  sra        $t1, $a3, 3
    /* 18BF1C 0018BEA8 424F0900 */  srl        $t1, $t1, 29
    /* 18BF20 0018BEAC 3000B1AF */  sw         $s1, 0x30($sp)
    /* 18BF24 0018BEB0 2188E900 */  addu       $s1, $a3, $t1
    /* 18BF28 0018BEB4 C3881100 */  sra        $s1, $s1, 3
    /* 18BF2C 0018BEB8 2B382802 */  sltu       $a3, $s1, $t0
    /* 18BF30 0018BEBC 3400B2AF */  sw         $s2, 0x34($sp)
    /* 18BF34 0018BEC0 3800B3AF */  sw         $s3, 0x38($sp)
    /* 18BF38 0018BEC4 3C00BFAF */  sw         $ra, 0x3C($sp)
    /* 18BF3C 0018BEC8 0500E010 */  beqz       $a3, .Leboot_0018BEE0
    /* 18BF40 0018BECC 1400B1AF */   sw        $s1, 0x14($sp)
    /* 18BF44 0018BED0 1000A727 */  addiu      $a3, $sp, 0x10
    /* 18BF48 0018BED4 0000E78C */  lw         $a3, 0x0($a3)
    /* 18BF4C 0018BED8 04000010 */  b          .Leboot_0018BEEC
    /* 18BF50 0018BEDC 21882702 */   addu      $s1, $s1, $a3
  .Leboot_0018BEE0:
    /* 18BF54 0018BEE0 1400A727 */  addiu      $a3, $sp, 0x14
    /* 18BF58 0018BEE4 0000E78C */  lw         $a3, 0x0($a3)
    /* 18BF5C 0018BEE8 21882702 */  addu       $s1, $s1, $a3
  .Leboot_0018BEEC:
    /* 18BF60 0018BEEC 16002012 */  beqz       $s1, .Leboot_0018BF48
    /* 18BF64 0018BEF0 00001334 */   ori       $s3, $zero, 0x0
    /* 18BF68 0018BEF4 2800A4AF */  sw         $a0, 0x28($sp)
    /* 18BF6C 0018BEF8 2000A6AF */  sw         $a2, 0x20($sp)
    /* 18BF70 0018BEFC C0201100 */  sll        $a0, $s1, 3
    /* 18BF74 0018BF00 1C00A5AF */  sw         $a1, 0x1C($sp)
    /* 18BF78 0018BF04 70C5040C */  jal        func_001315C0
    /* 18BF7C 0018BF08 2400A4AF */   sw        $a0, 0x24($sp)
    /* 18BF80 0018BF0C 1C00A58F */  lw         $a1, 0x1C($sp)
    /* 18BF84 0018BF10 2000A68F */  lw         $a2, 0x20($sp)
    /* 18BF88 0018BF14 2400A78F */  lw         $a3, 0x24($sp)
    /* 18BF8C 0018BF18 25984000 */  or         $s3, $v0, $zero
    /* 18BF90 0018BF1C 0A006016 */  bnez       $s3, .Leboot_0018BF48
    /* 18BF94 0018BF20 2800A48F */   lw        $a0, 0x28($sp)
    /* 18BF98 0018BF24 2800A4AF */  sw         $a0, 0x28($sp)
    /* 18BF9C 0018BF28 2000A6AF */  sw         $a2, 0x20($sp)
    /* 18BFA0 0018BF2C 1C00A5AF */  sw         $a1, 0x1C($sp)
    /* 18BFA4 0018BF30 AB41050C */  jal        func_001506AC
    /* 18BFA8 0018BF34 2520E000 */   or        $a0, $a3, $zero
    /* 18BFAC 0018BF38 1C00A58F */  lw         $a1, 0x1C($sp)
    /* 18BFB0 0018BF3C 2000A68F */  lw         $a2, 0x20($sp)
    /* 18BFB4 0018BF40 25984000 */  or         $s3, $v0, $zero
    /* 18BFB8 0018BF44 2800A48F */  lw         $a0, 0x28($sp)
  .Leboot_0018BF48:
    /* 18BFBC 0018BF48 0000078E */  lw         $a3, 0x0($s0)
    /* 18BFC0 0018BF4C 25906002 */  or         $s2, $s3, $zero
    /* 18BFC4 0018BF50 0B00E510 */  beq        $a3, $a1, .Leboot_0018BF80
    /* 18BFC8 0018BF54 1800A0A3 */   sb        $zero, 0x18($sp)
  .Leboot_0018BF58:
    /* 18BFCC 0018BF58 25406002 */  or         $t0, $s3, $zero
    /* 18BFD0 0018BF5C 06000051 */  beql       $t0, $zero, .Leboot_0018BF78
    /* 18BFD4 0018BF60 0800E724 */   addiu     $a3, $a3, 0x8
    /* 18BFD8 0018BF64 0000ECC4 */  lwc1       $f12, 0x0($a3)
    /* 18BFDC 0018BF68 00000CE5 */  swc1       $f12, 0x0($t0)
    /* 18BFE0 0018BF6C 0400ECC4 */  lwc1       $f12, 0x4($a3)
    /* 18BFE4 0018BF70 04000CE5 */  swc1       $f12, 0x4($t0)
    /* 18BFE8 0018BF74 0800E724 */  addiu      $a3, $a3, 0x8
  .Leboot_0018BF78:
    /* 18BFEC 0018BF78 F7FFE514 */  bne        $a3, $a1, .Leboot_0018BF58
    /* 18BFF0 0018BF7C 08007326 */   addiu     $s3, $s3, 0x8
  .Leboot_0018BF80:
    /* 18BFF4 0018BF80 1000A78F */  lw         $a3, 0x10($sp)
    /* 18BFF8 0018BF84 01000834 */  ori        $t0, $zero, 0x1
    /* 18BFFC 0018BF88 0B00E814 */  bne        $a3, $t0, .Leboot_0018BFB8
    /* 18C000 0018BF8C 00000000 */   nop
    /* 18C004 0018BF90 25386002 */  or         $a3, $s3, $zero
    /* 18C008 0018BF94 0500E010 */  beqz       $a3, .Leboot_0018BFAC
    /* 18C00C 0018BF98 00000000 */   nop
    /* 18C010 0018BF9C 0000CCC4 */  lwc1       $f12, 0x0($a2)
    /* 18C014 0018BFA0 0000ECE4 */  swc1       $f12, 0x0($a3)
    /* 18C018 0018BFA4 0400CCC4 */  lwc1       $f12, 0x4($a2)
    /* 18C01C 0018BFA8 0400ECE4 */  swc1       $f12, 0x4($a3)
  .Leboot_0018BFAC:
    /* 18C020 0018BFAC 08007326 */  addiu      $s3, $s3, 0x8
    /* 18C024 0018BFB0 0E000010 */  b          .Leboot_0018BFEC
    /* 18C028 0018BFB4 0400068E */   lw        $a2, 0x4($s0)
  .Leboot_0018BFB8:
    /* 18C02C 0018BFB8 0B00E010 */  beqz       $a3, .Leboot_0018BFE8
    /* 18C030 0018BFBC 1900A0A3 */   sb        $zero, 0x19($sp)
  .Leboot_0018BFC0:
    /* 18C034 0018BFC0 25406002 */  or         $t0, $s3, $zero
    /* 18C038 0018BFC4 06000051 */  beql       $t0, $zero, .Leboot_0018BFE0
    /* 18C03C 0018BFC8 FFFFE724 */   addiu     $a3, $a3, -0x1
    /* 18C040 0018BFCC 0000CCC4 */  lwc1       $f12, 0x0($a2)
    /* 18C044 0018BFD0 00000CE5 */  swc1       $f12, 0x0($t0)
    /* 18C048 0018BFD4 0400CCC4 */  lwc1       $f12, 0x4($a2)
    /* 18C04C 0018BFD8 04000CE5 */  swc1       $f12, 0x4($t0)
    /* 18C050 0018BFDC FFFFE724 */  addiu      $a3, $a3, -0x1
  .Leboot_0018BFE0:
    /* 18C054 0018BFE0 F7FFE014 */  bnez       $a3, .Leboot_0018BFC0
    /* 18C058 0018BFE4 08007326 */   addiu     $s3, $s3, 0x8
  .Leboot_0018BFE8:
    /* 18C05C 0018BFE8 0400068E */  lw         $a2, 0x4($s0)
  .Leboot_0018BFEC:
    /* 18C060 0018BFEC 10008014 */  bnez       $a0, .Leboot_0018C030
    /* 18C064 0018BFF0 00000000 */   nop
    /* 18C068 0018BFF4 2520A000 */  or         $a0, $a1, $zero
    /* 18C06C 0018BFF8 2528C000 */  or         $a1, $a2, $zero
    /* 18C070 0018BFFC 0C008510 */  beq        $a0, $a1, .Leboot_0018C030
    /* 18C074 0018C000 1A00A0A3 */   sb        $zero, 0x1A($sp)
  .Leboot_0018C004:
    /* 18C078 0018C004 25306002 */  or         $a2, $s3, $zero
    /* 18C07C 0018C008 0600C050 */  beql       $a2, $zero, .Leboot_0018C024
    /* 18C080 0018C00C 08008424 */   addiu     $a0, $a0, 0x8
    /* 18C084 0018C010 00008CC4 */  lwc1       $f12, 0x0($a0)
    /* 18C088 0018C014 0000CCE4 */  swc1       $f12, 0x0($a2)
    /* 18C08C 0018C018 04008CC4 */  lwc1       $f12, 0x4($a0)
    /* 18C090 0018C01C 0400CCE4 */  swc1       $f12, 0x4($a2)
    /* 18C094 0018C020 08008424 */  addiu      $a0, $a0, 0x8
  .Leboot_0018C024:
    /* 18C098 0018C024 F7FF8514 */  bne        $a0, $a1, .Leboot_0018C004
    /* 18C09C 0018C028 08007326 */   addiu     $s3, $s3, 0x8
    /* 18C0A0 0018C02C 0400068E */  lw         $a2, 0x4($s0)
  .Leboot_0018C030:
    /* 18C0A4 0018C030 0000048E */  lw         $a0, 0x0($s0)
    /* 18C0A8 0018C034 25288000 */  or         $a1, $a0, $zero
    /* 18C0AC 0018C038 0400A610 */  beq        $a1, $a2, .Leboot_0018C04C
    /* 18C0B0 0018C03C 1B00A0A3 */   sb        $zero, 0x1B($sp)
    /* 18C0B4 0018C040 0800A524 */  addiu      $a1, $a1, 0x8
  .Leboot_0018C044:
    /* 18C0B8 0018C044 FFFFA614 */  bne        $a1, $a2, .Leboot_0018C044
    /* 18C0BC 0018C048 0800A524 */   addiu     $a1, $a1, 0x8
  .Leboot_0018C04C:
    /* 18C0C0 0018C04C 03008010 */  beqz       $a0, .Leboot_0018C05C
    /* 18C0C4 0018C050 00000000 */   nop
    /* 18C0C8 0018C054 DDC6040C */  jal        func_00131B74
    /* 18C0CC 0018C058 00000000 */   nop
  .Leboot_0018C05C:
    /* 18C0D0 0018C05C C0201100 */  sll        $a0, $s1, 3
    /* 18C0D4 0018C060 000012AE */  sw         $s2, 0x0($s0)
    /* 18C0D8 0018C064 21204402 */  addu       $a0, $s2, $a0
    /* 18C0DC 0018C068 040013AE */  sw         $s3, 0x4($s0)
    /* 18C0E0 0018C06C 080004AE */  sw         $a0, 0x8($s0)
    /* 18C0E4 0018C070 2C00B08F */  lw         $s0, 0x2C($sp)
    /* 18C0E8 0018C074 3000B18F */  lw         $s1, 0x30($sp)
    /* 18C0EC 0018C078 3400B28F */  lw         $s2, 0x34($sp)
    /* 18C0F0 0018C07C 3800B38F */  lw         $s3, 0x38($sp)
    /* 18C0F4 0018C080 3C00BF8F */  lw         $ra, 0x3C($sp)
    /* 18C0F8 0018C084 0800E003 */  jr         $ra
    /* 18C0FC 0018C088 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel func_0018BE84
