.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00073E44, 0x8

glabel func_00073E44
    /* 73EB8 00073E44 0800E003 */  jr         $ra
    /* 73EBC 00073E48 25100000 */   or        $v0, $zero, $zero
endlabel func_00073E44
