.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_001A6240, 0x1A8

glabel func_001A6240
    /* 1A62B4 001A6240 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* 1A62B8 001A6244 3C00B2AF */  sw         $s2, 0x3C($sp)
    /* 1A62BC 001A6248 6000A6AF */  sw         $a2, 0x60($sp)
    /* 1A62C0 001A624C 25908000 */  or         $s2, $a0, $zero
    /* 1A62C4 001A6250 3400B0AF */  sw         $s0, 0x34($sp)
    /* 1A62C8 001A6254 3800B1AF */  sw         $s1, 0x38($sp)
    /* 1A62CC 001A6258 4000B3AF */  sw         $s3, 0x40($sp)
    /* 1A62D0 001A625C 4400B4AF */  sw         $s4, 0x44($sp)
    /* 1A62D4 001A6260 4800B5AF */  sw         $s5, 0x48($sp)
    /* 1A62D8 001A6264 4C00B6AF */  sw         $s6, 0x4C($sp)
    /* 1A62DC 001A6268 5000B7AF */  sw         $s7, 0x50($sp)
    /* 1A62E0 001A626C 5400BEAF */  sw         $fp, 0x54($sp)
    /* 1A62E4 001A6270 5800BFAF */  sw         $ra, 0x58($sp)
    /* 1A62E8 001A6274 03008514 */  bne        $a0, $a1, .Leboot_001A6284
    /* 1A62EC 001A6278 2538A000 */   or        $a3, $a1, $zero
    /* 1A62F0 001A627C 4E000010 */  b          .Leboot_001A63B8
    /* 1A62F4 001A6280 00000000 */   nop
  .Leboot_001A6284:
    /* 1A62F8 001A6284 10005026 */  addiu      $s0, $s2, 0x10
    /* 1A62FC 001A6288 4B000712 */  beq        $s0, $a3, .Leboot_001A63B8
    /* 1A6300 001A628C 3000A7AF */   sw        $a3, 0x30($sp)
    /* 1A6304 001A6290 6000B583 */  lb         $s5, 0x60($sp)
    /* 1A6308 001A6294 2400BE83 */  lb         $fp, 0x24($sp)
    /* 1A630C 001A6298 2900B783 */  lb         $s7, 0x29($sp)
    /* 1A6310 001A629C 1000B427 */  addiu      $s4, $sp, 0x10
    /* 1A6314 001A62A0 1400B327 */  addiu      $s3, $sp, 0x14
    /* 1A6318 001A62A4 2700B683 */  lb         $s6, 0x27($sp)
    /* 1A631C 001A62A8 1000B5A3 */  sb         $s5, 0x10($sp)
  .Leboot_001A62AC:
    /* 1A6320 001A62AC 0000048E */  lw         $a0, 0x0($s0)
    /* 1A6324 001A62B0 08000CC6 */  lwc1       $f12, 0x8($s0)
    /* 1A6328 001A62B4 0400058E */  lw         $a1, 0x4($s0)
    /* 1A632C 001A62B8 0C000DC6 */  lwc1       $f13, 0xC($s0)
    /* 1A6330 001A62BC 00600644 */  mfc1       $a2, $f12
    /* 1A6334 001A62C0 1400A4AF */  sw         $a0, 0x14($sp)
    /* 1A6338 001A62C4 1800A5AF */  sw         $a1, 0x18($sp)
    /* 1A633C 001A62C8 00680444 */  mfc1       $a0, $f13
    /* 1A6340 001A62CC 1C00A6AF */  sw         $a2, 0x1C($sp)
    /* 1A6344 001A62D0 2000A4AF */  sw         $a0, 0x20($sp)
    /* 1A6348 001A62D4 25208002 */  or         $a0, $s4, $zero
    /* 1A634C 001A62D8 25286002 */  or         $a1, $s3, $zero
    /* 1A6350 001A62DC 2443030C */  jal        func_000D0C90
    /* 1A6354 001A62E0 25304002 */   or        $a2, $s2, $zero
    /* 1A6358 001A62E4 29004010 */  beqz       $v0, .Leboot_001A638C
    /* 1A635C 001A62E8 10001126 */   addiu     $s1, $s0, 0x10
    /* 1A6360 001A62EC 2500A0A3 */  sb         $zero, 0x25($sp)
    /* 1A6364 001A62F0 2500BE83 */  lb         $fp, 0x25($sp)
    /* 1A6368 001A62F4 2800A0A3 */  sb         $zero, 0x28($sp)
    /* 1A636C 001A62F8 6B8F060C */  jal        func_001A3DAC
    /* 1A6370 001A62FC 2800B783 */   lb        $s7, 0x28($sp)
    /* 1A6374 001A6300 23281202 */  subu       $a1, $s0, $s2
    /* 1A6378 001A6304 03310500 */  sra        $a2, $a1, 4
    /* 1A637C 001A6308 2C00A2AF */  sw         $v0, 0x2C($sp)
    /* 1A6380 001A630C 02370600 */  srl        $a2, $a2, 28
    /* 1A6384 001A6310 2C00B683 */  lb         $s6, 0x2C($sp)
    /* 1A6388 001A6314 2128A600 */  addu       $a1, $a1, $a2
    /* 1A638C 001A6318 25202002 */  or         $a0, $s1, $zero
    /* 1A6390 001A631C 03290500 */  sra        $a1, $a1, 4
    /* 1A6394 001A6320 0F00A018 */  blez       $a1, .Leboot_001A6360
    /* 1A6398 001A6324 2A00A0A3 */   sb        $zero, 0x2A($sp)
  .Leboot_001A6328:
    /* 1A639C 001A6328 F0FF1026 */  addiu      $s0, $s0, -0x10
    /* 1A63A0 001A632C 0000068E */  lw         $a2, 0x0($s0)
    /* 1A63A4 001A6330 08000CC6 */  lwc1       $f12, 0x8($s0)
    /* 1A63A8 001A6334 0400078E */  lw         $a3, 0x4($s0)
    /* 1A63AC 001A6338 F0FF8424 */  addiu      $a0, $a0, -0x10
    /* 1A63B0 001A633C 00600844 */  mfc1       $t0, $f12
    /* 1A63B4 001A6340 0C000DC6 */  lwc1       $f13, 0xC($s0)
    /* 1A63B8 001A6344 000086AC */  sw         $a2, 0x0($a0)
    /* 1A63BC 001A6348 040087AC */  sw         $a3, 0x4($a0)
    /* 1A63C0 001A634C 00680644 */  mfc1       $a2, $f13
    /* 1A63C4 001A6350 080088AC */  sw         $t0, 0x8($a0)
    /* 1A63C8 001A6354 FFFFA524 */  addiu      $a1, $a1, -0x1
    /* 1A63CC 001A6358 F3FFA01C */  bgtz       $a1, .Leboot_001A6328
    /* 1A63D0 001A635C 0C0086AC */   sw        $a2, 0xC($a0)
  .Leboot_001A6360:
    /* 1A63D4 001A6360 1400A48F */  lw         $a0, 0x14($sp)
    /* 1A63D8 001A6364 1C00ACC7 */  lwc1       $f12, 0x1C($sp)
    /* 1A63DC 001A6368 1800A58F */  lw         $a1, 0x18($sp)
    /* 1A63E0 001A636C 2000ADC7 */  lwc1       $f13, 0x20($sp)
    /* 1A63E4 001A6370 00600644 */  mfc1       $a2, $f12
    /* 1A63E8 001A6374 000044AE */  sw         $a0, 0x0($s2)
    /* 1A63EC 001A6378 040045AE */  sw         $a1, 0x4($s2)
    /* 1A63F0 001A637C 00680444 */  mfc1       $a0, $f13
    /* 1A63F4 001A6380 080046AE */  sw         $a2, 0x8($s2)
    /* 1A63F8 001A6384 05000010 */  b          .Leboot_001A639C
    /* 1A63FC 001A6388 0C0044AE */   sw        $a0, 0xC($s2)
  .Leboot_001A638C:
    /* 1A6400 001A638C 1000A683 */  lb         $a2, 0x10($sp)
    /* 1A6404 001A6390 25200002 */  or         $a0, $s0, $zero
    /* 1A6408 001A6394 FA98060C */  jal        func_001A63E8
    /* 1A640C 001A6398 25286002 */   or        $a1, $s3, $zero
  .Leboot_001A639C:
    /* 1A6410 001A639C 3000A48F */  lw         $a0, 0x30($sp)
    /* 1A6414 001A63A0 25802002 */  or         $s0, $s1, $zero
    /* 1A6418 001A63A4 C1FF0456 */  bnel       $s0, $a0, .Leboot_001A62AC
    /* 1A641C 001A63A8 1000B5A3 */   sb        $s5, 0x10($sp)
    /* 1A6420 001A63AC 2400BEA3 */  sb         $fp, 0x24($sp)
    /* 1A6424 001A63B0 2900B7A3 */  sb         $s7, 0x29($sp)
    /* 1A6428 001A63B4 2700B6A3 */  sb         $s6, 0x27($sp)
  .Leboot_001A63B8:
    /* 1A642C 001A63B8 3400B08F */  lw         $s0, 0x34($sp)
    /* 1A6430 001A63BC 3800B18F */  lw         $s1, 0x38($sp)
    /* 1A6434 001A63C0 3C00B28F */  lw         $s2, 0x3C($sp)
    /* 1A6438 001A63C4 4000B38F */  lw         $s3, 0x40($sp)
    /* 1A643C 001A63C8 4400B48F */  lw         $s4, 0x44($sp)
    /* 1A6440 001A63CC 4800B58F */  lw         $s5, 0x48($sp)
    /* 1A6444 001A63D0 4C00B68F */  lw         $s6, 0x4C($sp)
    /* 1A6448 001A63D4 5000B78F */  lw         $s7, 0x50($sp)
    /* 1A644C 001A63D8 5400BE8F */  lw         $fp, 0x54($sp)
    /* 1A6450 001A63DC 5800BF8F */  lw         $ra, 0x58($sp)
    /* 1A6454 001A63E0 0800E003 */  jr         $ra
    /* 1A6458 001A63E4 6000BD27 */   addiu     $sp, $sp, 0x60
endlabel func_001A6240
