.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00196C04, 0x2C

glabel func_00196C04
    /* 196C78 00196C04 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 196C7C 00196C08 7800868C */  lw         $a2, 0x78($a0)
    /* 196C80 00196C0C 7800C624 */  addiu      $a2, $a2, 0x78
    /* 196C84 00196C10 0000C784 */  lh         $a3, 0x0($a2)
    /* 196C88 00196C14 0400C68C */  lw         $a2, 0x4($a2)
    /* 196C8C 00196C18 1000BFAF */  sw         $ra, 0x10($sp)
    /* 196C90 00196C1C 09F8C000 */  jalr       $a2
    /* 196C94 00196C20 21208700 */   addu      $a0, $a0, $a3
    /* 196C98 00196C24 1000BF8F */  lw         $ra, 0x10($sp)
    /* 196C9C 00196C28 0800E003 */  jr         $ra
    /* 196CA0 00196C2C 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_00196C04
