.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_001138D0, 0x20

glabel func_001138D0
    /* 113944 001138D0 2E008494 */  lhu        $a0, 0x2E($a0)
    /* 113948 001138D4 03008018 */  blez       $a0, .Leboot_001138E4
    /* 11394C 001138D8 00000000 */   nop
    /* 113950 001138DC 02000010 */  b          .Leboot_001138E8
    /* 113954 001138E0 25100000 */   or        $v0, $zero, $zero
  .Leboot_001138E4:
    /* 113958 001138E4 01000234 */  ori        $v0, $zero, 0x1
  .Leboot_001138E8:
    /* 11395C 001138E8 0800E003 */  jr         $ra
    /* 113960 001138EC 00000000 */   nop
endlabel func_001138D0
