.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00048AE0, 0x228

glabel func_00048AE0
    /* 48B54 00048AE0 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 48B58 00048AE4 1D00043C */  lui        $a0, %hi(sym_001D3D58)
    /* 48B5C 00048AE8 583D8CC4 */  lwc1       $f12, %lo(sym_001D3D58)($a0)
    /* 48B60 00048AEC 3443043C */  lui        $a0, (0x43340000 >> 16)
    /* 48B64 00048AF0 00688444 */  mtc1       $a0, $f13
    /* 48B68 00048AF4 83630D46 */  div.s      $f14, $f12, $f13
    /* 48B6C 00048AF8 1D00073C */  lui        $a3, %hi(sym_001D3D5C)
    /* 48B70 00048AFC 7266043C */  lui        $a0, %hi(D_66727573)
    /* 48B74 00048B00 1D00083C */  lui        $t0, %hi(sym_001D3D60)
    /* 48B78 00048B04 3A000534 */  ori        $a1, $zero, 0x3A
    /* 48B7C 00048B08 80000634 */  ori        $a2, $zero, 0x80
    /* 48B80 00048B0C 73758424 */  addiu      $a0, $a0, %lo(D_66727573)
    /* 48B84 00048B10 1000B4E7 */  swc1       $f20, 0x10($sp)
    /* 48B88 00048B14 1400BFAF */  sw         $ra, 0x14($sp)
    /* 48B8C 00048B18 036B0C46 */  div.s      $f12, $f13, $f12
    /* 48B90 00048B1C 5C3DEEE4 */  swc1       $f14, %lo(sym_001D3D5C)($a3)
    /* 48B94 00048B20 611B040C */  jal        elem_register_chunk_tag
    /* 48B98 00048B24 603D0CE5 */   swc1      $f12, %lo(sym_001D3D60)($t0)
    /* 48B9C 00048B28 1D00043C */  lui        $a0, %hi(sym_001D3D64)
    /* 48BA0 00048B2C 1C00053C */  lui        $a1, %hi(str_JoystickX_4D00)
    /* 48BA4 00048B30 643D8424 */  addiu      $a0, $a0, %lo(sym_001D3D64)
    /* 48BA8 00048B34 00A08044 */  mtc1       $zero, $f20
    /* 48BAC 00048B38 06A30046 */  mov.s      $f12, $f20
    /* 48BB0 00048B3C 31BA020C */  jal        func_000AE8C4
    /* 48BB4 00048B40 004DA524 */   addiu     $a1, $a1, %lo(str_JoystickX_4D00)
    /* 48BB8 00048B44 1D00043C */  lui        $a0, %hi(sym_001D3D68)
    /* 48BBC 00048B48 06A30046 */  mov.s      $f12, $f20
    /* 48BC0 00048B4C 1C00053C */  lui        $a1, %hi(str_JoystickY_4D0C)
    /* 48BC4 00048B50 683D8424 */  addiu      $a0, $a0, %lo(sym_001D3D68)
    /* 48BC8 00048B54 31BA020C */  jal        func_000AE8C4
    /* 48BCC 00048B58 0C4DA524 */   addiu     $a1, $a1, %lo(str_JoystickY_4D0C)
    /* 48BD0 00048B5C 1D00043C */  lui        $a0, %hi(sym_001D3D6C)
    /* 48BD4 00048B60 06A30046 */  mov.s      $f12, $f20
    /* 48BD8 00048B64 1C00053C */  lui        $a1, %hi(str_Button_Circle_4D18)
    /* 48BDC 00048B68 6C3D8424 */  addiu      $a0, $a0, %lo(sym_001D3D6C)
    /* 48BE0 00048B6C 31BA020C */  jal        func_000AE8C4
    /* 48BE4 00048B70 184DA524 */   addiu     $a1, $a1, %lo(str_Button_Circle_4D18)
    /* 48BE8 00048B74 1D00043C */  lui        $a0, %hi(sym_001D3D70)
    /* 48BEC 00048B78 06A30046 */  mov.s      $f12, $f20
    /* 48BF0 00048B7C 1C00053C */  lui        $a1, %hi(str_Button_Square_4D28)
    /* 48BF4 00048B80 703D8424 */  addiu      $a0, $a0, %lo(sym_001D3D70)
    /* 48BF8 00048B84 31BA020C */  jal        func_000AE8C4
    /* 48BFC 00048B88 284DA524 */   addiu     $a1, $a1, %lo(str_Button_Square_4D28)
    /* 48C00 00048B8C 1D00043C */  lui        $a0, %hi(sym_001D3D74)
    /* 48C04 00048B90 06A30046 */  mov.s      $f12, $f20
    /* 48C08 00048B94 1C00053C */  lui        $a1, %hi(str_Button_Triangle_4D38)
    /* 48C0C 00048B98 743D8424 */  addiu      $a0, $a0, %lo(sym_001D3D74)
    /* 48C10 00048B9C 31BA020C */  jal        func_000AE8C4
    /* 48C14 00048BA0 384DA524 */   addiu     $a1, $a1, %lo(str_Button_Triangle_4D38)
    /* 48C18 00048BA4 1D00043C */  lui        $a0, %hi(sym_001D3D78)
    /* 48C1C 00048BA8 06A30046 */  mov.s      $f12, $f20
    /* 48C20 00048BAC 1C00053C */  lui        $a1, %hi(str_Button_X_4D48)
    /* 48C24 00048BB0 783D8424 */  addiu      $a0, $a0, %lo(sym_001D3D78)
    /* 48C28 00048BB4 31BA020C */  jal        func_000AE8C4
    /* 48C2C 00048BB8 484DA524 */   addiu     $a1, $a1, %lo(str_Button_X_4D48)
    /* 48C30 00048BBC 1D00043C */  lui        $a0, %hi(sym_001D3D7C)
    /* 48C34 00048BC0 06A30046 */  mov.s      $f12, $f20
    /* 48C38 00048BC4 1C00053C */  lui        $a1, %hi(str_Confirm_4D54)
    /* 48C3C 00048BC8 7C3D8424 */  addiu      $a0, $a0, %lo(sym_001D3D7C)
    /* 48C40 00048BCC 31BA020C */  jal        func_000AE8C4
    /* 48C44 00048BD0 544DA524 */   addiu     $a1, $a1, %lo(str_Confirm_4D54)
    /* 48C48 00048BD4 1D00043C */  lui        $a0, %hi(sym_001D3D80)
    /* 48C4C 00048BD8 06A30046 */  mov.s      $f12, $f20
    /* 48C50 00048BDC 1C00053C */  lui        $a1, %hi(str_Cancel_4D5C)
    /* 48C54 00048BE0 803D8424 */  addiu      $a0, $a0, %lo(sym_001D3D80)
    /* 48C58 00048BE4 31BA020C */  jal        func_000AE8C4
    /* 48C5C 00048BE8 5C4DA524 */   addiu     $a1, $a1, %lo(str_Cancel_4D5C)
    /* 48C60 00048BEC 1D00043C */  lui        $a0, %hi(sym_001D3D84)
    /* 48C64 00048BF0 06A30046 */  mov.s      $f12, $f20
    /* 48C68 00048BF4 1C00053C */  lui        $a1, %hi(str_Start_4D64)
    /* 48C6C 00048BF8 843D8424 */  addiu      $a0, $a0, %lo(sym_001D3D84)
    /* 48C70 00048BFC 31BA020C */  jal        func_000AE8C4
    /* 48C74 00048C00 644DA524 */   addiu     $a1, $a1, %lo(str_Start_4D64)
    /* 48C78 00048C04 1D00043C */  lui        $a0, %hi(sym_001D3D88)
    /* 48C7C 00048C08 06A30046 */  mov.s      $f12, $f20
    /* 48C80 00048C0C 1C00053C */  lui        $a1, %hi(str_ActiveController_4D6C)
    /* 48C84 00048C10 883D8424 */  addiu      $a0, $a0, %lo(sym_001D3D88)
    /* 48C88 00048C14 31BA020C */  jal        func_000AE8C4
    /* 48C8C 00048C18 6C4DA524 */   addiu     $a1, $a1, %lo(str_ActiveController_4D6C)
    /* 48C90 00048C1C 6864043C */  lui        $a0, %hi(D_64687367)
    /* 48C94 00048C20 0D000534 */  ori        $a1, $zero, 0xD
    /* 48C98 00048C24 20000634 */  ori        $a2, $zero, 0x20
    /* 48C9C 00048C28 611B040C */  jal        elem_register_chunk_tag
    /* 48CA0 00048C2C 67738424 */   addiu     $a0, $a0, %lo(D_64687367)
    /* 48CA4 00048C30 6D73043C */  lui        $a0, %hi(D_736D6472)
    /* 48CA8 00048C34 36000534 */  ori        $a1, $zero, 0x36
    /* 48CAC 00048C38 40000634 */  ori        $a2, $zero, 0x40
    /* 48CB0 00048C3C 611B040C */  jal        elem_register_chunk_tag
    /* 48CB4 00048C40 72648424 */   addiu     $a0, $a0, %lo(D_736D6472)
    /* 48CB8 00048C44 726E043C */  lui        $a0, %hi(D_6E726574)
    /* 48CBC 00048C48 06000534 */  ori        $a1, $zero, 0x6
    /* 48CC0 00048C4C 20000634 */  ori        $a2, $zero, 0x20
    /* 48CC4 00048C50 611B040C */  jal        elem_register_chunk_tag
    /* 48CC8 00048C54 74658424 */   addiu     $a0, $a0, %lo(D_6E726574)
    /* 48CCC 00048C58 7665043C */  lui        $a0, %hi(D_65766177)
    /* 48CD0 00048C5C 09000534 */  ori        $a1, $zero, 0x9
    /* 48CD4 00048C60 20000634 */  ori        $a2, $zero, 0x20
    /* 48CD8 00048C64 611B040C */  jal        elem_register_chunk_tag
    /* 48CDC 00048C68 77618424 */   addiu     $a0, $a0, %lo(D_65766177)
    /* 48CE0 00048C6C 7461043C */  lui        $a0, %hi(D_61746473)
    /* 48CE4 00048C70 01000534 */  ori        $a1, $zero, 0x1
    /* 48CE8 00048C74 20000634 */  ori        $a2, $zero, 0x20
    /* 48CEC 00048C78 611B040C */  jal        elem_register_chunk_tag
    /* 48CF0 00048C7C 73648424 */   addiu     $a0, $a0, %lo(D_61746473)
    /* 48CF4 00048C80 6220043C */  lui        $a0, %hi(D_20626D78)
    /* 48CF8 00048C84 25280000 */  or         $a1, $zero, $zero
    /* 48CFC 00048C88 40000634 */  ori        $a2, $zero, 0x40
    /* 48D00 00048C8C 611B040C */  jal        elem_register_chunk_tag
    /* 48D04 00048C90 786D8424 */   addiu     $a0, $a0, %lo(D_20626D78)
    /* 48D08 00048C94 7320043C */  lui        $a0, %hi(D_20736D78)
    /* 48D0C 00048C98 25280000 */  or         $a1, $zero, $zero
    /* 48D10 00048C9C 40000634 */  ori        $a2, $zero, 0x40
    /* 48D14 00048CA0 611B040C */  jal        elem_register_chunk_tag
    /* 48D18 00048CA4 786D8424 */   addiu     $a0, $a0, %lo(D_20736D78)
    /* 48D1C 00048CA8 6820043C */  lui        $a0, %hi(D_20686D78)
    /* 48D20 00048CAC 25280000 */  or         $a1, $zero, $zero
    /* 48D24 00048CB0 20000634 */  ori        $a2, $zero, 0x20
    /* 48D28 00048CB4 611B040C */  jal        elem_register_chunk_tag
    /* 48D2C 00048CB8 786D8424 */   addiu     $a0, $a0, %lo(D_20686D78)
    /* 48D30 00048CBC 6267043C */  lui        $a0, %hi(D_6762646E)
    /* 48D34 00048CC0 04000534 */  ori        $a1, $zero, 0x4
    /* 48D38 00048CC4 20000634 */  ori        $a2, $zero, 0x20
    /* 48D3C 00048CC8 611B040C */  jal        elem_register_chunk_tag
    /* 48D40 00048CCC 6E648424 */   addiu     $a0, $a0, %lo(D_6762646E)
    /* 48D44 00048CD0 6465043C */  lui        $a0, %hi(D_65646F6E)
    /* 48D48 00048CD4 D0000534 */  ori        $a1, $zero, 0xD0
    /* 48D4C 00048CD8 20000634 */  ori        $a2, $zero, 0x20
    /* 48D50 00048CDC 611B040C */  jal        elem_register_chunk_tag
    /* 48D54 00048CE0 6E6F8424 */   addiu     $a0, $a0, %lo(D_65646F6E)
    /* 48D58 00048CE4 766C043C */  lui        $a0, %hi(D_6C76656C)
    /* 48D5C 00048CE8 62000534 */  ori        $a1, $zero, 0x62
    /* 48D60 00048CEC 20000634 */  ori        $a2, $zero, 0x20
    /* 48D64 00048CF0 611B040C */  jal        elem_register_chunk_tag
    /* 48D68 00048CF4 6C658424 */   addiu     $a0, $a0, %lo(D_6C76656C)
    /* 48D6C 00048CF8 1000B4C7 */  lwc1       $f20, 0x10($sp)
    /* 48D70 00048CFC 1400BF8F */  lw         $ra, 0x14($sp)
    /* 48D74 00048D00 0800E003 */  jr         $ra
    /* 48D78 00048D04 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_00048AE0
