.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

/* Handwritten function */
nonmatching func_00091BC4, 0x2F4

glabel func_00091BC4
    /* 91C38 00091BC4 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* 91C3C 00091BC8 0000ACC4 */  lwc1       $f12, 0x0($a1)
    /* 91C40 00091BCC 00008DC4 */  lwc1       $f13, 0x0($a0)
    /* 91C44 00091BD0 0400AEC4 */  lwc1       $f14, 0x4($a1)
    /* 91C48 00091BD4 04008FC4 */  lwc1       $f15, 0x4($a0)
    /* 91C4C 00091BD8 01630D46 */  sub.s      $f12, $f12, $f13
    /* 91C50 00091BDC 0800B0C4 */  lwc1       $f16, 0x8($a1)
    /* 91C54 00091BE0 080091C4 */  lwc1       $f17, 0x8($a0)
    /* 91C58 00091BE4 81730F46 */  sub.s      $f14, $f14, $f15
    /* 91C5C 00091BE8 0100073C */  lui        $a3, %hi(sym_0000C9CC)
    /* 91C60 00091BEC 01841146 */  sub.s      $f16, $f16, $f17
    /* 91C64 00091BF0 0C00ACE7 */  swc1       $f12, 0xC($sp)
    /* 91C68 00091BF4 CCC9E724 */  addiu      $a3, $a3, %lo(sym_0000C9CC)
    /* 91C6C 00091BF8 1000AEE7 */  swc1       $f14, 0x10($sp)
    /* 91C70 00091BFC 1400B0E7 */  swc1       $f16, 0x14($sp)
    /* 91C74 00091C00 00008CC4 */  lwc1       $f12, 0x0($a0)
    /* 91C78 00091C04 0000EDC4 */  lwc1       $f13, 0x0($a3)
    /* 91C7C 00091C08 0400EEC4 */  lwc1       $f14, 0x4($a3)
    /* 91C80 00091C0C 04008FC4 */  lwc1       $f15, 0x4($a0)
    /* 91C84 00091C10 016B0C46 */  sub.s      $f12, $f13, $f12
    /* 91C88 00091C14 0800F0C4 */  lwc1       $f16, 0x8($a3)
    /* 91C8C 00091C18 81730F46 */  sub.s      $f14, $f14, $f15
    /* 91C90 00091C1C 080091C4 */  lwc1       $f17, 0x8($a0)
    /* 91C94 00091C20 0C00A827 */  addiu      $t0, $sp, 0xC
    /* 91C98 00091C24 0000ACE7 */  swc1       $f12, 0x0($sp)
    /* 91C9C 00091C28 01831146 */  sub.s      $f12, $f16, $f17
    /* 91CA0 00091C2C 0000ADC7 */  lwc1       $f13, 0x0($sp)
    /* 91CA4 00091C30 0400AEE7 */  swc1       $f14, 0x4($sp)
    /* 91CA8 00091C34 00000EC5 */  lwc1       $f14, 0x0($t0)
    /* 91CAC 00091C38 0400B2C7 */  lwc1       $f18, 0x4($sp)
    /* 91CB0 00091C3C 0800ACE7 */  swc1       $f12, 0x8($sp)
    /* 91CB4 00091C40 04000FC5 */  lwc1       $f15, 0x4($t0)
    /* 91CB8 00091C44 026B0E46 */  mul.s      $f12, $f13, $f14
    /* 91CBC 00091C48 0800B0C7 */  lwc1       $f16, 0x8($sp)
    /* 91CC0 00091C4C 42940F46 */  mul.s      $f17, $f18, $f15
    /* 91CC4 00091C50 080013C5 */  lwc1       $f19, 0x8($t0)
    /* 91CC8 00091C54 82730E46 */  mul.s      $f14, $f14, $f14
    /* 91CCC 00091C58 42831346 */  mul.s      $f13, $f16, $f19
    /* 91CD0 00091C5C C27B0F46 */  mul.s      $f15, $f15, $f15
    /* 91CD4 00091C60 00631146 */  add.s      $f12, $f12, $f17
    /* 91CD8 00091C64 C29C1346 */  mul.s      $f19, $f19, $f19
    /* 91CDC 00091C68 80730F46 */  add.s      $f14, $f14, $f15
    /* 91CE0 00091C6C 00630D46 */  add.s      $f12, $f12, $f13
    /* 91CE4 00091C70 80731346 */  add.s      $f14, $f14, $f19
    /* 91CE8 00091C74 03630E46 */  div.s      $f12, $f12, $f14
    /* 91CEC 00091C78 00808044 */  mtc1       $zero, $f16
    /* 91CF0 00091C7C 3C601046 */  c.lt.s     $f12, $f16
    /* 91CF4 00091C80 00000000 */  nop
    /* 91CF8 00091C84 25000045 */  bc1f       .Leboot_00091D1C /* handwritten instruction */
    /* 91CFC 00091C88 00000000 */   nop
    /* 91D00 00091C8C 0100053C */  lui        $a1, %hi(sym_0000C9CC)
    /* 91D04 00091C90 00008CC4 */  lwc1       $f12, 0x0($a0)
    /* 91D08 00091C94 CCC9A524 */  addiu      $a1, $a1, %lo(sym_0000C9CC)
    /* 91D0C 00091C98 0000ADC4 */  lwc1       $f13, 0x0($a1)
    /* 91D10 00091C9C 04008EC4 */  lwc1       $f14, 0x4($a0)
    /* 91D14 00091CA0 0400AFC4 */  lwc1       $f15, 0x4($a1)
    /* 91D18 00091CA4 01630D46 */  sub.s      $f12, $f12, $f13
    /* 91D1C 00091CA8 080090C4 */  lwc1       $f16, 0x8($a0)
    /* 91D20 00091CAC 0800B1C4 */  lwc1       $f17, 0x8($a1)
    /* 91D24 00091CB0 81730F46 */  sub.s      $f14, $f14, $f15
    /* 91D28 00091CB4 1800A527 */  addiu      $a1, $sp, 0x18
    /* 91D2C 00091CB8 01841146 */  sub.s      $f16, $f16, $f17
    /* 91D30 00091CBC 1800ACE7 */  swc1       $f12, 0x18($sp)
    /* 91D34 00091CC0 1C00AEE7 */  swc1       $f14, 0x1C($sp)
    /* 91D38 00091CC4 2000B0E7 */  swc1       $f16, 0x20($sp)
    /* 91D3C 00091CC8 0000ACC4 */  lwc1       $f12, 0x0($a1)
    /* 91D40 00091CCC 0400ADC4 */  lwc1       $f13, 0x4($a1)
    /* 91D44 00091CD0 02630C46 */  mul.s      $f12, $f12, $f12
    /* 91D48 00091CD4 0100053C */  lui        $a1, %hi(sym_0000C9D8)
    /* 91D4C 00091CD8 426B0D46 */  mul.s      $f13, $f13, $f13
    /* 91D50 00091CDC D8C9AEC4 */  lwc1       $f14, %lo(sym_0000C9D8)($a1)
    /* 91D54 00091CE0 00630D46 */  add.s      $f12, $f12, $f13
    /* 91D58 00091CE4 3C600E46 */  c.lt.s     $f12, $f14
    /* 91D5C 00091CE8 00000000 */  nop
    /* 91D60 00091CEC 09000045 */  bc1f       .Leboot_00091D14 /* handwritten instruction */
    /* 91D64 00091CF0 00000000 */   nop
    /* 91D68 00091CF4 0000858C */  lw         $a1, 0x0($a0)
    /* 91D6C 00091CF8 0400878C */  lw         $a3, 0x4($a0)
    /* 91D70 00091CFC 0800848C */  lw         $a0, 0x8($a0)
    /* 91D74 00091D00 0000C5AC */  sw         $a1, 0x0($a2)
    /* 91D78 00091D04 0400C7AC */  sw         $a3, 0x4($a2)
    /* 91D7C 00091D08 0800C4AC */  sw         $a0, 0x8($a2)
    /* 91D80 00091D0C 68000010 */  b          .Leboot_00091EB0
    /* 91D84 00091D10 02000234 */   ori       $v0, $zero, 0x2
  .Leboot_00091D14:
    /* 91D88 00091D14 66000010 */  b          .Leboot_00091EB0
    /* 91D8C 00091D18 25100000 */   or        $v0, $zero, $zero
  .Leboot_00091D1C:
    /* 91D90 00091D1C 803F073C */  lui        $a3, (0x3F800000 >> 16)
    /* 91D94 00091D20 00688744 */  mtc1       $a3, $f13
    /* 91D98 00091D24 3E600D46 */  c.le.s     $f12, $f13
    /* 91D9C 00091D28 00000000 */  nop
    /* 91DA0 00091D2C 25000345 */  bc1tl      .Leboot_00091DC4 /* handwritten instruction */
    /* 91DA4 00091D30 0C00A527 */   addiu     $a1, $sp, 0xC
    /* 91DA8 00091D34 0100043C */  lui        $a0, %hi(sym_0000C9CC)
    /* 91DAC 00091D38 0000ACC4 */  lwc1       $f12, 0x0($a1)
    /* 91DB0 00091D3C CCC98424 */  addiu      $a0, $a0, %lo(sym_0000C9CC)
    /* 91DB4 00091D40 00008DC4 */  lwc1       $f13, 0x0($a0)
    /* 91DB8 00091D44 0400AEC4 */  lwc1       $f14, 0x4($a1)
    /* 91DBC 00091D48 04008FC4 */  lwc1       $f15, 0x4($a0)
    /* 91DC0 00091D4C 01630D46 */  sub.s      $f12, $f12, $f13
    /* 91DC4 00091D50 0800B0C4 */  lwc1       $f16, 0x8($a1)
    /* 91DC8 00091D54 080091C4 */  lwc1       $f17, 0x8($a0)
    /* 91DCC 00091D58 81730F46 */  sub.s      $f14, $f14, $f15
    /* 91DD0 00091D5C 2400A427 */  addiu      $a0, $sp, 0x24
    /* 91DD4 00091D60 01841146 */  sub.s      $f16, $f16, $f17
    /* 91DD8 00091D64 2400ACE7 */  swc1       $f12, 0x24($sp)
    /* 91DDC 00091D68 2800AEE7 */  swc1       $f14, 0x28($sp)
    /* 91DE0 00091D6C 2C00B0E7 */  swc1       $f16, 0x2C($sp)
    /* 91DE4 00091D70 00008CC4 */  lwc1       $f12, 0x0($a0)
    /* 91DE8 00091D74 04008DC4 */  lwc1       $f13, 0x4($a0)
    /* 91DEC 00091D78 02630C46 */  mul.s      $f12, $f12, $f12
    /* 91DF0 00091D7C 0100043C */  lui        $a0, %hi(sym_0000C9D8)
    /* 91DF4 00091D80 426B0D46 */  mul.s      $f13, $f13, $f13
    /* 91DF8 00091D84 D8C98EC4 */  lwc1       $f14, %lo(sym_0000C9D8)($a0)
    /* 91DFC 00091D88 00630D46 */  add.s      $f12, $f12, $f13
    /* 91E00 00091D8C 3C600E46 */  c.lt.s     $f12, $f14
    /* 91E04 00091D90 00000000 */  nop
    /* 91E08 00091D94 09000045 */  bc1f       .Leboot_00091DBC /* handwritten instruction */
    /* 91E0C 00091D98 00000000 */   nop
    /* 91E10 00091D9C 0000A48C */  lw         $a0, 0x0($a1)
    /* 91E14 00091DA0 0400A78C */  lw         $a3, 0x4($a1)
    /* 91E18 00091DA4 0800A58C */  lw         $a1, 0x8($a1)
    /* 91E1C 00091DA8 0000C4AC */  sw         $a0, 0x0($a2)
    /* 91E20 00091DAC 0400C7AC */  sw         $a3, 0x4($a2)
    /* 91E24 00091DB0 0800C5AC */  sw         $a1, 0x8($a2)
    /* 91E28 00091DB4 3E000010 */  b          .Leboot_00091EB0
    /* 91E2C 00091DB8 02000234 */   ori       $v0, $zero, 0x2
  .Leboot_00091DBC:
    /* 91E30 00091DBC 3C000010 */  b          .Leboot_00091EB0
    /* 91E34 00091DC0 25100000 */   or        $v0, $zero, $zero
  .Leboot_00091DC4:
    /* 91E38 00091DC4 0000ADC4 */  lwc1       $f13, 0x0($a1)
    /* 91E3C 00091DC8 0400AEC4 */  lwc1       $f14, 0x4($a1)
    /* 91E40 00091DCC 426B0C46 */  mul.s      $f13, $f13, $f12
    /* 91E44 00091DD0 0800AFC4 */  lwc1       $f15, 0x8($a1)
    /* 91E48 00091DD4 82730C46 */  mul.s      $f14, $f14, $f12
    /* 91E4C 00091DD8 3000A527 */  addiu      $a1, $sp, 0x30
    /* 91E50 00091DDC 3000ADE7 */  swc1       $f13, 0x30($sp)
    /* 91E54 00091DE0 027B0C46 */  mul.s      $f12, $f15, $f12
    /* 91E58 00091DE4 3400AEE7 */  swc1       $f14, 0x34($sp)
    /* 91E5C 00091DE8 3800ACE7 */  swc1       $f12, 0x38($sp)
    /* 91E60 00091DEC 00008CC4 */  lwc1       $f12, 0x0($a0)
    /* 91E64 00091DF0 0000ADC4 */  lwc1       $f13, 0x0($a1)
    /* 91E68 00091DF4 04008EC4 */  lwc1       $f14, 0x4($a0)
    /* 91E6C 00091DF8 0400B0C4 */  lwc1       $f16, 0x4($a1)
    /* 91E70 00091DFC 00630D46 */  add.s      $f12, $f12, $f13
    /* 91E74 00091E00 08008FC4 */  lwc1       $f15, 0x8($a0)
    /* 91E78 00091E04 0800B1C4 */  lwc1       $f17, 0x8($a1)
    /* 91E7C 00091E08 80731046 */  add.s      $f14, $f14, $f16
    /* 91E80 00091E0C 4800A427 */  addiu      $a0, $sp, 0x48
    /* 91E84 00091E10 C07B1146 */  add.s      $f15, $f15, $f17
    /* 91E88 00091E14 4800ACE7 */  swc1       $f12, 0x48($sp)
    /* 91E8C 00091E18 0100053C */  lui        $a1, %hi(sym_0000C9CC)
    /* 91E90 00091E1C 4C00AEE7 */  swc1       $f14, 0x4C($sp)
    /* 91E94 00091E20 CCC9A524 */  addiu      $a1, $a1, %lo(sym_0000C9CC)
    /* 91E98 00091E24 5000AFE7 */  swc1       $f15, 0x50($sp)
    /* 91E9C 00091E28 00008CC4 */  lwc1       $f12, 0x0($a0)
    /* 91EA0 00091E2C 0000ADC4 */  lwc1       $f13, 0x0($a1)
    /* 91EA4 00091E30 04008EC4 */  lwc1       $f14, 0x4($a0)
    /* 91EA8 00091E34 0400AFC4 */  lwc1       $f15, 0x4($a1)
    /* 91EAC 00091E38 01630D46 */  sub.s      $f12, $f12, $f13
    /* 91EB0 00091E3C 080090C4 */  lwc1       $f16, 0x8($a0)
    /* 91EB4 00091E40 0800B1C4 */  lwc1       $f17, 0x8($a1)
    /* 91EB8 00091E44 81730F46 */  sub.s      $f14, $f14, $f15
    /* 91EBC 00091E48 3C00A427 */  addiu      $a0, $sp, 0x3C
    /* 91EC0 00091E4C 01841146 */  sub.s      $f16, $f16, $f17
    /* 91EC4 00091E50 3C00ACE7 */  swc1       $f12, 0x3C($sp)
    /* 91EC8 00091E54 4000AEE7 */  swc1       $f14, 0x40($sp)
    /* 91ECC 00091E58 4400B0E7 */  swc1       $f16, 0x44($sp)
    /* 91ED0 00091E5C 00008CC4 */  lwc1       $f12, 0x0($a0)
    /* 91ED4 00091E60 04008DC4 */  lwc1       $f13, 0x4($a0)
    /* 91ED8 00091E64 02630C46 */  mul.s      $f12, $f12, $f12
    /* 91EDC 00091E68 0100043C */  lui        $a0, %hi(sym_0000C9D8)
    /* 91EE0 00091E6C 426B0D46 */  mul.s      $f13, $f13, $f13
    /* 91EE4 00091E70 D8C98EC4 */  lwc1       $f14, %lo(sym_0000C9D8)($a0)
    /* 91EE8 00091E74 00630D46 */  add.s      $f12, $f12, $f13
    /* 91EEC 00091E78 3C600E46 */  c.lt.s     $f12, $f14
    /* 91EF0 00091E7C 00000000 */  nop
    /* 91EF4 00091E80 09000045 */  bc1f       .Leboot_00091EA8 /* handwritten instruction */
    /* 91EF8 00091E84 00000000 */   nop
    /* 91EFC 00091E88 4800A48F */  lw         $a0, 0x48($sp)
    /* 91F00 00091E8C 4C00A58F */  lw         $a1, 0x4C($sp)
    /* 91F04 00091E90 5000A78F */  lw         $a3, 0x50($sp)
    /* 91F08 00091E94 0000C4AC */  sw         $a0, 0x0($a2)
    /* 91F0C 00091E98 0400C5AC */  sw         $a1, 0x4($a2)
    /* 91F10 00091E9C 0800C7AC */  sw         $a3, 0x8($a2)
    /* 91F14 00091EA0 03000010 */  b          .Leboot_00091EB0
    /* 91F18 00091EA4 01000234 */   ori       $v0, $zero, 0x1
  .Leboot_00091EA8:
    /* 91F1C 00091EA8 01000010 */  b          .Leboot_00091EB0
    /* 91F20 00091EAC 25100000 */   or        $v0, $zero, $zero
  .Leboot_00091EB0:
    /* 91F24 00091EB0 0800E003 */  jr         $ra
    /* 91F28 00091EB4 6000BD27 */   addiu     $sp, $sp, 0x60
endlabel func_00091BC4
