.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000F7F14, 0x20

glabel func_000F7F14
    /* F7F88 000F7F14 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* F7F8C 000F7F18 0400A48C */  lw         $a0, 0x4($a1)
    /* F7F90 000F7F1C 1000BFAF */  sw         $ra, 0x10($sp)
    /* F7F94 000F7F20 AEC1060C */  jal        stub_001B06B8
    /* F7F98 000F7F24 03000534 */   ori       $a1, $zero, 0x3
    /* F7F9C 000F7F28 1000BF8F */  lw         $ra, 0x10($sp)
    /* F7FA0 000F7F2C 0800E003 */  jr         $ra
    /* F7FA4 000F7F30 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_000F7F14
