.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0008F558, 0x54

glabel func_0008F558
    /* 8F5CC 0008F558 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 8F5D0 0008F55C 1000B0AF */  sw         $s0, 0x10($sp)
    /* 8F5D4 0008F560 1400B1AF */  sw         $s1, 0x14($sp)
    /* 8F5D8 0008F564 FF009130 */  andi       $s1, $a0, 0xFF
    /* 8F5DC 0008F568 00001034 */  ori        $s0, $zero, 0x0
    /* 8F5E0 0008F56C 1800BFAF */  sw         $ra, 0x18($sp)
    /* 8F5E4 0008F570 AA9D040C */  jal        elem_operator_new
    /* 8F5E8 0008F574 08000434 */   ori       $a0, $zero, 0x8
    /* 8F5EC 0008F578 25204000 */  or         $a0, $v0, $zero
    /* 8F5F0 0008F57C 05008010 */  beqz       $a0, .Leboot_0008F594
    /* 8F5F4 0008F580 0000053C */   lui       $a1, %hi(sym_000012EC)
    /* 8F5F8 0008F584 EC12A524 */  addiu      $a1, $a1, %lo(sym_000012EC)
    /* 8F5FC 0008F588 000085AC */  sw         $a1, 0x0($a0)
    /* 8F600 0008F58C 040091A0 */  sb         $s1, 0x4($a0)
    /* 8F604 0008F590 25808000 */  or         $s0, $a0, $zero
  .Leboot_0008F594:
    /* 8F608 0008F594 25100002 */  or         $v0, $s0, $zero
    /* 8F60C 0008F598 1000B08F */  lw         $s0, 0x10($sp)
    /* 8F610 0008F59C 1400B18F */  lw         $s1, 0x14($sp)
    /* 8F614 0008F5A0 1800BF8F */  lw         $ra, 0x18($sp)
    /* 8F618 0008F5A4 0800E003 */  jr         $ra
    /* 8F61C 0008F5A8 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0008F558
