.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000F69E4, 0x84

glabel func_000F69E4
    /* F6A58 000F69E4 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* F6A5C 000F69E8 1400B1AF */  sw         $s1, 0x14($sp)
    /* F6A60 000F69EC 25888000 */  or         $s1, $a0, $zero
    /* F6A64 000F69F0 1F00043C */  lui        $a0, %hi(sym_001EDC30)
    /* F6A68 000F69F4 30DC8424 */  addiu      $a0, $a0, %lo(sym_001EDC30)
    /* F6A6C 000F69F8 000024AE */  sw         $a0, 0x0($s1)
    /* F6A70 000F69FC 1000B0AF */  sw         $s0, 0x10($sp)
    /* F6A74 000F6A00 2580C000 */  or         $s0, $a2, $zero
    /* F6A78 000F6A04 040025AE */  sw         $a1, 0x4($s1)
    /* F6A7C 000F6A08 080030AE */  sw         $s0, 0x8($s1)
    /* F6A80 000F6A0C 0000A48C */  lw         $a0, 0x0($a1)
    /* F6A84 000F6A10 60008424 */  addiu      $a0, $a0, 0x60
    /* F6A88 000F6A14 00008684 */  lh         $a2, 0x0($a0)
    /* F6A8C 000F6A18 0400878C */  lw         $a3, 0x4($a0)
    /* F6A90 000F6A1C 2120A600 */  addu       $a0, $a1, $a2
    /* F6A94 000F6A20 80BF053C */  lui        $a1, (0xBF800000 >> 16)
    /* F6A98 000F6A24 1800BFAF */  sw         $ra, 0x18($sp)
    /* F6A9C 000F6A28 09F8E000 */  jalr       $a3
    /* F6AA0 000F6A2C 00608544 */   mtc1      $a1, $f12
    /* F6AA4 000F6A30 0000048E */  lw         $a0, 0x0($s0)
    /* F6AA8 000F6A34 60008424 */  addiu      $a0, $a0, 0x60
    /* F6AAC 000F6A38 00008584 */  lh         $a1, 0x0($a0)
    /* F6AB0 000F6A3C 0400868C */  lw         $a2, 0x4($a0)
    /* F6AB4 000F6A40 21200502 */  addu       $a0, $s0, $a1
    /* F6AB8 000F6A44 803F053C */  lui        $a1, (0x3F800000 >> 16)
    /* F6ABC 000F6A48 09F8C000 */  jalr       $a2
    /* F6AC0 000F6A4C 00608544 */   mtc1      $a1, $f12
    /* F6AC4 000F6A50 25102002 */  or         $v0, $s1, $zero
    /* F6AC8 000F6A54 1000B08F */  lw         $s0, 0x10($sp)
    /* F6ACC 000F6A58 1400B18F */  lw         $s1, 0x14($sp)
    /* F6AD0 000F6A5C 1800BF8F */  lw         $ra, 0x18($sp)
    /* F6AD4 000F6A60 0800E003 */  jr         $ra
    /* F6AD8 000F6A64 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_000F69E4
