.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000C8E34, 0x90

glabel func_000C8E34
    /* C8EA8 000C8E34 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* C8EAC 000C8E38 1000B0AF */  sw         $s0, 0x10($sp)
    /* C8EB0 000C8E3C 25808000 */  or         $s0, $a0, $zero
    /* C8EB4 000C8E40 1400B1AF */  sw         $s1, 0x14($sp)
    /* C8EB8 000C8E44 1800B2AF */  sw         $s2, 0x18($sp)
    /* C8EBC 000C8E48 1C00BFAF */  sw         $ra, 0x1C($sp)
    /* C8EC0 000C8E4C C401048E */  lw         $a0, 0x1C4($s0)
    /* C8EC4 000C8E50 00001234 */  ori        $s2, $zero, 0x0
    /* C8EC8 000C8E54 2A204402 */  slt        $a0, $s2, $a0
    /* C8ECC 000C8E58 13008010 */  beqz       $a0, .Leboot_000C8EA8
    /* C8ED0 000C8E5C 00001134 */   ori       $s1, $zero, 0x0
  .Leboot_000C8E60:
    /* C8ED4 000C8E60 C801048E */  lw         $a0, 0x1C8($s0)
    /* C8ED8 000C8E64 21289100 */  addu       $a1, $a0, $s1
    /* C8EDC 000C8E68 7800A58C */  lw         $a1, 0x78($a1)
    /* C8EE0 000C8E6C 21209100 */  addu       $a0, $a0, $s1
    /* C8EE4 000C8E70 A000A524 */  addiu      $a1, $a1, 0xA0
    /* C8EE8 000C8E74 0000A684 */  lh         $a2, 0x0($a1)
    /* C8EEC 000C8E78 0400A58C */  lw         $a1, 0x4($a1)
    /* C8EF0 000C8E7C 09F8A000 */  jalr       $a1
    /* C8EF4 000C8E80 21208600 */   addu      $a0, $a0, $a2
    /* C8EF8 000C8E84 03004010 */  beqz       $v0, .Leboot_000C8E94
    /* C8EFC 000C8E88 00000000 */   nop
    /* C8F00 000C8E8C 07000010 */  b          .Leboot_000C8EAC
    /* C8F04 000C8E90 01000234 */   ori       $v0, $zero, 0x1
  .Leboot_000C8E94:
    /* C8F08 000C8E94 C401048E */  lw         $a0, 0x1C4($s0)
    /* C8F0C 000C8E98 01005226 */  addiu      $s2, $s2, 0x1
    /* C8F10 000C8E9C 2A204402 */  slt        $a0, $s2, $a0
    /* C8F14 000C8EA0 EFFF8014 */  bnez       $a0, .Leboot_000C8E60
    /* C8F18 000C8EA4 60013126 */   addiu     $s1, $s1, 0x160
  .Leboot_000C8EA8:
    /* C8F1C 000C8EA8 25100000 */  or         $v0, $zero, $zero
  .Leboot_000C8EAC:
    /* C8F20 000C8EAC 1000B08F */  lw         $s0, 0x10($sp)
    /* C8F24 000C8EB0 1400B18F */  lw         $s1, 0x14($sp)
    /* C8F28 000C8EB4 1800B28F */  lw         $s2, 0x18($sp)
    /* C8F2C 000C8EB8 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* C8F30 000C8EBC 0800E003 */  jr         $ra
    /* C8F34 000C8EC0 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_000C8E34
