.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0017D7F8, 0xE4

glabel func_0017D7F8
    /* 17D86C 0017D7F8 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 17D870 0017D7FC 1800B0AF */  sw         $s0, 0x18($sp)
    /* 17D874 0017D800 2000B2AF */  sw         $s2, 0x20($sp)
    /* 17D878 0017D804 25808000 */  or         $s0, $a0, $zero
    /* 17D87C 0017D808 1000B227 */  addiu      $s2, $sp, 0x10
    /* 17D880 0017D80C 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* 17D884 0017D810 0700053C */  lui        $a1, %hi(sym_00074260)
    /* 17D888 0017D814 01001134 */  ori        $s1, $zero, 0x1
    /* 17D88C 0017D818 25204002 */  or         $a0, $s2, $zero
    /* 17D890 0017D81C 2400B3AF */  sw         $s3, 0x24($sp)
    /* 17D894 0017D820 2800B4AF */  sw         $s4, 0x28($sp)
    /* 17D898 0017D824 2C00BFAF */  sw         $ra, 0x2C($sp)
    /* 17D89C 0017D828 73C4020C */  jal        func_000B11CC
    /* 17D8A0 0017D82C 6042A524 */   addiu     $a1, $a1, %lo(sym_00074260)
    /* 17D8A4 0017D830 0000043C */  lui        $a0, %hi(sym_00000B1C)
    /* 17D8A8 0017D834 1C0B9324 */  addiu      $s3, $a0, %lo(sym_00000B1C)
    /* 17D8AC 0017D838 1400B3AF */  sw         $s3, 0x14($sp)
    /* 17D8B0 0017D83C 25200002 */  or         $a0, $s0, $zero
    /* 17D8B4 0017D840 01000534 */  ori        $a1, $zero, 0x1
    /* 17D8B8 0017D844 5B15010C */  jal        func_0004556C
    /* 17D8BC 0017D848 25304002 */   or        $a2, $s2, $zero
    /* 17D8C0 0017D84C 25A04000 */  or         $s4, $v0, $zero
    /* 17D8C4 0017D850 1400B3AF */  sw         $s3, 0x14($sp)
    /* 17D8C8 0017D854 25204002 */  or         $a0, $s2, $zero
    /* 17D8CC 0017D858 8BC5020C */  jal        func_000B162C
    /* 17D8D0 0017D85C 25280000 */   or        $a1, $zero, $zero
    /* 17D8D4 0017D860 06008012 */  beqz       $s4, .Leboot_0017D87C
    /* 17D8D8 0017D864 00000434 */   ori       $a0, $zero, 0x0
    /* 17D8DC 0017D868 25200002 */  or         $a0, $s0, $zero
    /* 17D8E0 0017D86C AF3F040C */  jal        func_0010FEBC
    /* 17D8E4 0017D870 01000534 */   ori       $a1, $zero, 0x1
    /* 17D8E8 0017D874 01000010 */  b          .Leboot_0017D87C
    /* 17D8EC 0017D878 25204000 */   or        $a0, $v0, $zero
  .Leboot_0017D87C:
    /* 17D8F0 0017D87C 0C008010 */  beqz       $a0, .Leboot_0017D8B0
    /* 17D8F4 0017D880 00000000 */   nop
    /* 17D8F8 0017D884 4800848C */  lw         $a0, 0x48($a0)
    /* 17D8FC 0017D888 00608444 */  mtc1       $a0, $f12
    /* 17D900 0017D88C 04008104 */  bgez       $a0, .Leboot_0017D8A0
    /* 17D904 0017D890 20638046 */   cvt.s.w   $f12, $f12
    /* 17D908 0017D894 804F043C */  lui        $a0, (0x4F800000 >> 16)
    /* 17D90C 0017D898 00688444 */  mtc1       $a0, $f13
    /* 17D910 0017D89C 00630D46 */  add.s      $f12, $f12, $f13
  .Leboot_0017D8A0:
    /* 17D914 0017D8A0 FD3F040C */  jal        func_0010FFF4
    /* 17D918 0017D8A4 25200002 */   or        $a0, $s0, $zero
    /* 17D91C 0017D8A8 03000010 */  b          .Leboot_0017D8B8
    /* 17D920 0017D8AC 00000000 */   nop
  .Leboot_0017D8B0:
    /* 17D924 0017D8B0 F73F040C */  jal        func_0010FFDC
    /* 17D928 0017D8B4 25200002 */   or        $a0, $s0, $zero
  .Leboot_0017D8B8:
    /* 17D92C 0017D8B8 25102002 */  or         $v0, $s1, $zero
    /* 17D930 0017D8BC 1800B08F */  lw         $s0, 0x18($sp)
    /* 17D934 0017D8C0 1C00B18F */  lw         $s1, 0x1C($sp)
    /* 17D938 0017D8C4 2000B28F */  lw         $s2, 0x20($sp)
    /* 17D93C 0017D8C8 2400B38F */  lw         $s3, 0x24($sp)
    /* 17D940 0017D8CC 2800B48F */  lw         $s4, 0x28($sp)
    /* 17D944 0017D8D0 2C00BF8F */  lw         $ra, 0x2C($sp)
    /* 17D948 0017D8D4 0800E003 */  jr         $ra
    /* 17D94C 0017D8D8 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_0017D7F8
