.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00129E88, 0x304

glabel func_00129E88
    /* 129EFC 00129E88 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 129F00 00129E8C 1C00B0AF */  sw         $s0, 0x1C($sp)
    /* 129F04 00129E90 25808000 */  or         $s0, $a0, $zero
    /* 129F08 00129E94 2000B1AF */  sw         $s1, 0x20($sp)
    /* 129F0C 00129E98 2400B2AF */  sw         $s2, 0x24($sp)
    /* 129F10 00129E9C 2800B3AF */  sw         $s3, 0x28($sp)
    /* 129F14 00129EA0 2C00B4AF */  sw         $s4, 0x2C($sp)
    /* 129F18 00129EA4 3000B5AF */  sw         $s5, 0x30($sp)
    /* 129F1C 00129EA8 3400B6AF */  sw         $s6, 0x34($sp)
    /* 129F20 00129EAC 3800BFAF */  sw         $ra, 0x38($sp)
    /* 129F24 00129EB0 4F6C030C */  jal        func_000DB13C
    /* 129F28 00129EB4 FF00B130 */   andi      $s1, $a1, 0xFF
    /* 129F2C 00129EB8 0C00128E */  lw         $s2, 0xC($s0)
    /* 129F30 00129EBC 0000048E */  lw         $a0, 0x0($s0)
    /* 129F34 00129EC0 70008424 */  addiu      $a0, $a0, 0x70
    /* 129F38 00129EC4 00008584 */  lh         $a1, 0x0($a0)
    /* 129F3C 00129EC8 0400868C */  lw         $a2, 0x4($a0)
    /* 129F40 00129ECC 00001334 */  ori        $s3, $zero, 0x0
    /* 129F44 00129ED0 09F8C000 */  jalr       $a2
    /* 129F48 00129ED4 21200502 */   addu      $a0, $s0, $a1
    /* 129F4C 00129ED8 0000048E */  lw         $a0, 0x0($s0)
    /* 129F50 00129EDC 78008424 */  addiu      $a0, $a0, 0x78
    /* 129F54 00129EE0 00008584 */  lh         $a1, 0x0($a0)
    /* 129F58 00129EE4 0400868C */  lw         $a2, 0x4($a0)
    /* 129F5C 00129EE8 09F8C000 */  jalr       $a2
    /* 129F60 00129EEC 21200502 */   addu      $a0, $s0, $a1
    /* 129F64 00129EF0 4400048E */  lw         $a0, 0x44($s0)
    /* 129F68 00129EF4 44001426 */  addiu      $s4, $s0, 0x44
    /* 129F6C 00129EF8 26289400 */  xor        $a1, $a0, $s4
    /* 129F70 00129EFC 2B280500 */  sltu       $a1, $zero, $a1
    /* 129F74 00129F00 1400A4AF */  sw         $a0, 0x14($sp)
    /* 129F78 00129F04 FF00A530 */  andi       $a1, $a1, 0xFF
    /* 129F7C 00129F08 6500A010 */  beqz       $a1, .Leboot_0012A0A0
    /* 129F80 00129F0C 1000B4AF */   sw        $s4, 0x10($sp)
    /* 129F84 00129F10 34001626 */  addiu      $s6, $s0, 0x34
  .Leboot_00129F14:
    /* 129F88 00129F14 1800A4AF */  sw         $a0, 0x18($sp)
    /* 129F8C 00129F18 0000858C */  lw         $a1, 0x0($a0)
    /* 129F90 00129F1C D8FF8624 */  addiu      $a2, $a0, -0x28
    /* 129F94 00129F20 1800A5AF */  sw         $a1, 0x18($sp)
    /* 129F98 00129F24 3000C590 */  lbu        $a1, 0x30($a2)
    /* 129F9C 00129F28 4F00A010 */  beqz       $a1, .Leboot_0012A068
    /* 129FA0 00129F2C 00000000 */   nop
    /* 129FA4 00129F30 D8FF8524 */  addiu      $a1, $a0, -0x28
    /* 129FA8 00129F34 0800A58C */  lw         $a1, 0x8($a1)
    /* 129FAC 00129F38 4600B210 */  beq        $a1, $s2, .Leboot_0012A054
    /* 129FB0 00129F3C 00000000 */   nop
    /* 129FB4 00129F40 2A002016 */  bnez       $s1, .Leboot_00129FEC
    /* 129FB8 00129F44 D8FF8524 */   addiu     $a1, $a0, -0x28
    /* 129FBC 00129F48 2400A58C */  lw         $a1, 0x24($a1)
    /* 129FC0 00129F4C 2A280500 */  slt        $a1, $zero, $a1
    /* 129FC4 00129F50 FF00A530 */  andi       $a1, $a1, 0xFF
    /* 129FC8 00129F54 2500A010 */  beqz       $a1, .Leboot_00129FEC
    /* 129FCC 00129F58 00000000 */   nop
    /* 129FD0 00129F5C 3400158E */  lw         $s5, 0x34($s0)
    /* 129FD4 00129F60 0000A58E */  lw         $a1, 0x0($s5)
    /* 129FD8 00129F64 2628B500 */  xor        $a1, $a1, $s5
    /* 129FDC 00129F68 0100A52C */  sltiu      $a1, $a1, 0x1
    /* 129FE0 00129F6C FF00A530 */  andi       $a1, $a1, 0xFF
    /* 129FE4 00129F70 0300A010 */  beqz       $a1, .Leboot_00129F80
    /* 129FE8 00129F74 00000000 */   nop
    /* 129FEC 00129F78 07000010 */  b          .Leboot_00129F98
    /* 129FF0 00129F7C 00000534 */   ori       $a1, $zero, 0x0
  .Leboot_00129F80:
    /* 129FF4 00129F80 6A8D040C */  jal        func_001235A8
    /* 129FF8 00129F84 2520A002 */   or        $a0, $s5, $zero
    /* 129FFC 00129F88 00000534 */  ori        $a1, $zero, 0x0
    /* 12A000 00129F8C 1400A48F */  lw         $a0, 0x14($sp)
    /* 12A004 00129F90 0100A056 */  bnel       $s5, $zero, .Leboot_00129F98
    /* 12A008 00129F94 D8FFA526 */   addiu     $a1, $s5, -0x28
  .Leboot_00129F98:
    /* 12A00C 00129F98 D8FF8424 */  addiu      $a0, $a0, -0x28
    /* 12A010 00129F9C 25384002 */  or         $a3, $s2, $zero
    /* 12A014 00129FA0 0800868C */  lw         $a2, 0x8($a0)
    /* 12A018 00129FA4 2590A000 */  or         $s2, $a1, $zero
    /* 12A01C 00129FA8 25204002 */  or         $a0, $s2, $zero
    /* 12A020 00129FAC 2330C700 */  subu       $a2, $a2, $a3
    /* 12A024 00129FB0 489E040C */  jal        func_00127920
    /* 12A028 00129FB4 2528E000 */   or        $a1, $a3, $zero
    /* 12A02C 00129FB8 300040A2 */  sb         $zero, 0x30($s2)
    /* 12A030 00129FBC 1400A48F */  lw         $a0, 0x14($sp)
    /* 12A034 00129FC0 00000534 */  ori        $a1, $zero, 0x0
    /* 12A038 00129FC4 D8FF8424 */  addiu      $a0, $a0, -0x28
    /* 12A03C 00129FC8 28008424 */  addiu      $a0, $a0, 0x28
    /* 12A040 00129FCC 01004056 */  bnel       $s2, $zero, .Leboot_00129FD4
    /* 12A044 00129FD0 28004526 */   addiu     $a1, $s2, 0x28
  .Leboot_00129FD4:
    /* 12A048 00129FD4 4E8D040C */  jal        func_00123538
    /* 12A04C 00129FD8 00000000 */   nop
    /* 12A050 00129FDC 1400A48F */  lw         $a0, 0x14($sp)
    /* 12A054 00129FE0 D8FF8524 */  addiu      $a1, $a0, -0x28
    /* 12A058 00129FE4 1B000010 */  b          .Leboot_0012A054
    /* 12A05C 00129FE8 0800B28C */   lw        $s2, 0x8($a1)
  .Leboot_00129FEC:
    /* 12A060 00129FEC D8FF8524 */  addiu      $a1, $a0, -0x28
    /* 12A064 00129FF0 0000A58C */  lw         $a1, 0x0($a1)
    /* 12A068 00129FF4 D8FF8424 */  addiu      $a0, $a0, -0x28
    /* 12A06C 00129FF8 0100B32C */  sltiu      $s3, $a1, 0x1
    /* 12A070 00129FFC B49E040C */  jal        func_00127AD0
    /* 12A074 0012A000 02000534 */   ori       $a1, $zero, 0x2
    /* 12A078 0012A004 1400A58F */  lw         $a1, 0x14($sp)
    /* 12A07C 0012A008 25204002 */  or         $a0, $s2, $zero
    /* 12A080 0012A00C D8FFA624 */  addiu      $a2, $a1, -0x28
    /* 12A084 0012A010 D8FFA524 */  addiu      $a1, $a1, -0x28
    /* 12A088 0012A014 0C00A78C */  lw         $a3, 0xC($a1)
    /* 12A08C 0012A018 0800C58C */  lw         $a1, 0x8($a2)
    /* 12A090 0012A01C DC0D050C */  jal        func_00143770
    /* 12A094 0012A020 2530E000 */   or        $a2, $a3, $zero
    /* 12A098 0012A024 1400A48F */  lw         $a0, 0x14($sp)
    /* 12A09C 0012A028 25284002 */  or         $a1, $s2, $zero
    /* 12A0A0 0012A02C D8FF8624 */  addiu      $a2, $a0, -0x28
    /* 12A0A4 0012A030 0C00C68C */  lw         $a2, 0xC($a2)
    /* 12A0A8 0012A034 489E040C */  jal        func_00127920
    /* 12A0AC 0012A038 D8FF8424 */   addiu     $a0, $a0, -0x28
    /* 12A0B0 0012A03C 04006012 */  beqz       $s3, .Leboot_0012A050
    /* 12A0B4 0012A040 1400A48F */   lw        $a0, 0x14($sp)
    /* 12A0B8 0012A044 4B9E040C */  jal        func_0012792C
    /* 12A0BC 0012A048 D8FF8424 */   addiu     $a0, $a0, -0x28
    /* 12A0C0 0012A04C 1400A48F */  lw         $a0, 0x14($sp)
  .Leboot_0012A050:
    /* 12A0C4 0012A050 01001334 */  ori        $s3, $zero, 0x1
  .Leboot_0012A054:
    /* 12A0C8 0012A054 D8FF8424 */  addiu      $a0, $a0, -0x28
    /* 12A0CC 0012A058 0C00858C */  lw         $a1, 0xC($a0)
    /* 12A0D0 0012A05C 1800A48F */  lw         $a0, 0x18($sp)
    /* 12A0D4 0012A060 08000010 */  b          .Leboot_0012A084
    /* 12A0D8 0012A064 21904502 */   addu      $s2, $s2, $a1
  .Leboot_0012A068:
    /* 12A0DC 0012A068 D8FF8424 */  addiu      $a0, $a0, -0x28
    /* 12A0E0 0012A06C 00000534 */  ori        $a1, $zero, 0x0
    /* 12A0E4 0012A070 01008054 */  bnel       $a0, $zero, .Leboot_0012A078
    /* 12A0E8 0012A074 28008524 */   addiu     $a1, $a0, 0x28
  .Leboot_0012A078:
    /* 12A0EC 0012A078 4E8D040C */  jal        func_00123538
    /* 12A0F0 0012A07C 2520C002 */   or        $a0, $s6, $zero
    /* 12A0F4 0012A080 1800A48F */  lw         $a0, 0x18($sp)
  .Leboot_0012A084:
    /* 12A0F8 0012A084 1400A4AF */  sw         $a0, 0x14($sp)
    /* 12A0FC 0012A088 1400A48F */  lw         $a0, 0x14($sp)
    /* 12A100 0012A08C 26289400 */  xor        $a1, $a0, $s4
    /* 12A104 0012A090 2B280500 */  sltu       $a1, $zero, $a1
    /* 12A108 0012A094 FF00A530 */  andi       $a1, $a1, 0xFF
    /* 12A10C 0012A098 9EFFA014 */  bnez       $a1, .Leboot_00129F14
    /* 12A110 0012A09C 1000B4AF */   sw        $s4, 0x10($sp)
  .Leboot_0012A0A0:
    /* 12A114 0012A0A0 0C00048E */  lw         $a0, 0xC($s0)
    /* 12A118 0012A0A4 0800118E */  lw         $s1, 0x8($s0)
    /* 12A11C 0012A0A8 23204402 */  subu       $a0, $s2, $a0
    /* 12A120 0012A0AC 23882402 */  subu       $s1, $s1, $a0
    /* 12A124 0012A0B0 1B002012 */  beqz       $s1, .Leboot_0012A120
    /* 12A128 0012A0B4 01000434 */   ori       $a0, $zero, 0x1
    /* 12A12C 0012A0B8 3400158E */  lw         $s5, 0x34($s0)
    /* 12A130 0012A0BC 0000A48E */  lw         $a0, 0x0($s5)
    /* 12A134 0012A0C0 26209500 */  xor        $a0, $a0, $s5
    /* 12A138 0012A0C4 0100842C */  sltiu      $a0, $a0, 0x1
    /* 12A13C 0012A0C8 FF008430 */  andi       $a0, $a0, 0xFF
    /* 12A140 0012A0CC 03008010 */  beqz       $a0, .Leboot_0012A0DC
    /* 12A144 0012A0D0 00000000 */   nop
    /* 12A148 0012A0D4 06000010 */  b          .Leboot_0012A0F0
    /* 12A14C 0012A0D8 00000434 */   ori       $a0, $zero, 0x0
  .Leboot_0012A0DC:
    /* 12A150 0012A0DC 6A8D040C */  jal        func_001235A8
    /* 12A154 0012A0E0 2520A002 */   or        $a0, $s5, $zero
    /* 12A158 0012A0E4 00000434 */  ori        $a0, $zero, 0x0
    /* 12A15C 0012A0E8 0100A056 */  bnel       $s5, $zero, .Leboot_0012A0F0
    /* 12A160 0012A0EC D8FFA426 */   addiu     $a0, $s5, -0x28
  .Leboot_0012A0F0:
    /* 12A164 0012A0F0 25302002 */  or         $a2, $s1, $zero
    /* 12A168 0012A0F4 25888000 */  or         $s1, $a0, $zero
    /* 12A16C 0012A0F8 489E040C */  jal        func_00127920
    /* 12A170 0012A0FC 25284002 */   or        $a1, $s2, $zero
    /* 12A174 0012A100 300020A2 */  sb         $zero, 0x30($s1)
    /* 12A178 0012A104 00001234 */  ori        $s2, $zero, 0x0
    /* 12A17C 0012A108 01002056 */  bnel       $s1, $zero, .Leboot_0012A110
    /* 12A180 0012A10C 28003226 */   addiu     $s2, $s1, 0x28
  .Leboot_0012A110:
    /* 12A184 0012A110 25208002 */  or         $a0, $s4, $zero
    /* 12A188 0012A114 4E8D040C */  jal        func_00123538
    /* 12A18C 0012A118 25284002 */   or        $a1, $s2, $zero
    /* 12A190 0012A11C 01000434 */  ori        $a0, $zero, 0x1
  .Leboot_0012A120:
    /* 12A194 0012A120 1000B4AF */  sw         $s4, 0x10($sp)
    /* 12A198 0012A124 300004A2 */  sb         $a0, 0x30($s0)
    /* 12A19C 0012A128 1000A48F */  lw         $a0, 0x10($sp)
    /* 12A1A0 0012A12C 4C000526 */  addiu      $a1, $s0, 0x4C
    /* 12A1A4 0012A130 0000A4AC */  sw         $a0, 0x0($a1)
    /* 12A1A8 0012A134 4C00048E */  lw         $a0, 0x4C($s0)
    /* 12A1AC 0012A138 0000058E */  lw         $a1, 0x0($s0)
    /* 12A1B0 0012A13C 0400848C */  lw         $a0, 0x4($a0)
    /* 12A1B4 0012A140 7800A524 */  addiu      $a1, $a1, 0x78
    /* 12A1B8 0012A144 4C0004AE */  sw         $a0, 0x4C($s0)
    /* 12A1BC 0012A148 0000A484 */  lh         $a0, 0x0($a1)
    /* 12A1C0 0012A14C 0400A58C */  lw         $a1, 0x4($a1)
    /* 12A1C4 0012A150 09F8A000 */  jalr       $a1
    /* 12A1C8 0012A154 21200402 */   addu      $a0, $s0, $a0
    /* 12A1CC 0012A158 01006012 */  beqz       $s3, .Leboot_0012A160
    /* 12A1D0 0012A15C 00000000 */   nop
  .Leboot_0012A160:
    /* 12A1D4 0012A160 25106002 */  or         $v0, $s3, $zero
    /* 12A1D8 0012A164 1C00B08F */  lw         $s0, 0x1C($sp)
    /* 12A1DC 0012A168 2000B18F */  lw         $s1, 0x20($sp)
    /* 12A1E0 0012A16C 2400B28F */  lw         $s2, 0x24($sp)
    /* 12A1E4 0012A170 2800B38F */  lw         $s3, 0x28($sp)
    /* 12A1E8 0012A174 2C00B48F */  lw         $s4, 0x2C($sp)
    /* 12A1EC 0012A178 3000B58F */  lw         $s5, 0x30($sp)
    /* 12A1F0 0012A17C 3400B68F */  lw         $s6, 0x34($sp)
    /* 12A1F4 0012A180 3800BF8F */  lw         $ra, 0x38($sp)
    /* 12A1F8 0012A184 0800E003 */  jr         $ra
    /* 12A1FC 0012A188 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel func_00129E88
