.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00006A68, 0x1E0

glabel func_00006A68
    /* 6ADC 00006A68 70FFBD27 */  addiu      $sp, $sp, -0x90
    /* 6AE0 00006A6C 7800B0AF */  sw         $s0, 0x78($sp)
    /* 6AE4 00006A70 0700103C */  lui        $s0, %hi(sym_00073DF4)
    /* 6AE8 00006A74 F43D048E */  lw         $a0, %lo(sym_00073DF4)($s0)
    /* 6AEC 00006A78 0000858C */  lw         $a1, 0x0($a0)
    /* 6AF0 00006A7C 3C00A4AF */  sw         $a0, 0x3C($sp)
    /* 6AF4 00006A80 3400A5AF */  sw         $a1, 0x34($sp)
    /* 6AF8 00006A84 3400A58F */  lw         $a1, 0x34($sp)
    /* 6AFC 00006A88 3C00A68F */  lw         $a2, 0x3C($sp)
    /* 6B00 00006A8C 2C00A5AF */  sw         $a1, 0x2C($sp)
    /* 6B04 00006A90 2C00A58F */  lw         $a1, 0x2C($sp)
    /* 6B08 00006A94 3000A6AF */  sw         $a2, 0x30($sp)
    /* 6B0C 00006A98 4800A5AF */  sw         $a1, 0x48($sp)
    /* 6B10 00006A9C 4800A58F */  lw         $a1, 0x48($sp)
    /* 6B14 00006AA0 3000A68F */  lw         $a2, 0x30($sp)
    /* 6B18 00006AA4 2638A600 */  xor        $a3, $a1, $a2
    /* 6B1C 00006AA8 2B380700 */  sltu       $a3, $zero, $a3
    /* 6B20 00006AAC FF00E730 */  andi       $a3, $a3, 0xFF
    /* 6B24 00006AB0 7C00B1AF */  sw         $s1, 0x7C($sp)
    /* 6B28 00006AB4 8000B2AF */  sw         $s2, 0x80($sp)
    /* 6B2C 00006AB8 8400BFAF */  sw         $ra, 0x84($sp)
    /* 6B30 00006ABC 0700E010 */  beqz       $a3, .Leboot_00006ADC
    /* 6B34 00006AC0 4400A0A3 */   sb        $zero, 0x44($sp)
  .Leboot_00006AC4:
    /* 6B38 00006AC4 0000A58C */  lw         $a1, 0x0($a1)
    /* 6B3C 00006AC8 2640A600 */  xor        $t0, $a1, $a2
    /* 6B40 00006ACC 2B380800 */  sltu       $a3, $zero, $t0
    /* 6B44 00006AD0 FF00E730 */  andi       $a3, $a3, 0xFF
    /* 6B48 00006AD4 FBFFE014 */  bnez       $a3, .Leboot_00006AC4
    /* 6B4C 00006AD8 4800A5AF */   sw        $a1, 0x48($sp)
  .Leboot_00006ADC:
    /* 6B50 00006ADC 0000928C */  lw         $s2, 0x0($a0)
    /* 6B54 00006AE0 1000A4AF */  sw         $a0, 0x10($sp)
    /* 6B58 00006AE4 26284402 */  xor        $a1, $s2, $a0
    /* 6B5C 00006AE8 2B280500 */  sltu       $a1, $zero, $a1
    /* 6B60 00006AEC FF00A530 */  andi       $a1, $a1, 0xFF
    /* 6B64 00006AF0 3000A010 */  beqz       $a1, .Leboot_00006BB4
    /* 6B68 00006AF4 1400B2AF */   sw        $s2, 0x14($sp)
    /* 6B6C 00006AF8 2000B127 */  addiu      $s1, $sp, 0x20
  .Leboot_00006AFC:
    /* 6B70 00006AFC 08004526 */  addiu      $a1, $s2, 0x8
    /* 6B74 00006B00 2400A014 */  bnez       $a1, .Leboot_00006B94
    /* 6B78 00006B04 00000000 */   nop
    /* 6B7C 00006B08 2400B2AF */  sw         $s2, 0x24($sp)
    /* 6B80 00006B0C 1800B2AF */  sw         $s2, 0x18($sp)
    /* 6B84 00006B10 0000448E */  lw         $a0, 0x0($s2)
    /* 6B88 00006B14 2000B2AF */  sw         $s2, 0x20($sp)
    /* 6B8C 00006B18 2400A4AF */  sw         $a0, 0x24($sp)
    /* 6B90 00006B1C 0000248E */  lw         $a0, 0x0($s1)
    /* 6B94 00006B20 0000928C */  lw         $s2, 0x0($a0)
    /* 6B98 00006B24 0400868C */  lw         $a2, 0x4($a0)
    /* 6B9C 00006B28 08008524 */  addiu      $a1, $a0, 0x8
    /* 6BA0 00006B2C 0000D2AC */  sw         $s2, 0x0($a2)
    /* 6BA4 00006B30 0E00A010 */  beqz       $a1, .Leboot_00006B6C
    /* 6BA8 00006B34 040046AE */   sw        $a2, 0x4($s2)
    /* 6BAC 00006B38 0C00A010 */  beqz       $a1, .Leboot_00006B6C
    /* 6BB0 00006B3C 00000000 */   nop
    /* 6BB4 00006B40 0800868C */  lw         $a2, 0x8($a0)
    /* 6BB8 00006B44 0900C010 */  beqz       $a2, .Leboot_00006B6C
    /* 6BBC 00006B48 00000000 */   nop
    /* 6BC0 00006B4C 0000C78C */  lw         $a3, 0x0($a2)
    /* 6BC4 00006B50 0500E510 */  beq        $a3, $a1, .Leboot_00006B68
    /* 6BC8 00006B54 0C00888C */   lw        $t0, 0xC($a0)
    /* 6BCC 00006B58 0400E624 */  addiu      $a2, $a3, 0x4
  .Leboot_00006B5C:
    /* 6BD0 00006B5C 0000C78C */  lw         $a3, 0x0($a2)
    /* 6BD4 00006B60 FEFFE554 */  bnel       $a3, $a1, .Leboot_00006B5C
    /* 6BD8 00006B64 0400E624 */   addiu     $a2, $a3, 0x4
  .Leboot_00006B68:
    /* 6BDC 00006B68 0000C8AC */  sw         $t0, 0x0($a2)
  .Leboot_00006B6C:
    /* 6BE0 00006B6C 03008010 */  beqz       $a0, .Leboot_00006B7C
    /* 6BE4 00006B70 00000000 */   nop
    /* 6BE8 00006B74 DDC6040C */  jal        func_00131B74
    /* 6BEC 00006B78 00000000 */   nop
  .Leboot_00006B7C:
    /* 6BF0 00006B7C 2400A48F */  lw         $a0, 0x24($sp)
    /* 6BF4 00006B80 1C00B2AF */  sw         $s2, 0x1C($sp)
    /* 6BF8 00006B84 1400A4AF */  sw         $a0, 0x14($sp)
    /* 6BFC 00006B88 F43D048E */  lw         $a0, %lo(sym_00073DF4)($s0)
    /* 6C00 00006B8C 04000010 */  b          .Leboot_00006BA0
    /* 6C04 00006B90 1400B28F */   lw        $s2, 0x14($sp)
  .Leboot_00006B94:
    /* 6C08 00006B94 2800B2AF */  sw         $s2, 0x28($sp)
    /* 6C0C 00006B98 0000528E */  lw         $s2, 0x0($s2)
    /* 6C10 00006B9C 1400B2AF */  sw         $s2, 0x14($sp)
  .Leboot_00006BA0:
    /* 6C14 00006BA0 26284402 */  xor        $a1, $s2, $a0
    /* 6C18 00006BA4 2B280500 */  sltu       $a1, $zero, $a1
    /* 6C1C 00006BA8 FF00A530 */  andi       $a1, $a1, 0xFF
    /* 6C20 00006BAC D3FFA014 */  bnez       $a1, .Leboot_00006AFC
    /* 6C24 00006BB0 1000A4AF */   sw        $a0, 0x10($sp)
  .Leboot_00006BB4:
    /* 6C28 00006BB4 0000858C */  lw         $a1, 0x0($a0)
    /* 6C2C 00006BB8 6400A4AF */  sw         $a0, 0x64($sp)
    /* 6C30 00006BBC 5C00A5AF */  sw         $a1, 0x5C($sp)
    /* 6C34 00006BC0 5C00A58F */  lw         $a1, 0x5C($sp)
    /* 6C38 00006BC4 6400A68F */  lw         $a2, 0x64($sp)
    /* 6C3C 00006BC8 5400A5AF */  sw         $a1, 0x54($sp)
    /* 6C40 00006BCC 5800A6AF */  sw         $a2, 0x58($sp)
    /* 6C44 00006BD0 5400A58F */  lw         $a1, 0x54($sp)
    /* 6C48 00006BD4 5800A78F */  lw         $a3, 0x58($sp)
    /* 6C4C 00006BD8 7000A5AF */  sw         $a1, 0x70($sp)
    /* 6C50 00006BDC 7000A68F */  lw         $a2, 0x70($sp)
    /* 6C54 00006BE0 6C00A0A3 */  sb         $zero, 0x6C($sp)
    /* 6C58 00006BE4 2640C700 */  xor        $t0, $a2, $a3
    /* 6C5C 00006BE8 2B400800 */  sltu       $t0, $zero, $t0
    /* 6C60 00006BEC FF000831 */  andi       $t0, $t0, 0xFF
    /* 6C64 00006BF0 08000011 */  beqz       $t0, .Leboot_00006C14
    /* 6C68 00006BF4 00000534 */   ori       $a1, $zero, 0x0
  .Leboot_00006BF8:
    /* 6C6C 00006BF8 0000C68C */  lw         $a2, 0x0($a2)
    /* 6C70 00006BFC 0100A524 */  addiu      $a1, $a1, 0x1
    /* 6C74 00006C00 2640C700 */  xor        $t0, $a2, $a3
    /* 6C78 00006C04 2B400800 */  sltu       $t0, $zero, $t0
    /* 6C7C 00006C08 FF000831 */  andi       $t0, $t0, 0xFF
    /* 6C80 00006C0C FAFF0015 */  bnez       $t0, .Leboot_00006BF8
    /* 6C84 00006C10 7000A6AF */   sw        $a2, 0x70($sp)
  .Leboot_00006C14:
    /* 6C88 00006C14 0600A010 */  beqz       $a1, .Leboot_00006C30
    /* 6C8C 00006C18 00000234 */   ori       $v0, $zero, 0x0
    /* 6C90 00006C1C 7400A4AF */  sw         $a0, 0x74($sp)
    /* 6C94 00006C20 0400848C */  lw         $a0, 0x4($a0)
    /* 6C98 00006C24 7400A4AF */  sw         $a0, 0x74($sp)
    /* 6C9C 00006C28 08008424 */  addiu      $a0, $a0, 0x8
    /* 6CA0 00006C2C 0000828C */  lw         $v0, 0x0($a0)
  .Leboot_00006C30:
    /* 6CA4 00006C30 7800B08F */  lw         $s0, 0x78($sp)
    /* 6CA8 00006C34 7C00B18F */  lw         $s1, 0x7C($sp)
    /* 6CAC 00006C38 8000B28F */  lw         $s2, 0x80($sp)
    /* 6CB0 00006C3C 8400BF8F */  lw         $ra, 0x84($sp)
    /* 6CB4 00006C40 0800E003 */  jr         $ra
    /* 6CB8 00006C44 9000BD27 */   addiu     $sp, $sp, 0x90
endlabel func_00006A68
