.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00190CA4, 0x16C

glabel func_00190CA4
    /* 190D18 00190CA4 A0FFBD27 */  addiu      $sp, $sp, -0x60
    /* 190D1C 00190CA8 4800B2AF */  sw         $s2, 0x48($sp)
    /* 190D20 00190CAC 25908000 */  or         $s2, $a0, $zero
    /* 190D24 00190CB0 5000B4AF */  sw         $s4, 0x50($sp)
    /* 190D28 00190CB4 0000548E */  lw         $s4, 0x0($s2)
    /* 190D2C 00190CB8 4C00B3AF */  sw         $s3, 0x4C($sp)
    /* 190D30 00190CBC 04008726 */  addiu      $a3, $s4, 0x4
    /* 190D34 00190CC0 0000F38C */  lw         $s3, 0x0($a3)
    /* 190D38 00190CC4 4400B1AF */  sw         $s1, 0x44($sp)
    /* 190D3C 00190CC8 01000434 */  ori        $a0, $zero, 0x1
    /* 190D40 00190CCC 2588A000 */  or         $s1, $a1, $zero
    /* 190D44 00190CD0 4000B0AF */  sw         $s0, 0x40($sp)
    /* 190D48 00190CD4 5400BFAF */  sw         $ra, 0x54($sp)
    /* 190D4C 00190CD8 0F006012 */  beqz       $s3, .Leboot_00190D18
    /* 190D50 00190CDC 2580C000 */   or        $s0, $a2, $zero
  .Leboot_00190CE0:
    /* 190D54 00190CE0 2800A0A3 */  sb         $zero, 0x28($sp)
    /* 190D58 00190CE4 3D00A0A3 */  sb         $zero, 0x3D($sp)
    /* 190D5C 00190CE8 25A06002 */  or         $s4, $s3, $zero
    /* 190D60 00190CEC 0000048E */  lw         $a0, 0x0($s0)
    /* 190D64 00190CF0 1000858E */  lw         $a1, 0x10($s4)
    /* 190D68 00190CF4 2A208500 */  slt        $a0, $a0, $a1
    /* 190D6C 00190CF8 04008010 */  beqz       $a0, .Leboot_00190D0C
    /* 190D70 00190CFC 0C006526 */   addiu     $a1, $s3, 0xC
    /* 190D74 00190D00 08006526 */  addiu      $a1, $s3, 0x8
    /* 190D78 00190D04 02000010 */  b          .Leboot_00190D10
    /* 190D7C 00190D08 0000B38C */   lw        $s3, 0x0($a1)
  .Leboot_00190D0C:
    /* 190D80 00190D0C 0000B38C */  lw         $s3, 0x0($a1)
  .Leboot_00190D10:
    /* 190D84 00190D10 F3FF6016 */  bnez       $s3, .Leboot_00190CE0
    /* 190D88 00190D14 00000000 */   nop
  .Leboot_00190D18:
    /* 190D8C 00190D18 1B008010 */  beqz       $a0, .Leboot_00190D88
    /* 190D90 00190D1C 2400B4AF */   sw        $s4, 0x24($sp)
    /* 190D94 00190D20 0000448E */  lw         $a0, 0x0($s2)
    /* 190D98 00190D24 2400A58F */  lw         $a1, 0x24($sp)
    /* 190D9C 00190D28 08008424 */  addiu      $a0, $a0, 0x8
    /* 190DA0 00190D2C 0000848C */  lw         $a0, 0x0($a0)
    /* 190DA4 00190D30 2628A400 */  xor        $a1, $a1, $a0
    /* 190DA8 00190D34 2C00A4AF */  sw         $a0, 0x2C($sp)
    /* 190DAC 00190D38 0100A42C */  sltiu      $a0, $a1, 0x1
    /* 190DB0 00190D3C FF008430 */  andi       $a0, $a0, 0xFF
    /* 190DB4 00190D40 05008014 */  bnez       $a0, .Leboot_00190D58
    /* 190DB8 00190D44 00000000 */   nop
    /* 190DBC 00190D48 1245050C */  jal        func_00151448
    /* 190DC0 00190D4C 2400A48F */   lw        $a0, 0x24($sp)
    /* 190DC4 00190D50 0D000010 */  b          .Leboot_00190D88
    /* 190DC8 00190D54 2400A2AF */   sw        $v0, 0x24($sp)
  .Leboot_00190D58:
    /* 190DCC 00190D58 3000A527 */  addiu      $a1, $sp, 0x30
    /* 190DD0 00190D5C 25204002 */  or         $a0, $s2, $zero
    /* 190DD4 00190D60 25306002 */  or         $a2, $s3, $zero
    /* 190DD8 00190D64 25388002 */  or         $a3, $s4, $zero
    /* 190DDC 00190D68 25400002 */  or         $t0, $s0, $zero
    /* 190DE0 00190D6C D541060C */  jal        func_00190754
    /* 190DE4 00190D70 25480000 */   or        $t1, $zero, $zero
    /* 190DE8 00190D74 3000A48F */  lw         $a0, 0x30($sp)
    /* 190DEC 00190D78 01000534 */  ori        $a1, $zero, 0x1
    /* 190DF0 00190D7C 000024AE */  sw         $a0, 0x0($s1)
    /* 190DF4 00190D80 1B000010 */  b          .Leboot_00190DF0
    /* 190DF8 00190D84 040025A2 */   sb        $a1, 0x4($s1)
  .Leboot_00190D88:
    /* 190DFC 00190D88 2400A48F */  lw         $a0, 0x24($sp)
    /* 190E00 00190D8C 3E00A0A3 */  sb         $zero, 0x3E($sp)
    /* 190E04 00190D90 10008424 */  addiu      $a0, $a0, 0x10
    /* 190E08 00190D94 2000A0A3 */  sb         $zero, 0x20($sp)
    /* 190E0C 00190D98 0000848C */  lw         $a0, 0x0($a0)
    /* 190E10 00190D9C 0000058E */  lw         $a1, 0x0($s0)
    /* 190E14 00190DA0 2A208500 */  slt        $a0, $a0, $a1
    /* 190E18 00190DA4 FF008430 */  andi       $a0, $a0, 0xFF
    /* 190E1C 00190DA8 0D008010 */  beqz       $a0, .Leboot_00190DE0
    /* 190E20 00190DAC 00000000 */   nop
    /* 190E24 00190DB0 3800A527 */  addiu      $a1, $sp, 0x38
    /* 190E28 00190DB4 25204002 */  or         $a0, $s2, $zero
    /* 190E2C 00190DB8 25306002 */  or         $a2, $s3, $zero
    /* 190E30 00190DBC 25388002 */  or         $a3, $s4, $zero
    /* 190E34 00190DC0 25400002 */  or         $t0, $s0, $zero
    /* 190E38 00190DC4 D541060C */  jal        func_00190754
    /* 190E3C 00190DC8 25480000 */   or        $t1, $zero, $zero
    /* 190E40 00190DCC 3800A48F */  lw         $a0, 0x38($sp)
    /* 190E44 00190DD0 01000534 */  ori        $a1, $zero, 0x1
    /* 190E48 00190DD4 000024AE */  sw         $a0, 0x0($s1)
    /* 190E4C 00190DD8 05000010 */  b          .Leboot_00190DF0
    /* 190E50 00190DDC 040025A2 */   sb        $a1, 0x4($s1)
  .Leboot_00190DE0:
    /* 190E54 00190DE0 2400A48F */  lw         $a0, 0x24($sp)
    /* 190E58 00190DE4 00000534 */  ori        $a1, $zero, 0x0
    /* 190E5C 00190DE8 000024AE */  sw         $a0, 0x0($s1)
    /* 190E60 00190DEC 040025A2 */  sb         $a1, 0x4($s1)
  .Leboot_00190DF0:
    /* 190E64 00190DF0 4000B08F */  lw         $s0, 0x40($sp)
    /* 190E68 00190DF4 4400B18F */  lw         $s1, 0x44($sp)
    /* 190E6C 00190DF8 4800B28F */  lw         $s2, 0x48($sp)
    /* 190E70 00190DFC 4C00B38F */  lw         $s3, 0x4C($sp)
    /* 190E74 00190E00 5000B48F */  lw         $s4, 0x50($sp)
    /* 190E78 00190E04 5400BF8F */  lw         $ra, 0x54($sp)
    /* 190E7C 00190E08 0800E003 */  jr         $ra
    /* 190E80 00190E0C 6000BD27 */   addiu     $sp, $sp, 0x60
endlabel func_00190CA4
