.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0019F488, 0x58

glabel func_0019F488
    /* 19F4FC 0019F488 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 19F500 0019F48C 1000BFAF */  sw         $ra, 0x10($sp)
    /* 19F504 0019F490 10008010 */  beqz       $a0, .Leboot_0019F4D4
    /* 19F508 0019F494 1F00063C */   lui       $a2, %hi(sym_001EBE98)
    /* 19F50C 0019F498 98BEC624 */  addiu      $a2, $a2, %lo(sym_001EBE98)
    /* 19F510 0019F49C 08008010 */  beqz       $a0, .Leboot_0019F4C0
    /* 19F514 0019F4A0 900086AC */   sw        $a2, 0x90($a0)
    /* 19F518 0019F4A4 1F00063C */  lui        $a2, %hi(sym_001EBE48)
    /* 19F51C 0019F4A8 48BEC624 */  addiu      $a2, $a2, %lo(sym_001EBE48)
    /* 19F520 0019F4AC 04008010 */  beqz       $a0, .Leboot_0019F4C0
    /* 19F524 0019F4B0 900086AC */   sw        $a2, 0x90($a0)
    /* 19F528 0019F4B4 0000063C */  lui        $a2, %hi(sym_00001914)
    /* 19F52C 0019F4B8 1419C624 */  addiu      $a2, $a2, %lo(sym_00001914)
    /* 19F530 0019F4BC 900086AC */  sw         $a2, 0x90($a0)
  .Leboot_0019F4C0:
    /* 19F534 0019F4C0 0100A530 */  andi       $a1, $a1, 0x1
    /* 19F538 0019F4C4 0300A010 */  beqz       $a1, .Leboot_0019F4D4
    /* 19F53C 0019F4C8 00000000 */   nop
    /* 19F540 0019F4CC C79D040C */  jal        func_0012771C
    /* 19F544 0019F4D0 00000000 */   nop
  .Leboot_0019F4D4:
    /* 19F548 0019F4D4 1000BF8F */  lw         $ra, 0x10($sp)
    /* 19F54C 0019F4D8 0800E003 */  jr         $ra
    /* 19F550 0019F4DC 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0019F488
