.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000E4B94, 0x10

glabel func_000E4B94
    /* E4C08 000E4B94 1800828C */  lw         $v0, 0x18($a0)
    /* E4C0C 000E4B98 1400848C */  lw         $a0, 0x14($a0)
    /* E4C10 000E4B9C 0800E003 */  jr         $ra
    /* E4C14 000E4BA0 23104400 */   subu      $v0, $v0, $a0
endlabel func_000E4B94
