.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000B9A3C, 0x64

glabel func_000B9A3C
    /* B9AB0 000B9A3C E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* B9AB4 000B9A40 1400B1AF */  sw         $s1, 0x14($sp)
    /* B9AB8 000B9A44 1D00113C */  lui        $s1, %hi(sym_001D5894)
    /* B9ABC 000B9A48 94583126 */  addiu      $s1, $s1, %lo(sym_001D5894)
    /* B9AC0 000B9A4C 1000B0AF */  sw         $s0, 0x10($sp)
    /* B9AC4 000B9A50 1800B2AF */  sw         $s2, 0x18($sp)
    /* B9AC8 000B9A54 1C00BFAF */  sw         $ra, 0x1C($sp)
    /* B9ACC 000B9A58 00000434 */  ori        $a0, $zero, 0x0
    /* B9AD0 000B9A5C 0E00103C */  lui        $s0, %hi(sym_000E28F0)
    /* B9AD4 000B9A60 00001234 */  ori        $s2, $zero, 0x0
    /* B9AD8 000B9A64 21889100 */  addu       $s1, $a0, $s1
    /* B9ADC 000B9A68 F0281026 */  addiu      $s0, $s0, %lo(sym_000E28F0)
  .Leboot_000B9A6C:
    /* B9AE0 000B9A6C 25200002 */  or         $a0, $s0, $zero
    /* B9AE4 000B9A70 4E8D040C */  jal        func_00123538
    /* B9AE8 000B9A74 25282002 */   or        $a1, $s1, $zero
    /* B9AEC 000B9A78 01005226 */  addiu      $s2, $s2, 0x1
    /* B9AF0 000B9A7C 0004442A */  slti       $a0, $s2, 0x400
    /* B9AF4 000B9A80 FAFF8014 */  bnez       $a0, .Leboot_000B9A6C
    /* B9AF8 000B9A84 10003126 */   addiu     $s1, $s1, 0x10
    /* B9AFC 000B9A88 1000B08F */  lw         $s0, 0x10($sp)
    /* B9B00 000B9A8C 1400B18F */  lw         $s1, 0x14($sp)
    /* B9B04 000B9A90 1800B28F */  lw         $s2, 0x18($sp)
    /* B9B08 000B9A94 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* B9B0C 000B9A98 0800E003 */  jr         $ra
    /* B9B10 000B9A9C 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_000B9A3C
