.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00080C34, 0x3C

glabel func_00080C34
    /* 80CA8 00080C34 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 80CAC 00080C38 1000BFAF */  sw         $ra, 0x10($sp)
    /* 80CB0 00080C3C CF02020C */  jal        func_00080B3C
    /* 80CB4 00080C40 00000000 */   nop
    /* 80CB8 00080C44 25204000 */  or         $a0, $v0, $zero
    /* 80CBC 00080C48 06008010 */  beqz       $a0, .Leboot_00080C64
    /* 80CC0 00080C4C 09000534 */   ori       $a1, $zero, 0x9
    /* 80CC4 00080C50 04008510 */  beq        $a0, $a1, .Leboot_00080C64
    /* 80CC8 00080C54 00000000 */   nop
    /* 80CCC 00080C58 1D00043C */  lui        $a0, %hi(str_interface_benguiat_gothic_medium18)
    /* 80CD0 00080C5C 0F81030C */  jal        func_000E043C
    /* 80CD4 00080C60 48838424 */   addiu     $a0, $a0, %lo(str_interface_benguiat_gothic_medium18)
  .Leboot_00080C64:
    /* 80CD8 00080C64 1000BF8F */  lw         $ra, 0x10($sp)
    /* 80CDC 00080C68 0800E003 */  jr         $ra
    /* 80CE0 00080C6C 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_00080C34
