.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000D38DC, 0x1F4

glabel func_000D38DC
    /* D3950 000D38DC D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* D3954 000D38E0 1800B0AF */  sw         $s0, 0x18($sp)
    /* D3958 000D38E4 25808000 */  or         $s0, $a0, $zero
    /* D395C 000D38E8 1401048E */  lw         $a0, 0x114($s0)
    /* D3960 000D38EC 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* D3964 000D38F0 2000B2AF */  sw         $s2, 0x20($sp)
    /* D3968 000D38F4 2400B3AF */  sw         $s3, 0x24($sp)
    /* D396C 000D38F8 2800BFAF */  sw         $ra, 0x28($sp)
    /* D3970 000D38FC 0500801C */  bgtz       $a0, .Leboot_000D3914
    /* D3974 000D3900 02008528 */   slti      $a1, $a0, 0x2
    /* D3978 000D3904 46008004 */  bltz       $a0, .Leboot_000D3A20
    /* D397C 000D3908 00000000 */   nop
    /* D3980 000D390C 0A000010 */  b          .Leboot_000D3938
    /* D3984 000D3910 00000000 */   nop
  .Leboot_000D3914:
    /* D3988 000D3914 0500A014 */  bnez       $a1, .Leboot_000D392C
    /* D398C 000D3918 03008428 */   slti      $a0, $a0, 0x3
    /* D3990 000D391C 13008014 */  bnez       $a0, .Leboot_000D396C
    /* D3994 000D3920 00000000 */   nop
    /* D3998 000D3924 3E000010 */  b          .Leboot_000D3A20
    /* D399C 000D3928 00000000 */   nop
  .Leboot_000D392C:
    /* D39A0 000D392C 5401118E */  lw         $s1, 0x154($s0)
    /* D39A4 000D3930 3D000010 */  b          .Leboot_000D3A28
    /* D39A8 000D3934 FFFF1324 */   addiu     $s3, $zero, -0x1
  .Leboot_000D3938:
    /* D39AC 000D3938 1E00043C */  lui        $a0, %hi(sym_001D9E64)
    /* D39B0 000D393C 649E848C */  lw         $a0, %lo(sym_001D9E64)($a0)
    /* D39B4 000D3940 06009010 */  beq        $a0, $s0, .Leboot_000D395C
    /* D39B8 000D3944 00000000 */   nop
    /* D39BC 000D3948 6A8D040C */  jal        func_001235A8
    /* D39C0 000D394C 04000426 */   addiu     $a0, $s0, 0x4
    /* D39C4 000D3950 5401118E */  lw         $s1, 0x154($s0)
    /* D39C8 000D3954 34000010 */  b          .Leboot_000D3A28
    /* D39CC 000D3958 FFFF1324 */   addiu     $s3, $zero, -0x1
  .Leboot_000D395C:
    /* D39D0 000D395C 01000434 */  ori        $a0, $zero, 0x1
    /* D39D4 000D3960 1E00053C */  lui        $a1, %hi(sym_001D9E68)
    /* D39D8 000D3964 53000010 */  b          .Leboot_000D3AB4
    /* D39DC 000D3968 689EA4A0 */   sb        $a0, %lo(sym_001D9E68)($a1)
  .Leboot_000D396C:
    /* D39E0 000D396C 3801048E */  lw         $a0, 0x138($s0)
    /* D39E4 000D3970 00001134 */  ori        $s1, $zero, 0x0
    /* D39E8 000D3974 3C01058E */  lw         $a1, 0x13C($s0)
    /* D39EC 000D3978 00001234 */  ori        $s2, $zero, 0x0
    /* D39F0 000D397C FFFF1324 */  addiu      $s3, $zero, -0x1
  .Leboot_000D3980:
    /* D39F4 000D3980 25308000 */  or         $a2, $a0, $zero
    /* D39F8 000D3984 00000734 */  ori        $a3, $zero, 0x0
    /* D39FC 000D3988 0100C054 */  bnel       $a2, $zero, .Leboot_000D3990
    /* D3A00 000D398C 0800C78C */   lw        $a3, 0x8($a2)
  .Leboot_000D3990:
    /* D3A04 000D3990 2130E500 */  addu       $a2, $a3, $a1
    /* D3A08 000D3994 0000C68C */  lw         $a2, 0x0($a2)
    /* D3A0C 000D3998 2A302602 */  slt        $a2, $s1, $a2
    /* D3A10 000D399C 1B00C010 */  beqz       $a2, .Leboot_000D3A0C
    /* D3A14 000D39A0 00000000 */   nop
    /* D3A18 000D39A4 25308000 */  or         $a2, $a0, $zero
    /* D3A1C 000D39A8 00000434 */  ori        $a0, $zero, 0x0
    /* D3A20 000D39AC 0100C054 */  bnel       $a2, $zero, .Leboot_000D39B4
    /* D3A24 000D39B0 0800C48C */   lw        $a0, 0x8($a2)
  .Leboot_000D39B4:
    /* D3A28 000D39B4 21208500 */  addu       $a0, $a0, $a1
    /* D3A2C 000D39B8 0400858C */  lw         $a1, 0x4($a0)
    /* D3A30 000D39BC 04008424 */  addiu      $a0, $a0, 0x4
    /* D3A34 000D39C0 21288500 */  addu       $a1, $a0, $a1
    /* D3A38 000D39C4 2128B200 */  addu       $a1, $a1, $s2
    /* D3A3C 000D39C8 2801078E */  lw         $a3, 0x128($s0)
    /* D3A40 000D39CC 0000A48C */  lw         $a0, 0x0($a1)
    /* D3A44 000D39D0 00000634 */  ori        $a2, $zero, 0x0
    /* D3A48 000D39D4 0100E054 */  bnel       $a3, $zero, .Leboot_000D39DC
    /* D3A4C 000D39D8 0800E68C */   lw        $a2, 0x8($a3)
  .Leboot_000D39DC:
    /* D3A50 000D39DC 2C01078E */  lw         $a3, 0x12C($s0)
    /* D3A54 000D39E0 0400A88C */  lw         $t0, 0x4($a1)
    /* D3A58 000D39E4 2130C700 */  addu       $a2, $a2, $a3
    /* D3A5C 000D39E8 0800A78C */  lw         $a3, 0x8($a1)
    /* D3A60 000D39EC 2128C800 */  addu       $a1, $a2, $t0
    /* D3A64 000D39F0 4A55030C */  jal        func_000D5528
    /* D3A68 000D39F4 2530E000 */   or        $a2, $a3, $zero
    /* D3A6C 000D39F8 3801048E */  lw         $a0, 0x138($s0)
    /* D3A70 000D39FC 01003126 */  addiu      $s1, $s1, 0x1
    /* D3A74 000D3A00 14005226 */  addiu      $s2, $s2, 0x14
    /* D3A78 000D3A04 DEFF0010 */  b          .Leboot_000D3980
    /* D3A7C 000D3A08 3C01058E */   lw        $a1, 0x13C($s0)
  .Leboot_000D3A0C:
    /* D3A80 000D3A0C 2001048E */  lw         $a0, 0x120($s0)
    /* D3A84 000D3A10 B49E040C */  jal        func_00127AD0
    /* D3A88 000D3A14 02000534 */   ori       $a1, $zero, 0x2
    /* D3A8C 000D3A18 03000010 */  b          .Leboot_000D3A28
    /* D3A90 000D3A1C 5401118E */   lw        $s1, 0x154($s0)
  .Leboot_000D3A20:
    /* D3A94 000D3A20 5401118E */  lw         $s1, 0x154($s0)
    /* D3A98 000D3A24 FFFF1324 */  addiu      $s3, $zero, -0x1
  .Leboot_000D3A28:
    /* D3A9C 000D3A28 19003312 */  beq        $s1, $s3, .Leboot_000D3A90
    /* D3AA0 000D3A2C 00000000 */   nop
    /* D3AA4 000D3A30 00001234 */  ori        $s2, $zero, 0x0
    /* D3AA8 000D3A34 AA9D040C */  jal        elem_operator_new
    /* D3AAC 000D3A38 10000434 */   ori       $a0, $zero, 0x10
    /* D3AB0 000D3A3C 25204000 */  or         $a0, $v0, $zero
    /* D3AB4 000D3A40 0E008010 */  beqz       $a0, .Leboot_000D3A7C
    /* D3AB8 000D3A44 1E00053C */   lui       $a1, %hi(sym_001D9E00)
    /* D3ABC 000D3A48 009EA624 */  addiu      $a2, $a1, %lo(sym_001D9E00)
    /* D3AC0 000D3A4C 009EA58C */  lw         $a1, %lo(sym_001D9E00)($a1)
    /* D3AC4 000D3A50 0400C68C */  lw         $a2, 0x4($a2)
    /* D3AC8 000D3A54 1F00073C */  lui        $a3, %hi(sym_001EC8A0)
    /* D3ACC 000D3A58 1000A5AF */  sw         $a1, 0x10($sp)
    /* D3AD0 000D3A5C A0C8E724 */  addiu      $a3, $a3, %lo(sym_001EC8A0)
    /* D3AD4 000D3A60 1400A6AF */  sw         $a2, 0x14($sp)
    /* D3AD8 000D3A64 000087AC */  sw         $a3, 0x0($a0)
    /* D3ADC 000D3A68 040090AC */  sw         $s0, 0x4($a0)
    /* D3AE0 000D3A6C 08008724 */  addiu      $a3, $a0, 0x8
    /* D3AE4 000D3A70 0000E5AC */  sw         $a1, 0x0($a3)
    /* D3AE8 000D3A74 0400E6AC */  sw         $a2, 0x4($a3)
    /* D3AEC 000D3A78 25908000 */  or         $s2, $a0, $zero
  .Leboot_000D3A7C:
    /* D3AF0 000D3A7C 25202002 */  or         $a0, $s1, $zero
    /* D3AF4 000D3A80 B3C1040C */  jal        func_001306CC
    /* D3AF8 000D3A84 25284002 */   or        $a1, $s2, $zero
    /* D3AFC 000D3A88 0A000010 */  b          .Leboot_000D3AB4
    /* D3B00 000D3A8C 00000000 */   nop
  .Leboot_000D3A90:
    /* D3B04 000D3A90 08000012 */  beqz       $s0, .Leboot_000D3AB4
    /* D3B08 000D3A94 00000000 */   nop
    /* D3B0C 000D3A98 0000048E */  lw         $a0, 0x0($s0)
    /* D3B10 000D3A9C 03000534 */  ori        $a1, $zero, 0x3
    /* D3B14 000D3AA0 08008424 */  addiu      $a0, $a0, 0x8
    /* D3B18 000D3AA4 00008684 */  lh         $a2, 0x0($a0)
    /* D3B1C 000D3AA8 0400878C */  lw         $a3, 0x4($a0)
    /* D3B20 000D3AAC 09F8E000 */  jalr       $a3
    /* D3B24 000D3AB0 21200602 */   addu      $a0, $s0, $a2
  .Leboot_000D3AB4:
    /* D3B28 000D3AB4 1800B08F */  lw         $s0, 0x18($sp)
    /* D3B2C 000D3AB8 1C00B18F */  lw         $s1, 0x1C($sp)
    /* D3B30 000D3ABC 2000B28F */  lw         $s2, 0x20($sp)
    /* D3B34 000D3AC0 2400B38F */  lw         $s3, 0x24($sp)
    /* D3B38 000D3AC4 2800BF8F */  lw         $ra, 0x28($sp)
    /* D3B3C 000D3AC8 0800E003 */  jr         $ra
    /* D3B40 000D3ACC 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_000D38DC
