.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000F92A0, 0x50

glabel func_000F92A0
    /* F9314 000F92A0 40390400 */  sll        $a3, $a0, 5
    /* F9318 000F92A4 80200400 */  sll        $a0, $a0, 2
    /* F931C 000F92A8 2320E400 */  subu       $a0, $a3, $a0
    /* F9320 000F92AC 0F00073C */  lui        $a3, %hi(sym_000EB850)
    /* F9324 000F92B0 50B8E724 */  addiu      $a3, $a3, %lo(sym_000EB850)
    /* F9328 000F92B4 21208700 */  addu       $a0, $a0, $a3
    /* F932C 000F92B8 0000878C */  lw         $a3, 0x0($a0)
    /* F9330 000F92BC 83400500 */  sra        $t0, $a1, 2
    /* F9334 000F92C0 0800E734 */  ori        $a3, $a3, 0x8
    /* F9338 000F92C4 82470800 */  srl        $t0, $t0, 30
    /* F933C 000F92C8 000087AC */  sw         $a3, 0x0($a0)
    /* F9340 000F92CC 2128A800 */  addu       $a1, $a1, $t0
    /* F9344 000F92D0 83380600 */  sra        $a3, $a2, 2
    /* F9348 000F92D4 83280500 */  sra        $a1, $a1, 2
    /* F934C 000F92D8 823F0700 */  srl        $a3, $a3, 30
    /* F9350 000F92DC 080085AC */  sw         $a1, 0x8($a0)
    /* F9354 000F92E0 2128C700 */  addu       $a1, $a2, $a3
    /* F9358 000F92E4 83280500 */  sra        $a1, $a1, 2
    /* F935C 000F92E8 0800E003 */  jr         $ra
    /* F9360 000F92EC 0C0085AC */   sw        $a1, 0xC($a0)
endlabel func_000F92A0
