.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_001A682C, 0xC

glabel func_001A682C
    /* 1A68A0 001A682C E400828C */  lw         $v0, 0xE4($a0)
    /* 1A68A4 001A6830 0800E003 */  jr         $ra
    /* 1A68A8 001A6834 01004230 */   andi      $v0, $v0, 0x1
endlabel func_001A682C
