.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0014DC9C, 0xCC

glabel func_0014DC9C
    /* 14DD10 0014DC9C 0000828C */  lw         $v0, 0x0($a0)
    /* 14DD14 0014DCA0 7F00033C */  lui        $v1, (0x7FFFFF >> 16)
    /* 14DD18 0014DCA4 FFFF6334 */  ori        $v1, $v1, (0x7FFFFF & 0xFFFF)
    /* 14DD1C 0014DCA8 C2350200 */  srl        $a2, $v0, 23
    /* 14DD20 0014DCAC C2270200 */  srl        $a0, $v0, 31
    /* 14DD24 0014DCB0 FF00C630 */  andi       $a2, $a2, 0xFF
    /* 14DD28 0014DCB4 0400A4AC */  sw         $a0, 0x4($a1)
    /* 14DD2C 0014DCB8 1700C014 */  bnez       $a2, .Leboot_0014DD18
    /* 14DD30 0014DCBC 24384300 */   and       $a3, $v0, $v1
    /* 14DD34 0014DCC0 1300E010 */  beqz       $a3, sym_0014DD10
    /* 14DD38 0014DCC4 02000224 */   addiu     $v0, $zero, 0x2
    /* 14DD3C 0014DCC8 FF3F023C */  lui        $v0, (0x3FFFFFFF >> 16)
    /* 14DD40 0014DCCC C0390700 */  sll        $a3, $a3, 7
    /* 14DD44 0014DCD0 FFFF4234 */  ori        $v0, $v0, (0x3FFFFFFF & 0xFFFF)
    /* 14DD48 0014DCD4 82FF0324 */  addiu      $v1, $zero, -0x7E
    /* 14DD4C 0014DCD8 03000424 */  addiu      $a0, $zero, 0x3
    /* 14DD50 0014DCDC 2B104700 */  sltu       $v0, $v0, $a3
    /* 14DD54 0014DCE0 0800A3AC */  sw         $v1, 0x8($a1)
    /* 14DD58 0014DCE4 08004014 */  bnez       $v0, sym_0014DD08
    /* 14DD5C 0014DCE8 0000A4AC */   sw        $a0, 0x0($a1)
    /* 14DD60 0014DCEC FF3F043C */  lui        $a0, (0x3FFFFFFF >> 16)
    /* 14DD64 0014DCF0 FFFF8434 */  ori        $a0, $a0, (0x3FFFFFFF & 0xFFFF)
  .Leboot_0014DCF4:
    /* 14DD68 0014DCF4 40380700 */  sll        $a3, $a3, 1
    /* 14DD6C 0014DCF8 2B108700 */  sltu       $v0, $a0, $a3
    /* 14DD70 0014DCFC FDFF4010 */  beqz       $v0, .Leboot_0014DCF4
    /* 14DD74 0014DD00 FFFF6324 */   addiu     $v1, $v1, -0x1
    /* 14DD78 0014DD04 0800A3AC */  sw         $v1, 0x8($a1)
  sym_0014DD08:
    /* 14DD7C 0014DD08 0800E003 */  jr         $ra
    /* 14DD80 0014DD0C 0C00A7AC */   sw        $a3, 0xC($a1)
  sym_0014DD10:
    /* 14DD84 0014DD10 0800E003 */  jr         $ra
    /* 14DD88 0014DD14 0000A2AC */   sw        $v0, 0x0($a1)
  .Leboot_0014DD18:
    /* 14DD8C 0014DD18 FF000224 */  addiu      $v0, $zero, 0xFF
    /* 14DD90 0014DD1C 0800C210 */  beq        $a2, $v0, .Leboot_0014DD40
    /* 14DD94 0014DD20 C0110700 */   sll       $v0, $a3, 7
    /* 14DD98 0014DD24 0040033C */  lui        $v1, (0x40000000 >> 16)
    /* 14DD9C 0014DD28 25104300 */  or         $v0, $v0, $v1
    /* 14DDA0 0014DD2C 81FFC424 */  addiu      $a0, $a2, -0x7F
    /* 14DDA4 0014DD30 0C00A2AC */  sw         $v0, 0xC($a1)
    /* 14DDA8 0014DD34 03000224 */  addiu      $v0, $zero, 0x3
    /* 14DDAC 0014DD38 44370508 */  j          sym_0014DD10
    /* 14DDB0 0014DD3C 0800A4AC */   sw        $a0, 0x8($a1)
  .Leboot_0014DD40:
    /* 14DDB4 0014DD40 0300E054 */  bnel       $a3, $zero, .Leboot_0014DD50
    /* 14DDB8 0014DD44 1000023C */   lui       $v0, (0x100000 >> 16)
    /* 14DDBC 0014DD48 44370508 */  j          sym_0014DD10
    /* 14DDC0 0014DD4C 04000224 */   addiu     $v0, $zero, 0x4
  .Leboot_0014DD50:
    /* 14DDC4 0014DD50 2410E200 */  and        $v0, $a3, $v0
    /* 14DDC8 0014DD54 ECFF4050 */  beql       $v0, $zero, sym_0014DD08
    /* 14DDCC 0014DD58 0000A0AC */   sw        $zero, 0x0($a1)
    /* 14DDD0 0014DD5C 01000224 */  addiu      $v0, $zero, 0x1
    /* 14DDD4 0014DD60 42370508 */  j          sym_0014DD08
    /* 14DDD8 0014DD64 0000A2AC */   sw        $v0, 0x0($a1)
endlabel func_0014DC9C
