.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000B086C, 0x60

glabel func_000B086C
    /* B08E0 000B086C D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* B08E4 000B0870 1D00043C */  lui        $a0, %hi(sym_001D576C)
    /* B08E8 000B0874 6C578CC4 */  lwc1       $f12, %lo(sym_001D576C)($a0)
    /* B08EC 000B0878 3443043C */  lui        $a0, (0x43340000 >> 16)
    /* B08F0 000B087C 00688444 */  mtc1       $a0, $f13
    /* B08F4 000B0880 83630D46 */  div.s      $f14, $f12, $f13
    /* B08F8 000B0884 1D000A3C */  lui        $t2, %hi(sym_001D5770)
    /* B08FC 000B0888 0E00043C */  lui        $a0, %hi(sym_000E6970)
    /* B0900 000B088C 1D00053C */  lui        $a1, %hi(str_lua_show_entire_contents_in_leak_report)
    /* B0904 000B0890 1D000B3C */  lui        $t3, %hi(sym_001D5774)
    /* B0908 000B0894 00000634 */  ori        $a2, $zero, 0x0
    /* B090C 000B0898 70698424 */  addiu      $a0, $a0, %lo(sym_000E6970)
    /* B0910 000B089C C896A524 */  addiu      $a1, $a1, %lo(str_lua_show_entire_contents_in_leak_report)
    /* B0914 000B08A0 25380000 */  or         $a3, $zero, $zero
    /* B0918 000B08A4 02000834 */  ori        $t0, $zero, 0x2
    /* B091C 000B08A8 25480000 */  or         $t1, $zero, $zero
    /* B0920 000B08AC 2000BFAF */  sw         $ra, 0x20($sp)
    /* B0924 000B08B0 036B0C46 */  div.s      $f12, $f13, $f12
    /* B0928 000B08B4 70574EE5 */  swc1       $f14, %lo(sym_001D5770)($t2)
    /* B092C 000B08B8 8C8E040C */  jal        func_00123A30
    /* B0930 000B08BC 74576CE5 */   swc1      $f12, %lo(sym_001D5774)($t3)
    /* B0934 000B08C0 2000BF8F */  lw         $ra, 0x20($sp)
    /* B0938 000B08C4 0800E003 */  jr         $ra
    /* B093C 000B08C8 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_000B086C
