.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000DD674, 0x28

glabel func_000DD674
    /* DD6E8 000DD674 1F00053C */  lui        $a1, %hi(sym_001ECAC0)
    /* DD6EC 000DD678 C0CAA524 */  addiu      $a1, $a1, %lo(sym_001ECAC0)
    /* DD6F0 000DD67C 040085AC */  sw         $a1, 0x4($a0)
    /* DD6F4 000DD680 000080AC */  sw         $zero, 0x0($a0)
    /* DD6F8 000DD684 1E00053C */  lui        $a1, %hi(sym_001D9FB0)
    /* DD6FC 000DD688 B09FA68C */  lw         $a2, %lo(sym_001D9FB0)($a1)
    /* DD700 000DD68C 25108000 */  or         $v0, $a0, $zero
    /* DD704 000DD690 0100C424 */  addiu      $a0, $a2, 0x1
    /* DD708 000DD694 0800E003 */  jr         $ra
    /* DD70C 000DD698 B09FA4AC */   sw        $a0, %lo(sym_001D9FB0)($a1)
endlabel func_000DD674
