.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00086C9C, 0x68

glabel func_00086C9C
    /* 86D10 00086C9C D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 86D14 00086CA0 1000B0AF */  sw         $s0, 0x10($sp)
    /* 86D18 00086CA4 1400B1AF */  sw         $s1, 0x14($sp)
    /* 86D1C 00086CA8 1C00B3AF */  sw         $s3, 0x1C($sp)
    /* 86D20 00086CAC 25888000 */  or         $s1, $a0, $zero
    /* 86D24 00086CB0 2580A000 */  or         $s0, $a1, $zero
    /* 86D28 00086CB4 00001334 */  ori        $s3, $zero, 0x0
    /* 86D2C 00086CB8 1800B2AF */  sw         $s2, 0x18($sp)
    /* 86D30 00086CBC 2000BFAF */  sw         $ra, 0x20($sp)
    /* 86D34 00086CC0 AA9D040C */  jal        elem_operator_new
    /* 86D38 00086CC4 40000434 */   ori       $a0, $zero, 0x40
    /* 86D3C 00086CC8 25904000 */  or         $s2, $v0, $zero
    /* 86D40 00086CCC 05004012 */  beqz       $s2, .Leboot_00086CE4
    /* 86D44 00086CD0 25204002 */   or        $a0, $s2, $zero
    /* 86D48 00086CD4 25282002 */  or         $a1, $s1, $zero
    /* 86D4C 00086CD8 DA1B020C */  jal        func_00086F68
    /* 86D50 00086CDC 25300002 */   or        $a2, $s0, $zero
    /* 86D54 00086CE0 25984002 */  or         $s3, $s2, $zero
  .Leboot_00086CE4:
    /* 86D58 00086CE4 25106002 */  or         $v0, $s3, $zero
    /* 86D5C 00086CE8 1000B08F */  lw         $s0, 0x10($sp)
    /* 86D60 00086CEC 1400B18F */  lw         $s1, 0x14($sp)
    /* 86D64 00086CF0 1800B28F */  lw         $s2, 0x18($sp)
    /* 86D68 00086CF4 1C00B38F */  lw         $s3, 0x1C($sp)
    /* 86D6C 00086CF8 2000BF8F */  lw         $ra, 0x20($sp)
    /* 86D70 00086CFC 0800E003 */  jr         $ra
    /* 86D74 00086D00 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_00086C9C
