.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0018DD2C, 0x8

glabel func_0018DD2C
    /* 18DDA0 0018DD2C 0800E003 */  jr         $ra
    /* 18DDA4 0018DD30 25100000 */   or        $v0, $zero, $zero
endlabel func_0018DD2C
