.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00084D5C, 0x50

glabel func_00084D5C
    /* 84DD0 00084D5C E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 84DD4 00084D60 1000B0AF */  sw         $s0, 0x10($sp)
    /* 84DD8 00084D64 1400BFAF */  sw         $ra, 0x14($sp)
    /* 84DDC 00084D68 9213020C */  jal        func_00084E48
    /* 84DE0 00084D6C 25808000 */   or        $s0, $a0, $zero
    /* 84DE4 00084D70 03004050 */  beql       $v0, $zero, .Leboot_00084D80
    /* 84DE8 00084D74 1C00048E */   lw        $a0, 0x1C($s0)
    /* 84DEC 00084D78 08000010 */  b          .Leboot_00084D9C
    /* 84DF0 00084D7C 0C000234 */   ori       $v0, $zero, 0xC
  .Leboot_00084D80:
    /* 84DF4 00084D80 0800848C */  lw         $a0, 0x8($a0)
    /* 84DF8 00084D84 0000858C */  lw         $a1, 0x0($a0)
    /* 84DFC 00084D88 1000A524 */  addiu      $a1, $a1, 0x10
    /* 84E00 00084D8C 0000A684 */  lh         $a2, 0x0($a1)
    /* 84E04 00084D90 0400A58C */  lw         $a1, 0x4($a1)
    /* 84E08 00084D94 09F8A000 */  jalr       $a1
    /* 84E0C 00084D98 21208600 */   addu      $a0, $a0, $a2
  .Leboot_00084D9C:
    /* 84E10 00084D9C 1000B08F */  lw         $s0, 0x10($sp)
    /* 84E14 00084DA0 1400BF8F */  lw         $ra, 0x14($sp)
    /* 84E18 00084DA4 0800E003 */  jr         $ra
    /* 84E1C 00084DA8 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_00084D5C
