.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0016C310, 0x168

glabel func_0016C310
    /* 16C384 0016C310 C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 16C388 0016C314 0800868C */  lw         $a2, 0x8($a0)
    /* 16C38C 0016C318 0000878C */  lw         $a3, 0x0($a0)
    /* 16C390 0016C31C 2330C700 */  subu       $a2, $a2, $a3
    /* 16C394 0016C320 83380600 */  sra        $a3, $a2, 2
    /* 16C398 0016C324 823F0700 */  srl        $a3, $a3, 30
    /* 16C39C 0016C328 2130C700 */  addu       $a2, $a2, $a3
    /* 16C3A0 0016C32C 83300600 */  sra        $a2, $a2, 2
    /* 16C3A4 0016C330 2400B0AF */  sw         $s0, 0x24($sp)
    /* 16C3A8 0016C334 25808000 */  or         $s0, $a0, $zero
    /* 16C3AC 0016C338 2B30C500 */  sltu       $a2, $a2, $a1
    /* 16C3B0 0016C33C 2800B1AF */  sw         $s1, 0x28($sp)
    /* 16C3B4 0016C340 2C00B2AF */  sw         $s2, 0x2C($sp)
    /* 16C3B8 0016C344 3000B3AF */  sw         $s3, 0x30($sp)
    /* 16C3BC 0016C348 3400B4AF */  sw         $s4, 0x34($sp)
    /* 16C3C0 0016C34C 3800B5AF */  sw         $s5, 0x38($sp)
    /* 16C3C4 0016C350 3C00BFAF */  sw         $ra, 0x3C($sp)
    /* 16C3C8 0016C354 3F00C010 */  beqz       $a2, .Leboot_0016C454
    /* 16C3CC 0016C358 2588A000 */   or        $s1, $a1, $zero
    /* 16C3D0 0016C35C 0400048E */  lw         $a0, 0x4($s0)
    /* 16C3D4 0016C360 0000058E */  lw         $a1, 0x0($s0)
    /* 16C3D8 0016C364 23208500 */  subu       $a0, $a0, $a1
    /* 16C3DC 0016C368 83300400 */  sra        $a2, $a0, 2
    /* 16C3E0 0016C36C 82370600 */  srl        $a2, $a2, 30
    /* 16C3E4 0016C370 21908600 */  addu       $s2, $a0, $a2
    /* 16C3E8 0016C374 2500A010 */  beqz       $a1, .Leboot_0016C40C
    /* 16C3EC 0016C378 83901200 */   sra       $s2, $s2, 2
    /* 16C3F0 0016C37C 0000138E */  lw         $s3, 0x0($s0)
    /* 16C3F4 0016C380 0400148E */  lw         $s4, 0x4($s0)
    /* 16C3F8 0016C384 0A002012 */  beqz       $s1, .Leboot_0016C3B0
    /* 16C3FC 0016C388 00001534 */   ori       $s5, $zero, 0x0
    /* 16C400 0016C38C 80201100 */  sll        $a0, $s1, 2
    /* 16C404 0016C390 70C5040C */  jal        func_001315C0
    /* 16C408 0016C394 2000A4AF */   sw        $a0, 0x20($sp)
    /* 16C40C 0016C398 25A84000 */  or         $s5, $v0, $zero
    /* 16C410 0016C39C 0400A016 */  bnez       $s5, .Leboot_0016C3B0
    /* 16C414 0016C3A0 2000A48F */   lw        $a0, 0x20($sp)
    /* 16C418 0016C3A4 AB41050C */  jal        func_001506AC
    /* 16C41C 0016C3A8 00000000 */   nop
    /* 16C420 0016C3AC 25A84000 */  or         $s5, $v0, $zero
  .Leboot_0016C3B0:
    /* 16C424 0016C3B0 1200A0A3 */  sb         $zero, 0x12($sp)
    /* 16C428 0016C3B4 1200A483 */  lb         $a0, 0x12($sp)
    /* 16C42C 0016C3B8 1500A0A3 */  sb         $zero, 0x15($sp)
    /* 16C430 0016C3BC 1000A0A3 */  sb         $zero, 0x10($sp)
    /* 16C434 0016C3C0 1500A583 */  lb         $a1, 0x15($sp)
    /* 16C438 0016C3C4 1100A4A3 */  sb         $a0, 0x11($sp)
    /* 16C43C 0016C3C8 1EB1050C */  jal        func_0016C478
    /* 16C440 0016C3CC 1600A5A3 */   sb        $a1, 0x16($sp)
    /* 16C444 0016C3D0 1800A2AF */  sw         $v0, 0x18($sp)
    /* 16C448 0016C3D4 1800A483 */  lb         $a0, 0x18($sp)
    /* 16C44C 0016C3D8 05009312 */  beq        $s4, $s3, .Leboot_0016C3F0
    /* 16C450 0016C3DC 1400A4A3 */   sb        $a0, 0x14($sp)
    /* 16C454 0016C3E0 23309302 */  subu       $a2, $s4, $s3
    /* 16C458 0016C3E4 2520A002 */  or         $a0, $s5, $zero
    /* 16C45C 0016C3E8 DC0D050C */  jal        func_00143770
    /* 16C460 0016C3EC 25286002 */   or        $a1, $s3, $zero
  .Leboot_0016C3F0:
    /* 16C464 0016C3F0 0000048E */  lw         $a0, 0x0($s0)
    /* 16C468 0016C3F4 10008010 */  beqz       $a0, .Leboot_0016C438
    /* 16C46C 0016C3F8 1700A0A3 */   sb        $zero, 0x17($sp)
    /* 16C470 0016C3FC DDC6040C */  jal        func_00131B74
    /* 16C474 0016C400 00000000 */   nop
    /* 16C478 0016C404 0C000010 */  b          .Leboot_0016C438
    /* 16C47C 0016C408 00000000 */   nop
  .Leboot_0016C40C:
    /* 16C480 0016C40C 0A002012 */  beqz       $s1, .Leboot_0016C438
    /* 16C484 0016C410 00001534 */   ori       $s5, $zero, 0x0
    /* 16C488 0016C414 80201100 */  sll        $a0, $s1, 2
    /* 16C48C 0016C418 70C5040C */  jal        func_001315C0
    /* 16C490 0016C41C 1C00A4AF */   sw        $a0, 0x1C($sp)
    /* 16C494 0016C420 25A84000 */  or         $s5, $v0, $zero
    /* 16C498 0016C424 0400A016 */  bnez       $s5, .Leboot_0016C438
    /* 16C49C 0016C428 1C00A48F */   lw        $a0, 0x1C($sp)
    /* 16C4A0 0016C42C AB41050C */  jal        func_001506AC
    /* 16C4A4 0016C430 00000000 */   nop
    /* 16C4A8 0016C434 25A84000 */  or         $s5, $v0, $zero
  .Leboot_0016C438:
    /* 16C4AC 0016C438 80201200 */  sll        $a0, $s2, 2
    /* 16C4B0 0016C43C 80281100 */  sll        $a1, $s1, 2
    /* 16C4B4 0016C440 2120A402 */  addu       $a0, $s5, $a0
    /* 16C4B8 0016C444 000015AE */  sw         $s5, 0x0($s0)
    /* 16C4BC 0016C448 2128A502 */  addu       $a1, $s5, $a1
    /* 16C4C0 0016C44C 040004AE */  sw         $a0, 0x4($s0)
    /* 16C4C4 0016C450 080005AE */  sw         $a1, 0x8($s0)
  .Leboot_0016C454:
    /* 16C4C8 0016C454 2400B08F */  lw         $s0, 0x24($sp)
    /* 16C4CC 0016C458 2800B18F */  lw         $s1, 0x28($sp)
    /* 16C4D0 0016C45C 2C00B28F */  lw         $s2, 0x2C($sp)
    /* 16C4D4 0016C460 3000B38F */  lw         $s3, 0x30($sp)
    /* 16C4D8 0016C464 3400B48F */  lw         $s4, 0x34($sp)
    /* 16C4DC 0016C468 3800B58F */  lw         $s5, 0x38($sp)
    /* 16C4E0 0016C46C 3C00BF8F */  lw         $ra, 0x3C($sp)
    /* 16C4E4 0016C470 0800E003 */  jr         $ra
    /* 16C4E8 0016C474 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel func_0016C310
