.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0008F350, 0x208

glabel func_0008F350
    /* 8F3C4 0008F350 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 8F3C8 0008F354 1D00043C */  lui        $a0, %hi(sym_001D4BC0)
    /* 8F3CC 0008F358 C04B8CC4 */  lwc1       $f12, %lo(sym_001D4BC0)($a0)
    /* 8F3D0 0008F35C 3443043C */  lui        $a0, (0x43340000 >> 16)
    /* 8F3D4 0008F360 00688444 */  mtc1       $a0, $f13
    /* 8F3D8 0008F364 83630D46 */  div.s      $f14, $f12, $f13
    /* 8F3DC 0008F368 1D00073C */  lui        $a3, %hi(sym_001D4BC4)
    /* 8F3E0 0008F36C 7665043C */  lui        $a0, %hi(D_65766177)
    /* 8F3E4 0008F370 1D00083C */  lui        $t0, %hi(sym_001D4BC8)
    /* 8F3E8 0008F374 09000534 */  ori        $a1, $zero, 0x9
    /* 8F3EC 0008F378 20000634 */  ori        $a2, $zero, 0x20
    /* 8F3F0 0008F37C 77618424 */  addiu      $a0, $a0, %lo(D_65766177)
    /* 8F3F4 0008F380 1000BFAF */  sw         $ra, 0x10($sp)
    /* 8F3F8 0008F384 036B0C46 */  div.s      $f12, $f13, $f12
    /* 8F3FC 0008F388 C44BEEE4 */  swc1       $f14, %lo(sym_001D4BC4)($a3)
    /* 8F400 0008F38C 611B040C */  jal        elem_register_chunk_tag
    /* 8F404 0008F390 C84B0CE5 */   swc1      $f12, %lo(sym_001D4BC8)($t0)
    /* 8F408 0008F394 7461043C */  lui        $a0, %hi(D_61746473)
    /* 8F40C 0008F398 01000534 */  ori        $a1, $zero, 0x1
    /* 8F410 0008F39C 20000634 */  ori        $a2, $zero, 0x20
    /* 8F414 0008F3A0 611B040C */  jal        elem_register_chunk_tag
    /* 8F418 0008F3A4 73648424 */   addiu     $a0, $a0, %lo(D_61746473)
    /* 8F41C 0008F3A8 6220043C */  lui        $a0, %hi(D_20626D78)
    /* 8F420 0008F3AC 25280000 */  or         $a1, $zero, $zero
    /* 8F424 0008F3B0 40000634 */  ori        $a2, $zero, 0x40
    /* 8F428 0008F3B4 611B040C */  jal        elem_register_chunk_tag
    /* 8F42C 0008F3B8 786D8424 */   addiu     $a0, $a0, %lo(D_20626D78)
    /* 8F430 0008F3BC 7320043C */  lui        $a0, %hi(D_20736D78)
    /* 8F434 0008F3C0 25280000 */  or         $a1, $zero, $zero
    /* 8F438 0008F3C4 40000634 */  ori        $a2, $zero, 0x40
    /* 8F43C 0008F3C8 611B040C */  jal        elem_register_chunk_tag
    /* 8F440 0008F3CC 786D8424 */   addiu     $a0, $a0, %lo(D_20736D78)
    /* 8F444 0008F3D0 6820043C */  lui        $a0, %hi(D_20686D78)
    /* 8F448 0008F3D4 25280000 */  or         $a1, $zero, $zero
    /* 8F44C 0008F3D8 20000634 */  ori        $a2, $zero, 0x20
    /* 8F450 0008F3DC 611B040C */  jal        elem_register_chunk_tag
    /* 8F454 0008F3E0 786D8424 */   addiu     $a0, $a0, %lo(D_20686D78)
    /* 8F458 0008F3E4 7266043C */  lui        $a0, %hi(D_66727573)
    /* 8F45C 0008F3E8 3A000534 */  ori        $a1, $zero, 0x3A
    /* 8F460 0008F3EC 80000634 */  ori        $a2, $zero, 0x80
    /* 8F464 0008F3F0 611B040C */  jal        elem_register_chunk_tag
    /* 8F468 0008F3F4 73758424 */   addiu     $a0, $a0, %lo(D_66727573)
    /* 8F46C 0008F3F8 6864043C */  lui        $a0, %hi(D_64687367)
    /* 8F470 0008F3FC 0D000534 */  ori        $a1, $zero, 0xD
    /* 8F474 0008F400 20000634 */  ori        $a2, $zero, 0x20
    /* 8F478 0008F404 611B040C */  jal        elem_register_chunk_tag
    /* 8F47C 0008F408 67738424 */   addiu     $a0, $a0, %lo(D_64687367)
    /* 8F480 0008F40C 6D73043C */  lui        $a0, %hi(D_736D6472)
    /* 8F484 0008F410 36000534 */  ori        $a1, $zero, 0x36
    /* 8F488 0008F414 40000634 */  ori        $a2, $zero, 0x40
    /* 8F48C 0008F418 611B040C */  jal        elem_register_chunk_tag
    /* 8F490 0008F41C 72648424 */   addiu     $a0, $a0, %lo(D_736D6472)
    /* 8F494 0008F420 726E043C */  lui        $a0, %hi(D_6E726574)
    /* 8F498 0008F424 06000534 */  ori        $a1, $zero, 0x6
    /* 8F49C 0008F428 20000634 */  ori        $a2, $zero, 0x20
    /* 8F4A0 0008F42C 611B040C */  jal        elem_register_chunk_tag
    /* 8F4A4 0008F430 74658424 */   addiu     $a0, $a0, %lo(D_6E726574)
    /* 8F4A8 0008F434 6267043C */  lui        $a0, %hi(D_6762646E)
    /* 8F4AC 0008F438 04000534 */  ori        $a1, $zero, 0x4
    /* 8F4B0 0008F43C 20000634 */  ori        $a2, $zero, 0x20
    /* 8F4B4 0008F440 611B040C */  jal        elem_register_chunk_tag
    /* 8F4B8 0008F444 6E648424 */   addiu     $a0, $a0, %lo(D_6762646E)
    /* 8F4BC 0008F448 6465043C */  lui        $a0, %hi(D_65646F6E)
    /* 8F4C0 0008F44C D0000534 */  ori        $a1, $zero, 0xD0
    /* 8F4C4 0008F450 20000634 */  ori        $a2, $zero, 0x20
    /* 8F4C8 0008F454 611B040C */  jal        elem_register_chunk_tag
    /* 8F4CC 0008F458 6E6F8424 */   addiu     $a0, $a0, %lo(D_65646F6E)
    /* 8F4D0 0008F45C 7368043C */  lui        $a0, %hi(D_68736D62)
    /* 8F4D4 0008F460 25000534 */  ori        $a1, $zero, 0x25
    /* 8F4D8 0008F464 20000634 */  ori        $a2, $zero, 0x20
    /* 8F4DC 0008F468 611B040C */  jal        elem_register_chunk_tag
    /* 8F4E0 0008F46C 626D8424 */   addiu     $a0, $a0, %lo(D_68736D62)
    /* 8F4E4 0008F470 6479043C */  lui        $a0, %hi(D_79646F62)
    /* 8F4E8 0008F474 46000534 */  ori        $a1, $zero, 0x46
    /* 8F4EC 0008F478 20000634 */  ori        $a2, $zero, 0x20
    /* 8F4F0 0008F47C 611B040C */  jal        elem_register_chunk_tag
    /* 8F4F4 0008F480 626F8424 */   addiu     $a0, $a0, %lo(D_79646F62)
    /* 8F4F8 0008F484 6E6D043C */  lui        $a0, %hi(D_6D6E6162)
    /* 8F4FC 0008F488 12000534 */  ori        $a1, $zero, 0x12
    /* 8F500 0008F48C 20000634 */  ori        $a2, $zero, 0x20
    /* 8F504 0008F490 611B040C */  jal        elem_register_chunk_tag
    /* 8F508 0008F494 62618424 */   addiu     $a0, $a0, %lo(D_6D6E6162)
    /* 8F50C 0008F498 0700043C */  lui        $a0, %hi(sym_00074190)
    /* 8F510 0008F49C 1D00063C */  lui        $a2, %hi(str_TurnToPoint_8B2C)
    /* 8F514 0008F4A0 04000534 */  ori        $a1, $zero, 0x4
    /* 8F518 0008F4A4 90418424 */  addiu      $a0, $a0, %lo(sym_00074190)
    /* 8F51C 0008F4A8 0B47060C */  jal        func_00191C2C
    /* 8F520 0008F4AC 2C8BC624 */   addiu     $a2, $a2, %lo(str_TurnToPoint_8B2C)
    /* 8F524 0008F4B0 1D00043C */  lui        $a0, %hi(sym_001D4BCC)
    /* 8F528 0008F4B4 7631050C */  jal        func_0014C5D8
    /* 8F52C 0008F4B8 CC4B8424 */   addiu     $a0, $a0, %lo(sym_001D4BCC)
    /* 8F530 0008F4BC 0700043C */  lui        $a0, %hi(sym_00074128)
    /* 8F534 0008F4C0 1D00063C */  lui        $a2, %hi(str_MoveToPoint)
    /* 8F538 0008F4C4 04000534 */  ori        $a1, $zero, 0x4
    /* 8F53C 0008F4C8 28418424 */  addiu      $a0, $a0, %lo(sym_00074128)
    /* 8F540 0008F4CC 2C48060C */  jal        func_001920B0
    /* 8F544 0008F4D0 508BC624 */   addiu     $a2, $a2, %lo(str_MoveToPoint)
    /* 8F548 0008F4D4 1D00043C */  lui        $a0, %hi(sym_001D4BD8)
    /* 8F54C 0008F4D8 7631050C */  jal        func_0014C5D8
    /* 8F550 0008F4DC D84B8424 */   addiu     $a0, $a0, %lo(sym_001D4BD8)
    /* 8F554 0008F4E0 0700043C */  lui        $a0, %hi(sym_000740C0)
    /* 8F558 0008F4E4 1D00063C */  lui        $a2, %hi(str_FollowPathOnce)
    /* 8F55C 0008F4E8 04000534 */  ori        $a1, $zero, 0x4
    /* 8F560 0008F4EC C0408424 */  addiu      $a0, $a0, %lo(sym_000740C0)
    /* 8F564 0008F4F0 4D49060C */  jal        func_00192534
    /* 8F568 0008F4F4 788BC624 */   addiu     $a2, $a2, %lo(str_FollowPathOnce)
    /* 8F56C 0008F4F8 1D00043C */  lui        $a0, %hi(sym_001D4BE4)
    /* 8F570 0008F4FC 7631050C */  jal        func_0014C5D8
    /* 8F574 0008F500 E44B8424 */   addiu     $a0, $a0, %lo(sym_001D4BE4)
    /* 8F578 0008F504 0700043C */  lui        $a0, %hi(sym_00074058)
    /* 8F57C 0008F508 1D00063C */  lui        $a2, %hi(str_NavigateToPoint)
    /* 8F580 0008F50C 04000534 */  ori        $a1, $zero, 0x4
    /* 8F584 0008F510 58408424 */  addiu      $a0, $a0, %lo(sym_00074058)
    /* 8F588 0008F514 6E4A060C */  jal        func_001929B8
    /* 8F58C 0008F518 E88BC624 */   addiu     $a2, $a2, %lo(str_NavigateToPoint)
    /* 8F590 0008F51C 1D00043C */  lui        $a0, %hi(sym_001D4BF0)
    /* 8F594 0008F520 7631050C */  jal        func_0014C5D8
    /* 8F598 0008F524 F04B8424 */   addiu     $a0, $a0, %lo(sym_001D4BF0)
    /* 8F59C 0008F528 0700043C */  lui        $a0, %hi(sym_00073FF0)
    /* 8F5A0 0008F52C 1D00063C */  lui        $a2, %hi(str_WarpTo)
    /* 8F5A4 0008F530 04000534 */  ori        $a1, $zero, 0x4
    /* 8F5A8 0008F534 F03F8424 */  addiu      $a0, $a0, %lo(sym_00073FF0)
    /* 8F5AC 0008F538 8F4B060C */  jal        func_00192E3C
    /* 8F5B0 0008F53C E08BC624 */   addiu     $a2, $a2, %lo(str_WarpTo)
    /* 8F5B4 0008F540 1D00043C */  lui        $a0, %hi(sym_001D4BFC)
    /* 8F5B8 0008F544 7631050C */  jal        func_0014C5D8
    /* 8F5BC 0008F548 FC4B8424 */   addiu     $a0, $a0, %lo(sym_001D4BFC)
    /* 8F5C0 0008F54C 1000BF8F */  lw         $ra, 0x10($sp)
    /* 8F5C4 0008F550 0800E003 */  jr         $ra
    /* 8F5C8 0008F554 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0008F350
