.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000E70C8, 0x4C

glabel func_000E70C8
    /* E713C 000E70C8 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* E7140 000E70CC 29008590 */  lbu        $a1, 0x29($a0)
    /* E7144 000E70D0 1000B0AF */  sw         $s0, 0x10($sp)
    /* E7148 000E70D4 1400BFAF */  sw         $ra, 0x14($sp)
    /* E714C 000E70D8 0A00A014 */  bnez       $a1, .Leboot_000E7104
    /* E7150 000E70DC 25808000 */   or        $s0, $a0, $zero
    /* E7154 000E70E0 01000434 */  ori        $a0, $zero, 0x1
    /* E7158 000E70E4 290004A2 */  sb         $a0, 0x29($s0)
    /* E715C 000E70E8 28000492 */  lbu        $a0, 0x28($s0)
    /* E7160 000E70EC 05008010 */  beqz       $a0, .Leboot_000E7104
    /* E7164 000E70F0 00000000 */   nop
    /* E7168 000E70F4 BC9D030C */  jal        func_000E76F0
    /* E716C 000E70F8 8000048E */   lw        $a0, 0x80($s0)
    /* E7170 000E70FC B370020C */  jal        func_0009C2CC
    /* E7174 000E7100 1000048E */   lw        $a0, 0x10($s0)
  .Leboot_000E7104:
    /* E7178 000E7104 1000B08F */  lw         $s0, 0x10($sp)
    /* E717C 000E7108 1400BF8F */  lw         $ra, 0x14($sp)
    /* E7180 000E710C 0800E003 */  jr         $ra
    /* E7184 000E7110 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_000E70C8
