.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0006B6B8, 0xC

glabel func_0006B6B8
    /* 6B72C 0006B6B8 0E00023C */  lui        $v0, %hi(sym_000E2240)
    /* 6B730 0006B6BC 0800E003 */  jr         $ra
    /* 6B734 0006B6C0 40224224 */   addiu     $v0, $v0, %lo(sym_000E2240)
endlabel func_0006B6B8
