.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000F6960, 0x2C

glabel func_000F6960
    /* F69D4 000F6960 1E00043C */  lui        $a0, %hi(sym_001DABD0)
    /* F69D8 000F6964 D0AB8CC4 */  lwc1       $f12, %lo(sym_001DABD0)($a0)
    /* F69DC 000F6968 3443043C */  lui        $a0, (0x43340000 >> 16)
    /* F69E0 000F696C 00688444 */  mtc1       $a0, $f13
    /* F69E4 000F6970 83630D46 */  div.s      $f14, $f12, $f13
    /* F69E8 000F6974 1E00043C */  lui        $a0, %hi(sym_001DABD4)
    /* F69EC 000F6978 1E00053C */  lui        $a1, %hi(sym_001DABD8)
    /* F69F0 000F697C 036B0C46 */  div.s      $f12, $f13, $f12
    /* F69F4 000F6980 D4AB8EE4 */  swc1       $f14, %lo(sym_001DABD4)($a0)
    /* F69F8 000F6984 0800E003 */  jr         $ra
    /* F69FC 000F6988 D8ABACE4 */   swc1      $f12, %lo(sym_001DABD8)($a1)
endlabel func_000F6960
