.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_001A96C4, 0x14

glabel func_001A96C4
    /* 1A9738 001A96C4 F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 1A973C 001A96C8 0000A0A3 */  sb         $zero, 0x0($sp)
    /* 1A9740 001A96CC 0000A28F */  lw         $v0, 0x0($sp)
    /* 1A9744 001A96D0 0800E003 */  jr         $ra
    /* 1A9748 001A96D4 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel func_001A96C4
