.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0006233C, 0x2C

glabel func_0006233C
    /* 623B0 0006233C 1D00043C */  lui        $a0, %hi(sym_001D43C0)
    /* 623B4 00062340 C0438CC4 */  lwc1       $f12, %lo(sym_001D43C0)($a0)
    /* 623B8 00062344 3443043C */  lui        $a0, (0x43340000 >> 16)
    /* 623BC 00062348 00688444 */  mtc1       $a0, $f13
    /* 623C0 0006234C 83630D46 */  div.s      $f14, $f12, $f13
    /* 623C4 00062350 1D00043C */  lui        $a0, %hi(sym_001D43C4)
    /* 623C8 00062354 1D00053C */  lui        $a1, %hi(sym_001D43C8)
    /* 623CC 00062358 036B0C46 */  div.s      $f12, $f13, $f12
    /* 623D0 0006235C C4438EE4 */  swc1       $f14, %lo(sym_001D43C4)($a0)
    /* 623D4 00062360 0800E003 */  jr         $ra
    /* 623D8 00062364 C843ACE4 */   swc1      $f12, %lo(sym_001D43C8)($a1)
endlabel func_0006233C
