.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000E3C6C, 0xC

glabel func_000E3C6C
    /* E3CE0 000E3C6C 01000534 */  ori        $a1, $zero, 0x1
    /* E3CE4 000E3C70 0800E003 */  jr         $ra
    /* E3CE8 000E3C74 2A0085A0 */   sb        $a1, 0x2A($a0)
endlabel func_000E3C6C
