.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0010233C, 0x64

glabel func_0010233C
    /* 1023B0 0010233C F0FFBD27 */  addiu      $sp, $sp, -0x10
    /* 1023B4 00102340 1E00043C */  lui        $a0, %hi(sym_001DB014)
    /* 1023B8 00102344 14B08424 */  addiu      $a0, $a0, %lo(sym_001DB014)
    /* 1023BC 00102348 2D008490 */  lbu        $a0, 0x2D($a0)
    /* 1023C0 0010234C 0000BFAF */  sw         $ra, 0x0($sp)
    /* 1023C4 00102350 10008010 */  beqz       $a0, .Leboot_00102394
    /* 1023C8 00102354 00000000 */   nop
    /* 1023CC 00102358 BA06040C */  jal        func_00101AE8
    /* 1023D0 0010235C 00000000 */   nop
    /* 1023D4 00102360 00004CC4 */  lwc1       $f12, 0x0($v0)
    /* 1023D8 00102364 04004DC4 */  lwc1       $f13, 0x4($v0)
    /* 1023DC 00102368 0D630046 */  trunc.w.s  $f12, $f12
    /* 1023E0 0010236C 1E00043C */  lui        $a0, %hi(sym_001DB12C)
    /* 1023E4 00102370 4D6B0046 */  trunc.w.s  $f13, $f13
    /* 1023E8 00102374 2CB1858C */  lw         $a1, %lo(sym_001DB12C)($a0)
    /* 1023EC 00102378 00600644 */  mfc1       $a2, $f12
    /* 1023F0 0010237C 43300600 */  sra        $a2, $a2, 1
    /* 1023F4 00102380 00680744 */  mfc1       $a3, $f13
    /* 1023F8 00102384 0C00A6A4 */  sh         $a2, 0xC($a1)
    /* 1023FC 00102388 2CB1848C */  lw         $a0, %lo(sym_001DB12C)($a0)
    /* 102400 0010238C 43380700 */  sra        $a3, $a3, 1
    /* 102404 00102390 0E0087A4 */  sh         $a3, 0xE($a0)
  .Leboot_00102394:
    /* 102408 00102394 0000BF8F */  lw         $ra, 0x0($sp)
    /* 10240C 00102398 0800E003 */  jr         $ra
    /* 102410 0010239C 1000BD27 */   addiu     $sp, $sp, 0x10
endlabel func_0010233C
