.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000ACCE0, 0x194

glabel func_000ACCE0
    /* ACD54 000ACCE0 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* ACD58 000ACCE4 1001858C */  lw         $a1, 0x110($a0)
    /* ACD5C 000ACCE8 1800B0AF */  sw         $s0, 0x18($sp)
    /* ACD60 000ACCEC 25808000 */  or         $s0, $a0, $zero
    /* ACD64 000ACCF0 5C00A48C */  lw         $a0, 0x5C($a1)
    /* ACD68 000ACCF4 1000B4E7 */  swc1       $f20, 0x10($sp)
    /* ACD6C 000ACCF8 02008428 */  slti       $a0, $a0, 0x2
    /* ACD70 000ACCFC 1400B6E7 */  swc1       $f22, 0x14($sp)
    /* ACD74 000ACD00 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* ACD78 000ACD04 2000B2AF */  sw         $s2, 0x20($sp)
    /* ACD7C 000ACD08 2400B3AF */  sw         $s3, 0x24($sp)
    /* ACD80 000ACD0C 2800B4AF */  sw         $s4, 0x28($sp)
    /* ACD84 000ACD10 2C00BFAF */  sw         $ra, 0x2C($sp)
    /* ACD88 000ACD14 03008010 */  beqz       $a0, .Leboot_000ACD24
    /* ACD8C 000ACD18 00000000 */   nop
    /* ACD90 000ACD1C 4B000010 */  b          .Leboot_000ACE4C
    /* ACD94 000ACD20 1C0100A2 */   sb        $zero, 0x11C($s0)
  .Leboot_000ACD24:
    /* ACD98 000ACD24 00B08044 */  mtc1       $zero, $f22
    /* ACD9C 000ACD28 E80300AE */  sw         $zero, 0x3E8($s0)
    /* ACDA0 000ACD2C E40316E6 */  swc1       $f22, 0x3E4($s0)
    /* ACDA4 000ACD30 25200002 */  or         $a0, $s0, $zero
    /* ACDA8 000ACD34 8DAF020C */  jal        func_000ABE34
    /* ACDAC 000ACD38 25280000 */   or        $a1, $zero, $zero
    /* ACDB0 000ACD3C 18010CC6 */  lwc1       $f12, 0x118($s0)
    /* ACDB4 000ACD40 14010DC6 */  lwc1       $f13, 0x114($s0)
    /* ACDB8 000ACD44 1001048E */  lw         $a0, 0x110($s0)
    /* ACDBC 000ACD48 02630D46 */  mul.s      $f12, $f12, $f13
    /* ACDC0 000ACD4C F4010534 */  ori        $a1, $zero, 0x1F4
    /* ACDC4 000ACD50 40008EC4 */  lwc1       $f14, 0x40($a0)
    /* ACDC8 000ACD54 803F043C */  lui        $a0, (0x3F800000 >> 16)
    /* ACDCC 000ACD58 00788444 */  mtc1       $a0, $f15
    /* ACDD0 000ACD5C 02630E46 */  mul.s      $f12, $f12, $f14
    /* ACDD4 000ACD60 B0030FE6 */  swc1       $f15, 0x3B0($s0)
    /* ACDD8 000ACD64 B4030FE6 */  swc1       $f15, 0x3B4($s0)
    /* ACDDC 000ACD68 B8030FE6 */  swc1       $f15, 0x3B8($s0)
    /* ACDE0 000ACD6C 25200002 */  or         $a0, $s0, $zero
    /* ACDE4 000ACD70 C8AF020C */  jal        func_000ABF20
    /* ACDE8 000ACD74 BC030CE6 */   swc1      $f12, 0x3BC($s0)
    /* ACDEC 000ACD78 25884000 */  or         $s1, $v0, $zero
    /* ACDF0 000ACD7C 25200002 */  or         $a0, $s0, $zero
    /* ACDF4 000ACD80 25280000 */  or         $a1, $zero, $zero
    /* ACDF8 000ACD84 64B0020C */  jal        func_000AC190
    /* ACDFC 000ACD88 25300000 */   or        $a2, $zero, $zero
    /* ACE00 000ACD8C 01C9043C */  lui        $a0, %hi(D_C9010100)
    /* ACE04 000ACD90 980111AE */  sw         $s1, 0x198($s0)
    /* ACE08 000ACD94 00018424 */  addiu      $a0, $a0, %lo(D_C9010100)
    /* ACE0C 000ACD98 9C0104AE */  sw         $a0, 0x19C($s0)
    /* ACE10 000ACD9C 1001148E */  lw         $s4, 0x110($s0)
    /* ACE14 000ACDA0 19001134 */  ori        $s1, $zero, 0x19
    /* ACE18 000ACDA4 0400848E */  lw         $a0, 0x4($s4)
    /* ACE1C 000ACDA8 17009114 */  bne        $a0, $s1, .Leboot_000ACE08
    /* ACE20 000ACDAC F40094C6 */   lwc1      $f20, 0xF4($s4)
    /* ACE24 000ACDB0 E533050C */  jal        func_0014CF94
    /* ACE28 000ACDB4 06A30046 */   mov.s     $f12, $f20
    /* ACE2C 000ACDB8 1D00043C */  lui        $a0, %hi(sym_001D56D8)
    /* ACE30 000ACDBC DC56878C */  lw         $a3, %lo(sym_001D56DC)($a0)
    /* ACE34 000ACDC0 25986000 */  or         $s3, $v1, $zero
    /* ACE38 000ACDC4 25904000 */  or         $s2, $v0, $zero
    /* ACE3C 000ACDC8 D856868C */  lw         $a2, %lo(sym_001D56D8)($a0)
    /* ACE40 000ACDCC 25286002 */  or         $a1, $s3, $zero
    /* ACE44 000ACDD0 6836050C */  jal        func_0014D9A0
    /* ACE48 000ACDD4 25204002 */   or        $a0, $s2, $zero
    /* ACE4C 000ACDD8 0B004018 */  blez       $v0, .Leboot_000ACE08
    /* ACE50 000ACDDC 1D00043C */   lui       $a0, %hi(sym_001D56E0)
    /* ACE54 000ACDE0 E456878C */  lw         $a3, %lo(sym_001D56E4)($a0)
    /* ACE58 000ACDE4 E056868C */  lw         $a2, %lo(sym_001D56E0)($a0)
    /* ACE5C 000ACDE8 25286002 */  or         $a1, $s3, $zero
    /* ACE60 000ACDEC 6836050C */  jal        func_0014D9A0
    /* ACE64 000ACDF0 25204002 */   or        $a0, $s2, $zero
    /* ACE68 000ACDF4 04004104 */  bgez       $v0, .Leboot_000ACE08
    /* ACE6C 000ACDF8 00000000 */   nop
    /* ACE70 000ACDFC 01000434 */  ori        $a0, $zero, 0x1
    /* ACE74 000ACE00 12000010 */  b          .Leboot_000ACE4C
    /* ACE78 000ACE04 F80304A6 */   sh        $a0, 0x3F8($s0)
  .Leboot_000ACE08:
    /* ACE7C 000ACE08 02000434 */  ori        $a0, $zero, 0x2
    /* ACE80 000ACE0C F80304A6 */  sh         $a0, 0x3F8($s0)
    /* ACE84 000ACE10 0400848E */  lw         $a0, 0x4($s4)
    /* ACE88 000ACE14 02009114 */  bne        $a0, $s1, .Leboot_000ACE20
    /* ACE8C 000ACE18 00000000 */   nop
    /* ACE90 000ACE1C F40096E6 */  swc1       $f22, 0xF4($s4)
  .Leboot_000ACE20:
    /* ACE94 000ACE20 25200002 */  or         $a0, $s0, $zero
    /* ACE98 000ACE24 01000534 */  ori        $a1, $zero, 0x1
    /* ACE9C 000ACE28 64B0020C */  jal        func_000AC190
    /* ACEA0 000ACE2C 01000634 */   ori       $a2, $zero, 0x1
    /* ACEA4 000ACE30 1001048E */  lw         $a0, 0x110($s0)
    /* ACEA8 000ACE34 03000534 */  ori        $a1, $zero, 0x3
    /* ACEAC 000ACE38 F40094E4 */  swc1       $f20, 0xF4($a0)
    /* ACEB0 000ACE3C 00C9043C */  lui        $a0, %hi(D_C9000103)
    /* ACEB4 000ACE40 D80105AE */  sw         $a1, 0x1D8($s0)
    /* ACEB8 000ACE44 03018424 */  addiu      $a0, $a0, %lo(D_C9000103)
    /* ACEBC 000ACE48 DC0104AE */  sw         $a0, 0x1DC($s0)
  .Leboot_000ACE4C:
    /* ACEC0 000ACE4C 1000B4C7 */  lwc1       $f20, 0x10($sp)
    /* ACEC4 000ACE50 1400B6C7 */  lwc1       $f22, 0x14($sp)
    /* ACEC8 000ACE54 1800B08F */  lw         $s0, 0x18($sp)
    /* ACECC 000ACE58 1C00B18F */  lw         $s1, 0x1C($sp)
    /* ACED0 000ACE5C 2000B28F */  lw         $s2, 0x20($sp)
    /* ACED4 000ACE60 2400B38F */  lw         $s3, 0x24($sp)
    /* ACED8 000ACE64 2800B48F */  lw         $s4, 0x28($sp)
    /* ACEDC 000ACE68 2C00BF8F */  lw         $ra, 0x2C($sp)
    /* ACEE0 000ACE6C 0800E003 */  jr         $ra
    /* ACEE4 000ACE70 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_000ACCE0
