.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00109C74, 0xBC

glabel func_00109C74
    /* 109CE8 00109C74 D0FFBD27 */  addiu      $sp, $sp, -0x30
    /* 109CEC 00109C78 1800B0AF */  sw         $s0, 0x18($sp)
    /* 109CF0 00109C7C 1D00063C */  lui        $a2, %hi(str_load)
    /* 109CF4 00109C80 25808000 */  or         $s0, $a0, $zero
    /* 109CF8 00109C84 02000534 */  ori        $a1, $zero, 0x2
    /* 109CFC 00109C88 25380000 */  or         $a3, $zero, $zero
    /* 109D00 00109C8C 1C00B1AF */  sw         $s1, 0x1C($sp)
    /* 109D04 00109C90 2000BFAF */  sw         $ra, 0x20($sp)
    /* 109D08 00109C94 4E1F040C */  jal        func_00107D38
    /* 109D0C 00109C98 38DBC624 */   addiu     $a2, $a2, %lo(str_load)
    /* 109D10 00109C9C 25884000 */  or         $s1, $v0, $zero
    /* 109D14 00109CA0 25200002 */  or         $a0, $s0, $zero
    /* 109D18 00109CA4 01000534 */  ori        $a1, $zero, 0x1
    /* 109D1C 00109CA8 061F040C */  jal        func_00107C18
    /* 109D20 00109CAC 06000634 */   ori       $a2, $zero, 0x6
    /* 109D24 00109CB0 25200002 */  or         $a0, $s0, $zero
    /* 109D28 00109CB4 FB3D040C */  jal        func_0010F7EC
    /* 109D2C 00109CB8 01000534 */   ori       $a1, $zero, 0x1
    /* 109D30 00109CBC 25200002 */  or         $a0, $s0, $zero
    /* 109D34 00109CC0 D621040C */  jal        func_00108758
    /* 109D38 00109CC4 F0D80524 */   addiu     $a1, $zero, -0x2710
    /* 109D3C 00109CC8 1000A2AF */  sw         $v0, 0x10($sp)
    /* 109D40 00109CCC FFFF0424 */  addiu      $a0, $zero, -0x1
    /* 109D44 00109CD0 1400A4AF */  sw         $a0, 0x14($sp)
    /* 109D48 00109CD4 1100053C */  lui        $a1, %hi(func_00109B84)
    /* 109D4C 00109CD8 1000A627 */  addiu      $a2, $sp, 0x10
    /* 109D50 00109CDC 25200002 */  or         $a0, $s0, $zero
    /* 109D54 00109CE0 25382002 */  or         $a3, $s1, $zero
    /* 109D58 00109CE4 0143040C */  jal        func_00110C04
    /* 109D5C 00109CE8 849BA524 */   addiu     $a1, $a1, %lo(func_00109B84)
    /* 109D60 00109CEC 1000A58F */  lw         $a1, 0x10($sp)
    /* 109D64 00109CF0 25884000 */  or         $s1, $v0, $zero
    /* 109D68 00109CF4 25200002 */  or         $a0, $s0, $zero
    /* 109D6C 00109CF8 2022040C */  jal        func_00108880
    /* 109D70 00109CFC F0D80624 */   addiu     $a2, $zero, -0x2710
    /* 109D74 00109D00 1400A58F */  lw         $a1, 0x14($sp)
    /* 109D78 00109D04 25200002 */  or         $a0, $s0, $zero
    /* 109D7C 00109D08 2022040C */  jal        func_00108880
    /* 109D80 00109D0C F0D80624 */   addiu     $a2, $zero, -0x2710
    /* 109D84 00109D10 25200002 */  or         $a0, $s0, $zero
    /* 109D88 00109D14 A326040C */  jal        func_00109A8C
    /* 109D8C 00109D18 25282002 */   or        $a1, $s1, $zero
    /* 109D90 00109D1C 1800B08F */  lw         $s0, 0x18($sp)
    /* 109D94 00109D20 1C00B18F */  lw         $s1, 0x1C($sp)
    /* 109D98 00109D24 2000BF8F */  lw         $ra, 0x20($sp)
    /* 109D9C 00109D28 0800E003 */  jr         $ra
    /* 109DA0 00109D2C 3000BD27 */   addiu     $sp, $sp, 0x30
endlabel func_00109C74
