.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00019740, 0x1C

glabel func_00019740
    /* 197B4 00019740 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 197B8 00019744 1000BFAF */  sw         $ra, 0x10($sp)
    /* 197BC 00019748 7065000C */  jal        func_000195C0
    /* 197C0 0001974C 2801A58C */   lw        $a1, 0x128($a1)
    /* 197C4 00019750 1000BF8F */  lw         $ra, 0x10($sp)
    /* 197C8 00019754 0800E003 */  jr         $ra
    /* 197CC 00019758 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_00019740
