.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_000E4A78, 0x58

glabel func_000E4A78
    /* E4AEC 000E4A78 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* E4AF0 000E4A7C 1400B1AF */  sw         $s1, 0x14($sp)
    /* E4AF4 000E4A80 25888000 */  or         $s1, $a0, $zero
    /* E4AF8 000E4A84 1000B0AF */  sw         $s0, 0x10($sp)
    /* E4AFC 000E4A88 1800BFAF */  sw         $ra, 0x18($sp)
    /* E4B00 000E4A8C E592030C */  jal        func_000E4B94
    /* E4B04 000E4A90 2580A000 */   or        $s0, $a1, $zero
    /* E4B08 000E4A94 08004018 */  blez       $v0, .Leboot_000E4AB8
    /* E4B0C 000E4A98 00000000 */   nop
    /* E4B10 000E4A9C 0C00248E */  lw         $a0, 0xC($s1)
    /* E4B14 000E4AA0 0400258E */  lw         $a1, 0x4($s1)
    /* E4B18 000E4AA4 80200400 */  sll        $a0, $a0, 2
    /* E4B1C 000E4AA8 2120A400 */  addu       $a0, $a1, $a0
    /* E4B20 000E4AAC 0000848C */  lw         $a0, 0x0($a0)
    /* E4B24 000E4AB0 02000010 */  b          .Leboot_000E4ABC
    /* E4B28 000E4AB4 000004AE */   sw        $a0, 0x0($s0)
  .Leboot_000E4AB8:
    /* E4B2C 000E4AB8 000000AE */  sw         $zero, 0x0($s0)
  .Leboot_000E4ABC:
    /* E4B30 000E4ABC 1000B08F */  lw         $s0, 0x10($sp)
    /* E4B34 000E4AC0 1400B18F */  lw         $s1, 0x14($sp)
    /* E4B38 000E4AC4 1800BF8F */  lw         $ra, 0x18($sp)
    /* E4B3C 000E4AC8 0800E003 */  jr         $ra
    /* E4B40 000E4ACC 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_000E4A78
