.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00108568, 0x38

glabel func_00108568
    /* 1085DC 00108568 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 1085E0 0010856C 1000B0AF */  sw         $s0, 0x10($sp)
    /* 1085E4 00108570 1400BFAF */  sw         $ra, 0x14($sp)
    /* 1085E8 00108574 0A21040C */  jal        func_00108428
    /* 1085EC 00108578 25808000 */   or        $s0, $a0, $zero
    /* 1085F0 0010857C 03004010 */  beqz       $v0, .Leboot_0010858C
    /* 1085F4 00108580 00000000 */   nop
    /* 1085F8 00108584 2421040C */  jal        func_00108490
    /* 1085FC 00108588 25200002 */   or        $a0, $s0, $zero
  .Leboot_0010858C:
    /* 108600 0010858C 0C000226 */  addiu      $v0, $s0, 0xC
    /* 108604 00108590 1000B08F */  lw         $s0, 0x10($sp)
    /* 108608 00108594 1400BF8F */  lw         $ra, 0x14($sp)
    /* 10860C 00108598 0800E003 */  jr         $ra
    /* 108610 0010859C 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_00108568
