.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0004C7AC, 0xA8

glabel func_0004C7AC
    /* 4C820 0004C7AC C0FFBD27 */  addiu      $sp, $sp, -0x40
    /* 4C824 0004C7B0 2000B0AF */  sw         $s0, 0x20($sp)
    /* 4C828 0004C7B4 2400B1AF */  sw         $s1, 0x24($sp)
    /* 4C82C 0004C7B8 2800B2AF */  sw         $s2, 0x28($sp)
    /* 4C830 0004C7BC 2C00B3AF */  sw         $s3, 0x2C($sp)
    /* 4C834 0004C7C0 2580C000 */  or         $s0, $a2, $zero
    /* 4C838 0004C7C4 2588A000 */  or         $s1, $a1, $zero
    /* 4C83C 0004C7C8 25908000 */  or         $s2, $a0, $zero
    /* 4C840 0004C7CC 0700133C */  lui        $s3, %hi(sym_000734D4)
    /* 4C844 0004C7D0 1C00063C */  lui        $a2, %hi(str_getDialogueLine)
    /* 4C848 0004C7D4 D434648E */  lw         $a0, %lo(sym_000734D4)($s3)
    /* 4C84C 0004C7D8 EFD80524 */  addiu      $a1, $zero, -0x2711
    /* 4C850 0004C7DC 3000BFAF */  sw         $ra, 0x30($sp)
    /* 4C854 0004C7E0 DC40040C */  jal        func_00110370
    /* 4C858 0004C7E4 7050C624 */   addiu     $a2, $a2, %lo(str_getDialogueLine)
    /* 4C85C 0004C7E8 D434648E */  lw         $a0, %lo(sym_000734D4)($s3)
    /* 4C860 0004C7EC 3140040C */  jal        func_001100C4
    /* 4C864 0004C7F0 25282002 */   or        $a1, $s1, $zero
    /* 4C868 0004C7F4 D434648E */  lw         $a0, %lo(sym_000734D4)($s3)
    /* 4C86C 0004C7F8 3140040C */  jal        func_001100C4
    /* 4C870 0004C7FC 25280002 */   or        $a1, $s0, $zero
    /* 4C874 0004C800 D434648E */  lw         $a0, %lo(sym_000734D4)($s3)
    /* 4C878 0004C804 02000534 */  ori        $a1, $zero, 0x2
    /* 4C87C 0004C808 BFC6020C */  jal        func_000B1AFC
    /* 4C880 0004C80C 01000634 */   ori       $a2, $zero, 0x1
    /* 4C884 0004C810 D434648E */  lw         $a0, %lo(sym_000734D4)($s3)
    /* 4C888 0004C814 6B3F040C */  jal        func_0010FDAC
    /* 4C88C 0004C818 FFFF0524 */   addiu     $a1, $zero, -0x1
    /* 4C890 0004C81C 1000A627 */  addiu      $a2, $sp, 0x10
    /* 4C894 0004C820 25204002 */  or         $a0, $s2, $zero
    /* 4C898 0004C824 E44F050C */  jal        func_00153F90
    /* 4C89C 0004C828 25284000 */   or        $a1, $v0, $zero
    /* 4C8A0 0004C82C D434648E */  lw         $a0, %lo(sym_000734D4)($s3)
    /* 4C8A4 0004C830 FB3D040C */  jal        func_0010F7EC
    /* 4C8A8 0004C834 FEFF0524 */   addiu     $a1, $zero, -0x2
    /* 4C8AC 0004C838 2000B08F */  lw         $s0, 0x20($sp)
    /* 4C8B0 0004C83C 2400B18F */  lw         $s1, 0x24($sp)
    /* 4C8B4 0004C840 2800B28F */  lw         $s2, 0x28($sp)
    /* 4C8B8 0004C844 2C00B38F */  lw         $s3, 0x2C($sp)
    /* 4C8BC 0004C848 3000BF8F */  lw         $ra, 0x30($sp)
    /* 4C8C0 0004C84C 0800E003 */  jr         $ra
    /* 4C8C4 0004C850 4000BD27 */   addiu     $sp, $sp, 0x40
endlabel func_0004C7AC
