.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_0018C714, 0x64

glabel func_0018C714
    /* 18C788 0018C714 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 18C78C 0018C718 1400B1AF */  sw         $s1, 0x14($sp)
    /* 18C790 0018C71C 25888000 */  or         $s1, $a0, $zero
    /* 18C794 0018C720 1000B0AF */  sw         $s0, 0x10($sp)
    /* 18C798 0018C724 1800B2AF */  sw         $s2, 0x18($sp)
    /* 18C79C 0018C728 1C00BFAF */  sw         $ra, 0x1C($sp)
    /* 18C7A0 0018C72C 0C00A010 */  beqz       $a1, .Leboot_0018C760
    /* 18C7A4 0018C730 2580A000 */   or        $s0, $a1, $zero
  .Leboot_0018C734:
    /* 18C7A8 0018C734 0C000426 */  addiu      $a0, $s0, 0xC
    /* 18C7AC 0018C738 0000858C */  lw         $a1, 0x0($a0)
    /* 18C7B0 0018C73C C531060C */  jal        func_0018C714
    /* 18C7B4 0018C740 25202002 */   or        $a0, $s1, $zero
    /* 18C7B8 0018C744 08000426 */  addiu      $a0, $s0, 0x8
    /* 18C7BC 0018C748 03000012 */  beqz       $s0, .Leboot_0018C758
    /* 18C7C0 0018C74C 0000928C */   lw        $s2, 0x0($a0)
    /* 18C7C4 0018C750 DDC6040C */  jal        func_00131B74
    /* 18C7C8 0018C754 25200002 */   or        $a0, $s0, $zero
  .Leboot_0018C758:
    /* 18C7CC 0018C758 F6FF4016 */  bnez       $s2, .Leboot_0018C734
    /* 18C7D0 0018C75C 25804002 */   or        $s0, $s2, $zero
  .Leboot_0018C760:
    /* 18C7D4 0018C760 1000B08F */  lw         $s0, 0x10($sp)
    /* 18C7D8 0018C764 1400B18F */  lw         $s1, 0x14($sp)
    /* 18C7DC 0018C768 1800B28F */  lw         $s2, 0x18($sp)
    /* 18C7E0 0018C76C 1C00BF8F */  lw         $ra, 0x1C($sp)
    /* 18C7E4 0018C770 0800E003 */  jr         $ra
    /* 18C7E8 0018C774 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_0018C714
