.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_00167B34, 0x5C

glabel func_00167B34
    /* 167BA8 00167B34 E0FFBD27 */  addiu      $sp, $sp, -0x20
    /* 167BAC 00167B38 1400B1AF */  sw         $s1, 0x14($sp)
    /* 167BB0 00167B3C 25888000 */  or         $s1, $a0, $zero
    /* 167BB4 00167B40 1000B0AF */  sw         $s0, 0x10($sp)
    /* 167BB8 00167B44 1800BFAF */  sw         $ra, 0x18($sp)
    /* 167BBC 00167B48 0C008010 */  beqz       $a0, .Leboot_00167B7C
    /* 167BC0 00167B4C 2580A000 */   or        $s0, $a1, $zero
    /* 167BC4 00167B50 0000043C */  lui        $a0, %hi(sym_00000B1C)
    /* 167BC8 00167B54 1C0B8424 */  addiu      $a0, $a0, %lo(sym_00000B1C)
    /* 167BCC 00167B58 040024AE */  sw         $a0, 0x4($s1)
    /* 167BD0 00167B5C 25202002 */  or         $a0, $s1, $zero
    /* 167BD4 00167B60 8BC5020C */  jal        func_000B162C
    /* 167BD8 00167B64 25280000 */   or        $a1, $zero, $zero
    /* 167BDC 00167B68 01000432 */  andi       $a0, $s0, 0x1
    /* 167BE0 00167B6C 03008010 */  beqz       $a0, .Leboot_00167B7C
    /* 167BE4 00167B70 00000000 */   nop
    /* 167BE8 00167B74 C79D040C */  jal        func_0012771C
    /* 167BEC 00167B78 25202002 */   or        $a0, $s1, $zero
  .Leboot_00167B7C:
    /* 167BF0 00167B7C 1000B08F */  lw         $s0, 0x10($sp)
    /* 167BF4 00167B80 1400B18F */  lw         $s1, 0x14($sp)
    /* 167BF8 00167B84 1800BF8F */  lw         $ra, 0x18($sp)
    /* 167BFC 00167B88 0800E003 */  jr         $ra
    /* 167C00 00167B8C 2000BD27 */   addiu     $sp, $sp, 0x20
endlabel func_00167B34
