.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching stub_001B0788, 0x8

glabel stub_001B0788
    /* 1B07FC 001B0788 0800E003 */  jr         $ra
    /* 1B0800 001B078C 00000000 */   nop
endlabel stub_001B0788
