.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching stub_001B01F8, 0x8

glabel stub_001B01F8
    /* 1B026C 001B01F8 0800E003 */  jr         $ra
    /* 1B0270 001B01FC 00000000 */   nop
endlabel stub_001B01F8
