.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching stub_001B06F0, 0x8

glabel stub_001B06F0
    /* 1B0764 001B06F0 0800E003 */  jr         $ra
    /* 1B0768 001B06F4 00000000 */   nop
endlabel stub_001B06F0
