"""Generate `config/eboot.symbols.ld`, the absolute linker symbols for EBOOT.

splat pins every section to the exact VRAM the original module used (the EBOOT
is linked at base 0 and relocated to 0x08804000 by the PSP loader), so plain
absolute assignments reproduce the original addresses exactly.  Two kinds of
symbol end up in the generated asm:

* addresses inside `.rodata`/`.data`/`.bss`, recovered from the relocation
  tables (`sym_XXXXXXXX` / the original function names), and
* `lui`/`addiu` constant pairs that spimdisasm materialised into a name.  Those
  are named after the value they hold (`D_3F7FFFFF`, `sym_B710B710`), which is
  exactly what the linker needs to define for `%hi`/`%lo` to reassemble.

Run this after splat so the generated `.s` files are available to scan.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from paths import ELF_PATH  # noqa: E402

import pspelf  # noqa: E402

# Labels spimdisasm names after the constant they carry.  Two families show up
# in the generated asm:
#   `D_XXXXXXXX` / `sym_XXXXXXXX`  full 32 bit materialised constants
#   `D_eboot_XXXXXXXX`              `%hi` of a value whose low half was folded
#                                   away by a mask, so only the name's digits
#                                   are needed - the name still encodes it.
CONSTANT_NAME = re.compile(r"\b((?:D_|sym_)(?:eboot_)?)([0-9A-F]{8})\b")
# Symbols the generated asm actually defines (function and branch labels).
DEFINED_LABEL = re.compile(r"^\s*(?:glabel|\.globl|\.global)\s+(\S+)",
                           re.MULTILINE)
ASM_SYMBOL_USE = re.compile(
    r"(?:%hi|%lo)\((\w+)\)|(?:\bjal|\bj|\bb|\bbeq\w*|\tbne\w*|"
    r"\bbal)\s+(\w+)|(?:^|\s)(\w+)\s*=\s*%lo|\bjalr\s")

HEADER = """\
/* ==========================================================================
 *  The Sims 2 PSP - absolute linker symbols for the EBOOT.
 *
 *  GENERATED BY tools/gen_linker_symbols.py - do not edit.
 *
 *  splat's linker script pins every section to the exact VRAM the original
 *  module used, so these absolute assignments reproduce the original addresses
 *  exactly.  They are what lets the generated asm name things inside
 *  .rodata/.data/.bss before those sections are decompiled into C.
 * ========================================================================== */
"""


def write_assets(elf) -> int:
    """Re-extract every data section verbatim.

    splat writes these blobs too, but it pads them out to the start of the
    following segment - which is wrong for the last sections (`.dtors` would
    gain the four alignment bytes that follow it) and shifts everything after
    them.  The bytes have to be exact, so they are written from the ELF.
    """
    written = 0
    for sec in elf.sections:
        if sec.type == 8 or sec.is_text or not sec.size:
            continue
        if not sec.flags & 0x2:
            continue
        out = (ROOT / "assets/eboot"
               / f"{sec.name.lstrip('.').replace('.', '_')}.bin")
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(sec.data)
        written += 1
    return written


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--elf", default=str(ELF_PATH))
    ap.add_argument("--asm", default=str(ROOT / "asm/eboot"))
    ap.add_argument("--out", default=str(ROOT / "config/eboot.symbols.ld"))
    ns = ap.parse_args()

    elf = pspelf.load(ns.elf)
    n_assets = write_assets(elf)
    print(f"re-extracted {n_assets} data blobs")

    # 1. section anchors, so the C sources can refer to whole sections
    lines = [HEADER, "", "/* --- section anchors --- */"]
    for sec in elf.sections:
        if (sec.flags & 0x2) and sec.size:
            cname = sec.name.lstrip(".").replace(".", "_")
            lines.append(f"_{cname}_START = 0x{sec.addr:08X};")
            lines.append(f"_{cname}_SIZE  = 0x{sec.size:08X};")
    lines.append("")

    # 2. function labels (spat emits them as `glabel`, so they only need to be
    #    defined once - by their own object file - but the data references to
    #    them need a definition in the layout the linker can compute)
    defined: set[str] = set()
    asm_dir = Path(ns.asm)
    asm_files = sorted(asm_dir.rglob("*.s"))
    for path in asm_files:
        defined.update(DEFINED_LABEL.findall(path.read_text(encoding="utf-8")))
    print(f"scanned {len(asm_files)} asm files, "
          f"{len(defined)} defined labels")

    # 3. function names, as absolute assignments.  Every function in the module
    #    is already `glabel`ed by its own assembly object, so the build resolves
    #    them correctly and does not need these - but a *candidate check* links
    #    one object on its own, and then `psp-ld` resolves an unknown name to
    #    the first symbol in the image instead of failing.  That silently
    #    produces wrong bytes, which is far worse than an error.  Defining every
    #    function to its real address here makes a standalone candidate link
    #    correctly; where the object's own `glabel` disagrees the object's own
    #    definition wins, since these are plain assignments in a -T script and
    #    the object symbol is more specific.
    func_labels: dict[str, int] = {}
    sym_map = ROOT / "config/eboot.symbol_addrs.txt"
    for line in sym_map.read_text(encoding="utf-8").splitlines():
        if "type:func" not in line or "=" not in line:
            continue
        try:
            func_labels[line.split("=", 1)[0].strip()] = \
                int(line.split("=")[1].split(";")[0].strip(), 16)
        except ValueError:
            continue
    if func_labels:
        lines.append("/* --- function addresses, for standalone candidate "
                     "links --- */")
        for name, value in sorted(func_labels.items(), key=lambda kv: kv[1]):
            lines.append(f"{name} = 0x{value:08X};")
        lines.append("")

    # 4. data labels: every address inside .rodata/.data/.bss that a relocation
    #    points at.  config/eboot.symbol_addrs.txt is the authority on which
    #    name belongs to which address, so read the names from there rather than
    #    reconstructing them - otherwise any name that is not a hex constant
    #    (a recovered string, say) ends up referenced but never defined.
    data_labels: dict[str, int] = {}
    sym_map = ROOT / "config/eboot.symbol_addrs.txt"
    for line in sym_map.read_text(encoding="utf-8").splitlines():
        if "=" not in line:
            continue
        name = line.split("=", 1)[0].strip()
        value = line.split("=", 1)[1].split(";")[0].strip()
        if "type:func" in line or name in defined:
            continue
        try:
            data_labels[name] = int(value, 16)
        except ValueError:
            continue
    if data_labels:
        lines.append("/* --- data labels recovered from the relocation tables --- */")
        for name, value in sorted(data_labels.items(), key=lambda kv: kv[1]):
            lines.append(f"{name} = 0x{value:08X};")
        lines.append("")

    # 5. constants spimdisasm materialised out of lui/addiu pairs.  The name
    #    already encodes the value, so no disassembly is needed.
    constants: dict[str, int] = {}
    for path in asm_files:
        text = path.read_text(encoding="utf-8")
        for match in CONSTANT_NAME.finditer(text):
            name = match.group(0)
            if name in defined or name in data_labels:
                continue
            constants[name] = int(match.group(2), 16)
    if constants:
        lines.append("/* --- constants materialised from lui/addiu pairs --- */")
        for name, value in sorted(constants.items(), key=lambda kv: kv[1]):
            lines.append(f"{name} = 0x{value:08X};")
        lines.append("")

    out = Path(ns.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(data_labels)} data labels, "
          f"{len(constants)} constants, {len(lines)} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
